### ISSUE TITLE
GRM failure with N >50k

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1004]

**Comment by tpoterba** [comment]
```text
grm: caught exception: java.lang.IllegalArgumentException: requirement failed: The length of the values array must be less than Int.MaxValue. Currently numRows * numCols: 12619826244
at scala.Predef$.require(Predef.scala:233)
at org.apache.spark.mllib.linalg.distributed.BlockMatrix.toLocalMatrix(BlockMatrix.scala:282)
at org.broadinstitute.hail.driver.GRM$.run(GRM.scala:56)
at org.broadinstitute.hail.driver.GRM$.run(GRM.scala:11)
at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:243)
```

**Comment by tpoterba** [comment]
Can't call `.toLocalMatrix()`, need to write out in parallel

**Comment by danking** [comment]
As @tpoterba noted out-of-band, the matrix is too large for Java to address every element. We need to write it out to a file in a distributed manner.
