### ISSUE TITLE
Hail fails on write to HDFS Encryption Zone

### ISSUE THREAD

**Issue by skeller2** [hail-is/hail#10087]
Hi,

I have an issue where hail fails when writing to an HDFS encryption zone.  HDFS writes to a non-encrypted HDFS work OK.

Here is the stacktrace:
java.io.IOException: Stream closed
        at org.apache.hadoop.crypto.CryptoOutputStream.checkStream(CryptoOutputStream.java:270)
        at org.apache.hadoop.crypto.CryptoOutputStream.flush(CryptoOutputStream.java:257)
        at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at is.hail.io.fs.HadoopFS$$anon$1.flush(HadoopFS.scala:35)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at is.hail.utils.package$.using(package.scala:620)
        at is.hail.io.RichContextRDDRegionValue$.writeSplitRegion(RichContextRDDRegionValue.scala:106)
        at is.hail.rvd.RVD$$anonfun$29.apply(RVD.scala:938)
        at is.hail.rvd.RVD$$anonfun$29.apply(RVD.scala:936)
        at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$18.apply(ContextRDD.scala:259)
        at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$18.apply(ContextRDD.scala:259)
        at is.hail.utils.richUtils.RichContextRDD$$anonfun$cleanupRegions$1$$anonfun$2.apply(RichContextRDD.scala:62)
        at is.hail.utils.richUtils.RichContextRDD$$anonfun$cleanupRegions$1$$anonfun$2.apply(RichContextRDD.scala:62)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
        at is.hail.utils.richUtils.RichContextRDD$$anonfun$cleanupRegions$1$$anon$1.hasNext(RichContextRDD.scala:71)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at scala.collection.AbstractIterator.to(Iterator.scala:1334)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1334)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1334)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:945)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:945)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1405)

The Hail version is: 0.2.61
The spark version is: 2.4.0.cloudera2

Checking the stacktrace and debugging it looks like flush() is being called on a closed stream.  On a non-encryption zone HDFS write this seems to be silently ignored, but it causes an exception when writing to an encryption zone HDFS.

Looking at the Hail code, there is a test for trying to close a stream that is already closed, so I created a patch to do the same check on a flush call:
--- current/hail/hail/src/main/scala/is/hail/io/fs/HadoopFS.scala       2021-02-12 11:17:14.000000000 -0500
+++ patched/hail/hail/src/main/scala/is/hail/io/fs/HadoopFS.scala       2021-02-16 10:16:46.156874381 -0500
@@ -32,7 +32,11 @@

       override def write(bytes: Array[Byte], off: Int, len: Int): Unit = os.write(bytes, off, len)

-      override def flush(): Unit = os.flush()
+      override def flush(): Unit = {
+        if (!closed) {
+          os.flush()
+        }
+      }

       override def close(): Unit = {
         if (!closed) {

This fixed the issue for us.  I am hoping that you can evaluate this patch and include it in future versions of Hail.

Please let me know if you need more information,

Thanks
Steve Keller

**Comment by tpoterba** [comment]
yeah, definitely a bug. If you've already got the patch, can you create a pull request?

**Comment by skeller2** [comment]
Hi Tpoterba,

Thanks for the quick response!

I'm not a github guru but I will try.  

Thanks again.

**Comment by tpoterba** [comment]
If it's a hassle I can do this in a few minutes.

**Comment by skeller2** [comment]
Hi Tpoterba,

That would be a big help.  I've attached the patch file I used.

[HadoopFS.scala.patch.zip](https://github.com/hail-is/hail/files/6023321/HadoopFS.scala.patch.zip)
