### ISSUE TITLE
On import, `TypeError: an integer is required (got type bytes)`

### ISSUE THREAD

**Issue by reece** [hail-is/hail#10197]
On Ubuntu 20.10, with Python 3.8.6 and hail 0.2.64 installed from pip, I get: ​I get `TypeError: an integer is required (got type bytes)` immediately upon importing hail. A full transcript is below. (pyve is an alias to create a python virtual env and activate it)

---

```
snafu$ pyve
+ python3.8 -m venv venv/3.8
+ source venv/3.8/bin/activate
+ pip install -U setuptools pip
Collecting setuptools
  Using cached setuptools-54.1.2-py3-none-any.whl (785 kB)
Collecting pip
  Using cached pip-21.0.1-py3-none-any.whl (1.5 MB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.0.0
    Uninstalling setuptools-44.0.0:
      Successfully uninstalled setuptools-44.0.0
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-21.0.1 setuptools-54.1.2
(3.8) ✔ ~/sandbox/hail [master|𝚫8?2]
snafu$ pip install hail ipython
Collecting hail
  Using cached hail-0.2.64-py3-none-any.whl (97.5 MB)
Collecting ipython
  Using cached ipython-7.21.0-py3-none-any.whl (784 kB)
Collecting pandas<1.1.5,>=1.1.0
  Using cached pandas-1.1.4-cp38-cp38-manylinux1_x86_64.whl (9.3 MB)
Collecting python-json-logger==0.1.11
  Using cached python_json_logger-0.1.11-py2.py3-none-any.whl
Collecting gcsfs==0.7.2
  Using cached gcsfs-0.7.2-py2.py3-none-any.whl (22 kB)
Collecting requests==2.22.0
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting tabulate==0.8.3
  Using cached tabulate-0.8.3-py3-none-any.whl
Collecting nest-asyncio
  Using cached nest_asyncio-1.5.1-py3-none-any.whl (5.0 kB)
Collecting parsimonious<0.9
  Using cached parsimonious-0.8.1-py3-none-any.whl
Collecting pyspark<2.4.2,>=2.4
  Using cached pyspark-2.4.1-py2.py3-none-any.whl
Collecting tqdm==4.42.1
  Using cached tqdm-4.42.1-py2.py3-none-any.whl (59 kB)
Collecting bokeh<2.0,>1.3
  Using cached bokeh-1.4.0-py3-none-any.whl
Collecting Deprecated<1.3,>=1.2.10
  Using cached Deprecated-1.2.12-py2.py3-none-any.whl (9.5 kB)
Collecting PyJWT
  Using cached PyJWT-2.0.1-py3-none-any.whl (15 kB)
Collecting numpy<2
  Using cached numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
Collecting aiohttp-session<2.8,>=2.7
  Using cached aiohttp_session-2.7.0-py3-none-any.whl (14 kB)
Collecting dill<0.4,>=0.3.1.1
  Using cached dill-0.3.3-py2.py3-none-any.whl (81 kB)
Collecting humanize==1.0.0
  Using cached humanize-1.0.0-py2.py3-none-any.whl (51 kB)
Collecting hurry.filesize==0.9
  Using cached hurry.filesize-0.9-py3-none-any.whl
Collecting scipy<1.7,>1.2
  Using cached scipy-1.6.1-cp38-cp38-manylinux1_x86_64.whl (27.3 MB)
Collecting asyncinit<0.3,>=0.2.4
  Using cached asyncinit-0.2.4-py3-none-any.whl (2.8 kB)
Collecting decorator<5
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting aiohttp==3.7.4
  Using cached aiohttp-3.7.4-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)
Collecting google-cloud-storage==1.25.*
  Using cached google_cloud_storage-1.25.0-py2.py3-none-any.whl (73 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.6.3-cp38-cp38-manylinux2014_x86_64.whl (324 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting attrs>=17.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting chardet<4.0,>=2.0
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.1.0-cp38-cp38-manylinux2014_x86_64.whl (159 kB)
Collecting google-auth>=1.2
  Using cached google_auth-1.27.1-py2.py3-none-any.whl (136 kB)
Collecting google-auth-oauthlib
  Using cached google_auth_oauthlib-0.4.3-py2.py3-none-any.whl (18 kB)
Collecting fsspec>=0.8.0
  Using cached fsspec-0.8.7-py3-none-any.whl (103 kB)
Collecting google-cloud-core<2.0dev,>=1.2.0
  Using cached google_cloud_core-1.6.0-py2.py3-none-any.whl (28 kB)
Collecting google-resumable-media<0.6dev,>=0.5.0
  Using cached google_resumable_media-0.5.1-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: setuptools in ./venv/3.8/lib/python3.8/site-packages (from hurry.filesize==0.9->hail) (54.1.2)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting idna<2.9,>=2.5
  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting tornado>=4.3
  Using cached tornado-6.1-cp38-cp38-manylinux2010_x86_64.whl (427 kB)
Collecting six>=1.5.2
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting packaging>=16.8
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting pillow>=4.0
  Using cached Pillow-8.1.2-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting PyYAML>=3.10
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting Jinja2>=2.7
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting wrapt<2,>=1.10
  Using cached wrapt-1.12.1-cp38-cp38-linux_x86_64.whl
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.1-py3-none-any.whl (12 kB)
Collecting google-api-core<2.0.0dev,>=1.21.0
  Using cached google_api_core-1.26.1-py2.py3-none-any.whl (92 kB)
Collecting pytz
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Using cached googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)
Collecting protobuf>=3.12.0
  Using cached protobuf-3.15.6-cp38-cp38-manylinux1_x86_64.whl (1.0 MB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux2010_x86_64.whl (32 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting py4j==0.10.7
  Using cached py4j-0.10.7-py2.py3-none-any.whl (197 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.17-py3-none-any.whl (367 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting traitlets>=4.2
  Using cached traitlets-5.0.5-py3-none-any.whl (100 kB)
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting jedi>=0.16
  Using cached jedi-0.18.0-py2.py3-none-any.whl (1.4 MB)
Collecting pygments
  Using cached Pygments-2.8.1-py3-none-any.whl (983 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.1-py2.py3-none-any.whl (93 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Installing collected packages: six, pyasn1, urllib3, rsa, pyparsing, pyasn1-modules, protobuf, idna, chardet, certifi, cachetools, requests, pytz, packaging, oauthlib, multidict, googleapis-common-protos, google-auth, yarl, typing-extensions, requests-oauthlib, MarkupSafe, google-api-core, attrs, async-timeout, wrapt, wcwidth, tornado, PyYAML, python-dateutil, py4j, ptyprocess, pillow, parso, numpy, Jinja2, ipython-genutils, google-resumable-media, google-cloud-core, google-auth-oauthlib, fsspec, decorator, aiohttp, traitlets, tqdm, tabulate, scipy, python-json-logger, pyspark, PyJWT, pygments, prompt-toolkit, pickleshare, pexpect, parsimonious, pandas, nest-asyncio, jedi, hurry.filesize, humanize, google-cloud-storage, gcsfs, dill, Deprecated, bokeh, backcall, asyncinit, aiohttp-session, ipython, hail
Successfully installed Deprecated-1.2.12 Jinja2-2.11.3 MarkupSafe-1.1.1 PyJWT-2.0.1 PyYAML-5.4.1 aiohttp-3.7.4 aiohttp-session-2.7.0 async-timeout-3.0.1 asyncinit-0.2.4 attrs-20.3.0 backcall-0.2.0 bokeh-1.4.0 cachetools-4.2.1 certifi-2020.12.5 chardet-3.0.4 decorator-4.4.2 dill-0.3.3 fsspec-0.8.7 gcsfs-0.7.2 google-api-core-1.26.1 google-auth-1.27.1 google-auth-oauthlib-0.4.3 google-cloud-core-1.6.0 google-cloud-storage-1.25.0 google-resumable-media-0.5.1 googleapis-common-protos-1.53.0 hail-0.2.64 humanize-1.0.0 hurry.filesize-0.9 idna-2.8 ipython-7.21.0 ipython-genutils-0.2.0 jedi-0.18.0 multidict-5.1.0 nest-asyncio-1.5.1 numpy-1.20.1 oauthlib-3.1.0 packaging-20.9 pandas-1.1.4 parsimonious-0.8.1 parso-0.8.1 pexpect-4.8.0 pickleshare-0.7.5 pillow-8.1.2 prompt-toolkit-3.0.17 protobuf-3.15.6 ptyprocess-0.7.0 py4j-0.10.7 pyasn1-0.4.8 pyasn1-modules-0.2.8 pygments-2.8.1 pyparsing-2.4.7 pyspark-2.4.1 python-dateutil-2.8.1 python-json-logger-0.1.11 pytz-2021.1 requests-2.22.0 requests-oauthlib-1.3.0 rsa-4.7.2 scipy-1.6.1 six-1.15.0 tabulate-0.8.3 tornado-6.1 tqdm-4.42.1 traitlets-5.0.5 typing-extensions-3.7.4.3 urllib3-1.25.11 wcwidth-0.2.5 wrapt-1.12.1 yarl-1.6.3
(3.8) ✔ ~/sandbox/hail [master|𝚫8?2]
snafu$ ipython 
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import hail
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-e24d842d2b9a> in <module>
----> 1 import hail

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/hail/__init__.py in <module>
     32 # F401 '.expr.*' imported but unused
     33 # E402 module level import not at top of file
---> 34 from .table import Table, GroupedTable, asc, desc  # noqa: E402
     35 from .matrixtable import MatrixTable, GroupedMatrixTable  # noqa: E402
     36 from .expr import *  # noqa: F401,F403,E402

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/hail/table.py in <module>
      2 import itertools
      3 import pandas
----> 4 import pyspark
      5 from typing import Optional, Dict, Callable
      6 

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/__init__.py in <module>
     49 
     50 from pyspark.conf import SparkConf
---> 51 from pyspark.context import SparkContext
     52 from pyspark.rdd import RDD, RDDBarrier
     53 from pyspark.files import SparkFiles

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/context.py in <module>
     29 from py4j.protocol import Py4JError
     30 
---> 31 from pyspark import accumulators
     32 from pyspark.accumulators import Accumulator
     33 from pyspark.broadcast import Broadcast, BroadcastPickleRegistry

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/accumulators.py in <module>
     95     import socketserver as SocketServer
     96 import threading
---> 97 from pyspark.serializers import read_int, PickleSerializer
     98 
     99 

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/serializers.py in <module>
     69     xrange = range
     70 
---> 71 from pyspark import cloudpickle
     72 from pyspark.util import _exception_message
     73 

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/cloudpickle.py in <module>
    143 
    144 
--> 145 _cell_set_template_code = _make_cell_set_template_code()
    146 
    147 

~/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/cloudpickle.py in _make_cell_set_template_code()
    124         )
    125     else:
--> 126         return types.CodeType(
    127             co.co_argcount,
    128             co.co_kwonlyargcount,

TypeError: an integer is required (got type bytes)

In [2]: 

```

**Comment by reece** [comment]
Drat, it appears that pyspark doesn't work with Python 3.8. https://stackoverflow.com/a/58849063/342839.

A simpler reproduction to demonstrate that this is a pyspark issues:

```
snafu$ python -m pyspark.cloudpickle
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/reece/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/__init__.py", line 51, in <module>
    from pyspark.context import SparkContext
  File "/home/reece/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/context.py", line 31, in <module>
    from pyspark import accumulators
  File "/home/reece/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/accumulators.py", line 97, in <module>
    from pyspark.serializers import read_int, PickleSerializer
  File "/home/reece/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/serializers.py", line 71, in <module>
    from pyspark import cloudpickle
  File "/home/reece/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 145, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/reece/sandbox/hail/venv/3.8/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 126, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```

**Comment by reece** [comment]
According to @johnc1231 in https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/Troubles.20getting.20started.20(Python.203.2E8):

> It's intentionally limited to 3.7 because of precisely that error
>
> John Compitello: This is because of our dependence on spark 2. Spark 3 won't have that restriction, we are in the process of upgrading, hopefully should be fixed next week

I'll close this and wait for the release with Spark 3.
