### ISSUE TITLE
UnsupportedFileSystemException: No FileSystem for scheme "gs"

### ISSUE THREAD

**Issue by tobyrmanders** [hail-is/hail#10530]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

When trying to use the load_dataset() function on any dataset, I receive the following error: 

```
mt = hl.experimental.load_dataset(name='1000_Genomes_chrMT',
                                version='phase_3',
                                reference_genome='GRCh37',
                                region='us',
                                cloud='gcp')
```

```
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-7-5fec92db8e26> in <module>
----> 1 mt = hl.experimental.load_dataset(name='1000_Genomes_chrMT',
      2                                 version='phase_3',
      3                                 reference_genome='GRCh37',
      4                                 region='us',
      5                                 cloud='gcp')

~/miniconda3/envs/hail-env/lib/python3.9/site-packages/hail/experimental/datasets.py in load_dataset(name, version, reference_genome, region, cloud)
    109         return hl.read_table(path)
    110     elif path.endswith('.mt'):
--> 111         return hl.read_matrix_table(path)
    112     elif path.endswith('.bm'):
    113         return hl.linalg.BlockMatrix.read(path)

~/miniconda3/envs/hail-env/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/miniconda3/envs/hail-env/lib/python3.9/site-packages/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    575     def wrapper(__original_func, *args, **kwargs):
    576         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 577         return __original_func(*args_, **kwargs_)
    578 
    579     return wrapper

~/miniconda3/envs/hail-env/lib/python3.9/site-packages/hail/methods/impex.py in read_matrix_table(path, _intervals, _filter_intervals, _drop_cols, _drop_rows, _n_partitions)
   2009     :class:`.MatrixTable`
   2010     """
-> 2011     for rg_config in Env.backend().load_references_from_dataset(path):
   2012         hl.ReferenceGenome._from_config(rg_config)
   2013 

~/miniconda3/envs/hail-env/lib/python3.9/site-packages/hail/backend/spark_backend.py in load_references_from_dataset(self, path)
    321 
    322     def load_references_from_dataset(self, path):
--> 323         return json.loads(Env.hail().variant.ReferenceGenome.fromHailDataset(self.fs._jfs, path))
    324 
    325     def from_fasta_file(self, name, fasta_file, index_file, x_contigs, y_contigs, mt_contigs, par):

~/miniconda3/envs/hail-env/lib/python3.9/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

~/miniconda3/envs/hail-env/lib/python3.9/site-packages/hail/backend/py4j_backend.py in deco(*args, **kwargs)
     28                 raise FatalError('Error summary: %s' % (deepest,), error_id) from None
     29             else:
---> 30                 raise FatalError('%s\n\nJava stack trace:\n%s\n'
     31                                  'Hail version: %s\n'
     32                                  'Error summary: %s' % (deepest, full, hail.__version__, deepest), error_id) from None

FatalError: UnsupportedFileSystemException: No FileSystem for scheme "gs"

Java stack trace:
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3281)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at is.hail.io.fs.HadoopFS.fileStatus(HadoopFS.scala:164)
	at is.hail.io.fs.FS.isDir(FS.scala:175)
	at is.hail.io.fs.FS.isDir$(FS.scala:173)
	at is.hail.io.fs.HadoopFS.isDir(HadoopFS.scala:70)
	at is.hail.expr.ir.RelationalSpec$.readMetadata(AbstractMatrixTableSpec.scala:30)
	at is.hail.expr.ir.RelationalSpec$.readReferences(AbstractMatrixTableSpec.scala:68)
	at is.hail.variant.ReferenceGenome$.fromHailDataset(ReferenceGenome.scala:596)
	at is.hail.variant.ReferenceGenome.fromHailDataset(ReferenceGenome.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)



Hail version: 0.2.67-a673309b0445
Error summary: UnsupportedFileSystemException: No FileSystem for scheme "gs"
```

**Comment by tpoterba** [comment]
This is expected -- the datasets repository currently supports Google Cloud applications, though we are working on replicating it to other clouds. It is possible to read/write `gs://` files from outside the cloud using the [google cloud storage connector for hadoop](https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage) but I don't recommend that here -- these files are not tiny, and you'll experience slow speeds and high egress fees.
