### ISSUE TITLE
[query] Liftover NoSuchElementException

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#10722]
Topics:
https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/key.20not.20found.3A.20GRCh38/near/247317975
https://discuss.hail.is/t/potential-liftover-issue-error-summary-nosuchelementexception-key-not-found-grch37/2154

Stack trace:
```
java.util.NoSuchElementException: key not found: GRCh37
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:65)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
	at is.hail.variant.ReferenceGenome.getLiftover(ReferenceGenome.scala:412)
	at is.hail.variant.ReferenceGenome.liftoverLocus(ReferenceGenome.scala:423)
	at __C700Compiled.applyregion0_8(Emit.scala)
	at __C700Compiled.apply(Emit.scala)
	at is.hail.expr.ir.TableMapRows.$anonfun$execute$43(TableIR.scala:1936)
```

See Lindo's comment in the Zulip thread to replicate (hopefully)

**Comment by DSuveges** [comment]
Hi Guys, I understand fixing this issue might be complicated and takes time. In the meantime, could you recommend an earlier hail version when the liftover functionality worked?

**Comment by tpoterba** [comment]
I'm intending to debug/fix this today. I'll update this evening about progress.

**Comment by tpoterba** [comment]
Sorry for the wait!

**Comment by tpoterba** [comment]
Also, if you could respond on the forum thread to help replicate, that would be great.

**Comment by DSuveges** [comment]
Oh sorry @tpoterba , this issue got completely slipped off my radar.
