### ISSUE TITLE
VCF combiner assertion error about schema mismatches

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#10813]
Here's a stack trace, shouldn't be too hard to replicate:

```
Java stack trace:
java.lang.IllegalArgumentException: requirement failed
    at scala.Predef$.require(Predef.scala:268)
    at is.hail.expr.ir.MatrixMultiWrite.<init>(IR.scala:609)
    at is.hail.expr.ir.IRParser$.$anonfun$ir_value_expr_1$167(Parser.scala:1350)
    at is.hail.utils.StackSafe$StackFrame.$anonfun$map$1(StackSafe.scala:30)
    at is.hail.utils.StackSafe$More.advance(StackSafe.scala:60)
    at is.hail.utils.StackSafe$.run(StackSafe.scala:16)
    at is.hail.utils.StackSafe$StackFrame.run(StackSafe.scala:32)
    at is.hail.expr.ir.IRParser$.$anonfun$parse_value_ir$1(Parser.scala:1970)
    at is.hail.expr.ir.IRParser$.parse(Parser.scala:1967)
    at is.hail.expr.ir.IRParser$.parse_value_ir(Parser.scala:1970)
    at is.hail.backend.spark.SparkBackend.$anonfun$parse_value_ir$2(SparkBackend.scala:637)
    at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:47)
    at is.hail.utils.package$.using(package.scala:627)
    at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:47)
    at is.hail.utils.package$.using(package.scala:627)
    at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
    at is.hail.expr.ir.ExecuteContext$.scoped(ExecuteContext.scala:46)
    at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:275)
    at is.hail.backend.spark.SparkBackend.$anonfun$parse_value_ir$1(SparkBackend.scala:636)
    at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
```

**Comment by danking** [comment]
Closing as stale. Please re-open if this occurs on recent versions of Hail.
