### ISSUE TITLE
pruned tuple isSupertype bug

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#10858]
```
Java stack trace:
is.hail.utils.HailException: error while checking subtype:
  super: struct{trait_type: str, phenocode: str, pheno_sex: str, coding: str, modifier: str, pheno_data: array<struct{}>, description: str, description_more: str, coding_description: str, category: str, n_cases_full_cohort_both_sexes: int64, n_cases_full_cohort_females: int64, n_cases_full_cohort_males: int64, col_array: tuple(1:struct{n_cases: int32, n_controls: int32, heritability: struct{estimates: struct{ldsc: struct{h2_liability: float64, h2_liability_se: float64, h2_z: float64, h2_observed: float64, h2_observed_se: float64, intercept: float64, intercept_se: float64, ratio: float64, ratio_se: float64}, sldsc_25bin: struct{h2_liability: float64, h2_liability_se: float64, h2_z: float64, h2_observed: float64, h2_observed_se: float64, intercept: float64, intercept_se: float64, ratio: float64, ratio_se: float64}, rhemc_25bin: struct{h2_liability: float64, h2_liability_se: float64, h2_z: float64, h2_observed: float64, h2_observed_se: float64}, rhemc_8bin: struct{h2_liability: float64, h2_liability_se: float64, h2_observed: float64, h2_observed_se: float64, h2_z: float64}, rhemc_25bin_50rv: struct{h2_observed: float64, h2_observed_se: float64, h2_liability: float64, h2_liability_se: float64, h2_z: float64}, final: struct{h2_observed: float64, h2_observed_se: float64, h2_liability: float64, h2_liability_se: float64, h2_z: float64}}, qcflags: struct{GWAS_run: bool, defined_h2: bool, significant_z: bool, in_bounds_h2: bool, normal_lambda: bool, normal_ratio: bool, EUR_plus_1: bool, pass_all: bool}, N_ancestry_QC_pass: int32}, saige_version: str, inv_normalized: bool, pop: str, lambda_gc: float64, n_variants: int64, n_sig_variants: int64, saige_heritability: float64}))}
  sub:   struct{trait_type: str, phenocode: str, pheno_sex: str, coding: str, modifier: str, pheno_data: array<struct{}>, description: str, description_more: str, coding_description: str, category: str, n_cases_full_cohort_both_sexes: int64, n_cases_full_cohort_females: int64, n_cases_full_cohort_males: int64, col_array: tuple(1:struct{n_cases: int32, n_controls: int32, heritability: struct{estimates: struct{ldsc: struct{h2_liability: float64, h2_liability_se: float64, h2_z: float64, h2_observed: float64, h2_observed_se: float64, intercept: float64, intercept_se: float64, ratio: float64, ratio_se: float64}, sldsc_25bin: struct{h2_liability: float64, h2_liability_se: float64, h2_z: float64, h2_observed: float64, h2_observed_se: float64, intercept: float64, intercept_se: float64, ratio: float64, ratio_se: float64}, rhemc_25bin: struct{h2_liability: float64, h2_liability_se: float64, h2_z: float64, h2_observed: float64, h2_observed_se: float64}, rhemc_8bin: struct{h2_liability: float64, h2_liability_se: float64, h2_observed: float64, h2_observed_se: float64, h2_z: float64}, rhemc_25bin_50rv: struct{h2_observed: float64, h2_observed_se: float64, h2_liability: float64, h2_liability_se: float64, h2_z: float64}, final: struct{h2_observed: float64, h2_observed_se: float64, h2_liability: float64, h2_liability_se: float64, h2_z: float64}}, qcflags: struct{GWAS_run: bool, defined_h2: bool, significant_z: bool, in_bounds_h2: bool, normal_lambda: bool, normal_ratio: bool, EUR_plus_1: bool, pass_all: bool}, N_ancestry_QC_pass: int32}, saige_version: str, inv_normalized: bool, pop: str, lambda_gc: float64, n_variants: int64, n_sig_variants: int64, saige_heritability: float64}))}
    at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:15)
    at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:15)
    at is.hail.utils.package$.fatal(package.scala:78)
    at is.hail.expr.ir.PruneDeadFields$.isSupertype(PruneDeadFields.scala:75)
    at is.hail.rvd.RVDCoercer.coerce(RVD.scala:31)
    at is.hail.rvd.RVD$.coerce(RVD.scala:1262)
    at is.hail.rvd.RVD.changeKey(RVD.scala:143)
    at is.hail.rvd.RVD.changeKey(RVD.scala:136)
[...]
java.util.NoSuchElementException: key not found: 0
    at scala.collection.immutable.Map$Map1.apply(Map.scala:114)
    at is.hail.expr.ir.PruneDeadFields$.$anonfun$isSupertype$2(PruneDeadFields.scala:62)
    at is.hail.expr.ir.PruneDeadFields$.$anonfun$isSupertype$2$adapted(PruneDeadFields.scala:61)
```

**Comment by danking** [comment]
@tpoterba I assume this is no longer relevant. Please re-open if it is.
