### ISSUE TITLE
handle fatal exceptions inside run_command to avoid bad python error msgs

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1096]
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-16-9cece1430bf6> in <module>()
----> 1 vds = (hc.import_vcf(vcf + 'asd'))
      2 help(vds)

/Users/tpoterba/hail/python/pyhail/context.pyc in import_vcf(self, path, force, force_bgz, header_file, npartitions, sites_only, store_gq, pp_as_pl, skip_bad_ad)
    377             pargs.append('--store-gq')
    378 
--> 379         return self.run_command(None, pargs)
    380 
    381     def index_bgen(self, path):

/Users/tpoterba/hail/python/pyhail/context.pyc in run_command(self, vds, pargs)
     43         jstate = self._jstate(vds.jvds if vds != None else None)
     44         result = cmd.run(jstate,
---> 45                          cmd_args)
     46         return VariantDataset(self, result.vds())
     47 

/Users/tpoterba/spark-1.6.2-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
    811         answer = self.gateway_client.send_command(command)
    812         return_value = get_return_value(
--> 813             answer, self.gateway_client, self.target_id, self.name)
    814 
    815         for temp_arg in temp_args:

/Users/tpoterba/spark-1.6.2-bin-hadoop2.6/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/Users/tpoterba/spark-1.6.2-bin-hadoop2.6/python/lib/py4j-0.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    306                 raise Py4JJavaError(
    307                     "An error occurred while calling {0}{1}{2}.\n".
--> 308                     format(target_id, ".", name), value)
    309             else:
    310                 raise Py4JError(

Py4JJavaError: An error occurred while calling o92.run.
: org.broadinstitute.hail.utils.package$FatalException: arguments refer to no files
	at org.broadinstitute.hail.utils.package$.fatal(package.scala:27)
	at org.broadinstitute.hail.driver.VCFImporter$class.globAllVcfs(ImportVCF.scala:17)
	at org.broadinstitute.hail.driver.ImportVCF$.globAllVcfs(ImportVCF.scala:33)
	at org.broadinstitute.hail.driver.ImportVCF$.run(ImportVCF.scala:83)
	at org.broadinstitute.hail.driver.ImportVCF$.run(ImportVCF.scala:33)
	at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:258)
	at org.broadinstitute.hail.driver.Command.run(Command.scala:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by tpoterba** [comment]
run command is gone
