### ISSUE TITLE
hl.methods.linear_regression_rows: is.hail.utils.HailException

### ISSUE THREAD

**Issue by williambrandler** [hail-is/hail#11413]
EDIT: I think this has to do with a library version change, not a hail version change

When using Hail 0.2.85, getting the following error (with code that worked with 0.2.78). 
Wondering what changes have been made between these versions that can help point to a solution?
Thanks!

code:
```
phenotypes = phenotype_df.columns[1:]

y = list(map(lambda p: hl.float64(mt[p]), phenotypes))

covs = list(map(lambda cov: mt[cov], covariate_df.columns[1:]))

x = mt.GT.n_alt_alleles()

hl_res = hl.methods.linear_regression_rows(y,x,[1]+covs)

hl_res.checkpoint(quantitative_gwas_results_chk, overwrite=True)
```

error

`is.hail.utils.HailException: 1 samples and 12 covariates (including x) implies -11 degrees of freedom.
`

stacktrace

```
Py4JJavaError                             Traceback (most recent call last)
<[command-1581524108362637]()> in <module>
      4 covs = list(map(lambda cov: mt[cov], covariate_df.columns[1:]))
      5 x = mt.GT.n_alt_alleles()
----> 6 hl_res = hl.methods.linear_regression_rows(y,x,[1]+covs)
      7 hl_res.checkpoint(quantitative_gwas_results_chk, overwrite=True)
      8 n_filtered_variants = hl_res.count()

<decorator-gen-1734> in linear_regression_rows(y, x, covariates, block_size, pass_through, weights)

/databricks/python/lib/python3.8/site-packages/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    575     def wrapper(__original_func, *args, **kwargs):
    576         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 577         return __original_func(*args_, **kwargs_)
    578 
    579     return wrapper

/databricks/python/lib/python3.8/site-packages/hail/methods/statgen.py in linear_regression_rows(y, x, covariates, block_size, pass_through, weights)
    374         ht_result = ht_result.annotate(**{f: ht_result[f][0] for f in fields})
    375 
--> 376     return ht_result.persist()
    377 
    378 

<decorator-gen-1132> in persist(self, storage_level)

/databricks/python/lib/python3.8/site-packages/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    575     def wrapper(__original_func, *args, **kwargs):
    576         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 577         return __original_func(*args_, **kwargs_)
    578 
    579     return wrapper

/databricks/python/lib/python3.8/site-packages/hail/table.py in persist(self, storage_level)
   1920             Persisted table.
   1921         """
-> 1922         return Env.backend().persist_table(self, storage_level)
   1923 
   1924     def unpersist(self) -> 'Table':

/databricks/python/lib/python3.8/site-packages/hail/backend/spark_backend.py in persist_table(self, t, storage_level)
    294 
    295     def persist_table(self, t, storage_level):
--> 296         return Table._from_java(self._jbackend.pyPersistTable(storage_level, self._to_java_table_ir(t._tir)))
    297 
    298     def unpersist_table(self, t):

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o504.pyPersistTable.
: is.hail.utils.HailException: 1 samples and 12 covariates (including x) implies -11 degrees of freedom.
	at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:11)
	at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:11)
	at is.hail.utils.package$.fatal(package.scala:78)
	at is.hail.methods.LinearRegressionRowsSingle.execute(LinearRegression.scala:51)
	at is.hail.expr.ir.functions.WrappedMatrixToTableFunction.execute(RelationalFunctions.scala:51)
	at is.hail.expr.ir.TableToTableApply.execute(TableIR.scala:2936)
	at is.hail.expr.ir.TableIR.analyzeAndExecute(TableIR.scala:57)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:27)
	at is.hail.backend.spark.SparkBackend.$anonfun$pyPersistTable$2(SparkBackend.scala:502)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:47)
	at is.hail.utils.package$.using(package.scala:638)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:47)
	at is.hail.utils.package$.using(package.scala:638)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:46)
	at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:275)
	at is.hail.backend.spark.SparkBackend.$anonfun$pyPersistTable$1(SparkBackend.scala:501)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:59)
	at is.hail.backend.spark.SparkBackend.pyPersistTable(SparkBackend.scala:493)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

**Comment by johnc1231** [comment]
Are you using the same data as you were last time? This is just saying you somehow only have one sample (column) in your matrix table

**Comment by johnc1231** [comment]
I'm closing this, please use https://discuss.hail.is/ if you have questions / need support, and we will file a new issue here if a hail bug is uncovered.

**Comment by williambrandler** [comment]
yeah this was a simple error, forgot to do one upstream processing step
