### ISSUE TITLE
Error in "transmute_entries" method

### ISSUE THREAD

**Issue by zhilizheng** [hail-is/hail#11660]
Dear hail team,

I would like to delete the gcvf information in the matrix table.  I run:

 mt = mt.transmute_entries(**mt.gvcf_info)

**1. error in the hail terminal:** 
2022-03-24 14:51:45 Hail: ERROR: Analysis exception: 'MatrixTable.transmute_entries': name collision with field indexed by ['row']: 'AS_MQRankSum'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-1132>", line 2, in transmute_entries
  File "/PATH_OMIT/.local/lib/python3.7/site-packages/hail/typecheck/check.py", line 577, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/PATH_OMIT/.local/lib/python3.7/site-packages/hail/matrixtable.py", line 1952, in transmute_entries
    check_annotate_exprs(caller, named_exprs, self._entry_indices, set())
  File "/PATH_OMIT/.local/lib/python3.7/site-packages/hail/utils/misc.py", line 468, in check_annotate_exprs
    check_collisions(caller, list(named_exprs), indices)
  File "/PATH_OMIT/.local/lib/python3.7/site-packages/hail/utils/misc.py", line 363, in check_collisions
    raise ExpressionException(msg)
hail.expr.expressions.base_expression.ExpressionException: 'MatrixTable.transmute_entries': name collision with field indexed by ['row']: 'AS_MQRankSum'

**2. Details in mt.gcvf_info:**
<StructExpression of type struct{AC: array<int32>, AF: array<float64>, AN: int32, AS_BaseQRankSum: array<float64>, AS_FS: array<float64>, AS_InbreedingCoeff: array<float64>, AS_MQ: array<float64>, AS_MQRankSum: array<float64>, AS_QD: array<float64>, AS_QUALapprox: array<int32>, AS_RAW_BaseQRankSum: str, AS_RAW_MQ: array<float64>, AS_RAW_MQRankSum: array<tuple(float64, int32)>, AS_RAW_ReadPosRankSum: array<tuple(float64, int32)>, AS_ReadPosRankSum: array<float64>, AS_SB_TABLE: array<array<int32>>, AS_SOR: array<float64>, AS_VarDP: array<int32>, BaseQRankSum: float64, ExcessHet: float64, FS: float64, InbreedingCoeff: float64, MQ: float64, MQRankSum: float64, MQ_DP: int32, QD: float64, QUALapprox: int32, RAW_GT_COUNT: array<int32>, RAW_MQandDP: array<int32>, ReadPosRankSum: float64, SOR: float64, VarDP: int32}>

**3. Hail version:** 
Hail version: 0.2.91-44b441376f9a
Apache Spark version 3.1.3

Could yo help check the code?  It's really confusing.  Thanks. 

Regards,
Zhili

**Comment by danking** [comment]
Hi @zhilizheng , if you want to drop fields, use drop:
```
mt = mt.drop('gvcf_info')
```
