### ISSUE TITLE
Invalid locus for reference genome 'GRCh37' while polygenic score calculation for 'GRCh38'

### ISSUE THREAD

**Issue by fkbyf14** [hail-is/hail#11836]
Hi!

Trying to calculate polygenic risk score with code from the [Polygenic Score Calculation](https://hail.is/docs/0.2/guides/genetics.html#polygenic-score-calculation), getting error with stacktrace:

`2022-05-14 12:09:07 Hail: INFO: Running Hail version 0.2.94-f0b38d6c436f
2022-05-14 12:09:08 SparkContext: WARN: Using an existing SparkContext; some configuration may not take effect.
2022-05-14 12:09:08 root: INFO: RegionPool: initialized for thread 30: Thread-4
2022-05-14 12:09:09 MemoryStore: INFO: Block broadcast_0 stored as values in memory (estimated size 34.3 KiB, free 434.4 MiB)
2022-05-14 12:09:09 MemoryStore: INFO: Block broadcast_0_piece0 stored as bytes in memory (estimated size 3.2 KiB, free 434.4 MiB)
2022-05-14 12:09:09 BlockManagerInfo: INFO: Added broadcast_0_piece0 in memory on 10.40.3.21:33951 (size: 3.2 KiB, free: 434.4 MiB)
2022-05-14 12:09:09 SparkContext: INFO: Created broadcast 0 from broadcast at SparkBackend.scala:311
2022-05-14 12:09:11 root: INFO: RegionPool: FREE: 64.0K allocated (64.0K blocks / 0 chunks), regions.size = 1, 0 current java objects, thread 30: Thread-4
2022-05-14 12:09:11 root: ERROR: HailException: Invalid locus '11:135009883' found. Position '135009883' is not within the range [1-135006516] for reference genome 'GRCh37'.
From is.hail.utils.HailException: /data/public/prs/ex_antonk.bim:1013423: Invalid locus '11:135009883' found. Position '135009883' is not within the range [1-135006516] for reference genome 'GRCh37'.
  offending line: 11	.	0	135009883	CT	C
	at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:30)
	at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:28)
	at is.hail.utils.package$.fatal(package.scala:78)
	at is.hail.utils.Context.wrapException(Context.scala:21)
	at is.hail.utils.WithContext.foreach(Context.scala:51)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$2(LoadPlink.scala:37)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$2$adapted(LoadPlink.scala:36)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$1(LoadPlink.scala:36)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$1$adapted(LoadPlink.scala:35)
	at is.hail.io.fs.FS.$anonfun$readLines$1(FS.scala:222)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.io.fs.FS.readLines(FS.scala:213)
	at is.hail.io.fs.FS.readLines$(FS.scala:211)
	at is.hail.io.fs.HadoopFS.readLines(HadoopFS.scala:72)
	at is.hail.io.plink.LoadPlink$.parseBim(LoadPlink.scala:35)
	at is.hail.io.plink.MatrixPLINKReader$.fromJValue(LoadPlink.scala:179)
	at is.hail.expr.ir.MatrixReader$.fromJson(MatrixIR.scala:88)
	at is.hail.expr.ir.IRParser$.matrix_ir_1(Parser.scala:1720)
	at is.hail.expr.ir.IRParser$.$anonfun$matrix_ir$1(Parser.scala:1646)
	at is.hail.utils.StackSafe$More.advance(StackSafe.scala:64)
	at is.hail.utils.StackSafe$.run(StackSafe.scala:16)
	at is.hail.utils.StackSafe$StackFrame.run(StackSafe.scala:32)
	at is.hail.expr.ir.IRParser$.$anonfun$parse_matrix_ir$1(Parser.scala:1986)
	at is.hail.expr.ir.IRParser$.parse(Parser.scala:1973)
	at is.hail.expr.ir.IRParser$.parse_matrix_ir(Parser.scala:1986)
	at is.hail.backend.spark.SparkBackend.$anonfun$parse_matrix_ir$2(SparkBackend.scala:689)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:69)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:69)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:58)
	at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:308)
	at is.hail.backend.spark.SparkBackend.$anonfun$parse_matrix_ir$1(SparkBackend.scala:688)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:59)
	at is.hail.backend.spark.SparkBackend.parse_matrix_ir(SparkBackend.scala:687)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)

is.hail.utils.HailException: Invalid locus '11:135009883' found. Position '135009883' is not within the range [1-135006516] for reference genome 'GRCh37'.
	at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:17)
	at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:17)
	at is.hail.utils.package$.fatal(package.scala:78)
	at is.hail.variant.ReferenceGenome.checkLocus(ReferenceGenome.scala:210)
	at is.hail.variant.Locus$.apply(Locus.scala:18)
	at is.hail.variant.Locus$.annotation(Locus.scala:24)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$3(LoadPlink.scala:43)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$3$adapted(LoadPlink.scala:37)
	at is.hail.utils.WithContext.foreach(Context.scala:49)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$2(LoadPlink.scala:37)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$2$adapted(LoadPlink.scala:36)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$1(LoadPlink.scala:36)
	at is.hail.io.plink.LoadPlink$.$anonfun$parseBim$1$adapted(LoadPlink.scala:35)
	at is.hail.io.fs.FS.$anonfun$readLines$1(FS.scala:222)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.io.fs.FS.readLines(FS.scala:213)
	at is.hail.io.fs.FS.readLines$(FS.scala:211)
	at is.hail.io.fs.HadoopFS.readLines(HadoopFS.scala:72)
	at is.hail.io.plink.LoadPlink$.parseBim(LoadPlink.scala:35)
	at is.hail.io.plink.MatrixPLINKReader$.fromJValue(LoadPlink.scala:179)
	at is.hail.expr.ir.MatrixReader$.fromJson(MatrixIR.scala:88)
	at is.hail.expr.ir.IRParser$.matrix_ir_1(Parser.scala:1720)
	at is.hail.expr.ir.IRParser$.$anonfun$matrix_ir$1(Parser.scala:1646)
	at is.hail.utils.StackSafe$More.advance(StackSafe.scala:64)
	at is.hail.utils.StackSafe$.run(StackSafe.scala:16)
	at is.hail.utils.StackSafe$StackFrame.run(StackSafe.scala:32)
	at is.hail.expr.ir.IRParser$.$anonfun$parse_matrix_ir$1(Parser.scala:1986)
	at is.hail.expr.ir.IRParser$.parse(Parser.scala:1973)
	at is.hail.expr.ir.IRParser$.parse_matrix_ir(Parser.scala:1986)
	at is.hail.backend.spark.SparkBackend.$anonfun$parse_matrix_ir$2(SparkBackend.scala:689)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:69)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:69)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:58)
	at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:308)
	at is.hail.backend.spark.SparkBackend.$anonfun$parse_matrix_ir$1(SparkBackend.scala:688)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:59)
	at is.hail.backend.spark.SparkBackend.parse_matrix_ir(SparkBackend.scala:687)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)

2022-05-14 12:09:11 SparkContext: INFO: Invoking stop() from shutdown hook
2022-05-14 12:09:11 AbstractConnector: INFO: Stopped Spark@15a2644a{HTTP/1.1, (http/1.1)}{0.0.0.0:4044}
2022-05-14 12:09:11 SparkUI: INFO: Stopped Spark web UI at http://10.40.3.21:4044
2022-05-14 12:09:11 MapOutputTrackerMasterEndpoint: INFO: MapOutputTrackerMasterEndpoint stopped!
2022-05-14 12:09:11 MemoryStore: INFO: MemoryStore cleared
2022-05-14 12:09:11 BlockManager: INFO: BlockManager stopped
2022-05-14 12:09:11 BlockManagerMaster: INFO: BlockManagerMaster stopped
2022-05-14 12:09:11 OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: INFO: OutputCommitCoordinator stopped!
2022-05-14 12:09:11 SparkContext: INFO: Successfully stopped SparkContext
2022-05-14 12:09:11 ShutdownHookManager: INFO: Shutdown hook called
2022-05-14 12:09:11 ShutdownHookManager: INFO: Deleting directory /tmp/spark-51f10d40-8377-4f52-a8ce-27e5f2970d9c
2022-05-14 12:09:11 ShutdownHookManager: INFO: Deleting directory /tmp/spark-acc398f9-392d-44b1-8f70-05573dad7cda
2022-05-14 12:09:11 ShutdownHookManager: INFO: Deleting directory /tmp/spark-acc398f9-392d-44b1-8f70-05573dad7cda/pyspark-aab08516-4526-40da-8556-7b50184b10eb`

prs weights and genome data for GRCh38 are in use

**Comment by daniel-goldstein** [comment]
Hi @fkbyf14, sorry for the delayed response. Could you ask this over on our forum, [discuss.hail.is](https://discuss.hail.is/)? We try to centralize our support there for discoverability and to make sure nothing goes unanswered (as can easily happen on our github issues!). Closing this issue so we can continue the discussion on the forum.
