### ISSUE TITLE
Stack trace when running pyhail shows content of wrong file

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#1184]
Below is the first part of the stack trace for for a job using pyhail with a user error in the expression language.  The text on line 7 isn't in the `utils.py` from pyspark but in my provided `utils.py` (though the error certainly did come from pyspark `utils.py`).

```
Traceback (most recent call last):
  File "/tmp/5d145552-3077-4992-8d29-3df6975c7247/genomes_qc.py", line 161, in <module>
    .export_variants(rf_path + ".va.txt.bgz", ",".join(out_metrics))
  File "/home/teamcity/TeamCityAgent1/work/591c293e3f6bfb1d/python/pyhail/dataset.py", line 489, in export_variants
  File "/tmp/5d145552-3077-4992-8d29-3df6975c7247/utils.py", line 209, in run_command
    cmd_args)
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    expression.append('va.calldata.%(pop_upper)s = gs.filter(g => %(criterion)s == "%(pop)s").callStats(v)' % input_dict)
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o93.run.
: org.broadinstitute.hail.utils.package$FatalException: `Struct' has no field `type'
``

**Comment by tpoterba** [comment]
Not replicable, and I think this is probably fixed
