### ISSUE TITLE
"Self-suppression not permitted"

### ISSUE THREAD

**Issue by bavila-broad** [hail-is/hail#1185]
Tried running 
`hail read -i file:///mnt/lustre/bavila/denovo/myrioux3.vep.vds exportvcf -o file:///mnt/lustre/bavila/denovo/myrioux3.vep.vcf`

got the following
```
hail: info: running: read -i file:///mnt/lustre/bavila/denovo/myrioux3.vep.vds
[Stage 1:======================================================>(255 + 1) / 256]hail: info: running: exportvcf -o file:///mnt/lustre/bavila/denovo/myrioux3.vep.vcf
[Stage 2:=====>                                            (2117 + 256) / 19042]hail: exportvcf: caught exception: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2137 in stage 2.0 failed 4 times, most recent failure: Lost task 2137.3 in stage 2.0 (TID 3028, nid00013.urika.com): java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.lang.Throwable.addSuppressed(Throwable.java:1043)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1219)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1116)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1095)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Full error and log below:

[error.txt](https://github.com/hail-is/hail/files/652656/error.txt)
[hail.log.txt](https://github.com/hail-is/hail/files/652665/hail.log.txt)

**Comment by johnc1231** [comment]
From googling, this seems like something that was probably relatively out of our control. Like cluster ran out of disk space, communication failed, etc. Considering no one else has complained about this (to my knowledge anyway), this is probably a safe issue to close, assuming you haven't had this problem since. @tpoterba , does this seem reasonable?
