### ISSUE TITLE
out of memory error when writing on the cloud

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#1186]
writing a simple command such as read and write produces different type of error, but all related to memory issues. 
The most explicit error is: 

```
error='Cannot allocate memory' (errno=12)
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 7376207872 bytes for committing reserved memory.
```

But also get this issue in other occasions:

```
ExecutorLostFailure (executor 2265 exited caused by one of the running tasks) Reason: Container marked as failed: container_1481808189977_0001_01_002296 on host: gnomadpsychk-sw-wpt8.c.wgspd-147615.internal. Exit status: 50. Diagnostics: Exception from container-launch.
Container id: container_1481808189977_0001_01_002296
Exit code: 50
Stack trace: ExitCodeException exitCode=50:
       	at org.apache.hadoop.util.Shell.runCommand(Shell.java:582)
       	at org.apache.hadoop.util.Shell.run(Shell.java:479)
       	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
       	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
       	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
       	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50

Driver stacktrace:
```

Log for this last error is here: https://storage.googleapis.com/wgspd_urv/hailNEW.log

I tried different projects and get the same error, both with pyhail and native hail. I don't see the same error when running on cray.

**Comment by danking** [comment]
I've replicated the issue

invocation:
```bash
./pyhail-submit cluster-2 foo.py
```
`foo.py`:
```python
#!/usr/bin/python

from pyhail import *

hc = HailContext(log="/tmp/hail.log")

(hc.read(<andrea's file here>)
  .write('gs://hail-1kg/trash.vds'))
```
source of the error:
```
2016-12-15 19:05:43 ERROR Utils:91 - Uncaught exception in thread task-result-getter-1
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuffer.append(StringBuffer.java:270)
        at org.apache.log4j.helpers.PatternParser$LiteralPatternConverter.format(PatternParser.java:419)
        at org.apache.log4j.PatternLayout.format(PatternLayout.java:506)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:400)
        at org.apache.spark.internal.Logging$class.logWarning(Logging.scala:66)
        at org.apache.spark.scheduler.TaskSetManager.logWarning(TaskSetManager.scala:52)
        at org.apache.spark.scheduler.TaskSetManager.handleFailedTask(TaskSetManager.scala:693)
        at org.apache.spark.scheduler.TaskSchedulerImpl.handleFailedTask(TaskSchedulerImpl.scala:421)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$2.apply$mcV$sp(TaskResultGetter.scala:139)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$2.apply(TaskResultGetter.scala:124)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$2.apply(TaskResultGetter.scala:124)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1953)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$3.run(TaskResultGetter.scala:124)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
`pyhail-submit`:
```bash
#!/bin/bash

if [ $# -ne 2 ]; then
    echo 'usage: gcp-pyhail-submit <cluster> <py-file>'
    exit 1
fi

cluster=$1
script=$2

echo cluster = $cluster
echo script = $script

HASH=`gsutil cat gs://hail-common/latest-hash.txt`

JAR_FILE=hail-hail-is-master-all-spark2.0.2-$HASH.jar
JAR=gs://hail-common/$JAR_FILE

PYHAIL_ZIP=gs://hail-common/pyhail-hail-is-master-$HASH.zip

gcloud dataproc jobs submit pyspark \
       $script \
       --cluster $cluster \
       --files=$JAR \
       --py-files=$PYHAIL_ZIP \
       --properties="spark.driver.extraClassPath=./$JAR_FILE,spark.executor.extraClassPath=./$JAR_FILE" \
       --
```
cluster JSON:
```
{
  "projectId": "broad-ctsa",
  "clusterName": "cluster-2",
  "config": {
    "configBucket": "dataproc-7f9e9d5e-03bd-4e95-bea1-fe0321239b35-us",
    "gceClusterConfig": {
      "zoneUri": "https://www.googleapis.com/compute/v1/projects/broad-ctsa/zones/us-central1-f",
      "networkUri": "https://www.googleapis.com/compute/v1/projects/broad-ctsa/global/networks/default",
      "serviceAccountScopes": [
        "https://www.googleapis.com/auth/bigquery",
        "https://www.googleapis.com/auth/bigtable.admin.table",
        "https://www.googleapis.com/auth/bigtable.data",
        "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
        "https://www.googleapis.com/auth/devstorage.full_control",
        "https://www.googleapis.com/auth/devstorage.read_write",
        "https://www.googleapis.com/auth/logging.write"
      ]
    },
    "masterConfig": {
      "numInstances": 1,
      "instanceNames": [
        "cluster-2-m"
      ],
      "imageUri": "https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-1-1-20161212-154751",
      "machineTypeUri": "https://www.googleapis.com/compute/v1/projects/broad-ctsa/zones/us-central1-f/machineTypes/n1-standard-4",
      "diskConfig": {
        "bootDiskSizeGb": 10
      }
    },
    "workerConfig": {
      "numInstances": 2,
      "instanceNames": [
        "cluster-2-w-0",
        "cluster-2-w-1"
      ],
      "imageUri": "https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-1-1-20161212-154751",
      "machineTypeUri": "https://www.googleapis.com/compute/v1/projects/broad-ctsa/zones/us-central1-f/machineTypes/n1-standard-4",
      "diskConfig": {
        "bootDiskSizeGb": 10
      }
    },
    "softwareConfig": {
      "imageVersion": "1.1.15",
      "properties": {
        "distcp:mapreduce.map.java.opts": "-Xmx2457m",
        "distcp:mapreduce.map.memory.mb": "3072",
        "distcp:mapreduce.reduce.java.opts": "-Xmx4915m",
        "distcp:mapreduce.reduce.memory.mb": "6144",
        "mapred:mapreduce.map.cpu.vcores": "1",
        "mapred:mapreduce.map.java.opts": "-Xmx2457m",
        "mapred:mapreduce.map.memory.mb": "3072",
        "mapred:mapreduce.reduce.cpu.vcores": "2",
        "mapred:mapreduce.reduce.java.opts": "-Xmx4915m",
        "mapred:mapreduce.reduce.memory.mb": "6144",
        "mapred:yarn.app.mapreduce.am.command-opts": "-Xmx4915m",
        "mapred:yarn.app.mapreduce.am.resource.cpu-vcores": "2",
        "mapred:yarn.app.mapreduce.am.resource.mb": "6144",
        "spark:spark.driver.maxResultSize": "1920m",
        "spark:spark.driver.memory": "3840m",
        "spark:spark.executor.cores": "2",
        "spark:spark.executor.memory": "5586m",
        "spark:spark.yarn.am.memory": "5586m",
        "spark:spark.yarn.am.memoryOverhead": "558",
        "spark:spark.yarn.executor.memoryOverhead": "558",
        "yarn:yarn.nodemanager.resource.memory-mb": "12288",
        "yarn:yarn.scheduler.maximum-allocation-mb": "12288",
        "yarn:yarn.scheduler.minimum-allocation-mb": "1024"
      }
    }
  },
  "status": {
    "state": "RUNNING",
    "stateStartTime": "2016-12-15T19:00:51.004Z"
  },
  "clusterUuid": "fb371071-cdd1-4bed-bd1b-3ce3049d07e5",
  "statusHistory": [
    {
      "state": "CREATING",
      "stateStartTime": "2016-12-15T18:59:19.745Z"
    }
  ],
  "metrics": {}
}
```

# Analysis Thus Far

The job doesn't terminate on its own. After stopping the job in the Google Cloud UI, subsequent jobs don't seem to be accepted (i.e. they hang before I see the Spark progress bar).

The source of the error is a log statement. Apparently a task failure is triggering a giant log statement. The [log statement (from Spark 2.0 branch)](https://github.com/apache/spark/blob/branch-2.0/core/src/main/scala/org/apache/spark/scheduler/TaskSetManager.scala#L693) seems innocuous.

So the real question is why are the tasks failing?

**Comment by danking** [comment]
I looked at the Spark worker logs by setting up the SSH tunnel (according to laurent's cloud post) and going to the Executor tab of the spark history server page.

It seems we're running into this issue: https://issues.apache.org/jira/browse/SPARK-16845

This is definitely because Andrea's VDS has lots of annotations. Here's a quote from that Spark issue:

> I've been struggling to duplicate this and finally came up with a strategy that duplicates it in a spark-shell. It's a combination of a wide dataset with nested (array) structures and performing a union that seem to trigger it.

**Comment by danking** [comment]
It's been 14 days since any activity on [the PR that fixes this issue](https://github.com/apache/spark/pull/15480). Spark 1.6 is probably not affected. I guess we'll have to wait for this PR to get merged.

**Comment by tpoterba** [comment]
We have characterized this issue well, and it will be fixed in an imminent spark release.
