### ISSUE TITLE
Crash when dividing Array[Int] / Int

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#1204]
The stack trace tells the story. This was a single command `annotateglobal exprbysample`

```
[Stage 0:======================================================>(199 + 1) / 200]hail: info: running: annotateglobal exprbysample -c 'global.x = [4,5] / 3'
hail: info: running: showglobals
hail: showglobals: caught exception: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
    at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
    at org.broadinstitute.hail.expr.JSONAnnotationImpex$.exportAnnotation(AnnotationImpex.scala:259)
    at org.broadinstitute.hail.expr.JSONAnnotationImpex$$anonfun$exportAnnotation$8.apply(AnnotationImpex.scala:266)
    at org.broadinstitute.hail.expr.JSONAnnotationImpex$$anonfun$exportAnnotation$8.apply(AnnotationImpex.scala:266)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.broadinstitute.hail.expr.JSONAnnotationImpex$.exportAnnotation(AnnotationImpex.scala:266)
    at org.broadinstitute.hail.expr.JSONAnnotationImpex$$anonfun$exportAnnotation$12.apply(AnnotationImpex.scala:284)
    at org.broadinstitute.hail.expr.JSONAnnotationImpex$$anonfun$exportAnnotation$12.apply(AnnotationImpex.scala:284)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.broadinstitute.hail.expr.JSONAnnotationImpex$.exportAnnotation(AnnotationImpex.scala:284)
    at org.broadinstitute.hail.expr.Type.toJSON(Type.scala:135)
    at org.broadinstitute.hail.driver.ShowGlobalAnnotations$.run(ShowGlobalAnnotations.scala:32)
    at org.broadinstitute.hail.driver.ShowGlobalAnnotations$.run(ShowGlobalAnnotations.scala:8)
    at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:259)
    at org.broadinstitute.hail.driver.Main$.runCommand(Main.scala:91)
    at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:115)
    at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:115)
    at org.broadinstitute.hail.utils.package$.time(package.scala:119)
    at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:114)
    at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:108)
    at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
    at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
    at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
    at org.broadinstitute.hail.driver.Main$.runCommands(Main.scala:108)
    at org.broadinstitute.hail.driver.Main$.main(Main.scala:233)
    at org.broadinstitute.hail.driver.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by lfrancioli** [comment]
thanks!!
