### ISSUE TITLE
wrong partition number with spark 1.6 

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#1213]
I get this error when using the last hail version built on Spark 1.6

``` hail: annotatevariants vds: caught exception: java.lang.IllegalArgumentException: requirement failed: nPartitions = 2847, ranges = 2844
       	at scala.Predef$.require(Predef.scala:233)
       	at org.broadinstitute.hail.sparkextras.OrderedPartitioner.<init>(OrderedPartitioner.scala:27)
       	at org.broadinstitute.hail.sparkextras.OrderedPartitioner$.read(OrderedPartitioner.scala:110)
       	at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$8.apply(VariantSampleMatrix.scala:185)
       	at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$8.apply(VariantSampleMatrix.scala:184)
       	at org.broadinstitute.hail.utils.richUtils.RichHadoopConfiguration$.readObjectFile$extension(RichHadoopConfiguration.scala:205)
       	at org.broadinstitute.hail.variant.VariantSampleMatrix$.read(VariantSampleMatrix.scala:184)
       	at org.broadinstitute.hail.driver.Read$$anonfun$1.apply(Read.scala:41)
       	at org.broadinstitute.hail.driver.Read$$anonfun$1.apply(Read.scala:41)
       	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
       	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
       	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
       	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
       	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
       	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
       	at org.broadinstitute.hail.driver.Read$.run(Read.scala:41)
       	at org.broadinstitute.hail.driver.Read$.run(Read.scala:9)
       	at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:259)
       	at org.broadinstitute.hail.driver.Command.run(Command.scala:264)
       	at org.broadinstitute.hail.driver.AnnotateVariantsVDS$.run(AnnotateVariantsVDS.scala:61)
       	at org.broadinstitute.hail.driver.AnnotateVariantsVDS$.run(AnnotateVariantsVDS.scala:9)```


however, the same commands work on the hail version built on Spark 2. 
Here the log: https://storage.googleapis.com/maryam_lipids/hailL.log

thanks

**Comment by jbloom22** [comment]
Closing as we've moved to Spark 2.

**Comment by andgan** [comment]
No wait. So there is no hope to get the bug fixed?
I cannot move the spark 2 because of the annotation issue.

**Comment by cseed** [comment]
This was sorted by setting the following parameters in submit: `spark.hadoop.mapreduce.input.fileinputformat.split.minsize=1099511627776,spark.hadoop.parquet.block.size=1099511627776`.  We're not supporting Spark 1 now so I'm not looking into this further.
