### ISSUE TITLE
IllegalArgumentException: array element type mismatch

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#1284]
this the exception (attached the log):

``` 
 File "/tmp/7f8f775e-2ec3-40ee-ad5b-3e4df5649682/annotate_and_generate_scores_cloud.py", line 24, in <module>
    .vep(config='/vep/vep-gcloud.properties', root='va.vep', force=True)
  File "/home/teamcity/TeamCityAgent1/work/591c293e3f6bfb1d/python/hail/dataset.py", line 3095, in vep
  File "/home/teamcity/TeamCityAgent1/work/591c293e3f6bfb1d/python/hail/context.py", line 81, in run_command
  File "/home/teamcity/TeamCityAgent1/work/591c293e3f6bfb1d/python/hail/java.py", line 5, in jarray
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_collections.py", line 228, in __setitem__
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_collections.py", line 211, in __set_item
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 323, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling None.None. Trace:
java.lang.IllegalArgumentException: array element type mismatch
           at java.lang.reflect.Array.set(Native Method)
           at py4j.commands.ArrayCommand.setArray(ArrayCommand.java:141)
           at py4j.commands.ArrayCommand.execute(ArrayCommand.java:94)
           at py4j.GatewayConnection.run(GatewayConnection.java:214)
           at java.lang.Thread.run(Thread.java:745) 
```

[hail.txt](https://github.com/hail-is/hail/files/725407/hail.txt)

**Comment by tpoterba** [comment]
Need your python script too

**Comment by andgan** [comment]
```

**Comment by andgan** [comment]
```

**Comment by andgan** [comment]
```

**Comment by andgan** [comment]
Notice that this script is working with spark 1.6, the error appears with spark 2.

```
exac_vds_split = hc.read(root + 'andrea_subset_splitmulti_hard.vds')
dbNSFP_vds = hc.read(root + 'dbNSFP_3.2a_variant.filtered.allhg19_nodup.vds')
discovEHR_vds = hc.read(root + 'discoverEHR.vds')
exacV2_vds = hc.read(root + 'exacV2_split_variants_non_in_andrea_subset.vds')
fin_vds = hc.read(root + 'finnish_noexac_subset.vds')

(exac_vds_split
# .filter_variants_expr('v.contig=="7" && v.start > 75013221 && v.start < 76253221', keep=True)
# .filter_variants_expr('v.contig=="20"', keep=True)
.annotate_variants_expr('va = drop(va, vep)')
.vep(config='/vep/vep-gcloud.properties', root='va.vep', force=True)
.write(stroot + '/andrea_subset_splitmulti_hard_vep.vds', overwrite=True))


exac_vds_split_vep = hc.read(stroot + 'andrea_subset_splitmulti_hard_vep.vds')

(exac_vds_split_vep
.annotate_global_list(root + 'all_scores_reduced.scores', root='global.allgenes')
.annotate_global_expr_by_sample('global.allgenes = global.allgenes.map(x => x.split("\\t"))')
.variant_qc()
.annotate_variants_vds(discovEHR_vds,root='va.EHR')
.annotate_variants_vds(exacV2_vds,root='va.EXACV2')
.annotate_variants_vds(fin_vds,root='va.FIN')
.annotate_variants_table(root + 'clinvar_clean.txt','Variant(Variant)', root='va.clinvar')
.annotate_variants_table(root + 'lethal_clean.txt','Variant(Variant)', root='va.lethal')
.annotate_variants_expr(
	"""
	va.clinvar.yes=if(isMissing(va.clinvar.Variant)) 0 else 1,
	va.lethal.yes=if(isMissing(va.lethal.Variant)) 0 else 1,
	va.nNonRef = gs.filter(g => g.isCalledNonRef).count()
	""")
.annotate_variants_expr(
	"""
	va.freq.AF01 = (va.qc.AF < 0.01),
	va.freq.AF001 = (va.qc.AF < 0.001),
	va.freq.DOUBLE = (va.qc.AC == 2),
	va.freq.SING = (va.nNonRef == 1),
	va.freq.URVEXACV2 = (va.nNonRef == 1 && isMissing(va.EXACV2.qc.AC)),
	va.freq.URVEXACV2EHR = (va.nNonRef == 1 && isMissing(va.EXACV2.qc.AC) && isMissing(va.EHR.info.AF) && isMissing(va.FIN.qc.AC)),
	va.freq.DOUBLEEXACV2EHR = (va.qc.AC < 3 && isMissing(va.EXACV2.qc.AC)  && isMissing(va.EHR.info.AF) && isMissing(va.FIN.qc.AC))
	""")
.annotate_variants_expr('va.geneann.transcript_canonicals = va.vep.transcript_consequences.filter(tc => tc.canonical == 1)')
.annotate_variants_expr(
	"""
	va.geneann.most_severe_csq = 
	let x = va.geneann.transcript_canonicals.map(y => y.consequence_terms.toSet) in 
	if (isMissing(x)) va.vep.most_severe_consequence
	else if (x.exists(tc => tc.contains("transcript_ablation"))) "transcript_ablation"
	else if (x.exists(tc => tc.contains("splice_acceptor_variant"))) "splice_acceptor_variant"
	else if (x.exists(tc => tc.contains("splice_donor_variant"))) "splice_donor_variant"
	else if (x.exists(tc => tc.contains("stop_gained"))) "stop_gained"
	else if (x.exists(tc => tc.contains("frameshift_variant"))) "frameshift_variant"
	else if (x.exists(tc => tc.contains("stop_lost"))) "stop_lost"
	else if (x.exists(tc => tc.contains("start_lost"))) "start_lost"
	else if (x.exists(tc => tc.contains("transcript_amplification"))) "transcript_amplification"
	else if (x.exists(tc => tc.contains("inframe_insertion"))) "inframe_insertion"
	else if (x.exists(tc => tc.contains("inframe_deletion"))) "inframe_deletion"
	else if (x.exists(tc => tc.contains("missense_variant"))) "missense_variant"
	else if (x.exists(tc => tc.contains("protein_altering_variant"))) "protein_altering_variant"
	else if (x.exists(tc => tc.contains("splice_region_variant"))) "splice_region_variant"
	else if (x.exists(tc => tc.contains("incomplete_terminal_codon_variant"))) "incomplete_terminal_codon_variant"
	else if (x.exists(tc => tc.contains("stop_retained_variant"))) "stop_retained_variant"
	else if (x.exists(tc => tc.contains("synonymous_variant"))) "synonymous_variant"
	else if (x.exists(tc => tc.contains("coding_sequence_variant"))) "coding_sequence_variant"
	else if (x.exists(tc => tc.contains("mature_miRNA_variant"))) "mature_miRNA_variant"
	else if (x.exists(tc => tc.contains("5_prime_UTR_variant"))) "5_prime_UTR_variant" 
	else if (x.exists(tc => tc.contains("3_prime_UTR_variant"))) "3_prime_UTR_variant"
	else if (x.exists(tc => tc.contains("non_coding_transcript_exon_variant"))) "non_coding_transcript_exon_variant"
	else if (x.exists(tc => tc.contains("intron_variant"))) "intron_variant"
	else if (x.exists(tc => tc.contains("NMD_transcript_variant"))) "NMD_transcript_variant"
	else if (x.exists(tc => tc.contains("non_coding_transcript_variant"))) "non_coding_transcript_variant"
	else if (x.exists(tc => tc.contains("upstream_gene_variant"))) "upstream_gene_variant"
	else if (x.exists(tc => tc.contains("downstream_gene_variant"))) "downstream_gene_variant"
	else if (x.exists(tc => tc.contains("TFBS_ablation"))) "TFBS_ablation"
	else if (x.exists(tc => tc.contains("TFBS_amplification"))) "TFBS_amplification"
	else if (x.exists(tc => tc.contains("TF_binding_site_variant"))) "TF_binding_site_variant"
	else if (x.exists(tc => tc.contains("regulatory_region_ablation"))) "regulatory_region_ablation"
	else if (x.exists(tc => tc.contains("regulatory_region_amplification"))) "regulatory_region_amplification"
	else if (x.exists(tc => tc.contains("feature_elongation"))) "feature_elongation"
	else if (x.exists(tc => tc.contains("regulatory_region_variant"))) "regulatory_region_variant"
	else if (x.exists(tc => tc.contains("feature_truncation"))) "feature_truncation"
	else if (x.exists(tc => tc.contains("intergenic_variant"))) "intergenic_variant"
	else va.vep.most_severe_consequence
	""")
.annotate_variants_expr(
	"""
	va.geneann.gene = 
	if (va.geneann.transcript_canonicals.exists(tc => tc.consequence_terms.toSet.contains(va.geneann.most_severe_csq))) (va.geneann.transcript_canonicals.find(tc => tc.canonical == 1 && tc.consequence_terms.toSet.contains(va.geneann.most_severe_csq)).gene_symbol)
	else va.vep.transcript_consequences.find(tc => tc.consequence_terms.toSet.contains(va.geneann.most_severe_csq)).gene_symbol
	""")
.annotate_variants_expr(
	"""
	va.geneann.LOFTEElof_flags = 
	if (va.geneann.transcript_canonicals.exists(tc => tc.consequence_terms.toSet.contains(va.geneann.most_severe_csq))) (va.geneann.transcript_canonicals.find(tc => tc.canonical == 1 && tc.consequence_terms.toSet.contains(va.geneann.most_severe_csq)).lof)
	else va.vep.transcript_consequences.find(tc => tc.consequence_terms.toSet.contains(va.geneann.most_severe_csq)).lof_flags
	""")
.annotate_variants_expr('va.geneann.LOFTEElof = (if (va.geneann.LOFTEElof_flags=="HC") 1 else 0)')
.annotate_variants_vds(dbNSFP_vds,root='va.dbNSFP')
.annotate_variants_expr(
	"""
	va.geneann.damascore = (if ("D" ~ va.dbNSFP.SIFT_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.PROVEAN_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.Polyphen2_HDIV_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.Polyphen2_HVAR_pred) 1 else 0) + (if ("D" ~ va.dbNSFP.LRT_pred) 1 else 0) + (if ("[HM]" ~ va.dbNSFP.MutationAssessor_pred) 1 else 0) + (if ("[AD]" ~ va.dbNSFP.MutationTaster_pred) 1 else 0)
	""")
.annotate_variants_expr(
	"""
	va.geneann.LOF = (if (va.geneann.most_severe_csq == "frameshift_variant" || va.geneann.most_severe_csq == "transcript_ablation" || va.geneann.most_severe_csq == "splice_acceptor_variant" || va.geneann.most_severe_csq == "splice_donor_variant" || va.geneann.most_severe_csq == "stop_gained") 1 else 0)
	""")
.annotate_variants_expr(
	"""
	va.geneann.missense = (if (va.geneann.most_severe_csq == "missense_variant" || va.geneann.most_severe_csq == "inframe_insertion" || va.geneann.most_severe_csq == "inframe_deletion") 1 else 0)
	""")
.annotate_variants_expr(
	"""
	va.geneann.LOFdamaging = (if (va.geneann.LOF==1 || (va.geneann.missense==1 && va.geneann.damascore >= 7)) 1 else 0),
	va.geneann.dama1 = (if ((va.geneann.missense==1 && va.geneann.damascore >= 1)) 1 else 0), 
	va.geneann.dama3 = (if ((va.geneann.missense==1 && va.geneann.damascore >= 3)) 1 else 0), 
	va.geneann.dama7 = (if ((va.geneann.missense==1 && va.geneann.damascore >= 7)) 1 else 0), 
	va.geneann.synonymous = (if (va.geneann.most_severe_csq == "synonymous_variant") 1 else 0)
	""")
.write(stroot + '/andrea_subset_splitmulti_hard_anno.vds', overwrite=True))


exac_vds_split_anno = hc.read(stroot + '/andrea_subset_splitmulti_hard_anno.vds')
```

**Comment by tpoterba** [comment]
This log doesn't have the mentioned exception. Closing because it's stale.
