### ISSUE TITLE
keytable to dataframe issue

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1311]
```
Traceback (most recent call last):
  File "/tmp/09d98b2f-4a41-4652-9eba-e319bfda2ca4/sandbox.py", line 17, in <module>
    pprint(hc.read('%s/variantqc/exacv2_rf.vds' % root, sites_only=True).filter_variants_intervals('gs://exac2/temp').head())
  File "/tmp/09d98b2f-4a41-4652-9eba-e319bfda2ca4/utils.py", line 201, in head
    return json.loads(self.variants_keytable().to_dataframe().toJSON().first())
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1328, in first
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1310, in take
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 933, in runJob
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    for criterion, pop in criteria_pops:
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 20 times, most recent failure: Lost task 0.19 in stage 5.0 (TID 20022, exac-sw-3pdd.c.broad-mpg-gnomad.internal): java.lang.ClassCastException: scala.Tuple2 cannot be cast to org.apache.spark.sql.Row
```

**Comment by tpoterba** [comment]
Is this still a problem? I imagine we fixed this bug?

**Comment by konradjk** [comment]
YES!
