### ISSUE TITLE
Batch ServiceBackend: calling run() on a batch with 0 jobs leads to a cryptic ValueError

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#13132]
### What happened?

Minor issue: the following code produces a cryptic ValueError:

```
import hailtop.batch as hb
b = hb.Batch(backend=hb.ServiceBackend())
b.run()
```

Example:
<img width="559" alt="image" src="https://github.com/hail-is/hail/assets/6240170/a62295fb-094a-48b1-9959-eadfad1c3adc">

Here is the full stack trace:
```
Traceback (most recent call last):
  File "single_sample_vcfs/single_sample_vcf_pipeline.py", line 154, in <module>
    main()
  File "single_sample_vcfs/single_sample_vcf_pipeline.py", line 95, in main
    b.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hailtop/batch/batch.py", line 687, in run
    run_result = self._backend._run(self, dry_run, verbose, delete_scratch_on_exit, **backend_kwargs)  # pylint: disable=assignment-from-no-return
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hailtop/batch/backend.py", line 543, in _run
    self._async_run(batch, dry_run, verbose, delete_scratch_on_exit, wait, open, disable_progress_bar, callback, token, **backend_kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hailtop/utils/utils.py", line 152, in async_to_blocking
    return loop.run_until_complete(task)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hailtop/batch/backend.py", line 792, in _async_run
    starting_job_id = min(j._client_job.job_id for j in unsubmitted_jobs)
ValueError: min() arg is an empty sequence
```

### Version

0.2.115

**Comment by daniel-goldstein** [comment]
This should have been fixed in #12953. Can you try updating to 0.2.117 and see if the issue persists? Please reopen if it does.
