### ISSUE TITLE
java.lang.ClassNotFoundException: is.hail.sparkextras.ReorderedPartitionsRDDPartition

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1360]
Getting this over the past few days when doing, well, basically any query. Log: [hail.log.txt](https://github.com/hail-is/hail/files/755839/hail.log.txt)

```
Caused by: java.lang.ClassNotFoundException: is.hail.sparkextras.ReorderedPartitionsRDDPartition
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

**Comment by konradjk** [comment]
An update: this seems to happen when running from an interactive shell as I'm setting up my own jar and python directory, so maybe I'm doing something wrong? Happens on the cloud but not locally...

**Comment by konradjk** [comment]
Btw, this happens when your jar is not on a shared filesystem. D'oh. I'll close this now, but just in case anyone has this issue, this is what a missing jar looks like.
