### ISSUE TITLE
[query] org.apache.hadoop.mapreduce.lib.input.TextInputFormat

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13706]
### What happened?

Local java tests failing. Caused by https://github.com/hail-is/hail/pull/13551

```
java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.lib.input.TextInputFormat
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

### Version

0.2.124

**Comment by danking** [comment]
The [TextInputFormat](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/mapred/TextInputFormat.html) class clearly comes from hadoop. It's no longer in the location from which we import it. We must get it from some other dependency.

OK. So, before my simplification of build.gradle, we used a configuration called `compile` and another one called `testCompile`. [Neither of those exist in modern gradle, apparently](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph). I found a side-note about the `compile` configuration [here](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_dependency_management_overview) (search for "compile"):

> <div class="admonitionblock note" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px; padding: 0px; direction: ltr;">

Why no compile configuration?The Java Library Plugin has historically used the compile configuration for dependencies that are required to both compile and run a project’s production code. It is now deprecated, and will issue warnings when used, because it doesn’t distinguish between dependencies that impact the public API of a Java library project and those that don’t. You can learn more about the importance of this distinction in Building Java libraries.
> **Why no compile configuration?**
> The Java Library Plugin has historically used the compile configuration for dependencies that are required to both compile and run a project’s production code. It is now deprecated, and will issue warnings when used, because it doesn’t distinguish between dependencies that impact the public API of a Java library project and those that don’t. You can learn more about the importance of this distinction in [Building Java libraries](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:building_java_libraries).

OK, so, we used to just dump everything into our runtime dependencies. I changed it so that we have three kinds of dependencies:
1. `shadow`: these are provided by Dataproc/QoB at run-time. They are not in any JAR. They are not on the `testRuntimeClasspath` or `runtimeClasspath`. They are on the `testCompileClasspath` because I [explicitly requested](https://github.com/hail-is/hail/blob/main/hail/build.gradle#L98) that `testCompileOnly` bring in our `shadow` dependencies.
2. `implementation`: these are included in all class paths and in shadow JARs (but not "thin" jars generated by `./gradlew jar`).
3. `testImplementation`: these are included in test class paths and JARs

Our test code references these third-party classes:
```
import breeze.linalg.DenseMatrix
import breeze.linalg._
import breeze.linalg.{*, diag, DenseMatrix => BDM, DenseVector => BDV}
import breeze.linalg.{DenseMatrix => BDM, _}
import breeze.linalg.{DenseMatrix => BDM}
import breeze.linalg.{DenseMatrix, DenseVector, eigSym, svd}
import breeze.linalg.{DenseMatrix, DenseVector}
import breeze.linalg.{DenseMatrix, Matrix, Vector}
import breeze.linalg.{Vector => BVector}
import htsjdk.samtools.reference.ReferenceSequenceFileFactory
import htsjdk.samtools.util.BlockCompressedFilePointerUtil
import htsjdk.tribble.readers.{TabixReader => HtsjdkTabixReader}
import org.apache.avro.SchemaBuilder
import org.apache.avro.file.DataFileWriter
import org.apache.avro.generic.{GenericDatumWriter, GenericRecord, GenericRecordBuilder}
import org.apache.commons.io.IOUtils
import org.apache.commons.math3.distribution.ChiSquaredDistribution
import org.apache.commons.math3.distribution.{ChiSquaredDistribution, NormalDistribution}
import org.apache.commons.math3.random.JDKRandomGenerator
import org.apache.commons.math3.util.CombinatoricsUtils.factorialLog
import org.apache.hadoop
import org.apache.log4j.{ConsoleAppender, PatternLayout}
import org.apache.spark.SparkContext
import org.apache.spark.SparkException
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.mllib.linalg.distributed.{DistributedMatrix, IndexedRow, IndexedRowMatrix}
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.Row
import org.apache.spark.storage.StorageLevel
import org.apache.{hadoop => hd}
import org.json4s.JValue
import org.json4s.JsonAST._
import org.json4s._
import org.json4s.jackson.JsonMethods
import org.json4s.jackson.JsonMethods._
import org.json4s.jackson.Serialization
import org.json4s.jackson.{JsonMethods, Serialization}
import org.json4s.{DefaultFormats, Formats}
import org.sparkproject.guava.util.concurrent.MoreExecutors
```

We explicitly depend on
- `htsjdk`
- `breeze`
- `json4s`

That leaves:

```
import org.apache.avro.SchemaBuilder
import org.apache.avro.file.DataFileWriter
import org.apache.avro.generic.{GenericDatumWriter, GenericRecord, GenericRecordBuilder}
import org.apache.commons.io.IOUtils
import org.apache.commons.math3.distribution.ChiSquaredDistribution
import org.apache.commons.math3.distribution.{ChiSquaredDistribution, NormalDistribution}
import org.apache.commons.math3.random.JDKRandomGenerator
import org.apache.commons.math3.util.CombinatoricsUtils.factorialLog
import org.apache.hadoop
import org.apache.log4j.{ConsoleAppender, PatternLayout}
import org.apache.spark.SparkContext
import org.apache.spark.SparkException
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.mllib.linalg.distributed.{DistributedMatrix, IndexedRow, IndexedRowMatrix}
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.Row
import org.apache.spark.storage.StorageLevel
import org.apache.{hadoop => hd}
import org.sparkproject.guava.util.concurrent.MoreExecutors
```

I could try to carefully figure out which one of `shadow` are needed for tests and which are not, but that seems annoying. Fix [here](https://github.com/hail-is/hail/pull/13740).
