### ISSUE TITLE
[batch] Batch workers log with ERROR severity when job is canceled

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#13803]
### What happened?

Job cancellation by users or the batch system is a normal operation, yet error logs are emitted when the operation occurs. This will raise false alarms as alerts are sent when error logs are observed. The batch driver, and the system moreover, should not emit ERROR logs for expected operations.

### Version

0.2.124

### Relevant log output

```shell
Example log:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 1013, in _run_until_done_or_deleted
    return await run_until_done_or_deleted(self.deleted_event, f, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 681, in run_until_done_or_deleted
    raise StepInterruptedError
StepInterruptedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 1888, in run_container
    await container.run(on_completion)
  File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 918, in run
    await self.wait()
  File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 904, in wait
    await self._run_fut
  File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 1015, in _run_until_done_or_deleted
    raise ContainerDeletedError from e
ContainerDeletedError
```

**Comment by danking** [comment]
@danking check if you fixed this

**Comment by danking** [comment]
I fixed this but a new thing arose: https://github.com/hail-is/hail/issues/13906
