### ISSUE TITLE
[fs] largeDirectoryOperations

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13827]
### What happened?

Something is wrong with the largeDirectoryOperations test. It occasionally fails because a file still exists. I do not know why.

Example: https://batch.hail.is/batches/8059890/jobs/202
```
starting test is.hail.io.fs.GoogleStorageFSSuite.largeDirectoryOperations...
Exception:
org.scalatest.exceptions.TestFailedException: files not deleted:
gs://hail-test-ezlis/fs-suite/delete-many-files/c287f9de-7e80-4d34-b22e-eb91736aeaac/467.suffix
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
	at org.scalatest.testng.TestNGSuite.newAssertionFailedException(TestNGSuite.scala:67)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
	at is.hail.io.fs.FSSuite.largeDirectoryOperations(FSSuite.scala:413)
	at is.hail.io.fs.FSSuite.largeDirectoryOperations$(FSSuite.scala:398)
	at is.hail.io.fs.GoogleStorageFSSuite.largeDirectoryOperations(GoogleStorageFSSuite.scala:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)

test is.hail.io.fs.GoogleStorageFSSuite.largeDirectoryOperations FAILURE
```

### Version

0.2.124

**Comment by danking** [comment]
https://batch.hail.is/batches/8062723/jobs/204
```
starting test is.hail.io.fs.GoogleStorageFSSuite.largeDirectoryOperations...
Exception:
org.scalatest.exceptions.TestFailedException: files not deleted:
gs://hail-test-ezlis/fs-suite/delete-many-files/376b0a1e-ee61-43ab-abb4-d67a0978ee46/791.suffix
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
	at org.scalatest.testng.TestNGSuite.newAssertionFailedException(TestNGSuite.scala:67)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
	at is.hail.io.fs.FSSuite.largeDirectoryOperations(FSSuite.scala:413)
	at is.hail.io.fs.FSSuite.largeDirectoryOperations$(FSSuite.scala:398)
	at is.hail.io.fs.GoogleStorageFSSuite.largeDirectoryOperations(GoogleStorageFSSuite.scala:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
```

**Comment by danking** [comment]
This still happens on the regular https://batch.hail.is/batches/8133279/jobs/203
