### ISSUE TITLE
[query] Local chain files cannot be registered in Dataproc

### ISSUE THREAD

**Issue by ireneisdoomed** [hail-is/hail#13993]
### What happened?

`add_liftover` fails when provided a local chain file on Dataproc. The error says the file does not exist, even though it does. 

## To reproduce
This is run in my GCP virtual machine following a simple example from [your documentation](https://github.com/hail-is/hail/blob/67801dfc66b504a7d49daa53f7ec6d22c1194585/hail/python/hail/genetics/reference_genome.py#L467):
```sh
gsutil cp gs://hail-common/references/grch37_to_grch38.over.chain.gz .
```
```py
import hail as hl
from pathlib import Path

local_chain_file = 'grch37_to_grch38.over.chain.gz'

if Path(local_chain_file).is_file():
    rg37 = hl.get_reference('GRCh37')
    rg38 = hl.get_reference('GRCh38')
    rg37.add_liftover(local_chain_file, rg38)
```
I've reproduced the bug trying with relative/absolute paths, and also referring to HDFS and the local filesystem. None of them worked on the GCP VM, however reading local chain files works on my computer.

### Version

0.2.126-ee77707f4fab

### Relevant log output

```shell
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-17-ef14f8017832> in <cell line: 3>()
      4     rg37 = hl.get_reference('GRCh37')
      5     rg38 = hl.get_reference('GRCh38')
----> 6     rg37.add_liftover(local_chain_file, rg38)
      7

<decorator-gen-150> in add_liftover(self, chain_file, dest_reference_genome)

/opt/conda/miniconda3/lib/python3.10/site-packages/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    585     def wrapper(__original_func: Callable[..., T], *args, **kwargs) -> T:
    586         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 587         return __original_func(*args_, **kwargs_)
    588
    589     return wrapper

/opt/conda/miniconda3/lib/python3.10/site-packages/hail/genetics/reference_genome.py in add_liftover(self, chain_file, dest_reference_genome)
    507         """
    508
--> 509         Env.backend().add_liftover(self.name, chain_file, dest_reference_genome.name)
    510         if dest_reference_genome.name in self._liftovers:
    511             raise KeyError(f"Liftover already exists from {self.name} to {dest_reference_genome.name}.")

/opt/conda/miniconda3/lib/python3.10/site-packages/hail/backend/py4j_backend.py in add_liftover(self, name, chain_file, dest_reference_genome)
    252
    253     def add_liftover(self, name, chain_file, dest_reference_genome):
--> 254         self._jbackend.pyAddLiftover(name, chain_file, dest_reference_genome)
    255
    256     def remove_liftover(self, name, dest_reference_genome):

/opt/conda/miniconda3/lib/python3.10/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1319
   1320         answer = self.gateway_client.send_command(command)
-> 1321         return_value = get_return_value(
   1322             answer, self.gateway_client, self.target_id, self.name)
   1323

/opt/conda/miniconda3/lib/python3.10/site-packages/hail/backend/py4j_backend.py in deco(*args, **kwargs)
     63             tpl = Env.jutils().handleForPython(e.java_exception)
     64             deepest, full, error_id = tpl._1(), tpl._2(), tpl._3()
---> 65             raise fatal_error_from_java_error_triplet(deepest, full, error_id) from None
     66         except pyspark.sql.utils.CapturedException as e:
     67             raise FatalError('%s\n\nJava stack trace:\n%s\n'

FatalError: HailException: Chain file 'grch37_to_grch38.over.chain.gz' does not exist.

Java stack trace:
is.hail.utils.HailException: Chain file 'grch37_to_grch38.over.chain.gz' does not exist.
	at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:18)
	at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:18)
	at is.hail.utils.package$.fatal(package.scala:81)
	at is.hail.variant.ReferenceGenome.addLiftover(ReferenceGenome.scala:407)
	at is.hail.backend.spark.SparkBackend.$anonfun$pyAddLiftover$2(SparkBackend.scala:613)
	at is.hail.backend.spark.SparkBackend.$anonfun$pyAddLiftover$2$adapted(SparkBackend.scala:612)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:76)
	at is.hail.utils.package$.using(package.scala:657)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:76)
	at is.hail.utils.package$.using(package.scala:657)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:62)
	at is.hail.backend.spark.SparkBackend.$anonfun$withExecuteContext$1(SparkBackend.scala:347)
	at is.hail.backend.spark.SparkBackend.$anonfun$pyAddLiftover$1(SparkBackend.scala:612)
	at is.hail.backend.spark.SparkBackend.$anonfun$pyAddLiftover$1$adapted(SparkBackend.scala:611)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:59)
	at is.hail.backend.spark.SparkBackend.pyAddLiftover(SparkBackend.scala:611)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)



Hail version: 0.2.126-ee77707f4fab
Error summary: HailException: Chain file 'grch37_to_grch38.over.chain.gz' does not exist.
```

**Comment by danking** [comment]
Hey @ireneisdoomed ! I'm sorry Hail isn't working as you expected. Thanks for the detailed report and stack trace!

> I've reproduced the bug trying with relative/absolute paths, and also referring to HDFS and the local filesystem. None of them worked on the GCP VM, however reading local chain files works on my computer.

When you say a GCP VM, do you mean a VM that is part of a Dataproc cluster? In particular, I think your code should work on a GCP VM that *is not* part of a Dataproc cluster.

The chain file needs to be readable by the worker VMs. A local path on the driver VM of a dataproc cluster isn't readable by worker VMs in that cluster. For that reason, I'd recommend using the `gs://` path instead of copying it locally and using that. Is the a reason you don't want to use the `gs://` path directly?

---
I'll try to directly address your question. When you say you've tried HDFS and local filesystem, do you mean that you've tried both:

1. Using an explicitly local file path:
   ```python3
   local_chain_file = 'file:///path/to/grch37_to_grch38.over.chain.gz'
   ```
2. Using an (implicitly) hdfs file path after copying the file into HDFS:
   ```
   hadoop fs -copyFromLocal grch37_to_grch38.over.chain.gz \
          /chainfiles/grch37_to_grch38.over.chain.gz
   ```
   ```python3
   local_chain_file = '/chainfiles/grch37_to_grch38.over.chain.gz'
   ```

If you've tried (2) and it didn't work, then this sounds like it could be a Hail bug. Could you tell me what happens if you run this on the VM?
```
hl.import_table('/chainfiles/grch37_to_grch38.over.chain.gzgz')
```

**Comment by danking** [comment]
@ireneisdoomed , bump! I need a bit more information to help resolve this issue.

**Comment by danking** [comment]
Need more information. Please re-open when more information is available!
