### ISSUE TITLE
Flaky Test: :testHail > vds_assoc.lmmreg

### ISSUE THREAD

**Issue by danking** [hail-is/hail#1416]
This test failure has occurred a few times. It's usually been resolved by simply re-running the test without any source code changes. There are at least four recent examples, all on different feature branches: 

 - [2017-02-21 11:10 UTC](https://ci.hail.is/viewLog.html?buildId=6489&tab=buildResultsDiv&buildTypeId=HailSourceCode_HailCi#)
 - [2017-02-15 21:51 UTC](https://ci.hail.is/viewLog.html?buildId=5446#2135525582_186_5446_problem)
 - [2017-02-15 18:45 UTC](https://ci.hail.is/viewLog.html?buildId=5333#1163765489_186_5333_problem)
 - [2017-02-13 22:42 UTC](https://ci.hail.is/viewLog.html?buildId=4934&tab=buildResultsDiv&buildTypeId=HailSourceCode_HailCi)

```
[11:19:14][:testHail] ======================================================================
[11:19:14][:testHail] ERROR: test_dataset (hail.tests.ContextTests)
[11:19:14][:testHail] ----------------------------------------------------------------------
[11:19:14][:testHail] Traceback (most recent call last):
[11:19:14][:testHail]   File "/home/ec2-user/BuildAgent/work/c38e75e72b769a7c/python/hail/tests.py", line 233, in test_dataset
[11:19:14][:testHail]     vds_assoc = vds_assoc.lmmreg(vds_kinship, 'sa.pheno', ['sa.cov1', 'sa.cov2'])
[11:19:14][:testHail]   File "<decorator-gen-89>", line 2, in lmmreg
[11:19:14][:testHail]   File "/home/ec2-user/BuildAgent/work/c38e75e72b769a7c/python/hail/java.py", line 93, in handle_py4j
[11:19:14][:testHail]     raise FatalError(msg)
[11:19:14][:testHail] FatalError: lmmreg: failed to fit delta: REML realized at delta upper search boundary e^10 = 22026.465794806718, indicating negligible genetic component of variance. Standard linear regression may be more appropriate.
```

These are the [offending lines](https://github.com/hail-is/hail/blob/master/python/hail/tests.py#L222-L233):

```
        vds_assoc = (hc.import_vcf(test_resources + '/sample.vcf')
                     .split_multi()
                     .variant_qc()
                     .annotate_samples_expr(
            'sa.culprit = gs.filter(g => v == Variant("20", 13753124, "A", "C")).map(g => g.gt).collect()[0]')
                     .annotate_samples_expr('sa.pheno = rnorm(1,1) * sa.culprit')
                     .annotate_samples_expr('sa.cov1 = rnorm(0,1)')
                     .annotate_samples_expr('sa.cov2 = rnorm(0,1)'))

        vds_kinship = vds_assoc.filter_variants_expr('va.qc.AF > .05')

        vds_assoc = vds_assoc.lmmreg(vds_kinship, 'sa.pheno', ['sa.cov1', 'sa.cov2'])
```

**Comment by danking** [comment]
FYI @jbloom22, if you know an obvious fix, let me know, otherwise I will dig into it when I have time.

**Comment by jbloom22** [comment]
I'm yanking out this test in PR #1475 in favor of a direct comparison of h2 with FaST-LMM.

That said, we should still understand what was causing different runs to give different values.
