### ISSUE TITLE
TLocus.mkOrdering NullPointerException

### ISSUE THREAD

**Issue by ehigham** [hail-is/hail#14249]
### What happened?

TBD

### Version

0.2.172

### Relevant log output

```shell
24/02/05 11:52:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Running on Apache Spark version 3.3.2
SparkUI available at http://192.168.1.140:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.127-d82c34a83360
LOGGING: writing to /private/tmp/varo/avro/hail-20240205-1152-0.2.127-d82c34a83360.log
2024-02-05 11:53:03.679 Hail: INFO: import_gvs: Importing and writing site filters to temporary storage
Traceback (most recent call last):
  File "/Users/dking/projects/gatk/scripts/variantstore/wdl/extract/hail_gvs_import.py", line 180, in <module>
    create_vds(arguments, vds_path, references_path, temp_path, use_classic_vqsr,
  File "/Users/dking/projects/gatk/scripts/variantstore/wdl/extract/hail_gvs_import.py", line 35, in create_vds
    import_gvs.import_gvs(
  File "<decorator-gen-1896>", line 2, in import_gvs
  File "/Users/dking/miniconda3/lib/python3.10/site-packages/hail/typecheck/check.py", line 584, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/dking/projects/gatk/scripts/variantstore/wdl/extract/import_gvs.py", line 211, in import_gvs
    site.write(site_path, overwrite=True)
  File "<decorator-gen-1224>", line 2, in write
  File "/Users/dking/miniconda3/lib/python3.10/site-packages/hail/typecheck/check.py", line 584, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/dking/miniconda3/lib/python3.10/site-packages/hail/table.py", line 2002, in write
    Env.backend().execute(
  File "/Users/dking/miniconda3/lib/python3.10/site-packages/hail/backend/backend.py", line 190, in execute
    raise e.maybe_user_error(ir) from None
  File "/Users/dking/miniconda3/lib/python3.10/site-packages/hail/backend/backend.py", line 188, in execute
    result, timings = self._rpc(ActionTag.EXECUTE, payload)
  File "/Users/dking/miniconda3/lib/python3.10/site-packages/hail/backend/py4j_backend.py", line 223, in _rpc
    raise fatal_error_from_java_error_triplet(
hail.utils.java.FatalError: NullPointerException: null

Java stack trace:
java.lang.NullPointerException: null
    at is.hail.types.virtual.TLocus.mkOrdering(TLocus.scala:45)
    at is.hail.types.virtual.Type.ordering(Type.scala:204)
    at is.hail.rvd.PartitionBoundOrdering$.$anonfun$apply$1(PartitionBoundOrdering.scala:16)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
    at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
    at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
    at scala.collection.TraversableLike.map(TraversableLike.scala:286)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
    at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
    at is.hail.rvd.PartitionBoundOrdering$.apply(PartitionBoundOrdering.scala:16)
    at is.hail.rvd.RVDPartitioner.<init>(RVDPartitioner.scala:62)
    at is.hail.rvd.RVDPartitioner.<init>(RVDPartitioner.scala:33)
    at is.hail.rvd.RVDPartitioner.copy(RVDPartitioner.scala:225)
    at is.hail.expr.ir.lowering.TableStage.extendKeyPreservesPartitioning(LowerTableIR.scala:534)
    at is.hail.expr.ir.lowering.LowerTableIR$.applyTable(LowerTableIR.scala:2035)
    at is.hail.expr.ir.lowering.LowerTableIR$.lower$2(LowerTableIR.scala:1051)
    at is.hail.expr.ir.lowering.LowerTableIR$.applyTable(LowerTableIR.scala:1655)
    at is.hail.expr.ir.lowering.LowerTableIR$.lower$1(LowerTableIR.scala:728)
    at is.hail.expr.ir.lowering.LowerTableIR$.apply(LowerTableIR.scala:1021)
    at is.hail.expr.ir.lowering.LowerToCDA$.lower(LowerToCDA.scala:27)
    at is.hail.expr.ir.lowering.LowerToCDA$.apply(LowerToCDA.scala:11)
    at is.hail.expr.ir.lowering.LowerToDistributedArrayPass.transform(LoweringPass.scala:91)
    at is.hail.expr.ir.LowerOrInterpretNonCompilable$.evaluate$1(LowerOrInterpretNonCompilable.scala:27)
    at is.hail.expr.ir.LowerOrInterpretNonCompilable$.rewrite$1(LowerOrInterpretNonCompilable.scala:59)
    at is.hail.expr.ir.LowerOrInterpretNonCompilable$.apply(LowerOrInterpretNonCompilable.scala:64)
    at is.hail.expr.ir.lowering.LowerOrInterpretNonCompilablePass$.transform(LoweringPass.scala:83)
    at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$3(LoweringPass.scala:32)
    at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
    at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$1(LoweringPass.scala:32)
    at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
    at is.hail.expr.ir.lowering.LoweringPass.apply(LoweringPass.scala:30)
    at is.hail.expr.ir.lowering.LoweringPass.apply$(LoweringPass.scala:29)
    at is.hail.expr.ir.lowering.LowerOrInterpretNonCompilablePass$.apply(LoweringPass.scala:78)
    at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1(LoweringPipeline.scala:21)
    at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1$adapted(LoweringPipeline.scala:19)
    at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
    at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
    at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:19)
    at is.hail.expr.ir.CompileAndEvaluate$._apply(CompileAndEvaluate.scala:45)
    at is.hail.backend.spark.SparkBackend._execute(SparkBackend.scala:600)
    at is.hail.backend.spark.SparkBackend.$anonfun$execute$4(SparkBackend.scala:636)
    at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
    at is.hail.backend.spark.SparkBackend.$anonfun$execute$3(SparkBackend.scala:631)
    at is.hail.backend.spark.SparkBackend.$anonfun$execute$3$adapted(SparkBackend.scala:630)
    at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:78)
    at is.hail.utils.package$.using(package.scala:664)
    at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:78)
    at is.hail.utils.package$.using(package.scala:664)
    at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:13)
    at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:65)
    at is.hail.backend.spark.SparkBackend.$anonfun$withExecuteContext$2(SparkBackend.scala:407)
    at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:55)
    at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:62)
    at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:393)
    at is.hail.backend.spark.SparkBackend.execute(SparkBackend.scala:630)
    at is.hail.backend.BackendHttpHandler.handle(BackendServer.scala:88)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
    at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:199)
    at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:544)
    at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:509)
    at java.lang.Thread.run(Thread.java:750)



Hail version: 0.2.127-d82c34a83360
Error summary: NullPointerException: null
```

**Comment by ehigham** [comment]
zulip thread(s): https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/NPE.20in.20TLocus.2EmkOrdering/near/419897695

**Comment by danking** [comment]
Reproduction: [repro.tar.gz](https://github.com/hail-is/hail/files/14170769/repro.tar.gz)

The core issue is that the Avro Java-side readers explicitly pass `null` for the `HailStateManager` to RVDPartitioner.

```python3
import hail as hl

def translate_locus(location):
    """Translates an int64-encoded locus into a locus object."""
    factor = 1000000000000
    chrom = hl.literal(hl.get_reference('GRCh38').contigs[:26])[hl.int32(location / factor) - 1]
    pos = hl.int32(location % factor)
    return hl.locus(chrom, pos, reference_genome=hl.get_reference('GRCh38'))

ht = hl.import_avro(['site_filtering_data_000000000000.avro'])
ht = ht.transmute(locus=translate_locus(ht.location))
ht._key_by_assert_sorted('locus').write('/tmp/foobar.ht', overwrite=True)
```
