### ISSUE TITLE
[query] NoSuchElementException: Ref with name __iruid_1834 could not be resolved in env BindingEnv((__iruid_1832 -> struct{},__iruid_2157 -> struct{}),None,None,())

### ISSUE THREAD

**Issue by danking** [hail-is/hail#14245]
### What happened?

I expected this to not error but it did.
```python3
import hail as hl

x = [hl.import_vcf(f, force_bgz=True, reference_genome='GRCh38', min_partitions=k).rows().select() for f, k in (
    ('hail/src/test/resources/gvcfs/HG00096.g.vcf.gz', 100),
    ('hail/src/test/resources/gvcfs/HG00268.g.vcf.gz', 1)
)]
hl.Table.multi_way_zip_join(x, 'data', 'new_globals').write('/tmp/foo.ht', overwrite=True)
```
The error:
```
2024-02-02 15:39:35.977 Hail: INFO: scanning VCF for sortedness...
2024-02-02 15:39:37.571 Hail: INFO: Coerced sorted VCF - no additional import work to do
2024-02-02 15:39:38.925 Hail: INFO: wrote table with 234687 rows in 1 partition to /tmp/__iruid_1841-E0rqVWB0ysj7E0SIeJeumv
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
Cell In[2], line 7
      1 import hail as hl
      3 x = [hl.import_vcf(f, force_bgz=True, reference_genome='GRCh38', min_partitions=k).rows().select() for f, k in (
      4     ('hail/src/test/resources/gvcfs/HG00096.g.vcf.gz', 100),
      5     ('hail/src/test/resources/gvcfs/HG00268.g.vcf.gz', 1)
      6 )]
----> 7 hl.Table.multi_way_zip_join(x, 'data', 'new_globals').write('/tmp/foo.ht', overwrite=True)

File <decorator-gen-1242>:2, in write(self, output, overwrite, stage_locally, _codec_spec)

File ~/projects/hail/hail/python/hail/typecheck/check.py:584, in _make_dec.<locals>.wrapper(__original_func, *args, **kwargs)
    581 @decorator
    582 def wrapper(__original_func: Callable[..., T], *args, **kwargs) -> T:
    583     args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 584     return __original_func(*args_, **kwargs_)

File ~/projects/hail/hail/python/hail/table.py:2002, in Table.write(self, output, overwrite, stage_locally, _codec_spec)
   1976 """Write to disk.
   1977 
   1978 Examples
   (...)
   1997     If ``True``, overwrite an existing file at the destination.
   1998 """
   2000 hl.current_backend().validate_file(output)
-> 2002 Env.backend().execute(
   2003     ir.TableWrite(self._tir, ir.TableNativeWriter(output, overwrite, stage_locally, _codec_spec))
   2004 )

File ~/projects/hail/hail/python/hail/backend/backend.py:190, in Backend.execute(self, ir, timed)
    188     result, timings = self._rpc(ActionTag.EXECUTE, payload)
    189 except FatalError as e:
--> 190     raise e.maybe_user_error(ir) from None
    191 if ir.typ == tvoid:
    192     value = None

File ~/projects/hail/hail/python/hail/backend/backend.py:188, in Backend.execute(self, ir, timed)
    186 payload = ExecutePayload(self._render_ir(ir), '{"name":"StreamBufferSpec"}', timed)
    187 try:
--> 188     result, timings = self._rpc(ActionTag.EXECUTE, payload)
    189 except FatalError as e:
    190     raise e.maybe_user_error(ir) from None

File ~/projects/hail/hail/python/hail/backend/py4j_backend.py:223, in Py4JBackend._rpc(self, action, payload)
    221 if resp.status_code >= 400:
    222     error_json = orjson.loads(resp.content)
--> 223     raise fatal_error_from_java_error_triplet(
    224         error_json['short'], error_json['expanded'], error_json['error_id']
    225     )
    226 return resp.content, resp.headers.get('X-Hail-Timings', '')

FatalError: NoSuchElementException: Ref with name __iruid_1834 could not be resolved in env BindingEnv((__iruid_1832 -> struct{},__iruid_2157 -> struct{}),None,None,())

Java stack trace:
is.hail.utils.HailException: error after applying LowerToDistributedArray
	at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:23)
	at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:23)
	at is.hail.utils.package$.fatal(package.scala:89)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1(LoweringPipeline.scala:32)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1$adapted(LoweringPipeline.scala:19)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:19)
	at is.hail.backend.local.LocalBackend._jvmLowerAndExecute(LocalBackend.scala:205)
	at is.hail.backend.local.LocalBackend._execute(LocalBackend.scala:249)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$2(LocalBackend.scala:314)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$1(LocalBackend.scala:309)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$1$adapted(LocalBackend.scala:308)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:78)
	at is.hail.utils.package$.using(package.scala:664)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:78)
	at is.hail.utils.package$.using(package.scala:664)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:13)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:65)
	at is.hail.backend.local.LocalBackend.$anonfun$withExecuteContext$2(LocalBackend.scala:144)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:55)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:62)
	at is.hail.backend.local.LocalBackend.withExecuteContext(LocalBackend.scala:130)
	at is.hail.backend.local.LocalBackend.execute(LocalBackend.scala:308)
	at is.hail.backend.BackendHttpHandler.handle(BackendServer.scala:88)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:199)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:544)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:509)
	at java.lang.Thread.run(Thread.java:750)

is.hail.utils.HailException: Error while typechecking IR:

%1 = Literal [Struct{}, <literal value>]
!2 = I64 [0] 
!3 = Str ["/tmp/__iru..."]
!4 = MakeStruct(partitionIndex: !2, partitionPath: !3)
!s = ReadPartition(!4) [Struct{}, "{\"name\":\"PartitionNativeReader\",\"spec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"+EBaseStruct{}\",\"_vType\":\"Struct{}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"uidFieldName\":\"__row_uid\"}"]
!5 = ToArray(!s) 
!c0 = I32 [0]
%6 = ArrayRef(!5, !c0) [-1]
!7 = MakeArray(%1, %undefined_ref) [Array[Struct{}]]
%8 = MakeStruct(new_globals: !7)
!9 = Literal [Array[Struct{partitionIndex:Int32,fileNum:Int32,file:String,start:Int64,end:Int64,split:Boolean}], <literal value>]
!s2 = ToStream(!9) [False]
%10 = ToArray(!s2)
!11 = Literal [Array[Array[Int32]], <literal value>]
!s3 = ToStream(!11) [False]
!s6 = StreamMap(!s3) { (%elt) =>
  !s4 = ToStream(%elt) [False]
  !s5 = StreamMap(!s4) { (%elt2) =>
    ArrayRef(%10, %elt2) [-1]
  }
  ToArray(!s5)
} 
!12 = Literal [Array[Struct{partitionIndex:Int64,partitionPath:String,indexPath:String,interval:Interval[Tuple[Struct{locus:Locus(GRCh38),alleles:Array[String]},Int32]]}], <literal value>]
!s7 = ToStream(!12) [False]
!s8 = StreamZip(!s6, !s7) [-1, AssumeSameLength] {
(%elt3, %elt4) =>
  MakeTuple(%elt3, %elt4) [(0 1)]
} 
!13 = Literal [Array[String], <literal value>]
!s9 = ToStream(!13) [False]
!s10 = StreamZip(!s8, !s9) [-1, AssertSameLength] {
(%elt5, %elt6) =>
  MakeStruct(oldCtx: %elt5, writeCtx: %elt6)
} 
!14 = MakeStruct(__iruid_1832: %1, __iruid_2157: %6, __iruid_2159: %8) 
!15 = NA [String]
%28 = CollectDistributedArray(!s10, !14, !15) {
(%ctx, %g) =>
  %16 = GetField(%g) [__iruid_1832]
  %17 = GetField(%g) [__iruid_2157]
  %18 = GetField(%g) [__iruid_2159]
  %19 = GetField(%ctx) [oldCtx]
  %20 = Ref [__iruid_2169]
  %21 = GetTupleElement(%20) [0]
  !s11 = ToStream(%21) [True]
  !s12 = StreamFlatMap(!s11) { (%elt7) =>
    %22 = Ref [__iruid_1840]
    ReadPartition(%22) [Struct{locus:Locus(GRCh38),alleles:Array[String]}, "{\"category\":\"PartitionIteratorLongReader\",\"fullRowType\":\"Struct{locus:Locus(GRCh38),alleles:Array[String],rsid:String,qual:Float64,filters:Set[String],info:Struct{BaseQRankSum:Float64,ClippingRankSum:Float64,DP:Int32,DS:Boolean,END:Int32,ExcessHet:Float64,HaplotypeScore:Float64,InbreedingCoeff:Float64,MLEAC:Array[Int32],MLEAF:Array[Float64],MQ:Float64,MQRankSum:Float64,RAW_MQ:Float64,ReadPosRankSum:Float64},`the entries! [877f12a8827e18f61222c6c8c5fb04a8]`:Array[Struct{AD:Array[Int32],DP:Int32,GQ:Int32,GT:Call,MIN_DP:Int32,PGT:Call,PID:String,PL:Array[Int32],SB:Array[Int32]}],__row_uid:Tuple[Int64,Int64]}\",\"uidFieldName\":\"__row_uid\",\"contextType\":\"Struct{partitionIndex:Int32,fileNum:Int32,file:String,start:Int64,end:Int64,split:Boolean}\"}"]
  } 
  %23 = GetTupleElement(%20) [1]
  !s13 = ReadPartition(%23) [Struct{locus:Locus(GRCh38),alleles:Array[String]}, "{\"name\":\"PartitionNativeReaderIndexed\",\"spec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"+EBaseStruct{locus:+EBaseStruct{contig:+EBinary,position:+EInt32},alleles:+EArray[+EBinary]}\",\"_vType\":\"Struct{locus:Locus(GRCh38),alleles:Array[String]}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"indexSpec\":{\"_relPath\":\"../index\",\"_leafCodec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"EBaseStruct{first_idx:+EInt64,keys:+EArray[+EBaseStruct{key:+EBaseStruct{locus:+EBaseStruct{contig:+EBinary,position:+EInt32},alleles:+EArray[+EBinary]},offset:+EInt64,annotation:+EBaseStruct{}}]}\",\"_vType\":\"Struct{first_idx:Int64,keys:Array[Struct{key:Struct{locus:Locus(GRCh38),alleles:Array[String]},offset:Int64,annotation:Struct{}}]}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"_internalNodeCodec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"EBaseStruct{children:+EArray[+EBaseStruct{index_file_offset:+EInt64,first_idx:+EInt64,first_key:+EBaseStruct{locus:+EBaseStruct{contig:+EBinary,position:+EInt32},alleles:+EArray[+EBinary]},first_record_offset:+EInt64,first_annotation:+EBaseStruct{}}]}\",\"_vType\":\"Struct{children:Array[Struct{index_file_offset:Int64,first_idx:Int64,first_key:Struct{locus:Locus(GRCh38),alleles:Array[String]},first_record_offset:Int64,first_annotation:Struct{}}]}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"_keyType\":\"Struct{locus:Locus(GRCh38),alleles:Array[String]}\",\"_annotationType\":\"Struct{}\"},\"key\":[\"locus\",\"alleles\"],\"uidFieldName\":\"__row_uid\"}"]
  !s16 = StreamZipJoin(!s12, !s13) {
  (%key, %elts) =>
    !s14 = ToStream(%elts) [False]
    !s15 = StreamMap(!s14) { (%elt8) =>
      SelectFields(%elt8) [()]
    }
    !24 = ToArray(!s15)
    InsertFields %key (data: !24)
  } 
  !25 = GetField(%ctx) [writeCtx] 
  !26 = UUID4 [__iruid_2171]
  !27 = Apply(!25, !26) [-1, concat, (), String]
  WritePartition(!s16, !27) ["{\"name\":\"PartitionNativeWriter\",\"spec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"+EBaseStruct{locus:+EBaseStruct{contig:+EBinary,position:+EInt32},alleles:+EArray[+EBinary],data:+EArray[EBaseStruct{}]}\",\"_vType\":\"Struct{locus:Locus(GRCh38),alleles:Array[String],data:Array[Struct{}]}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"keyFields\":[\"locus\",\"alleles\"],\"partPrefix\":\"/tmp/foo.ht/rows/parts/\",\"index\":{\"/tmp/foo.ht/index/\":\"+PCStruct{locus:+PCLocus(GRCh38),alleles:+PCArray[+PCString]}\"},\"trackTotalBytes\":false}"]
}
%29 = Ref [__iruid_2172]
!s17 = MakeStream(%8) [Stream[Struct{new_globals:Array[Struct{}]}], False] 
!30 = Str ["part-0"]
!31 = WritePartition(!s17, !30) ["{\"name\":\"PartitionNativeWriter\",\"spec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"+EBaseStruct{new_globals:+EArray[+EBaseStruct{}]}\",\"_vType\":\"Struct{new_globals:Array[Struct{}]}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"keyFields\":[],\"partPrefix\":\"/tmp/foo.ht/globals/parts/\",\"trackTotalBytes\":false}"]
!32 = GetField(!31) [filePath]
!33 = MakeArray(!32) [Array[String]]
!34 = WriteMetadata(!33) ["{\"name\":\"RVDSpecWriter\",\"path\":\"/tmp/foo.ht/globals\",\"spec\":{\"name\":\"RVDSpecMaker\",\"codecSpec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"+EBaseStruct{new_globals:+EArray[+EBaseStruct{}]}\",\"_vType\":\"Struct{new_globals:Array[Struct{}]}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"key\":[],\"bounds\":[{\"start\":{},\"end\":{},\"includeStart\":true,\"includeEnd\":true}],\"indexSpec\":null,\"attrs\":{}}}"] 
!s18 = ToStream(%29) [False]
!s19 = StreamMap(!s18) { (%elt9) =>
  GetField(%elt9) [filePath]
}
!35 = ToArray(!s19)
!36 = WriteMetadata(!35) ["{\"name\":\"RVDSpecWriter\",\"path\":\"/tmp/foo.ht/rows\",\"spec\":{\"name\":\"RVDSpecMaker\",\"codecSpec\":{\"name\":\"TypedCodecSpec\",\"_eType\":\"+EBaseStruct{locus:+EBaseStruct{contig:+EBinary,position:+EInt32},alleles:+EArray[+EBinary],data:+EArray[EBaseStruct{}]}\",\"_vType\":\"Struct{locus:Locus(GRCh38),alleles:Array[String],data:Array[Struct{}]}\",\"_bufferSpec\":{\"name\":\"LEB128BufferSpec\",\"child\":{\"name\":\"BlockingBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"ZstdBlockBufferSpec\",\"blockSize\":65536,\"child\":{\"name\":\"StreamBlockBufferSpec\"}}}}},\"key\":[\"locus\",\"alleles\"],\"bounds\":[{\"start\":{\"locus\":{\"contig\":\"chr20\",\"position\":17959479},\"alleles\":[\"T\",\"<NON_REF>\"]},\"end\":{\"locus\":{\"contig\":\"chr20\",\"position\":17994753},\"alleles\":[\"A\",\"<NON_REF>\"]},\"includeStart\":true,\"includeEnd\":true},{\"start\":{\"locus\":{\"contig\":\"chr20\",\"position\":17994753},\"alleles\":[\"A\",\"<NON_REF>\"]},\"end\":{\"locus\":{\"cont..."] 
!s20 = ToStream(%29) [False]
!s21 = StreamMap(!s20) { (%elt10) =>
  SelectFields(%elt10) [
  (partitionCounts distinctlyKeyed firstKey
    lastKey)]
}
!37 = ToArray(!s21)
!38 = WriteMetadata(!37) ["{\"name\":\"TableSpecWriter\",\"path\":\"/tmp/foo.ht\",\"typ\":{\"rowType\":\"Struct{locus:Locus(GRCh38),alleles:Array[String],data:Array[Struct{}]}\",\"key\":[\"locus\",\"alleles\"],\"globalType\":\"Struct{new_globals:Array[Struct{}]}\"},\"rowRelPath\":\"rows\",\"globalRelPath\":\"globals\",\"refRelPath\":\"references\",\"log\":true}"]
!39 = Begin(!34, !36, !38)
WriteMetadata(!39) ["{\"name\":\"RelationalWriter\",\"path\":\"/tmp/foo.ht\",\"overwrite\":true,\"maybeRefs\":{\"references\":[\"GRCh38\"]}}"]

	at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:23)
	at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:23)
	at is.hail.utils.package$.fatal(package.scala:89)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:17)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1(LoweringPipeline.scala:29)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1$adapted(LoweringPipeline.scala:19)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:19)
	at is.hail.backend.local.LocalBackend._jvmLowerAndExecute(LocalBackend.scala:205)
	at is.hail.backend.local.LocalBackend._execute(LocalBackend.scala:249)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$2(LocalBackend.scala:314)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$1(LocalBackend.scala:309)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$1$adapted(LocalBackend.scala:308)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:78)
	at is.hail.utils.package$.using(package.scala:664)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:78)
	at is.hail.utils.package$.using(package.scala:664)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:13)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:65)
	at is.hail.backend.local.LocalBackend.$anonfun$withExecuteContext$2(LocalBackend.scala:144)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:55)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:62)
	at is.hail.backend.local.LocalBackend.withExecuteContext(LocalBackend.scala:130)
	at is.hail.backend.local.LocalBackend.execute(LocalBackend.scala:308)
	at is.hail.backend.BackendHttpHandler.handle(BackendServer.scala:88)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:199)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:544)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:509)
	at java.lang.Thread.run(Thread.java:750)

java.util.NoSuchElementException: Ref with name __iruid_1834 could not be resolved in env BindingEnv((__iruid_1832 -> struct{},__iruid_2157 -> struct{}),None,None,())
	at is.hail.expr.ir.TypeCheck$.checkSingleNode(TypeCheck.scala:110)
	at is.hail.expr.ir.TypeCheck$.$anonfun$check$4(TypeCheck.scala:37)
	at is.hail.expr.ir.TypeCheck$.$anonfun$check$4$adapted(TypeCheck.scala:29)
	at is.hail.utils.StackSafe$StackFrame.$anonfun$map$1(StackSafe.scala:30)
	at is.hail.utils.StackSafe$StackFrame.flatMap(StackSafe.scala:21)
	at is.hail.utils.StackSafe$StackFrame.map(StackSafe.scala:30)
	at is.hail.expr.ir.TypeCheck$.check(TypeCheck.scala:29)
	at is.hail.expr.ir.TypeCheck$.$anonfun$check$2(TypeCheck.scala:31)
	at is.hail.utils.StackSafe$More.advance(StackSafe.scala:64)
	at is.hail.utils.StackSafe$.run(StackSafe.scala:16)
	at is.hail.utils.StackSafe$StackFrame.run(StackSafe.scala:32)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:15)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1(LoweringPipeline.scala:29)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1$adapted(LoweringPipeline.scala:19)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:19)
	at is.hail.backend.local.LocalBackend._jvmLowerAndExecute(LocalBackend.scala:205)
	at is.hail.backend.local.LocalBackend._execute(LocalBackend.scala:249)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$2(LocalBackend.scala:314)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$1(LocalBackend.scala:309)
	at is.hail.backend.local.LocalBackend.$anonfun$execute$1$adapted(LocalBackend.scala:308)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:78)
	at is.hail.utils.package$.using(package.scala:664)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:78)
	at is.hail.utils.package$.using(package.scala:664)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:13)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:65)
	at is.hail.backend.local.LocalBackend.$anonfun$withExecuteContext$2(LocalBackend.scala:144)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:55)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:62)
	at is.hail.backend.local.LocalBackend.withExecuteContext(LocalBackend.scala:130)
	at is.hail.backend.local.LocalBackend.execute(LocalBackend.scala:308)
	at is.hail.backend.BackendHttpHandler.handle(BackendServer.scala:88)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:199)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:544)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:509)
	at java.lang.Thread.run(Thread.java:750)





Hail version: 0.2.127-d2615543476b
Error summary: NoSuchElementException: Ref with name __iruid_1834 could not be resolved in env BindingEnv((__iruid_1832 -> struct{},__iruid_2157 -> struct{}),None,None,())
```

### Version

0.2.127

**Comment by danking** [comment]
https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/java.2Eutil.2ENoSuchElementException.3A.20Ref.20with.20name.20__iruid_1.2E.2E.2E
