### ISSUE TITLE
ClassTooLargeException for 10x3202 table

### ISSUE THREAD

**Issue by IMarkusz** [hail-is/hail#14362]
### What happened?

When I try select some rows (10) of a large matrixtable and convert it into a pandas dataframe the execution fails with `ClassTooLargeException`. The problem arises after I invoke `make_table()` and try to take some rows. I expected hail to be able to handle data with dimensions 10x3202, which is not too large.

Data was downloaded from the 1000 Genomes ftp site: [link](https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/)

```
# load data
vcf_path = ".../1000G_b38_20201028_3202_phased/CCDG_14151_B01_GRM_WGS_2020-08-05_chr*.filtered.shapeit2-duohmm-phased.vcf.gz"
mt = hl.import_vcf(vcf_path, force_bgz=True)

# select a few random variants
n_selected_variants = 10
selected_variants = np.random.choice(mt.rsid.collect(), n_selected_variants)
selected_variants = hl.array(list(selected_variants))

(
    mt.filter_rows(selected_variants.contains(mt.rsid))
    .select_rows('rsid')
    .select_entries('GT')
).count()
```
```
[Stage 18:=====================================================>(255 + 1) / 256]
(10, 3202)
```

Trying to convert to pandas dataframe `.make_table().to_pandas()`, or even just taking 1 row `.make_table().take(1)` results in the following error:
```
(
    mt.filter_rows(selected_variants.contains(mt.rsid))
    .select_rows('rsid')
    .select_entries('GT')
).make_table().take(1)
```
```
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
Cell In[10], [line 5](vscode-notebook-cell:?execution_count=10&line=5)
      [1](vscode-notebook-cell:?execution_count=10&line=1) (
      [2](vscode-notebook-cell:?execution_count=10&line=2)     mt.filter_rows(selected_variants.contains(mt.rsid))
      [3](vscode-notebook-cell:?execution_count=10&line=3)     .select_rows('rsid')
      [4](vscode-notebook-cell:?execution_count=10&line=4)     .select_entries('GT')
----> [5](vscode-notebook-cell:?execution_count=10&line=5) ).make_table().take(1)

File .../python3.10/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    [230](.../python3.10/site-packages/decorator.py:230) if not kwsyntax:
    [231](.../python3.10/site-packages/decorator.py:231)     args, kw = fix(args, kw, sig)
--> [232](.../python3.10/site-packages/decorator.py:232) return caller(func, *(extras + args), **kw)

File .../python3.10/site-packages/hail/typecheck/check.py:584, in _make_dec.<locals>.wrapper(__original_func, *args, **kwargs)
    [581](.../python3.10/site-packages/hail/typecheck/check.py:581) @decorator
    [582](.../python3.10/site-packages/hail/typecheck/check.py:582) def wrapper(__original_func: Callable[..., T], *args, **kwargs) -> T:
    [583](.../python3.10/site-packages/hail/typecheck/check.py:583)     args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> [584](.../python3.10/site-packages/hail/typecheck/check.py:584)     return __original_func(*args_, **kwargs_)

File .../python3.10/site-packages/hail/table.py:2426, in Table.take(self, n, _localize)
   [2392](.../python3.10/site-packages/hail/table.py:2392) @typecheck_method(n=int, _localize=bool)
   [2393](.../python3.10/site-packages/hail/table.py:2393) def take(self, n, _localize=True):
   [2394](.../python3.10/site-packages/hail/table.py:2394)     """Collect the first `n` rows of the table into a local list.
   [2395](.../python3.10/site-packages/hail/table.py:2395) 
   [2396](.../python3.10/site-packages/hail/table.py:2396)     Examples
   (...)
   [2423](.../python3.10/site-packages/hail/table.py:2423)         List of row structs.
   [2424](.../python3.10/site-packages/hail/table.py:2424)     """
-> [2426](.../python3.10/site-packages/hail/table.py:2426)     return self.head(n).collect(_localize)

File .../python3.10/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    [230](.../python3.10/site-packages/decorator.py:230) if not kwsyntax:
    [231](.../python3.10/site-packages/decorator.py:231)     args, kw = fix(args, kw, sig)
--> [232](.../python3.10/site-packages/decorator.py:232) return caller(func, *(extras + args), **kw)

File .../python3.10/site-packages/hail/typecheck/check.py:584, in _make_dec.<locals>.wrapper(__original_func, *args, **kwargs)
    [581](.../python3.10/site-packages/hail/typecheck/check.py:581) @decorator
    [582](.../python3.10/site-packages/hail/typecheck/check.py:582) def wrapper(__original_func: Callable[..., T], *args, **kwargs) -> T:
    [583](.../python3.10/site-packages/hail/typecheck/check.py:583)     args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> [584](.../python3.10/site-packages/hail/typecheck/check.py:584)     return __original_func(*args_, **kwargs_)

File .../python3.10/site-packages/hail/table.py:2213, in Table.collect(self, _localize, _timed)
   [2211](.../python3.10/site-packages/hail/table.py:2211) e = construct_expr(rows_ir, hl.tarray(t.row.dtype))
   [2212](.../python3.10/site-packages/hail/table.py:2212) if _localize:
-> [2213](.../python3.10/site-packages/hail/table.py:2213)     return Env.backend().execute(e._ir, timed=_timed)
   [2214](.../python3.10/site-packages/hail/table.py:2214) else:
   [2215](.../python3.10/site-packages/hail/table.py:2215)     return e

File .../python3.10/site-packages/hail/backend/backend.py:190, in Backend.execute(self, ir, timed)
    [188](.../python3.10/site-packages/hail/backend/backend.py:188)     result, timings = self._rpc(ActionTag.EXECUTE, payload)
    [189](.../python3.10/site-packages/hail/backend/backend.py:189) except FatalError as e:
--> [190](.../python3.10/site-packages/hail/backend/backend.py:190)     raise e.maybe_user_error(ir) from None
    [191](.../python3.10/site-packages/hail/backend/backend.py:191) if ir.typ == tvoid:
    [192](.../python3.10/site-packages/hail/backend/backend.py:192)     value = None

File .../python3.10/site-packages/hail/backend/backend.py:188, in Backend.execute(self, ir, timed)
    [186](.../python3.10/site-packages/hail/backend/backend.py:186) payload = ExecutePayload(self._render_ir(ir), '{"name":"StreamBufferSpec"}', timed)
    [187](.../python3.10/site-packages/hail/backend/backend.py:187) try:
--> [188](.../python3.10/site-packages/hail/backend/backend.py:188)     result, timings = self._rpc(ActionTag.EXECUTE, payload)
    [189](.../python3.10/site-packages/hail/backend/backend.py:189) except FatalError as e:
    [190](.../python3.10/site-packages/hail/backend/backend.py:190)     raise e.maybe_user_error(ir) from None

File .../python3.10/site-packages/hail/backend/py4j_backend.py:220, in Py4JBackend._rpc(self, action, payload)
    [218](.../python3.10/site-packages/hail/backend/py4j_backend.py:218) if resp.status_code >= 400:
    [219](.../python3.10/site-packages/hail/backend/py4j_backend.py:219)     error_json = orjson.loads(resp.content)
--> [220](.../python3.10/site-packages/hail/backend/py4j_backend.py:220)     raise fatal_error_from_java_error_triplet(
    [221](.../python3.10/site-packages/hail/backend/py4j_backend.py:221)         error_json['short'], error_json['expanded'], error_json['error_id']
    [222](.../python3.10/site-packages/hail/backend/py4j_backend.py:222)     )
    [223](.../python3.10/site-packages/hail/backend/py4j_backend.py:223) return resp.content, resp.headers.get('X-Hail-Timings', '')

FatalError: ClassTooLargeException: Class too large: __C67907collect_distributed_array_table_collect

Java stack trace:
is.hail.relocated.org.objectweb.asm.ClassTooLargeException: Class too large: __C67907collect_distributed_array_table_collect
	at is.hail.relocated.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:599)
	at is.hail.lir.Emit$.apply(Emit.scala:234)
	at is.hail.lir.Classx.$anonfun$asBytes$4(X.scala:109)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at scala.collection.AbstractIterator.to(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
	at is.hail.lir.Classx.asBytes(X.scala:120)
	at is.hail.asm4s.ClassBuilder.classBytes(ClassBuilder.scala:488)
	at is.hail.asm4s.ModuleBuilder.$anonfun$classesBytes$1(ClassBuilder.scala:166)
	at is.hail.asm4s.ModuleBuilder.$anonfun$classesBytes$1$adapted(ClassBuilder.scala:166)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at scala.collection.AbstractIterator.to(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
	at is.hail.asm4s.ModuleBuilder.classesBytes(ClassBuilder.scala:167)
	at is.hail.expr.ir.EmitClassBuilder.resultWithIndex(EmitClassBuilder.scala:959)
	at is.hail.expr.ir.WrappedEmitClassBuilder.resultWithIndex(EmitClassBuilder.scala:272)
	at is.hail.expr.ir.WrappedEmitClassBuilder.resultWithIndex$(EmitClassBuilder.scala:270)
	at is.hail.expr.ir.EmitFunctionBuilder.resultWithIndex(EmitClassBuilder.scala:1489)
	at is.hail.expr.ir.Emit.$anonfun$emitI$282(Emit.scala:3275)
	at is.hail.expr.ir.IEmitCodeGen.map(Emit.scala:423)
	at is.hail.expr.ir.Emit.emitI(Emit.scala:3180)
	at is.hail.expr.ir.streams.EmitStream$.is$hail$expr$ir$streams$EmitStream$$emit$1(EmitStream.scala:166)
	at is.hail.expr.ir.streams.EmitStream$.produce(EmitStream.scala:390)
	at is.hail.expr.ir.streams.EmitStream$.produce$1(EmitStream.scala:313)
	at is.hail.expr.ir.streams.EmitStream$.produce(EmitStream.scala:1582)
	at is.hail.expr.ir.Emit.emitI(Emit.scala:2820)
	at is.hail.expr.ir.Emit.$anonfun$emitSplitMethod$1(Emit.scala:720)
	at is.hail.expr.ir.Emit.$anonfun$emitSplitMethod$1$adapted(Emit.scala:718)
	at is.hail.expr.ir.EmitCodeBuilder$.scoped(EmitCodeBuilder.scala:17)
	at is.hail.expr.ir.EmitCodeBuilder$.scopedVoid(EmitCodeBuilder.scala:27)
	at is.hail.expr.ir.EmitMethodBuilder.voidWithBuilder(EmitClassBuilder.scala:1422)
	at is.hail.expr.ir.Emit.emitSplitMethod(Emit.scala:718)
	at is.hail.expr.ir.Emit.emitInSeparateMethod(Emit.scala:743)
	at is.hail.expr.ir.Emit.emitI(Emit.scala:1008)
	at is.hail.expr.ir.Emit.emitInNewBuilder$1(Emit.scala:1031)
	at is.hail.expr.ir.Emit.$anonfun$emitI$39(Emit.scala:1221)
	at is.hail.expr.ir.EmitCode$.fromI(Emit.scala:545)
	at is.hail.expr.ir.Emit.$anonfun$emitI$38(Emit.scala:1221)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at is.hail.expr.ir.Emit.emitI(Emit.scala:1220)
	at is.hail.expr.ir.Emit.emitInNewBuilder$1(Emit.scala:1031)
	at is.hail.expr.ir.Emit.$anonfun$emitI$41(Emit.scala:1231)
	at is.hail.expr.ir.EmitCode$.fromI(Emit.scala:545)
	at is.hail.expr.ir.Emit.$anonfun$emitI$40(Emit.scala:1231)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at is.hail.expr.ir.Emit.emitI(Emit.scala:1230)
	at is.hail.expr.ir.Emit$.$anonfun$apply$5(Emit.scala:126)
	at is.hail.expr.ir.EmitCodeBuilder$.scoped(EmitCodeBuilder.scala:17)
	at is.hail.expr.ir.EmitCodeBuilder$.scopedCode(EmitCodeBuilder.scala:22)
	at is.hail.expr.ir.EmitMethodBuilder.emitWithBuilder(EmitClassBuilder.scala:1419)
	at is.hail.expr.ir.WrappedEmitMethodBuilder.emitWithBuilder(EmitClassBuilder.scala:1472)
	at is.hail.expr.ir.WrappedEmitMethodBuilder.emitWithBuilder$(EmitClassBuilder.scala:1472)
	at is.hail.expr.ir.EmitFunctionBuilder.emitWithBuilder(EmitClassBuilder.scala:1489)
	at is.hail.expr.ir.Emit$.apply(Emit.scala:121)
	at is.hail.expr.ir.Compile$.$anonfun$apply$4(Compile.scala:90)
	at is.hail.backend.BackendWithCodeCache.lookupOrCompileCachedFunction(Backend.scala:279)
	at is.hail.backend.BackendWithCodeCache.lookupOrCompileCachedFunction$(Backend.scala:274)
	at is.hail.backend.spark.SparkBackend.lookupOrCompileCachedFunction(SparkBackend.scala:298)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:50)
	at is.hail.expr.ir.CompileAndEvaluate$.$anonfun$_apply$5(CompileAndEvaluate.scala:66)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.expr.ir.CompileAndEvaluate$._apply(CompileAndEvaluate.scala:66)
	at is.hail.expr.ir.CompileAndEvaluate$.evalToIR(CompileAndEvaluate.scala:28)
	at is.hail.expr.ir.LowerOrInterpretNonCompilable$.evaluate$1(LowerOrInterpretNonCompilable.scala:30)
	at is.hail.expr.ir.LowerOrInterpretNonCompilable$.rewrite$1(LowerOrInterpretNonCompilable.scala:59)
	at is.hail.expr.ir.LowerOrInterpretNonCompilable$.apply(LowerOrInterpretNonCompilable.scala:64)
	at is.hail.expr.ir.lowering.LowerOrInterpretNonCompilablePass$.transform(LoweringPass.scala:83)
	at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$3(LoweringPass.scala:32)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$1(LoweringPass.scala:32)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.expr.ir.lowering.LoweringPass.apply(LoweringPass.scala:30)
	at is.hail.expr.ir.lowering.LoweringPass.apply$(LoweringPass.scala:29)
	at is.hail.expr.ir.lowering.LowerOrInterpretNonCompilablePass$.apply(LoweringPass.scala:78)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1(LoweringPipeline.scala:21)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1$adapted(LoweringPipeline.scala:19)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:19)
	at is.hail.expr.ir.lowering.EvalRelationalLets$.execute$1(EvalRelationalLets.scala:13)
	at is.hail.expr.ir.lowering.EvalRelationalLets$.lower$1(EvalRelationalLets.scala:21)
	at is.hail.expr.ir.lowering.EvalRelationalLets$.apply(EvalRelationalLets.scala:35)
	at is.hail.expr.ir.lowering.EvalRelationalLetsPass.transform(LoweringPass.scala:170)
	at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$3(LoweringPass.scala:32)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.expr.ir.lowering.LoweringPass.$anonfun$apply$1(LoweringPass.scala:32)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.expr.ir.lowering.LoweringPass.apply(LoweringPass.scala:30)
	at is.hail.expr.ir.lowering.LoweringPass.apply$(LoweringPass.scala:29)
	at is.hail.expr.ir.lowering.EvalRelationalLetsPass.apply(LoweringPass.scala:164)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1(LoweringPipeline.scala:21)
	at is.hail.expr.ir.lowering.LoweringPipeline.$anonfun$apply$1$adapted(LoweringPipeline.scala:19)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:19)
	at is.hail.expr.ir.CompileAndEvaluate$._apply(CompileAndEvaluate.scala:45)
	at is.hail.backend.spark.SparkBackend._execute(SparkBackend.scala:601)
	at is.hail.backend.spark.SparkBackend.$anonfun$execute$4(SparkBackend.scala:637)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:84)
	at is.hail.backend.spark.SparkBackend.$anonfun$execute$3(SparkBackend.scala:632)
	at is.hail.backend.spark.SparkBackend.$anonfun$execute$3$adapted(SparkBackend.scala:631)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:77)
	at is.hail.utils.package$.using(package.scala:665)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:77)
	at is.hail.utils.package$.using(package.scala:665)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:64)
	at is.hail.backend.spark.SparkBackend.$anonfun$withExecuteContext$2(SparkBackend.scala:407)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:55)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:62)
	at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:393)
	at is.hail.backend.spark.SparkBackend.execute(SparkBackend.scala:631)
	at is.hail.backend.BackendHttpHandler.handle(BackendServer.scala:89)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:848)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:817)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:201)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:560)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:526)
	at java.base/java.lang.Thread.run(Thread.java:829)



Hail version: 0.2.127-bb535cd096c5
Error summary: ClassTooLargeException: Class too large: __C67907collect_distributed_array_table_collect
```

Hail log (in chunks, as it is 77 MB large):
[hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk1.txt](https://github.com/hail-is/hail/files/14418491/hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk1.txt)
[hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk2.txt](https://github.com/hail-is/hail/files/14418492/hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk2.txt)
[hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk3.txt](https://github.com/hail-is/hail/files/14418560/hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk3.txt)
[hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk4.txt](https://github.com/hail-is/hail/files/14418551/hail-20240227-1113-0.2.127-bb535cd096c5.log.chunk4.txt)

### Version

0.2.127-bb535cd096c5

**Comment by ehigham** [comment]
Hi @IMarkusz, thanks for reporting this!
`make_table` was designed to work with a small number of columns only.
As you've observed, we don't do a great job at handling larger numbers of columns.
To work around this limitation, you could try [localize_entries](https://hail.is/docs/0.2/hail.MatrixTable.html#hail.MatrixTable.localize_entries) which will give you a table of the form:
```
----------------------------------------
Global fields:
    'cols': array<struct {
        s: str
    }> 
----------------------------------------
Row fields:
    'locus': locus<GRCh38> 
    'alleles': array<str> 
    'rsid': str 
    'entries': array<struct {
        GT: call
    }> 
----------------------------------------
Key: ['locus', 'alleles']
----------------------------------------
```

**Comment by IMarkusz** [comment]
Thank you, `localize_entries` works as expected.
