### ISSUE TITLE
[batch] query_billing_projects_with_cost should not lock in share mode

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#14423]
### What happened?

`query_billing_projects_with_cost` runs a `select_and_fetchall` query against the database to load information about certain billing projects. It currently locks the affected rows in share mode, but I don't believe there's any reason to do this and it can lead to deadlock errors in `monitor_billing_limits`.

It is also worth noting that in `monitor_billing_limits`, we might not want to reuse this method at all, as it only needs to load rows from the database that have exceeded their billing limit. In practice currently this doesn't much matter as the number of billing projects is fairly small, but it is still not ideal.

### Version

0.2.128

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/hailtop/utils/utils.py", line 900, in retry_long_running
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/hailtop/utils/utils.py", line 944, in loop
    await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/batch/driver/main.py", line 1288, in monitor_billing_limits
    records = await query_billing_projects_with_cost(db)
  File "/usr/local/lib/python3.9/dist-packages/batch/utils.py", line 165, in query_billing_projects_with_cost
    async for record in db.select_and_fetchall(sql, tuple(args)):
  File "/usr/local/lib/python3.9/dist-packages/gear/database.py", line 339, in select_and_fetchall
    async for row in tx.execute_and_fetchall(sql, args, query_name):
  File "/usr/local/lib/python3.9/dist-packages/gear/database.py", line 254, in execute_and_fetchall
    await cursor.execute(sql, args)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 1172, in read
    await self._read_result_packet(first_packet)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 1232, in _read_result_packet
    await self._read_rowdata_packet()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 1282, in _read_rowdata_packet
    packet = await self.connection._read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**Comment by daniel-goldstein** [comment]
Fixed in #14443
