### ISSUE TITLE
Initializing hail with `backend='batch'` fails with `TypeError: Cannot instantiate typing.Literal`.

### ISSUE THREAD

**Issue by chrisvittal** [hail-is/hail#14573]
### What happened?

```
Python 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hail as hl
>>> hl.init(backend='batch')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-1610>", line 2, in init
  File "/Users/cvittal/src/hail/hail/python/hail/typecheck/check.py", line 584, in wrapper
    args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
  File "/Users/cvittal/src/hail/hail/python/hail/typecheck/check.py", line 554, in check_all
    kwargs_[arg_name] = arg_check(arg, name, arg_name, checker)
  File "/Users/cvittal/src/hail/hail/python/hail/typecheck/check.py", line 592, in arg_check
    return checker.check(arg, function_name, arg_name)
  File "/Users/cvittal/src/hail/hail/python/hail/typecheck/check.py", line 82, in check
    return tc.check(x, caller, param)
  File "/Users/cvittal/src/hail/hail/python/hail/typecheck/check.py", line 61, in check
    return self.tc.check(x, caller, param)
  File "/Users/cvittal/src/hail/hail/python/hail/typecheck/check.py", line 51, in tc
    t = self.f()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 957, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 387, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Literal
```

Introduced in #14512

### Version

main

**Comment by chrisvittal** [comment]
Longer term project, introspect on the type annotations themselves and check based on those.
