### ISSUE TITLE
[batch] Delete orphaned disks loop fails to list disks

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#14613]
### What happened?

We observed this error log message 

```
deleting disk batch-disk-3d106c666a364d82bec3 from instance that no longer exists
```

followed by what appears to be an endless stream of the following assertion error in the background task loop that tries to delete orphaned disks:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/hailtop/utils/utils.py", line 915, in retry_long_running
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/hailtop/utils/utils.py", line 959, in loop
    await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/batch/cloud/gcp/driver/driver.py", line 180, in delete_orphaned_disks
    await delete_orphaned_disks(
  File "/usr/local/lib/python3.9/dist-packages/batch/cloud/gcp/driver/disks.py", line 30, in delete_orphaned_disks
    async for disk in await compute_client.list(f'/zones/{zone}/disks', params=params):
  File "/usr/local/lib/python3.9/dist-packages/hailtop/aiocloud/aiogoogle/client/compute_client.py", line 59, in __anext__
    assert 'pageToken' not in self._request_params
AssertionError
```

This is an invalid state for the `PagedIterator` to be in, and could imply that this garbage disk collection loop just doesn't work. We should track down the broken invariant here and fix it, if possible testing that the async iterator works correctly.

### Version

0.2.132

**Comment by daniel-goldstein** [comment]
This is a result of accidental mutation of the `params` dictionary that's passed into this generator. Notice that the same `params` dictionary is used for each listing per zone https://github.com/hail-is/hail/blob/de0f7a8d54f29f601b7321950ca3bc2425befecf/batch/batch/cloud/gcp/driver/disks.py#L27-L31
and the dictionary is mutated here https://github.com/hail-is/hail/blob/de0f7a8d54f29f601b7321950ca3bc2425befecf/hail/python/hailtop/aiocloud/aiogoogle/client/compute_client.py#L73. This means that on the second iteration (second zone), `self._request_params` will contain the last `nextPageToken` from the previous iteration, triggering this assertion.

Avoiding this accidental mutation should resolve this issue.

**Comment by daniel-goldstein** [comment]
Used this to test

```python
import asyncio

from hailtop.aiocloud.aiogoogle import GoogleComputeClient

async def main():
    params = {'filter': f'(labels.namespace = default)'}
    async with GoogleComputeClient('hail-vdc') as client:
        for zone in ('a', 'b', 'c', 'f'):
            async for disk in client.list(f'/zones/us-central1-{zone}/disks', params=params):
                pass

asyncio.run(main())
```
