### ISSUE TITLE
[query] StreamConstraintsException in Spark backend

### ISSUE THREAD

**Issue by chrisvittal** [hail-is/hail#14650]
### What happened?

From Mike Wilson on hail zulip [here](https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/hail.200.2E2.2E132.20streamconstraintsexception/near/453934859).

> I'm running the new vds combiner on ~340 DRAGEN gVCFs and have hit this error
>
> ```
> Error summary: StreamConstraintsException: String length (20054016) exceeds the maximum length (20000000)
> ```

### Version

0.2.132

### Relevant log output

```shell
Full java stack trace:

Java stack trace:
com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (20054016) exceeds the maximum length (20000000)
    at com.fasterxml.jackson.core.StreamReadConstraints.validateStringLength(StreamReadConstraints.java:324)
    at com.fasterxml.jackson.core.util.ReadConstrainedTextBuffer.validateStringLength(ReadConstrainedTextBuffer.java:27)
    at com.fasterxml.jackson.core.util.TextBuffer.finishCurrentSegment(TextBuffer.java:939)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2584)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2560)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:335)
    at is.hail.relocated.org.json4s.jackson.JValueDeserializer._deserialize$1(JValueDeserializer.scala:26)
    at is.hail.relocated.org.json4s.jackson.JValueDeserializer._deserialize$1(JValueDeserializer.scala:48)
    at is.hail.relocated.org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:57)
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
    at is.hail.relocated.org.json4s.jackson.JsonMethods.parse(JsonMethods.scala:35)
    at is.hail.relocated.org.json4s.jackson.JsonMethods.parse$(JsonMethods.scala:20)
    at is.hail.relocated.org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:71)
    at is.hail.backend.BackendHttpHandler.$anonfun$handle$1(BackendServer.scala:85)
    at is.hail.utils.package$.using(package.scala:673)
    at is.hail.backend.BackendHttpHandler.handle(BackendServer.scala:85)
    at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
    at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:848)
    at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:817)
    at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:201)
    at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:560)
    at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:526)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by chrisvittal** [comment]
I believe the fix here is to update the 'entry points' to the Spark and Local backends as we did similarly to the Service backend in #14567.
