### ISSUE TITLE
VEP acting up again

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1518]
Getting this with current master on the cloud:

```
Use of uninitialized value in hash element at /vep/ensembl-tools-release-85/scripts/variant_effect_predictor/Bio/EnsEMBL/Variation/Utils/VEP.pm line 4255, <VARS> line 1.
[Stage 18:=>                                                (273 + 410) / 13592]Traceback (most recent call last):
  File "/tmp/7ff73b01-6ea1-4254-a49d-01e9075ab5b0/subset.py", line 75, in <module>
    main(args, pops)
  File "/tmp/7ff73b01-6ea1-4254-a49d-01e9075ab5b0/subset.py", line 51, in main
    'va.rf').write(args.output + ".autosomes.vds", overwrite=True)
  File "/tmp/7ff73b01-6ea1-4254-a49d-01e9075ab5b0/utils.py", line 452, in post_process_vds
    vds = vds.vep(config=vep_config, csq=True, root='va.info.CSQ', force=True)
  File "<decorator-gen-110>", line 2, in vep
  File "/tmp/7ff73b01-6ea1-4254-a49d-01e9075ab5b0/pyhail-attr.zip/hail/java.py", line 93, in handle_py4j
hail.java.FatalError: NoSuchElementException: None.get
[Stage 18:=>                                                (277 + 409) / 13592]java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@2a632cbb rejected from java.util.concurrent.ThreadPoolExecutor@974d518[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2913]
```

Lmk if you need more log.

**Comment by cseed** [comment]
@konradjk This was an out of date version, right?

**Comment by konradjk** [comment]
We narrowed it down to star alleles. I think @lfrancioli has a PR for it, but not sure if it's through yet?
