### ISSUE TITLE
error message from lambda in filter expr

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1623]
```python
vds.filter_variants_expr('v => va.pass').count()
```

```
vds.filter_variants_expr('v => va.pass').count()
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-44-0380f72331b7> in <module>()
----> 1 vds.filter_variants_expr('v => va.pass').count()

<decorator-gen-223> in filter_variants_expr(self, condition, keep)

/Users/tpoterba/hail/python/hail/java.py in handle_py4j(func, *args, **kwargs)
    111         raise FatalError('%s\n\nJava stack trace:\n%s\n'
    112                          'Hail version: %s\n'
--> 113                          'Error summary: %s' % (deepest, full, Env.hc().version, deepest))
    114     except py4j.protocol.Py4JError as e:
    115         if e.args[0].startswith('An error occurred while calling'):

FatalError: UnsupportedOperationException: null

Java stack trace:
java.lang.UnsupportedOperationException: null
	at is.hail.expr.AST.typecheckThis(AST.scala:215)
	at is.hail.expr.AST.typecheckThis(AST.scala:213)
	at is.hail.expr.AST.typecheck(AST.scala:219)
	at is.hail.expr.Parser$.is$hail$expr$Parser$$eval(Parser.scala:57)
	at is.hail.expr.Parser$.parseExpr(Parser.scala:67)
	at is.hail.expr.Parser$.parseTypedExpr(Parser.scala:77)
	at is.hail.variant.VariantSampleMatrix.filterVariantsExpr(VariantSampleMatrix.scala:1229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

Hail version: devel-a3d64be
Error summary: UnsupportedOperationException: null```

**Comment by tpoterba** [comment]
also, this error message is WAY better and fully debuggable.
