### ISSUE TITLE
VDS in `gs://hail-common/` not working

### ISSUE THREAD

**Issue by TarjinderSingh** [hail-is/hail#1683]
When accessing two VDS files in `gs://hail-common/`, I got two errors.

1. gs://hail-common/all_coding_plus_minus_50bp_vep.vds

```
File "<decorator-gen-162>", line 2, in read
  File "/home/ec2-user/BuildAgent/work/c38e75e72b769a7c/python/hail/java.py", line 113, in handle_py4j
hail.java.FatalError: HailException: missing partitioner.json.gz when loading VDS, create with HailContext.write_partitioning.

Java stack trace:
is.hail.utils.HailException: missing partitioner.json.gz when loading VDS, create with HailContext.write_partitioning.
	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:6)
	at is.hail.utils.package$.fatal(package.scala:20)
	at is.hail.variant.VariantDataset$.liftedTree1$1(VariantDataset.scala:89)
	at is.hail.variant.VariantDataset$.read(VariantDataset.scala:84)
	at is.hail.HailContext$$anonfun$10.apply(HailContext.scala:414)
	at is.hail.HailContext$$anonfun$10.apply(HailContext.scala:413)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at is.hail.HailContext.readAll(HailContext.scala:413)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

Hail version: devel-2e237ca
Error summary: HailException: missing partitioner.json.gz when loading VDS, create with HailContext.write_partitioning.
```

2. gs://hail-common/gencode_and_production_intervals.merged.hg19.vds

```
File "<decorator-gen-162>", line 2, in read
  File "/home/ec2-user/BuildAgent/work/c38e75e72b769a7c/python/hail/java.py", line 113, in handle_py4j
hail.java.FatalError: HailException: missing partitioner.json.gz when loading VDS, create with HailContext.write_partitioning.

Java stack trace:
is.hail.utils.HailException: missing partitioner.json.gz when loading VDS, create with HailContext.write_partitioning.
	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:6)
	at is.hail.utils.package$.fatal(package.scala:20)
	at is.hail.variant.VariantDataset$.liftedTree1$1(VariantDataset.scala:89)
	at is.hail.variant.VariantDataset$.read(VariantDataset.scala:84)
	at is.hail.HailContext$$anonfun$10.apply(HailContext.scala:414)
	at is.hail.HailContext$$anonfun$10.apply(HailContext.scala:413)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at is.hail.HailContext.readAll(HailContext.scala:413)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

Hail version: devel-2e237ca
Error summary: HailException: missing partitioner.json.gz when loading VDS, create with HailContext.write_partitioning.
```

**Comment by johnc1231** [comment]
Yeah, that error indicates that those are old format VDS's, so Hail won't load them unless someone with write access to hail-common uses the "write_partioning" method to update them. I'll handle that now.

**Comment by johnc1231** [comment]
They should work now.
