### ISSUE TITLE
Bad error message prints Java Bytecode

### ISSUE THREAD

**Issue by johnc1231** [hail-is/hail#1705]
Tried to run this code:

`vds.annotate_samples_expr('sa.variant1 = gs.filter(g => v == Variant("1:55505447:C:T")).collect()[0].gt')`

But the variant was not in the dataset at all, so got an out of bounds error, but it looked like this:

```
[Stage 2:======================================================>(278 + 1) / 279]// class version 52.0 (52)
// access flags 0x1
public class is/hail/codegen/generated/C0 implements java/io/Serializable scala/Function2  {


  // access flags 0x1
  public apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
   L0
    ALOAD 1
    CHECKCAST [Ljava/lang/Object;
    LDC 0
    AALOAD
    INVOKEINTERFACE scala/Function0.apply ()Ljava/lang/Object;
    CHECKCAST scala/collection/IndexedSeq
    ASTORE 3
    ALOAD 3
    IFNULL L1
    NEW java/lang/Integer
    DUP
    LDC 0
    INVOKESPECIAL java/lang/Integer.<init> (I)V
    ASTORE 4
    ALOAD 4
    IFNULL L2
    ALOAD 4
    INVOKEVIRTUAL java/lang/Number.intValue ()I
    ISTORE 5
    ALOAD 3
    ILOAD 5
    LDC 0
    IF_ICMPGE L3
    GOTO L4
   L4
   FRAME FULL [is/hail/codegen/generated/C0 java/lang/Object java/lang/Object scala/collection/IndexedSeq java/lang/Integer I] [scala/collection/IndexedSeq]
    ILOAD 5
    ALOAD 3
    INVOKEINTERFACE scala/collection/IndexedSeq.size ()I
    IADD
    GOTO L5
   L3
   FRAME SAME1 scala/collection/IndexedSeq
    ILOAD 5
   L5
   FRAME FULL [is/hail/codegen/generated/C0 java/lang/Object java/lang/Object scala/collection/IndexedSeq java/lang/Integer I] [scala/collection/IndexedSeq I]
    INVOKEINTERFACE scala/collection/IndexedSeq.apply (I)Ljava/lang/Object;
    GOTO L6
   L2
   FRAME CHOP 1
    ACONST_NULL
   L6
   FRAME SAME1 java/lang/Object
    GOTO L7
   L1
   FRAME CHOP 1
    ACONST_NULL
   L7
   FRAME SAME1 java/lang/Object
    CHECKCAST is/hail/variant/Genotype
    ASTORE 6
    ALOAD 6
    IFNULL L8
    ALOAD 6
    INVOKEVIRTUAL is/hail/variant/Genotype.unboxedGT ()I
    ISTORE 7
    ILOAD 7
    LDC -1
    IF_ICMPEQ L9
    GOTO L10
   L10
   FRAME FULL [is/hail/codegen/generated/C0 java/lang/Object java/lang/Object scala/collection/IndexedSeq T T is/hail/variant/Genotype I] []
    NEW java/lang/Integer
    DUP
    ILOAD 7
    INVOKESPECIAL java/lang/Integer.<init> (I)V
    GOTO L11
   L9
   FRAME SAME
    ACONST_NULL
   L11
   FRAME SAME1 java/lang/Integer
    GOTO L12
   L8
   FRAME CHOP 1
    ACONST_NULL
   L12
   FRAME SAME1 java/lang/Integer
    CHECKCAST java/lang/Integer
    ARETURN
   L13
    LOCALVARIABLE local3 Ljava/lang/Object; L0 L13 3
    LOCALVARIABLE local4 Ljava/lang/Object; L0 L13 4
    LOCALVARIABLE local5 I L0 L13 5
    LOCALVARIABLE local6 Ljava/lang/Object; L0 L13 6
    LOCALVARIABLE local7 I L0 L13 7
    MAXSTACK = 3
    MAXLOCALS = 8

  // access flags 0x1
  public <init>()V
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 1
}
Traceback (most recent call last):
  File "/tmp/990e2e0c-f333-467e-b1fd-6cfe8f5d5645/fastlmmForJon.py", line 6, in <module>
    vds = vds.annotate_samples_expr('sa.variant1 = gs.filter(g => v == Variant("1:15211:T:G")).collect()[0].gt')
  File "<decorator-gen-65>", line 2, in annotate_samples_expr
  File "/home/ec2-user/BuildAgent/work/c38e75e72b769a7c/python/hail/java.py", line 113, in handle_py4j
hail.java.FatalError: IndexOutOfBoundsException: 0

Java stack trace:
java.lang.IndexOutOfBoundsException: 0
	at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
	at is.hail.codegen.generated.C0.apply(Unknown Source)
	at is.hail.asm4s.Function2Builder$$anon$11.apply(FunctionBuilder.scala:441)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:72)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:70)
	at is.hail.expr.Parser$$anonfun$is$hail$expr$Parser$$evalNoTypeCheck$1.apply(Parser.scala:53)
	at is.hail.expr.Parser$$anonfun$parseNamedExprs$2$$anonfun$apply$2.apply$mcV$sp(Parser.scala:218)
	at is.hail.expr.Parser$$anonfun$parseNamedExprs$3$$anonfun$apply$15.apply(Parser.scala:229)
	at is.hail.expr.Parser$$anonfun$parseNamedExprs$3$$anonfun$apply$15.apply(Parser.scala:229)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at is.hail.expr.Parser$$anonfun$parseNamedExprs$3.apply(Parser.scala:229)
	at is.hail.expr.Parser$$anonfun$parseNamedExprs$3.apply(Parser.scala:228)
	at is.hail.expr.Parser$$anonfun$parseAnnotationExprs$4.apply(Parser.scala:115)
	at is.hail.expr.Parser$$anonfun$parseAnnotationExprs$4.apply(Parser.scala:114)
	at is.hail.variant.VariantSampleMatrix$$anonfun$34.apply(VariantSampleMatrix.scala:544)
	at is.hail.variant.VariantSampleMatrix$$anonfun$34.apply(VariantSampleMatrix.scala:540)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at is.hail.variant.VariantSampleMatrix.annotateSamplesExpr(VariantSampleMatrix.scala:540)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

Hail version: devel-e081278
Error summary: IndexOutOfBoundsException: 0
```

**Comment by johnc1231** [comment]
Intentional
