### ISSUE TITLE
keytable.join() bug

### ISSUE THREAD

**Issue by 09mh** [hail-is/hail#1725]
```
Struct {
    varid: String,
    C1: Double,
    C2: Double
}
[u'varid']
+--------------------+--------+---------+
|               varid|      C1|       C2|
+--------------------+--------+---------+
|         1:10013_A_C|0.982391| 0.739284|
|         1:10179_G_T|0.999869| 0.830932|
|         1:10259_C_A|0.995202| 0.714716|
|         1:10292_C_T|0.999978| 0.894148|
|         1:10402_G_A|0.999978| 0.410557|
|         1:10527_T_A|0.996032| 0.586588|
|         1:10611_G_A|0.999209| 0.917891|
|         1:10754_G_C|0.999745| 0.773538|
|         1:11099_T_G|0.999707| 0.886131|
|         1:11155_C_A|0.999120| 0.541211|
+--------------------+--------+---------+
only showing top 10 rows

Struct {
    v: Variant,
    `va.varid`: String
}
[u'v']
+--------+-------+--------------------+--------------------+--------------------+
|v.contig|v.start|               v.ref|        v.altAlleles|            va.varid|
+--------+-------+--------------------+--------------------+--------------------+
|      01|  10013|                   A|             [[A,C]]|         1:10013_A_C|
|      01|  10179|                   G|             [[G,T]]|         1:10179_G_T|
|      01|  10259|                   C|             [[C,A]]|         1:10259_C_A|
|      01|  10292|                   C|             [[C,T]]|         1:10292_C_T|
|      01|  10402|                   G|             [[G,A]]|         1:10402_G_A|
|      01|  10527|                   T|             [[T,A]]|         1:10527_T_A|
|      01|  10611|                   G|             [[G,A]]|         1:10611_G_A|
|      01|  10754|                   G|             [[G,C]]|         1:10754_G_C|
|      01|  11099|                   T|             [[T,G]]|         1:11099_T_G|
|      01|  11115|                   C|             [[C,A]]|         1:11155_C_A|
+--------+-------+--------------------+--------------------+--------------------+
only showing top 10 rows

Struct {
    v: Variant,
    `va.varid`: String
}
[u'va.varid']
+--------+-------+--------------------+--------------------+--------------------+
|v.contig|v.start|               v.ref|        v.altAlleles|            va.varid|
+--------+-------+--------------------+--------------------+--------------------+
|      01|  10013|                   A|             [[A,C]]|         1:10013_A_C|
|      01|  10179|                   G|             [[G,T]]|         1:10179_G_T|
|      01|  10259|                   C|             [[C,A]]|         1:10259_C_A|
|      01|  10292|                   C|             [[C,T]]|         1:10292_C_T|
|      01|  10402|                   G|             [[G,A]]|         1:10402_G_A|
|      01|  10527|                   T|             [[T,A]]|         1:10527_T_A|
|      01|  10611|                   G|             [[G,A]]|         1:10611_G_A|
|      01|  10754|                   G|             [[G,C]]|         1:10754_G_C|
|      01|  11099|                   T|             [[T,G]]|         1:11099_T_G|
|      01|  11115|                   C|             [[C,A]]|         1:11155_C_A|
+--------+-------+--------------------+--------------------+--------------------+
only showing top 10 rows

Struct {
    v: Variant,
    `va.varid`: String,
    C1: Double,
    C2: Double
}
[u'va.varid']
[Stage 6:====================================================>(1640 + 1) / 1641]Traceback (most recent call last):
  File "/tmp/ec5f6e42-0ea7-404d-8311-f97f7ec26ad6/kt_troubleshooting_issue_042617.py", line 31, in <module>
    kt2.to_dataframe().show(10)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 287, in show
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o448.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8.0 failed 20 times, most recent failure: Lost task 0.19 in stage 8.0 (TID 3406, cluster-mh-sw-xn3h.c.practice.internal): java.lang.ClassCastException: java.lang.String cannot be cast to is.hail.variant.Variant
```

**Comment by 09mh** [comment]
Script for above output:
```
#load hail
from hail import *

#set minimum partition size and log location
hc = HailContext(min_block_size=50, log="/home/09mh/kt_troubleshooting_issue_042617.hail.log")

#import bgen and convert to vds
vds = hc.import_bgen("gs://pipeline/testGWAS/chr1.bgen",sample_file="gs://pipeline/testGWAS/inds_info.sample")

kt1 = hc.import_keytable('gs://pipeline/testGWAS/var_anno.tsv', config=TextTableConfig(impute=True,delimiter=' ')).rename(['varid','rsid','C1','C2']).select(['varid','C1','C2']).key_by(['varid'])
#check import of var_anno & conversion
print(kt1.schema)
print(kt1.key_names)
kt1.to_dataframe().show(10)

vds_kt = vds.variants_keytable().flatten().select(['v','va.varid']).key_by(['v'])
#check keytable made from vds
print(vds_kt.schema)
print(vds_kt.key_names)
vds_kt.to_dataframe().show(10)

vds_kt = vds.variants_keytable().flatten().select(['v','va.varid']).key_by(['va.varid'])
print(vds_kt.schema)
print(vds_kt.key_names)
vds_kt.to_dataframe().show(10)

kt2 = vds_kt.join(kt1,how='left')
#check join
print(kt2.schema)
print(kt2.key_names)
kt2.to_dataframe().show(10)
kt2 = kt2.key_by(['v'])

print('After rekeying:')
print(kt2.schema)
print(kt2.key_names)
kt2.to_dataframe().show(10)

kt2.write('gs://pipeline/testGWAS/chr1_var_anno.kt')
```

**Comment by tpoterba** [comment]
ok, I have this replicating locally
