### ISSUE TITLE
is.hail.driver.Main changed to something else

### ISSUE THREAD

**Issue by tushu1232** [hail-is/hail#1807]
I am getting following error while using spark submit with --class "is.hail.driver.Main" /test/spark/hail15may.jar

java.lang.ClassNotFoundException: is.hail.driver.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:693)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by tpoterba** [comment]
It sounds like you were using the old command-line interface. Hail has moved to a python API, documented here:
https://hail.is/hail/api.html
https://hail.is/hail/getting_started.html

**Comment by tushu1232** [comment]
Is there way to use the old command line as well?

**Comment by jbloom22** [comment]
No, we moved to the Python model about a year ago and have added many features since, so the command line is fully deprecated.

**Comment by tpoterba** [comment]
Analysts at the Broad usually spent less than an hour converting their old cmd-line scripts to Python, as well.

**Comment by tpoterba** [comment]
One more note: feel free to drop by the gitter channel (https://gitter.im/hail-is/hail?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) if you questions about this change!

**Comment by tushu1232** [comment]
Thank you for the help!!
