### ISSUE TITLE
PCA throws error using Breeze 0.12 and natives (BLAS)

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#209]
Cotton thinks this is related to paths in Spark runner

java.lang.NoSuchMethodError: breeze.linalg.DenseVector$.canSetD()Lbreeze/generic/UFunc$InPlaceImpl2;
    at org.apache.spark.mllib.linalg.EigenValueDecomposition$.symmetricEigs(EigenValueDecomposition.scala:110)
    at org.apache.spark.mllib.linalg.distributed.RowMatrix.computeSVD(RowMatrix.scala:269)
    at org.apache.spark.mllib.linalg.distributed.RowMatrix.computeSVD(RowMatrix.scala:195)
    at org.apache.spark.mllib.linalg.distributed.IndexedRowMatrix.computeSVD(IndexedRowMatrix.scala:154)
    at org.broadinstitute.hail.methods.SamplePCA.apply(SamplePCA.scala:10)
    at org.broadinstitute.hail.driver.PCA$.run(PCA.scala:23)
    at org.broadinstitute.hail.driver.PCA$.run(PCA.scala:7)
    at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:69)
    at org.broadinstitute.hail.driver.Command.run(Command.scala:73)
    at org.broadinstitute.hail.PipelineSuite.defaultPipeline(PipelineSuite.scala:22)

**Comment by cseed** [comment]
@jbloom22 Is this still an issue?  It is over a year old, I'm not aware of any problems and there or no details on how to reproduce.

**Comment by jbloom22** [comment]
Same, I'll close.
