### ISSUE TITLE
import_vcf is not happy with 2788 VCFs

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#2136]
Much OOM. Related to #2108?

```
Java stack trace:
java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at htsjdk.variant.vcf.VCFHeader.buildVCFReaderMaps(VCFHeader.java:164)
	at htsjdk.variant.vcf.VCFHeader.<init>(VCFHeader.java:146)
	at htsjdk.variant.vcf.VCFStandardHeaderLines.repairStandardHeaderLines(VCFStandardHeaderLines.java:75)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:223)
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:83)
	at is.hail.io.vcf.LoadVCF$.parseHeader(LoadVCF.scala:162)
	at is.hail.io.vcf.LoadVCF$$anonfun$4.apply(LoadVCF.scala:205)
	at is.hail.io.vcf.LoadVCF$$anonfun$4.apply(LoadVCF.scala:205)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at is.hail.io.vcf.LoadVCF$.apply(LoadVCF.scala:205)
	at is.hail.HailContext.importVCFsGeneric(HailContext.scala:528)
	at is.hail.HailContext.importVCFs(HailContext.scala:484)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by konradjk** [comment]
I would be happy with a `skip_header_check` option in the short run btw :-D

**Comment by tpoterba** [comment]
We'll fix this.
