### ISSUE TITLE
Bytecode failed verification 2 ?

### ISSUE THREAD

**Issue by jtkoskel** [hail-is/hail#2178]
I tried out the tiebreaking_expr with some dummyish data:

```from hail import *
from hail.representation import *
import subprocess
import os
hc = HailContext()

vds = hc.read('gs://daly_atgu_finnish_swedish_exomes_v8/daly_atgu_finnish_swedish_exomes_99prosAndPSC.vds')

vds = vds.filter_variants_expr('va.filters.isEmpty()', keep=True)

intervals = KeyTable.import_interval_list('gs://ibd-exomes/5k.txt')
vds = vds.filter_variants_table(intervals, keep=True)

vds = vds.variant_qc()
vds = vds.filter_variants_expr('va.qc.AF>0.01 && va.qc.callRate>0.99', keep=True)

table = hc.import_table('gs://daly_atgu_finnish_swedish_exomes_v8/finnibdPSC_isCase.txt', impute=True).key_by('s')
vds = vds.annotate_samples_table(table, root='sa.pheno')

vds = vds.repartition(100)
vds = vds.ibd_prune(0.35, tiebreaking_expr="if (sa1.pheno.iscase) 1 else 0")

vds.export_samples('gs://daly_atgu_finnish_swedish_exomes_v8/99pros_psc_relBelowPIHAT35.tsv','s=s')

```

But this results in an error:

```hail: info: Reading table to impute column types
hail: info: Finished type imputation
  Loading column `s' as type String (imputed)
  Loading column `case' as type Int (imputed)
Struct{
     pheno: Int
 }
[Stage 6:====================================================>(3347 + 1) / 3348]Verify Output for is/hail/codegen/generated/C3:
Traceback (most recent call last):
  File "/tmp/0a89b0df-1299-4db1-9e90-0efc77501684/99pros_psc_relatedness_short.py", line 26, in <module>
    vds = vds.ibd_prune(0.35, tiebreaking_expr="if (sa1.pheno) 1 else 0")
  File "<decorator-gen-322>", line 2, in ibd_prune
  File "/home/ec2-user/BuildAgent/work/179f3a9ad532f105/python/hail/java.py", line 112, in handle_py4j
hail.java.FatalError: IllegalStateException: Bytecode failed verification 2

Java stack trace:
java.lang.IllegalStateException: Bytecode failed verification 2
	at is.hail.asm4s.FunctionBuilder.classAsBytes(FunctionBuilder.scala:196)
	at is.hail.asm4s.FunctionBuilder.result(FunctionBuilder.scala:208)
	at is.hail.expr.CM.runWithDelayedValues(CM.scala:78)
	at is.hail.expr.Parser$.is$hail$expr$Parser$$evalNoTypeCheck(Parser.scala:49)
	at is.hail.expr.Parser$.is$hail$expr$Parser$$eval(Parser.scala:62)
	at is.hail.expr.Parser$.parseExpr(Parser.scala:77)
	at is.hail.expr.Parser$.parseTypedExpr(Parser.scala:87)
	at is.hail.methods.IBDPrune$$anonfun$16.apply(IBD.scala:308)
	at is.hail.methods.IBDPrune$$anonfun$16.apply(IBD.scala:308)
	at scala.Option.map(Option.scala:146)
	at is.hail.methods.IBDPrune$.apply(IBD.scala:308)
	at is.hail.variant.VariantDatasetFunctions$.ibdPrune$extension(VariantDataset.scala:529)
	at is.hail.variant.VariantDatasetFunctions.ibdPrune(VariantDataset.scala:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: 0.1-dfca956
Error summary: IllegalStateException: Bytecode failed verification 2
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [0a89b0df-1299-4db1-9e90-0efc77501684] entered state [ERROR] while waiting for [DONE].```

Any idea what's wrong? Thanks!

**Comment by danking** [comment]
@jtkoskel How did you invoke Hail? I suspect there's a missing JAR.

**Comment by konradjk** [comment]
Btw I just saw this too on my local hail rig:
```
In [5]: hc.eval_expr('let x = 5 in x')
Out[5]: 5
```
works fine.
```
hc.eval_expr("let x = if (1) '1' else NA: String in x")
```
throws:
```
FatalError: IllegalStateException: Bytecode failed verification 2

Java stack trace:
java.lang.IllegalStateException: Bytecode failed verification 2
	at is.hail.asm4s.FunctionBuilder.classAsBytes(FunctionBuilder.scala:196)
	at is.hail.asm4s.FunctionBuilder.result(FunctionBuilder.scala:208)
	at is.hail.expr.CM.runWithDelayedValues(CM.scala:78)
	at is.hail.expr.Parser$.is$hail$expr$Parser$$evalNoTypeCheck(Parser.scala:50)
	at is.hail.expr.Parser$.is$hail$expr$Parser$$eval(Parser.scala:63)
	at is.hail.expr.Parser$.parseExpr(Parser.scala:78)
	at is.hail.HailContext.eval(HailContext.scala:622)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```
Happens on `0.1-1fd5cc7` as well as `devel-9e4a5bb`

**Comment by konradjk** [comment]
There's an `if else` in both of our expressions so perhaps that's the culprit?

**Comment by danking** [comment]
Do you see a `ByteCodeOuput.txt` file in your current working directory? That would be very helpful to me if you can upload it.

**Comment by danking** [comment]
@konradjk thanks for the succinct test case, I can reproduce.

**Comment by danking** [comment]
@konradjk @jtkoskel Ah the issue is two-fold: the compiler doesn't automatically cast types to booleans AND (perhaps more importantly) it doesn't signal a type error when the condition of an if expression is not a boolean. I'll look into this more on Monday.

**Comment by danking** [comment]
@konradjk @jtkoskel Quick solution for you two is to explicitly convert the `Int` valued expression to a `Boolean` valued expression, i.e. `sa1.pheno.iscase == 1` (if `1` means the sample is a case).

**Comment by jtkoskel** [comment]
@danking I then get
```Error summary: HailException: expression has wrong type: expected `Int', got Boolean```

**Comment by danking** [comment]
@jtkoskel The condition of an `if` must be a `Boolean`, but the tie breaking expression must indicate an [ordering of the two samples](https://hail.is/docs/stable/hail.VariantDataset.html?highlight=ibd_prune#hail.VariantDataset.ibd_prune). I believe you're looking for this line:

```
vds = vds.ibd_prune(0.35, tiebreaking_expr="if (sa1.pheno.iscase == 1) 1 else 0")
```

Assuming that `1` means that the sample is a case and that you prefer to keep cases over controls.

**Comment by jtkoskel** [comment]
@danking Right, thanks!!

**Comment by tpoterba** [comment]
looks like this is fixed
