### ISSUE TITLE
functions.cond can't be added together

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#2653]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:
```
eval_expr(functions.cond(functions.capture(True), 'T', 'F') + functions.cond(functions.capture(True), 'T', 'F'))
```

### What went wrong (all error messages here, including the full java stack trace):

```
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-20-3b0a2ce317c2> in <module>()
----> 1 eval_expr(functions.cond(functions.capture(True), 'T', 'F') + functions.cond(functions.capture(True), 'T', 'F'))

<decorator-gen-365> in eval_expr(expression)

/hadoop_gcs_connector_metadata_cache/hail/hail-devel-45429b164934.zip/hail/expr/expression.py in args_to_expr(func, *args)
    176 @decorator
    177 def args_to_expr(func, *args):
--> 178     return func(*(to_expr(a) for a in args))
    179
    180

/hadoop_gcs_connector_metadata_cache/hail/hail-devel-45429b164934.zip/hail/expr/expression.py in eval_expr(expression)
   3576         Result of evaluating `expression`.
   3577     """
-> 3578     return eval_expr_typed(expression)[0]
   3579
   3580

<decorator-gen-366> in eval_expr_typed(expression)

/hadoop_gcs_connector_metadata_cache/hail/hail-devel-45429b164934.zip/hail/expr/expression.py in args_to_expr(func, *args)
    176 @decorator
    177 def args_to_expr(func, *args):
--> 178     return func(*(to_expr(a) for a in args))
    179
    180

/hadoop_gcs_connector_metadata_cache/hail/hail-devel-45429b164934.zip/hail/expr/expression.py in eval_expr_typed(expression)
   3612     if len(expression._joins) > 0:
   3613         raise ExpressionException("'eval_expr' methods do not support joins or broadcasts")
-> 3614     r, t = Env.hc().eval_expr_typed(expression._ast.to_hql())
   3615     return r, t
   3616

<decorator-gen-1049> in eval_expr_typed(self, expr)

/hadoop_gcs_connector_metadata_cache/hail/hail-devel-45429b164934.zip/hail/utils/java.py in handle_py4j(func, *args, **kwargs)
    153         raise FatalError('%s\n\nJava stack trace:\n%s\n'
    154                          'Hail version: %s\n'
--> 155                          'Error summary: %s' % (deepest, full, Env.hc().version, deepest))
    156     except py4j.protocol.Py4JError as e:
    157         if e.args[0].startswith('An error occurred while calling'):

FatalError: HailException: `(' expected but `i' found
<input>:1:(if (true) "T" else "F" + if (true) "T" else "F")
                                    ^

Java stack trace:
is.hail.utils.HailException: `(' expected but `i' found
<input>:1:(if (true) "T" else "F" + if (true) "T" else "F")
                                    ^
	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:6)
	at is.hail.utils.package$.fatal(package.scala:27)
	at is.hail.expr.ParserUtils$.error(Parser.scala:32)
	at is.hail.expr.RichParser.parse(Parser.scala:16)
	at is.hail.expr.Parser$.parseExpr(Parser.scala:85)
	at is.hail.HailContext.eval(HailContext.scala:613)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-45429b1
Error summary: HailException: `(' expected but `i' found
<input>:1:(if (true) "T" else "F" + if (true) "T" else "F")
                                    ^
```

**Comment by konradjk** [comment]
Looks like not enough parens?

**Comment by tpoterba** [comment]
yeah, if/else should be wrapped in parens. Will submit a patch.
