### ISSUE TITLE
VEP error - Can't zip RDDs with unequal numbers of partitions

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#2666]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What went wrong (all error messages here, including the full java stack trace):

Traceback (most recent call last):
  File "/tmp/2f781c88-64f1-4345-a2b9-433c49d5a099/script_to_submit.py", line 8, in <module>
    vdsvep = vds.vep("/vep/vep-gcloud.properties")
  File "<decorator-gen-878>", line 2, in vep
  File "/tmp/2f781c88-64f1-4345-a2b9-433c49d5a099/hail-devel-6191d4ce69aa.zip/hail/utils/java.py", line 167, in handle_py4j
hail.utils.java.FatalError: Can't zip RDDs with unequal numbers of partitions: List(16979, 16992)

Java stack trace:
org.apache.spark.rdd.ZippedPartitionsBaseRDD.getPartitions(ZippedPartitionsRDD.scala:57)
	 at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
	 at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
	 at scala.Option.getOrElse(Option.scala:121)
	 at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
	 at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	 at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
	 at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
	 at scala.Option.getOrElse(Option.scala:121)
	 at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
	 at is.hail.sparkextras.OrderedRDD$.coerce(OrderedRDD.scala:58)
	 at is.hail.sparkextras.OrderedRDD$.apply(OrderedRDD.scala:48)
	 at is.hail.utils.richUtils.RichPairRDD$.toOrderedRDD$extension1(RichPairRDD.scala:44)
	 at is.hail.variant.MatrixTable$.fromLegacy(MatrixTable.scala:84)
	 at is.hail.variant.MatrixTable.copyLegacy(MatrixTable.scala:2019)
	 at is.hail.methods.VEP$.annotate(VEP.scala:407)
	 at is.hail.methods.VEP$.apply(VEP.scala:412)
	 at is.hail.methods.VEP.apply(VEP.scala)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	 at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	 at py4j.Gateway.invoke(Gateway.java:280)
	 at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	 at py4j.commands.CallCommand.execute(CallCommand.java:79)
	 at py4j.GatewayConnection.run(GatewayConnection.java:214)
	 at java.lang.Thread.run(Thread.java:748)
Hail version: devel-6191d4c
Error summary: Can't zip RDDs with unequal numbers of partitions: List(16979, 16992)

**Comment by tpoterba** [comment]
think this is fixed
