### ISSUE TITLE
assertion failed error when using concordance

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#2743]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
devel

### What you did:
```
hc = HailContext()
    past_vds = hc.read(args.past)
    future_vds = hc.read(args.future)

    bi_past_vds = past_vds.filter_rows(past_vds.v.is_biallelic())
    bi_future_vds = future_vds.filter_rows(future_vds.v.is_biallelic())
    bi_summary, bi_samples, bi_variants = methods.concordance(bi_past_vds, bi_future_vds)
```

### What went wrong (all error messages here, including the full java stack trace):
```
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version devel-08a1543
WARNING: This is an unstable development build.
2018-01-17 18:32:09 Hail: INFO: Found 729 overlapping samples
  Left: 729 total samples
  Right: 729 total samples
2018-01-17 18:32:10 Hail: WARN: converting OrderedRVD => OrderedRDD
[Stage 0:====================================================>(4627 + 1) / 4628]2018-01-17 18:47:04 Hail: INFO: Coerced sorted dataset
2018-01-17 18:47:04 Hail: WARN: converting OrderedRVD => OrderedRDD
[Stage 1:>                                                      (7 + 28) / 4969]Traceback (most recent call last):
  File "/tmp/f93de2d1-2d89-43f9-9868-f266eb88a6f1/concordance.py", line 38, in <module>
    main(args)
  File "/tmp/f93de2d1-2d89-43f9-9868-f266eb88a6f1/concordance.py", line 19, in main
    bi_summary, bi_samples, bi_variants = methods.concordance(bi_past_vds, bi_future_vds)
  File "<decorator-gen-1304>", line 2, in concordance
  File "/tmp/f93de2d1-2d89-43f9-9868-f266eb88a6f1/hail-devel-08a15431a0ef.zip/hail/utils/java.py", line 155, in handle_py4j
hail.utils.java.FatalError: AssertionError: assertion failed

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 30 in stage 1.0 failed 20 times, most recent failure: Lost task 30.19 in stage 1.0 (TID 4847, lfdev2-sw-f5w2.c.broad-mpg-gnomad.internal): java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at is.hail.annotations.Region.loadInt(Region.scala:36)
	at is.hail.expr.types.TBinary$.loadLength(TBinary.scala:62)
	at is.hail.annotations.UnsafeRow$.readBinary(UnsafeRow.scala:128)
	at is.hail.annotations.UnsafeRow$.readString(UnsafeRow.scala:139)
	at is.hail.annotations.UnsafeRow$.readAltAllele(UnsafeRow.scala:152)
	at is.hail.annotations.UnsafeRow$.readArrayAltAllele(UnsafeRow.scala:164)
	at is.hail.annotations.UnsafeRow$.read(UnsafeRow.scala:210)
	at is.hail.annotations.UnsafeRow.get(UnsafeRow.scala:257)
	at is.hail.expr.FilterVariants$$anonfun$10.apply(Relational.scala:503)
	at is.hail.expr.FilterVariants$$anonfun$10.apply(Relational.scala:500)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.hasNext(OrderedRVD.scala:658)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.hasNext(OrderedRVD.scala:658)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.hasNext(OrderedRVD.scala:658)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$5$$anon$2.hasNext(OrderedRDD.scala:194)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.PartitionKeyInfo$.apply(PartitionKeyInfo.scala:30)
	at is.hail.sparkextras.OrderedRDD$$anonfun$4.apply(OrderedRDD.scala:72)
	at is.hail.sparkextras.OrderedRDD$$anonfun$4.apply(OrderedRDD.scala:70)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:820)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:820)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1886)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1899)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1913)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:912)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:911)
	at is.hail.sparkextras.OrderedRDD$.coerce(OrderedRDD.scala:75)
	at is.hail.sparkextras.OrderedRDD$.apply(OrderedRDD.scala:49)
	at is.hail.utils.richUtils.RichPairRDD$.toOrderedRDD$extension1(RichPairRDD.scala:44)
	at is.hail.variant.MatrixTable.typedRDD(MatrixTable.scala:475)
	at is.hail.methods.CalculateConcordance$.apply(CalculateConcordance.scala:108)
	at is.hail.methods.CalculateConcordance.apply(CalculateConcordance.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at is.hail.annotations.Region.loadInt(Region.scala:36)
	at is.hail.expr.types.TBinary$.loadLength(TBinary.scala:62)
	at is.hail.annotations.UnsafeRow$.readBinary(UnsafeRow.scala:128)
	at is.hail.annotations.UnsafeRow$.readString(UnsafeRow.scala:139)
	at is.hail.annotations.UnsafeRow$.readAltAllele(UnsafeRow.scala:152)
	at is.hail.annotations.UnsafeRow$.readArrayAltAllele(UnsafeRow.scala:164)
	at is.hail.annotations.UnsafeRow$.read(UnsafeRow.scala:210)
	at is.hail.annotations.UnsafeRow.get(UnsafeRow.scala:257)
	at is.hail.expr.FilterVariants$$anonfun$10.apply(Relational.scala:503)
	at is.hail.expr.FilterVariants$$anonfun$10.apply(Relational.scala:500)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.hasNext(OrderedRVD.scala:658)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.hasNext(OrderedRVD.scala:658)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.hasNext(OrderedRVD.scala:658)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$5$$anon$2.hasNext(OrderedRDD.scala:194)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.PartitionKeyInfo$.apply(PartitionKeyInfo.scala:30)
	at is.hail.sparkextras.OrderedRDD$$anonfun$4.apply(OrderedRDD.scala:72)
	at is.hail.sparkextras.OrderedRDD$$anonfun$4.apply(OrderedRDD.scala:70)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:820)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:820)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


Hail version: devel-08a1543
Error summary: AssertionError: assertion failed
```

**Comment by tpoterba** [comment]
can you read and write each of these vdses with current version?

**Comment by lfrancioli** [comment]
yes, just tried and finished successfully

**Comment by tpoterba** [comment]
okay, so this must be some problem with the code, not the file format. Can you reproduce the error in the current version from the new files?

**Comment by lfrancioli** [comment]
yes, exact same problem.

The VDSs are:
`gs://future-variant-calling/future-pipeline/future.vds`
and
`gs://future-variant-calling/old-pipeline/past.vds`

You should have access in case you want to try things.

**Comment by tpoterba** [comment]
will look into it! thanks for helping.

**Comment by lfrancioli** [comment]
So it seems like the problem is with 
`gs://future-variant-calling/future-pipeline/future.vds`

trying to run `sample_qc` on it also fails in exactly the same way...

**Comment by tpoterba** [comment]
fixed.
