### ISSUE TITLE
split_multi_hts on hardcalled VDS

### ISSUE THREAD

**Issue by uqrmaie1** [hail-is/hail#2755]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
devel-64a1fac

### What you did:
run split_multi_hts on a VDS with only GT genotype field

### What went wrong (all error messages here, including the full java stack trace):
```
is.hail.utils.HailException: Struct has no field `AD'
  Available fields:
    GT: Call
<input>:4:  newad = if (isDefined(g.AD))
                                   ^
                    at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:6)
                    at is.hail.utils.package$.fatal(package.scala:27)
                    at is.hail.expr.ParserUtils$.error(Parser.scala:33)
                    at is.hail.expr.AST.parseError(AST.scala:255)
                    at is.hail.expr.Select.typecheckThis(AST.scala:333)
                    at is.hail.expr.AST.typecheckThis(AST.scala:246)
                    at is.hail.expr.AST.typecheck(AST.scala:252)
                    at is.hail.expr.AST$$anonfun$typecheck$1.apply(AST.scala:251)
                    at is.hail.expr.AST$$anonfun$typecheck$1.apply(AST.scala:251)
                    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
                    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
                    at is.hail.expr.AST.typecheck(AST.scala:251)
                    at is.hail.expr.Apply.typecheck(AST.scala:663)
                    at is.hail.expr.AST$$anonfun$typecheck$1.apply(AST.scala:251)
                    at is.hail.expr.AST$$anonfun$typecheck$1.apply(AST.scala:251)
                    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
                    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
                    at is.hail.expr.AST.typecheck(AST.scala:251)
                    at is.hail.expr.Let$$anonfun$typecheck$18.apply(AST.scala:850)
                    at is.hail.expr.Let$$anonfun$typecheck$18.apply(AST.scala:849)
                    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
                    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
                    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
                    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
                    at is.hail.expr.Let.typecheck(AST.scala:849)
                    at is.hail.expr.Parser$$anonfun$13.apply(Parser.scala:204)
                    at is.hail.expr.Parser$$anonfun$13.apply(Parser.scala:203)
                    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                    at scala.collection.immutable.List.foreach(List.scala:381)
                    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
                    at scala.collection.immutable.List.map(List.scala:285)
                    at is.hail.expr.Parser$.parseNamedExprs(Parser.scala:203)
                    at is.hail.expr.Parser$.parseAnnotationExprs(Parser.scala:123)
                    at is.hail.methods.ExprAnnotator.<init>(SplitMulti.scala:14)
                    at is.hail.methods.SplitMulti.<init>(SplitMulti.scala:179)
                    at is.hail.methods.SplitMulti$.apply(SplitMulti.scala:149)
                    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                    at java.lang.reflect.Method.invoke(Method.java:498)
                    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
                    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
                    at py4j.Gateway.invoke(Gateway.java:280)
```

**Comment by jigold** [comment]
I think the fix for this is to add a `hasField` method on a Struct AST that takes a string with the field name and returns a boolean. So the expr code would be `if (g.hasField("AD")) ...`.
