### ISSUE TITLE
region memory layout/access bug related to joins

### ISSUE THREAD

**Issue by uqrmaie1** [hail-is/hail#2763]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
devel-92bbe4b

### What you did:
I used `join` to combine two VDS. Empty sample schema, different variant schema, no overlapping samples, hardcalls.

### What went wrong (all error messages here, including the full java stack trace):
Got an AssertionError:
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 20 times, most recent failure: Lost task 0.19 in stage 5.0 (TID 677, mycluster3-w-1.c.ccdg-wgs.internal): java.lang.AssertionError: assertion failed
                    at scala.Predef$.assert(Predef.scala:156)
                    at is.hail.annotations.Region.loadInt(Region.scala:36)
                    at is.hail.expr.types.TContainer$.loadLength(TContainer.scala:9)
                    at is.hail.expr.types.TContainer.loadLength(TContainer.scala:27)
                    at is.hail.variant.MatrixTable$$anonfun$105$$anonfun$apply$58.apply(MatrixTable.scala:1702)
                    at is.hail.variant.MatrixTable$$anonfun$105$$anonfun$apply$58.apply(MatrixTable.scala:1685)
                    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
                    at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.next(OrderedRVD.scala:661)
                    at is.hail.rvd.OrderedRVD$$anonfun$apply$9$$anon$5.next(OrderedRVD.scala:655)
```

I can make it work by copying the variant annotation from one VDS to the other before calling `join`.

**Comment by cseed** [comment]
Thanks for the clear bug report @uqrmaie1!  Let me know if you have any more trouble.
