### ISSUE TITLE
Table IR makeArray is broken

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#2905]
Trigger with `Table.range(1).annotate(x=[1, 1.0])`
```
Java stack trace:
java.lang.AssertionError: assertion failed: at position 1 type mismatch: Int32 Float64
	at scala.Predef$.assert(Predef.scala:170)
	at is.hail.expr.ir.Infer$$anonfun$apply$4.apply(Infer.scala:59)
	at is.hail.expr.ir.Infer$$anonfun$apply$4.apply(Infer.scala:59)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:59)
	at is.hail.expr.ir.Infer$.is$hail$expr$ir$Infer$$infer$1(Infer.scala:9)
	at is.hail.expr.ir.Infer$$anonfun$apply$10.apply(Infer.scala:129)
	at is.hail.expr.ir.Infer$$anonfun$apply$10.apply(Infer.scala:129)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:129)
	at is.hail.expr.TableAnnotate.<init>(Relational.scala:495)
	at is.hail.table.Table.annotate(Table.scala:502)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tpoterba** [comment]
fixed with the Python3 commit by punting toIR for heterogeneous array declarations.
