### ISSUE TITLE
Hail JAR not visible on workers when using PySpark shell.

### ISSUE THREAD

**Issue by mptrepanier** [hail-is/hail#2966]
### Hail version:
Hail version: 0.1-20613ed
Error summary: ClassNotFoundException: is.hail.asm4s.AsmFunction2

Hail JAR appears to not be visible on workers despite setting `--jars`, `--driver-class-path`, and `--conf spark.executor.extraClassPath`. 

### What you did:
1) Downloaded pre-built binaries for 2.0.2

2) Zipped the hail/python/hail folder into hail.zip.

3) Launched a local pyspark shell as follows:
```
pyspark --jars $HAIL_HOME/jars/hail-all-spark.jar \
>         --driver-class-path ./hail-all-spark.jar \
>         --conf spark.executor.extraClassPath=./hail-all-spark.jar \
>         --py-files $HAIL_HOME/python/hail.zip \
>         --conf spark.sql.files.openCostInBytes=1099511627776 \
>         --conf spark.sql.files.maxPartitionBytes=1099511627776 \
>         --conf spark.hadoop.parquet.block.size=1099511627776
```

4) Attempted to run the Hail tutorial, received an error when calling `common_vds = common_vds.filter_genotypes('let ab = g.ad[1] / g.ad.sum() in ((g.isHomRef && ab <= 0.1) || (g.isHet && ab >= 0.25 && ab <= 0.75) ||(g.isHomVar && ab >= 0.9))')`.

### What went wrong (all error messages here, including the full java stack trace):
```
Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
18/02/22 20:29:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/02/22 20:29:10 WARN Utils: Your hostname, CompyWompy resolves to a loopback address: 127.0.1.1; using 192.168.1.122 instead (on interface eth0)
18/02/22 20:29:10 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.0.2
      /_/

Using Python version 2.7.14 (default, Oct 16 2017 17:29:19)
SparkSession available as 'spark'.
>>> from hail import *
>>> hc = HailContext(spark.sparkContext)
Running on Apache Spark version 2.0.2
SparkUI available at http://192.168.1.122:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.1-20613ed
>>> table = hc.import_table('data/1kg_annotations.txt', impute=True).key_by('Sample')
2018-02-22 20:29:45 Hail: INFO: Reading table to impute column types
2018-02-22 20:29:45 Hail: INFO: Finished type imputation
  Loading column `Sample' as type String (imputed)
  Loading column `Population' as type String (imputed)
  Loading column `SuperPopulation' as type String (imputed)
  Loading column `isFemale' as type Boolean (imputed)
  Loading column `PurpleHair' as type Boolean (imputed)
  Loading column `CaffeineConsumption' as type Int (imputed)
>>> common_vds = hc.read('/mnt/d/metistream/hail/data/1kg.vds')
>>> common_vds = common_vds.annotate_samples_table(table, root='sa')
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
>>> common_vds = common_vds.sample_qc()
>>> common_vds = common_vds.filter_samples_expr('sa.qc.dpMean >= 4 && sa.qc.callRate >= 0.97')
>>> common_vds = common_vds.filter_genotypes('let ab = g.ad[1] / g.ad.sum() in ((g.isHomRef && ab <= 0.1) || (g.isHet && ab >= 0.25 && ab <= 0.75) ||(g.isHomVar && ab >= 0.9))')
// class version 52.0 (52)
// access flags 0x1
public class is/hail/codegen/generated/C0 implements java/io/Serializable is/hail/asm4s/AsmFunction2  {


  // access flags 0x1
  public apply([Ljava/lang/Object;Lscala/collection/mutable/ArrayBuffer;)Ljava/lang/Object;
   L0
    ALOAD 2
    LDC 2
    INVOKEVIRTUAL scala/collection/mutable/ArrayBuffer.apply (I)Ljava/lang/Object;
    CHECKCAST org/apache/spark/sql/Row
    ASTORE 3
    ALOAD 3
    IFNULL L1
    ALOAD 3
    LDC 5
    INVOKEINTERFACE org/apache/spark/sql/Row.get (I)Ljava/lang/Object;
    CHECKCAST org/apache/spark/sql/Row
    GOTO L2
   L1
   FRAME APPEND [org/apache/spark/sql/Row]
    ACONST_NULL
   L2
   FRAME SAME1 org/apache/spark/sql/Row
    ASTORE 4
    ALOAD 4
    IFNULL L3
    ALOAD 4
    LDC 12
    INVOKEINTERFACE org/apache/spark/sql/Row.get (I)Ljava/lang/Object;
    CHECKCAST java/lang/Double
    GOTO L4
   L3
   FRAME APPEND [org/apache/spark/sql/Row]
    ACONST_NULL
   L4
   FRAME SAME1 java/lang/Double
    ASTORE 5
    ALOAD 5
    IFNULL L5
    NEW java/lang/Integer
    DUP
    LDC 4
    INVOKESPECIAL java/lang/Integer.<init> (I)V
    ASTORE 6
    ALOAD 6
    IFNULL L6
    ALOAD 1
    LDC 0
    AALOAD
    ALOAD 5
    ALOAD 6
    INVOKEINTERFACE scala/Function2.apply (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    GOTO L7
   L6
   FRAME APPEND [java/lang/Double java/lang/Integer]
    ACONST_NULL
   L7
   FRAME SAME1 java/lang/Object
    GOTO L8
   L5
   FRAME CHOP 1
    ACONST_NULL
   L8
   FRAME SAME1 java/lang/Object
    CHECKCAST java/lang/Boolean
    DUP
    IFNULL L9
    DUP
    INVOKEVIRTUAL java/lang/Boolean.booleanValue ()Z
    IFEQ L10
   L9
   FRAME SAME1 java/lang/Boolean
    DUP
    ALOAD 2
    LDC 2
    INVOKEVIRTUAL scala/collection/mutable/ArrayBuffer.apply (I)Ljava/lang/Object;
    CHECKCAST org/apache/spark/sql/Row
    ASTORE 7
    ALOAD 7
    IFNULL L11
    ALOAD 7
    LDC 5
    INVOKEINTERFACE org/apache/spark/sql/Row.get (I)Ljava/lang/Object;
    CHECKCAST org/apache/spark/sql/Row
    GOTO L12
   L11
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row] [java/lang/Boolean java/lang/Boolean]
    ACONST_NULL
   L12
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row] [java/lang/Boolean java/lang/Boolean org/apache/spark/sql/Row]
    ASTORE 8
    ALOAD 8
    IFNULL L13
    ALOAD 8
    LDC 0
    INVOKEINTERFACE org/apache/spark/sql/Row.get (I)Ljava/lang/Object;
    CHECKCAST java/lang/Double
    GOTO L14
   L13
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row] [java/lang/Boolean java/lang/Boolean]
    ACONST_NULL
   L14
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row] [java/lang/Boolean java/lang/Boolean java/lang/Double]
    ASTORE 9
    ALOAD 9
    IFNULL L15
    NEW java/lang/Double
    DUP
    LDC 0.97
    INVOKESPECIAL java/lang/Double.<init> (D)V
    ASTORE 10
    ALOAD 10
    IFNULL L16
    ALOAD 1
    LDC 1
    AALOAD
    ALOAD 9
    ALOAD 10
    INVOKEINTERFACE scala/Function2.apply (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    GOTO L17
   L16
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double java/lang/Double] [java/lang/Boolean java/lang/Boolean]
    ACONST_NULL
   L17
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double java/lang/Double] [java/lang/Boolean java/lang/Boolean java/lang/Object]
    GOTO L18
   L15
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double] [java/lang/Boolean java/lang/Boolean]
    ACONST_NULL
   L18
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double] [java/lang/Boolean java/lang/Boolean java/lang/Object]
    CHECKCAST java/lang/Boolean
    SWAP
    IFNONNULL L19
    DUP
    IFNULL L20
    DUP
    INVOKEVIRTUAL java/lang/Boolean.booleanValue ()Z
    IFNE L20
   L19
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double] [java/lang/Boolean java/lang/Boolean]
    SWAP
   L20
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double T org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double] [java/lang/Boolean java/lang/Boolean]
    POP
   L10
   FRAME FULL [is/hail/codegen/generated/C0 [Ljava/lang/Object; scala/collection/mutable/ArrayBuffer org/apache/spark/sql/Row org/apache/spark/sql/Row java/lang/Double] [java/lang/Boolean]
    CHECKCAST java/lang/Boolean
    ARETURN
   L21
   FRAME FULL [] [java/lang/Throwable]
    ATHROW
   L22
    LOCALVARIABLE local3 Ljava/lang/Object; L0 L22 3
    LOCALVARIABLE local4 Ljava/lang/Object; L0 L22 4
    LOCALVARIABLE local5 Ljava/lang/Object; L0 L22 5
    LOCALVARIABLE local6 Ljava/lang/Object; L0 L22 6
    LOCALVARIABLE local7 Ljava/lang/Object; L0 L22 7
    LOCALVARIABLE local8 Ljava/lang/Object; L0 L22 8
    LOCALVARIABLE local9 Ljava/lang/Object; L0 L22 9
    LOCALVARIABLE local10 Ljava/lang/Object; L0 L22 10
    MAXSTACK = 6
    MAXLOCALS = 11

  // access flags 0x1
  public <init>()V
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 1

  // access flags 0x1
  public apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    ALOAD 0
    ALOAD 1
    CHECKCAST [Ljava/lang/Object;
    ALOAD 2
    CHECKCAST scala/collection/mutable/ArrayBuffer
    INVOKESPECIAL is/hail/codegen/generated/C0.apply ([Ljava/lang/Object;Lscala/collection/mutable/ArrayBuffer;)Ljava/lang/Object;
    ARETURN
    MAXSTACK = 3
    MAXLOCALS = 3
}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-297>", line 2, in filter_genotypes
  File "/tmp/spark-0721abd3-c72d-4439-a655-c09fddad864c/userFiles-7c41df44-c5b2-44b1-924e-8f73a9aa8148/hail.zip/hail/java.py", line 121, in handle_py4j
hail.java.FatalError: ClassNotFoundException: is.hail.asm4s.AsmFunction2

Java stack trace:
java.lang.NoClassDefFoundError: is/hail/asm4s/AsmFunction2
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at is.hail.asm4s.package$HailClassLoader$.liftedTree1$1(package.scala:254)
        at is.hail.asm4s.package$HailClassLoader$.loadOrDefineClass(package.scala:250)
        at is.hail.asm4s.package$.loadClass(package.scala:261)
        at is.hail.asm4s.FunctionBuilder$$anon$2.apply(FunctionBuilder.scala:218)
        at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
        at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:80)
        at is.hail.expr.Parser$$anonfun$is$hail$expr$Parser$$evalNoTypeCheck$1.apply(Parser.scala:53)
        at is.hail.expr.Parser$$anonfun$evalTypedExpr$1.apply(Parser.scala:71)
        at is.hail.expr.FilterSamples$$anonfun$12.apply(Relational.scala:324)
        at is.hail.expr.FilterSamples$$anonfun$12.apply(Relational.scala:321)
        at is.hail.expr.MatrixValue$$anonfun$4.apply(Relational.scala:156)
        at is.hail.expr.MatrixValue$$anonfun$4.apply(Relational.scala:156)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at is.hail.expr.MatrixValue.filterSamples(Relational.scala:156)
        at is.hail.expr.FilterSamples.execute(Relational.scala:326)
        at is.hail.variant.VariantSampleMatrix.value$lzycompute(VariantSampleMatrix.scala:490)
        at is.hail.variant.VariantSampleMatrix.value(VariantSampleMatrix.scala:488)
        at is.hail.variant.VariantSampleMatrix.x$13$lzycompute(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantSampleMatrix.x$13(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantSampleMatrix.globalAnnotation$lzycompute(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantSampleMatrix.globalAnnotation(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantDatasetFunctions$.filterGenotypes$extension(VariantDataset.scala:463)
        at is.hail.variant.VariantDatasetFunctions.filterGenotypes(VariantDataset.scala:449)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)java.lang.ClassNotFoundException: is.hail.asm4s.AsmFunction2
        at java.lang.ClassLoader.findClass(ClassLoader.java:530)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at is.hail.asm4s.package$HailClassLoader$.liftedTree1$1(package.scala:254)
        at is.hail.asm4s.package$HailClassLoader$.loadOrDefineClass(package.scala:250)
        at is.hail.asm4s.package$.loadClass(package.scala:261)
        at is.hail.asm4s.FunctionBuilder$$anon$2.apply(FunctionBuilder.scala:218)
        at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
        at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:80)
        at is.hail.expr.Parser$$anonfun$is$hail$expr$Parser$$evalNoTypeCheck$1.apply(Parser.scala:53)
        at is.hail.expr.Parser$$anonfun$evalTypedExpr$1.apply(Parser.scala:71)
        at is.hail.expr.FilterSamples$$anonfun$12.apply(Relational.scala:324)
        at is.hail.expr.FilterSamples$$anonfun$12.apply(Relational.scala:321)
        at is.hail.expr.MatrixValue$$anonfun$4.apply(Relational.scala:156)
        at is.hail.expr.MatrixValue$$anonfun$4.apply(Relational.scala:156)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at is.hail.expr.MatrixValue.filterSamples(Relational.scala:156)
        at is.hail.expr.FilterSamples.execute(Relational.scala:326)
        at is.hail.variant.VariantSampleMatrix.value$lzycompute(VariantSampleMatrix.scala:490)
        at is.hail.variant.VariantSampleMatrix.value(VariantSampleMatrix.scala:488)
        at is.hail.variant.VariantSampleMatrix.x$13$lzycompute(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantSampleMatrix.x$13(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantSampleMatrix.globalAnnotation$lzycompute(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantSampleMatrix.globalAnnotation(VariantSampleMatrix.scala:493)
        at is.hail.variant.VariantDatasetFunctions$.filterGenotypes$extension(VariantDataset.scala:463)
        at is.hail.variant.VariantDatasetFunctions.filterGenotypes(VariantDataset.scala:449)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
```

Hail version: 0.1-20613ed
Error summary: ClassNotFoundException: is.hail.asm4s.AsmFunction2

**Comment by mptrepanier** [comment]
Calling the

**Comment by mptrepanier** [comment]
When setting the driver classpath and running in `client` mode, ensure that the absolute path is used.
