### ISSUE TITLE
Fix cloudtools submit

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#2982]
```
import hail as hl
ds = hl.balding_nichols_model(3, 100, 100)
ds.annotate_globals(x=[1,2,3])
```
The above script breaks on devel clusters.
```
py4j.protocol.Py4JJavaError: An error occurred while calling o64.annotateGlobalExpr.
: java.lang.NoClassDefFoundError: is/hail/asm4s/AsmFunction2
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at is.hail.asm4s.package$HailClassLoader$.liftedTree1$1(package.scala:174)
	at is.hail.asm4s.package$HailClassLoader$.loadOrDefineClass(package.scala:170)
	at is.hail.asm4s.package$.loadClass(package.scala:181)
	at is.hail.asm4s.FunctionBuilder$$anon$1.apply(FunctionBuilder.scala:312)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:84)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
	at is.hail.expr.Parser$$anonfun$is$hail$expr$Parser$$evalNoTypeCheck$1.apply(Parser.scala:64)
	at is.hail.expr.Parser$$anonfun$12$$anonfun$apply$6.apply(Parser.scala:172)
```

**Comment by tpoterba** [comment]
is fixed
