### ISSUE TITLE
MT/Table needs __iter__

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3038]
Full error message:

```[Stage 2:>                                                         (0 + 0) / 16]2018-02-28 23:41:58 Hail: INFO: interval filter loaded 2453 of 103675 partitions
2018-02-28 23:42:08 Hail: WARN: deprecation: 'drop_cols' will be removed before 0.2 release
Traceback (most recent call last):
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/hail-devel-53d795c163fd.zip/hail/typecheck/check.py", line 415, in check_all
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/hail-devel-53d795c163fd.zip/hail/typecheck/check.py", line 53, in check
hail.typecheck.check.TypecheckFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/generate_qc_annotations.py", line 220, in <module>
    try_slack(args.slack_channel, main, args)
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/pyscripts_8Rer6O.zip/gnomad_hail/slack_utils.py", line 94, in try_slack
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/pyscripts_8Rer6O.zip/gnomad_hail/slack_utils.py", line 77, in try_slack
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/generate_qc_annotations.py", line 187, in main
    vds, sample_table = generate_qc_annotations(vds, medians=not args.skip_medians)
  File "<decorator-gen-616>", line 2, in __getitem__
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/hail-devel-53d795c163fd.zip/hail/typecheck/check.py", line 478, in _typecheck
  File "/tmp/98788bda-73b9-4ebe-924d-440665f0cd1d/hail-devel-53d795c163fd.zip/hail/typecheck/check.py", line 425, in check_all
TypeError: __getitem__: parameter 'item': expected (str or tuple[(slice or hail.expr.expression.Expression or tuple[hail.expr.expression.Expression]),(slice or hail.expr.expression.Expression or tuple[hail.expr.expression.Expression])]), found int: '0'```

**Comment by konradjk** [comment]
PEBKAC. I was returning a VDS and capturing it with 2 arguments.

**Comment by tpoterba** [comment]
(can fix by defining `def __iter__` on MT/Table to throw an error)
