### ISSUE TITLE
sporadic segfault

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3053]
Getting a sporadic task failure, with the error:
```
ExecutorLostFailure (executor 99 exited caused by one of the running tasks) Reason: Container marked as failed: container_1519994715701_0003_01_000102 on host: exomes-sw-pxt3.c.broad-mpg-gnomad.internal. Exit status: 134. Diagnostics: Exception from container-launch.
Container id: container_1519994715701_0003_01_000102
Exit code: 134
Exception message: /bin/bash: line 1:  6739 Aborted                 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -server -Xmx11171m '-Xss4M' -Djava.io.tmpdir=/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1519994715701_0003/container_1519994715701_0003_01_000102/tmp '-Dspark.driver.port=41843' '-Dspark.rpc.message.maxSize=512' -Dspark.yarn.app.container.log.dir=/var/log/hadoop-yarn/userlogs/application_1519994715701_0003/container_1519994715701_0003_01_000102 -XX:OnOutOfMemoryError='kill %p' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@10.128.0.4:41843 --executor-id 99 --hostname exomes-sw-pxt3.c.broad-mpg-gnomad.internal --cores 4 --app-id application_1519994715701_0003 --user-class-path file:/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1519994715701_0003/container_1519994715701_0003_01_000102/__app__.jar --user-class-path file:/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1519994715701_0003/container_1519994715701_0003_01_000102/hail.jar > /var/log/hadoop-yarn/userlogs/application_1519994715701_0003/container_1519994715701_0003_01_000102/stdout 2> /var/log/hadoop-yarn/userlogs/application_1519994715701_0003/container_1519994715701_0003_01_000102/stderr

Stack trace: ExitCodeException exitCode=134: /bin/bash: line 1:  6739 Aborted                 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -server -Xmx11171m '-Xss4M' -Djava.io.tmpdir=/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1519994715701_0003/container_1519994715701_0003_01_000102/tmp '-Dspark.driver.port=41843' '-Dspark.rpc.message.maxSize=512' -Dspark.yarn.app.container.log.dir=/var/log/hadoop-yarn/userlogs/application_1519994715701_0003/container_1519994715701_0003_01_000102 -XX:OnOutOfMemoryError='kill %p' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@10.128.0.4:41843 --executor-id 99 --hostname exomes-sw-pxt3.c.broad-mpg-gnomad.internal --cores 4 --app-id application_1519994715701_0003 --user-class-path file:/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1519994715701_0003/container_1519994715701_0003_01_000102/__app__.jar --user-class-path file:/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1519994715701_0003/container_1519994715701_0003_01_000102/hail.jar > /var/log/hadoop-yarn/userlogs/application_1519994715701_0003/container_1519994715701_0003_01_000102/stdout 2> /var/log/hadoop-yarn/userlogs/application_1519994715701_0003/container_1519994715701_0003_01_000102/stderr

	at org.apache.hadoop.util.Shell.runCommand(Shell.java:972)
	at org.apache.hadoop.util.Shell.run(Shell.java:869)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1170)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:236)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:305)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 134
```
When I dig into the container logs, the stdout is empty on most, stderr is full of warnings, but no errors:
```
18/03/02 15:28:07 WARN com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel: Channel for 'gs://gnomad/coverage/hail-0.2/coverage/exomes/parts/part_partition1049.vds/entries/rows/parts/part-0095' is not open.
```
But then one machine I logged into had:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa70eb59074, pid=4361, tid=0x00007fa707702700
#
# JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libconscrypt_openjdk_jni.so+0x43074]
[error occurred during error reporting (printing problematic frame), id 0xb]

# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1519994715701_0001/container_1519994715701_0001_01_000558/hs_err_pid4361.log
# [ timer expired, abort... ]
```
But said log file has no information. The job is finishing, just with a high (~50-100%) task failure rate.

**Comment by konradjk** [comment]
Oh and the pipeline is a series of:
```
                next_vds = hl.read_matrix_table('{}/parts/part_{}.vds'.format(root, base))
                next_vds = next_vds.select_rows(next_vds.row_id)
                vds = vds.union_cols(next_vds)
```

**Comment by dossett** [comment]
Hi @konradjk Did you ever determine a cause of this? I am seeing very, very similar errors in an unrelated project (but also executing in GCP).

**Comment by konradjk** [comment]
No, the framework has changed a lot since then so it just works now. My guess for why this happens would be memory issues, but not sure. What's your pipeline?

**Comment by tpoterba** [comment]
@dossett what version are you using?

**Comment by tpoterba** [comment]
oh, sorry. you're not running hail

**Comment by tpoterba** [comment]
This was a segfault inside of Hail, I think.

**Comment by dossett** [comment]
Thanks @konradjk @tpoterba This is happening in a scalding job running on Dataproc. The same job runs fine on a different hadoop cluster, albeit on a slightly different JDK.

**Comment by konradjk** [comment]
And it's reproducible? I think I found this one to be non-deterministic

**Comment by dossett** [comment]
@konradjk Yes, sadly I can reproduce it 100% of the time. I won't be actively working on this for the time being, and I'll hope that when I come back to it a JDK and/or OS upgrade on the dataproc side has fixed it.

**Comment by tpoterba** [comment]
are you sure it's a dataproc problem?

If scalding is using java unsafe in a not-guaranteed-to-work way, then a core dump s totally possible.

Example - the JVM will sometimes tolerate misaligned floats/ints, and sometimes will crash.

**Comment by dossett** [comment]
@tpoterba That is a good point, it is probably not a dataproc problem specifically but a function of the JDK and native libraries (slightly different versions between dataproc and our other environment).

**Comment by dossett** [comment]
@tpoterba @konradjk A workaround for this issue, should you encounter it again, is to disable the conscrypt library with this dataproc config:

`dataproc:dataproc.conscrypt.provider.enable: 'false'`

Capturing a core file provided a little more detail, but google support cannot explain why it happens.

Cheers.

**Comment by tpoterba** [comment]
huh, interesting. Thanks for update!
