### ISSUE TITLE
Assertion error when using mt.annotate_rows() with different partition keys

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#3119]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:
```
vp_ht = vp_ht.transmute(
            locus1=hl.locus(vp_ht.chrom1, vp_ht.pos1),
            locus2=hl.locus(vp_ht.chrom1, vp_ht.pos2),
            alleles1=[vp_ht.ref1, vp_ht.alt1],
            alleles2=[vp_ht.ref2, vp_ht.alt2]
        )

        vp_mt = hl.MatrixTable.from_rows_table(vp_ht)
        vp_mt = vp_mt.key_rows_by('locus1', 'alleles1')

        mt = mt.annotate_rows(v1=hl.is_defined(vp_mt[(mt.locus, mt.alleles), :]))
```

### What went wrong (all error messages here, including the full java stack trace):
```
In [49]: mt = mt.annotate_rows(v1=hl.is_defined(vp_mt[(mt.locus, mt.alleles),:]))
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-49-5ea2fe942ada> in <module>()
----> 1 mt = mt.annotate_rows(v1=hl.is_defined(vp_mt[(mt.locus, mt.alleles),:]))

/home/hail/hail.zip/hail/matrixtable.py in annotate_rows(self, **named_exprs)
    894         exprs = []
    895         named_exprs = {k: to_expr(v) for k, v in named_exprs.items()}
--> 896         base, cleanup = self._process_joins(*named_exprs.values())
    897
    898         for k, v in named_exprs.items():

/home/hail/hail.zip/hail/matrixtable.py in _process_joins(self, *exprs)
   2205             for j in list(e._joins)[::-1]:
   2206                 if j.uid not in used_uids:
-> 2207                     left = j.join_function(left)
   2208                     all_uids.extend(j.temp_vars)
   2209                     used_uids.add(j.uid)

/home/hail/hail.zip/hail/matrixtable.py in <lambda>(left)
   2157                 prefix = 'va'
   2158                 joiner = lambda left: (
-> 2159                     MatrixTable(left._jvds.annotateRowsVDS(right._jvds, uid)))
   2160             else:
   2161                 return self.rows().index(*exprs)

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134
   1135         for temp_arg in temp_args:

/home/hail/hail.zip/hail/utils/java.py in deco(*args, **kwargs)
    236             # this is a hack to suppress the original error's stack trace
    237             if _exception:
--> 238                 raise _exception
    239
    240     return deco

FatalError: AssertionError: assertion failed

Java stack trace:
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at is.hail.variant.MatrixTable.orderedRVDLeftJoinDistinctAndInsert(MatrixTable.scala:982)
	at is.hail.variant.MatrixTable.annotateRowsVDS(MatrixTable.scala:1449)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-14287a4
Error summary: AssertionError: assertion failed
```

**Comment by tpoterba** [comment]
fixed
