### ISSUE TITLE
AssertionError when filtering columns of a MatrixTable

### ISSUE THREAD

**Issue by liameabbott** [hail-is/hail#3173]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
0.2

### What you did:
```
mt = hl.read_matrix_table('gs://...')
mt = mt.filter_cols(mt.used_in_pca_calculation)
print(mt.count_cols())
```
The MatrixTable has a lot of row and column annotations. `mt.used_in_pca_calculation` is a Boolean column annotation.

### What went wrong (all error messages here, including the full java stack trace):
```
Traceback (most recent call last):
  File "/tmp/8d5cc778-fdc7-4210-a60b-5efd1f67c45f/subset_genotype_pca.py", line 8, in <module>
    print(mt.count_cols())
  File "/home/hail/hail.zip/hail/matrixtable.py", line 1950, in count_cols
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/home/hail/hail.zip/hail/utils/java.py", line 206, in deco
hail.utils.java.FatalError: AssertionError: assertion failed

Java stack trace:
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at is.hail.expr.MatrixValue.filterSamplesKeep(Relational.scala:110)
	at is.hail.expr.MatrixValue.filterCols(Relational.scala:133)
	at is.hail.expr.FilterCols.execute(Relational.scala:333)
	at is.hail.variant.MatrixTable.value$lzycompute(MatrixTable.scala:536)
	at is.hail.variant.MatrixTable.value(MatrixTable.scala:534)
	at is.hail.variant.MatrixTable.x$16$lzycompute(MatrixTable.scala:541)
	at is.hail.variant.MatrixTable.x$16(MatrixTable.scala:541)
	at is.hail.variant.MatrixTable.colValues$lzycompute(MatrixTable.scala:541)
	at is.hail.variant.MatrixTable.colValues(MatrixTable.scala:541)
	at is.hail.variant.MatrixTable.numCols(MatrixTable.scala:2378)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-3cf3108
Error summary: AssertionError: assertion failed
```

**Comment by liameabbott** [comment]
I should be using `.filter_entries()` rather than `.filter_cols()` I think -- can disregard this issue

**Comment by tpoterba** [comment]
this is still a bug we want to fix!
