### ISSUE TITLE
Out of memory running ld_prune

### ISSUE THREAD

**Issue by jjfarrell** [hail-is/hail#3463]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:

Tried to run ld_prune and pc_relate on 5000 WGS samples.

```
spark-submit --verbose --master yarn  --deploy-mode client \
   --num-executors 14 \
   --executor-cores 6 \
   --jars $JAR \
   --conf spark.kryo.registrator=is.hail.kryo.HailKryoRegistrator \
   --conf "spark.driver.extraClassPath=$JAR" \
   --conf "spark.executor.extraClassPath=$JAR" \
   --executor-memory 90G\
   --driver-memory 80g\
   --conf spark.yarn.executor.memoryOverhead=8000 \
   --conf spark.network.timeout=600 \
   --conf spark.executor.heartbeatInterval=120\
   hc_prune.py
```

Where hc_prune.py is:

```
import matplotlib.pyplot as plt
import seaborn

import numpy as np
import pandas as pd
from collections import Counter
from math import log, isnan
from pprint import pprint
# hail
import hail as hl
import hail.expr.aggregators as agg
import hail.expr.functions

hl.init(default_reference='GRCh38')
print("Read in PASS SNVs")
passed=hl.read_matrix_table('/project/casa/hail.ds/gatk.hc/gcad.5k.snv.vqsr.pass')
print("Filtering Common Variants")
common=passed.filter_rows(passed.variant_qc.AF > 0.01).persist()
common.write('/project/casa/hail.ds/gatk.hc/gcad.5k.snv.vqsr.pass.common')
print("Pruning LD Variants")
pruned =hl.ld_prune(common,30,r2=0.1, memory_per_core=2048)
pruned.write('/project/casa/hail.ds/gatk.hc/gcad.5k.snv.vqsr.pruned')
print("Sample 20% of variants for running PC-Relate")
pruned_subsample = pruned.sample_rows(0.2).persist()
print("Running PC_Relate")
rel = hl.pc_relate(pruned_subsample.GT, 0.01, k=10)
rel_df = rel.to_pandas()
rel_df.describe()
pprint(rel_df)
rel_df.to_csv('gcad_5k.snv.rel.csv')
```

### What went wrong (all error messages here, including the full java stack trace):

Got a memory error. but not sure what memory needs to be increased.  The job seems to restart but does not progress and need to kill. 

java.lang.OutOfMemoryError: Java heap spaceop

Running on Apache Spark version 2.2.0
SparkUI available at http://10.48.225.55:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version devel-63d60cc
NOTE: This is a beta version. Interfaces may change
  during the beta period. We also recommend pulling
  the latest changes weekly.
Read in PASS SNVs
Filtering Common Variants
[Stage 0:==================================================>(96600 + 1) / 96601]2018-04-27 20:54:43 Hail: INFO: wrote 11341822 items in 96601 partitions
Pruning LD Variants
[Stage 1:==================================================>(96598 + 3) / 96601]2018-04-27 21:19:04 Hail: INFO: Running LD prune with nSamples=4795, nVariants=11341822, nPartitions=96601, and maxQueueSize=429841.
[Stage 2:=========================================>        (79823 + 18) / 96601]java.lang.OutOfMemoryError: Java heap spaceop"
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.toArray(ArrayList.java:376)
        at java.util.Collections$SynchronizedCollection.toArray(Collections.java:2024)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at org.apache.spark.util.CollectionAccumulator.value(AccumulatorV2.scala:470)
        at org.apache.spark.util.CollectionAccumulator.value(AccumulatorV2.scala:444)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$updateAccumulators$1.apply(DAGScheduler.scala:1103)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$updateAccumulators$1.apply(DAGScheduler.scala:1092)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.updateAccumulators(DAGScheduler.scala:1092)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:1168)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1711)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
[Stage 2:=========================================>        (79823 + 18) / 96601]

Used yarn application -kill to kill but driver still runs. Then use kill -KILL to terminate the driver.

**Comment by jjfarrell** [comment]
Increasing the executor memory  per core  to 20G/core seemed to help get by this memory error. 

 It would be useful to have some rule of thumbs for estimating memory requirements based on number of samples and variants.

spark-submit --verbose --master yarn  --deploy-mode client \
   --num-executors 12\
   --executor-cores 4\
   --jars $JAR \
   --conf spark.kryo.registrator=is.hail.kryo.HailKryoRegistrator \
   --conf "spark.driver.extraClassPath=$JAR" \
   --conf "spark.executor.extraClassPath=$JAR" \
   --executor-memory 80G\
   --driver-memory 60g\
   --driver-cores 1\
   --name "$1"  \
   --conf spark.yarn.executor.memoryOverhead=8000 \
   --conf spark.network.timeout=600 \
   --conf spark.executor.heartbeatInterval=120\
