### ISSUE TITLE
IllegalArgumentException in call_stats aggregator

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3465]
Pretty simple pipeline, only failed about ~3/4 through the final (write) stage...
```
    mt = hl.read_matrix_table()
    sample_group_filters = {
        "qc_samples_raw": mt.meta.high_quality,
        "release_samples_raw": mt.meta.release,
        "all_samples_raw": True
    }
    mt = mt.select_cols(**sample_group_filters)
    mt = unphase_mt(mt.select_rows(*mt.row_key))
    call_stats_expression = []
    for group in sample_group_filters.keys():
        call_stats_expression.append(
            hl.struct(call_stats=hl.agg.call_stats(hl.agg.filter(mt[group], mt.GT), mt.alleles),
                      meta={'group': group})
        )
    mt.annotate_rows(qc_callstats=call_stats_expression).drop_cols().write()
```

```
Traceback (most recent call last):
  File "/tmp/a913d6ce5b814a63ad7af31060416237/pyscripts_Xr0D99.zip/gnomad_hail/slack_utils.py", line 77, in try_slack
  File "/tmp/a913d6ce5b814a63ad7af31060416237/generate_qc_annotations.py", line 247, in main
    generate_call_stats(mt).write(annotations_mt_path(data_type, 'call_stats'), args.overwrite)
  File "<decorator-gen-556>", line 2, in write
  File "/tmp/a913d6ce5b814a63ad7af31060416237/hail-devel-a1d6ecc71ce3.zip/hail/typecheck/check.py", line 481, in _typecheck
  File "/tmp/a913d6ce5b814a63ad7af31060416237/hail-devel-a1d6ecc71ce3.zip/hail/matrixtable.py", line 2027, in write
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/tmp/a913d6ce5b814a63ad7af31060416237/hail-devel-a1d6ecc71ce3.zip/hail/utils/java.py", line 196, in deco
hail.utils.java.FatalError: IllegalArgumentException: requirement failed

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 9716 in stage 1.0 failed 20 times, most recent failure: Lost task 9716.19 in stage 1.0 (TID 10060, exomes3-sw-dfpw.c.broad-mpg-gnomad.internal, executor 134): java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at is.hail.variant.Call$.alleleByIndex(Call.scala:128)
	at is.hail.expr.FunctionRegistry$$anonfun$11.apply$mcIII$sp(FunctionRegistry.scala:685)
	at is.hail.expr.FunctionRegistry$$anonfun$11.apply(FunctionRegistry.scala:685)
	at is.hail.expr.FunctionRegistry$$anonfun$11.apply(FunctionRegistry.scala:685)
	at is.hail.expr.BinaryFun.apply(Fun.scala:122)
	at is.hail.codegen.generated.C9.apply(Unknown Source)
	at is.hail.codegen.generated.C9.apply(Unknown Source)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:84)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
	at is.hail.expr.Parser$$anonfun$is$hail$expr$Parser$$evalNoTypeCheck$1.apply(Parser.scala:64)
	at is.hail.variant.MatrixTable$$anonfun$selectEntries$2.apply(MatrixTable.scala:1112)
	at is.hail.variant.MatrixTable$$anonfun$selectEntries$2.apply(MatrixTable.scala:1102)
	at is.hail.variant.MatrixTable$$anonfun$61$$anonfun$apply$52$$anonfun$apply$5.apply$mcV$sp(MatrixTable.scala:1364)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$1.apply(TStruct.scala:191)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$1.apply(TStruct.scala:191)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$2.apply(TStruct.scala:211)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$2.apply(TStruct.scala:200)
	at is.hail.variant.MatrixTable$$anonfun$61$$anonfun$apply$52.apply(MatrixTable.scala:1363)
	at is.hail.variant.MatrixTable$$anonfun$61$$anonfun$apply$52.apply(MatrixTable.scala:1359)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:818)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:812)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:818)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:812)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:818)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:812)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(RowStore.scala:915)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(RowStore.scala:908)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(RowStore.scala:908)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(RowStore.scala:907)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.utils.richUtils.RichHadoopConfiguration$.writeFile$extension(RichHadoopConfiguration.scala:265)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2.apply(RowStore.scala:907)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2.apply(RowStore.scala:904)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1.apply(RowStore.scala:904)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1.apply(RowStore.scala:903)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.utils.richUtils.RichHadoopConfiguration$.writeFile$extension(RichHadoopConfiguration.scala:265)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9.apply(RowStore.scala:903)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9.apply(RowStore.scala:897)
	at is.hail.sparkextras.ContextRDD$$anonfun$mapPartitionsWithIndex$1.apply(ContextRDD.scala:155)
	at is.hail.sparkextras.ContextRDD$$anonfun$mapPartitionsWithIndex$1.apply(ContextRDD.scala:155)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$23.apply(ContextRDD.scala:297)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$23.apply(ContextRDD.scala:297)
	at is.hail.sparkextras.ContextRDD$$anonfun$run$1$$anonfun$apply$5$$anonfun$apply$6.apply(ContextRDD.scala:129)
	at is.hail.sparkextras.ContextRDD$$anonfun$run$1$$anonfun$apply$5$$anonfun$apply$6.apply(ContextRDD.scala:129)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1504)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1732)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2050)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2094)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
	at is.hail.sparkextras.ContextRDD.collect(ContextRDD.scala:132)
	at is.hail.io.RichContextRDDRegionValue$.writeRowsSplit$extension(RowStore.scala:946)
	at is.hail.rvd.OrderedRVD.writeRowsSplit(OrderedRVD.scala:391)
	at is.hail.expr.MatrixValue.write(Relational.scala:117)
	at is.hail.expr.ir.Interpret$.is$hail$expr$ir$Interpret$$interpret(Interpret.scala:384)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:36)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:15)
	at is.hail.variant.MatrixTable.write(MatrixTable.scala:2168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at is.hail.variant.Call$.alleleByIndex(Call.scala:128)
	at is.hail.expr.FunctionRegistry$$anonfun$11.apply$mcIII$sp(FunctionRegistry.scala:685)
	at is.hail.expr.FunctionRegistry$$anonfun$11.apply(FunctionRegistry.scala:685)
	at is.hail.expr.FunctionRegistry$$anonfun$11.apply(FunctionRegistry.scala:685)
	at is.hail.expr.BinaryFun.apply(Fun.scala:122)
	at is.hail.codegen.generated.C9.apply(Unknown Source)
	at is.hail.codegen.generated.C9.apply(Unknown Source)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:84)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
	at is.hail.expr.Parser$$anonfun$is$hail$expr$Parser$$evalNoTypeCheck$1.apply(Parser.scala:64)
	at is.hail.variant.MatrixTable$$anonfun$selectEntries$2.apply(MatrixTable.scala:1112)
	at is.hail.variant.MatrixTable$$anonfun$selectEntries$2.apply(MatrixTable.scala:1102)
	at is.hail.variant.MatrixTable$$anonfun$61$$anonfun$apply$52$$anonfun$apply$5.apply$mcV$sp(MatrixTable.scala:1364)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$1.apply(TStruct.scala:191)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$1.apply(TStruct.scala:191)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$2.apply(TStruct.scala:211)
	at is.hail.expr.types.TStruct$$anonfun$unsafeInsert$2.apply(TStruct.scala:200)
	at is.hail.variant.MatrixTable$$anonfun$61$$anonfun$apply$52.apply(MatrixTable.scala:1363)
	at is.hail.variant.MatrixTable$$anonfun$61$$anonfun$apply$52.apply(MatrixTable.scala:1359)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:818)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:812)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:818)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:812)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:818)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$10$$anon$3.next(OrderedRVD.scala:812)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(RowStore.scala:915)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(RowStore.scala:908)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(RowStore.scala:908)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(RowStore.scala:907)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.utils.richUtils.RichHadoopConfiguration$.writeFile$extension(RichHadoopConfiguration.scala:265)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2.apply(RowStore.scala:907)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1$$anonfun$apply$2.apply(RowStore.scala:904)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1.apply(RowStore.scala:904)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9$$anonfun$apply$1.apply(RowStore.scala:903)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.utils.richUtils.RichHadoopConfiguration$.writeFile$extension(RichHadoopConfiguration.scala:265)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9.apply(RowStore.scala:903)
	at is.hail.io.RichContextRDDRegionValue$$anonfun$9.apply(RowStore.scala:897)
	at is.hail.sparkextras.ContextRDD$$anonfun$mapPartitionsWithIndex$1.apply(ContextRDD.scala:155)
	at is.hail.sparkextras.ContextRDD$$anonfun$mapPartitionsWithIndex$1.apply(ContextRDD.scala:155)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$23.apply(ContextRDD.scala:297)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$23.apply(ContextRDD.scala:297)
	at is.hail.sparkextras.ContextRDD$$anonfun$run$1$$anonfun$apply$5$$anonfun$apply$6.apply(ContextRDD.scala:129)
	at is.hail.sparkextras.ContextRDD$$anonfun$run$1$$anonfun$apply$5$$anonfun$apply$6.apply(ContextRDD.scala:129)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Hail version: devel-c37301a
Error summary: IllegalArgumentException: requirement failed
```

**Comment by konradjk** [comment]
Ok I just looked at the scala code, and this must have happened around the sex chromosomes when my dataset shifted to haploid (or more specifically, a mix of haploid and diploid calls for male and female). I'll write in the workaround for my own pipeline, but you might want to have a more explicit error message.

**Comment by konradjk** [comment]
(Re-assign if you want @jigold but thought you'd want to know about this)

**Comment by konradjk** [comment]
Welp, I found the problem. I was trying to index `mt.GT[1]` into a haploid call...

**Comment by jigold** [comment]
@konradjk Can I close this?
