### ISSUE TITLE
Scala dies after filter_rows + .show()

### ISSUE THREAD

**Issue by ce-carey** [hail-is/hail#3508]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

Sorry for the awful formatting!! I'm not familiar with how to properly format for GitHub, and clearly some of my code got picked up as formatting.... 

EDIT: Fixed the formatting :)

### What you did: 
```
import

hail as hl

def flip_text(base):
    """
    :param StringExpression base: Expression of a single base
    :return: StringExpression of flipped base
    :rtype: StringExpression
    """
    return hl.cond(base == 'A', 'T',
                          hl.cond(base == 'T', 'A',
                                         hl.cond(base == 'C', 'G',
                                                        hl.cond(base == 'G', 'C', base))))

# load ldpred sumstats file
sumstats = hl.import_table('gs://ukbb_prs/sumstats/UKB_SCZ_LDPred.txt', delimiter='\s+', impute=True)

# create locus and alleles columns and key by locus
sumstats = (sumstats.annotate(locus=hl.parse_locus(sumstats.chrom[6:] + ":" + hl.str(sumstats.pos)),
                             alleles=[sumstats.nt1,sumstats.nt2])
                .key_by('locus')
                .order_by('locus'))

# repartition sumstats to save time
sumstats = sumstats.repartition(100)

# write the sumstats table
sumstats.write('gs://ukbb_prs/sumstats/UKB_SCZ_LDPred.kt', overwrite=True)

# read the sumstats table
sumstats = hl.read_table('gs://ukbb_prs/sumstats/UKB_SCZ_LDPred.kt')

# remove leading zeros from contigs
contigs = {'0{}'.format(x):str(x) for x in range(1, 10)}

# import variants
variants = hl.methods.import_bgen('gs://fc-7d5088b4-7673-45b5-95c2-17ae00a04183/imputed/ukb_imp_chr{22}_v3.bgen',
                            [],
                            sample_file='gs://phenotype_31063/ukb31063.imputed_v3.autosomes.sample',
                            contig_recoding=contigs)

# merge sumstats on bgen matrixtable
variants = variants.annotate_rows(ss = sumstats[variants.locus])

# handle strand/allele flips
variants = variants.annotate_rows(beta = hl.case()
                  .when(((variants.alleles[0] == variants.ss.nt1) &
                        (variants.alleles[1] == variants.ss.nt2)) | 
                        ((flip_text(variants.alleles[0]) == variants.ss.nt1) & 
                        (flip_text(variants.alleles[1]) == variants.ss.nt2)),
                       (-1*variants.ss.ldpred_inf_beta))
                  .when(((variants.alleles[0] == variants.ss.nt2) &
                        (variants.alleles[1] == variants.ss.nt1)) | 
                        ((flip_text(variants.alleles[0]) == variants.ss.nt2) & 
                        (flip_text(variants.alleles[1]) == variants.ss.nt1)),
                       variants.ss.ldpred_inf_beta)
                  .or_missing())


variants = variants.filter_rows(hl.is_defined(variants.beta))
variants.beta.show()
```

### What went wrong (all error messages here, including the full java stack trace): When I went to try to show the beta column, Scala "crashed" such that I had to type in "localhost:4040" to reconnect and go into my application history to see what happened. I didn't get any errors in the Notebook I was using--it just stopped doing any work. 

In the Scala tasks console, all of my workers had the following error:
```
java.lang.NegativeArraySizeException
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at is.hail.annotations.Region.ensure(Region.scala:139)
	at is.hail.annotations.Region.allocate(Region.scala:152)
	at is.hail.annotations.Region.allocate(Region.scala:159)
	at is.hail.expr.types.TBinary$.allocate(TBinary.scala:101)
	at is.hail.annotations.RegionValueBuilder.fixupBinary(RegionValueBuilder.scala:263)
	at is.hail.annotations.RegionValueBuilder.fixupStruct(RegionValueBuilder.scala:319)
	at is.hail.annotations.RegionValueBuilder.fixupArray(RegionValueBuilder.scala:288)
	at is.hail.annotations.RegionValueBuilder.addRegionValue(RegionValueBuilder.scala:432)
	at is.hail.expr.MatrixMapRows$$anonfun$31$$anonfun$apply$21.apply(Relational.scala:975)
	at is.hail.expr.MatrixMapRows$$anonfun$31$$anonfun$apply$21.apply(Relational.scala:964)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:914)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.utils.package$.getIteratorSizeWithMaxN(package.scala:347)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Under "Failed Stages", these were the details for what I was running:
```
org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
is.hail.sparkextras.ContextRDD.runJob(ContextRDD.scala:456)
is.hail.sparkextras.ContextRDD.head(ContextRDD.scala:433)
is.hail.rvd.OrderedRVD.head(OrderedRVD.scala:285)
is.hail.rvd.OrderedRVD.head(OrderedRVD.scala:21)
is.hail.rvd.RVD$class.takeAsBytes(RVD.scala:243)
is.hail.rvd.OrderedRVD.takeAsBytes(OrderedRVD.scala:21)
is.hail.rvd.RVD$class.take(RVD.scala:247)
is.hail.rvd.OrderedRVD.take(OrderedRVD.scala:21)
is.hail.table.Table.take(Table.scala:990)
is.hail.table.Table.showString(Table.scala:1031)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:280)
py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
py4j.commands.CallCommand.execute(CallCommand.java:79)
```

Also under Failed Stages, the Failure Reason was given as:
```
Job aborted due to stage failure: Task 0 in stage 10.0 failed 20 times, most recent failure: Lost task 0.19 in stage 10.0 (TID 526, ccarey-sw-svrp.c.ukbb-robinson.internal, executor 43): java.lang.NegativeArraySizeException
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at is.hail.annotations.Region.ensure(Region.scala:139)
	at is.hail.annotations.Region.allocate(Region.scala:152)
	at is.hail.annotations.Region.allocate(Region.scala:159)
	at is.hail.expr.types.TBinary$.allocate(TBinary.scala:101)
	at is.hail.annotations.RegionValueBuilder.fixupBinary(RegionValueBuilder.scala:263)
	at is.hail.annotations.RegionValueBuilder.fixupStruct(RegionValueBuilder.scala:319)
	at is.hail.annotations.RegionValueBuilder.fixupArray(RegionValueBuilder.scala:288)
	at is.hail.annotations.RegionValueBuilder.addRegionValue(RegionValueBuilder.scala:432)
	at is.hail.expr.MatrixMapRows$$anonfun$31$$anonfun$apply$21.apply(Relational.scala:975)
	at is.hail.expr.MatrixMapRows$$anonfun$31$$anonfun$apply$21.apply(Relational.scala:964)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:914)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.utils.package$.getIteratorSizeWithMaxN(package.scala:347)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
```

**Comment by konradjk** [comment]
Ah I didn't see you had posted this a couple of days ago. I'm also getting this error on the pipeline below (which works on ~15K genomes, but not ~125K exomes):
```
    mt = mt.select_cols(group_membership=tuple(x[1] for x in sample_group_filters), project_id=mt.meta.project_id)
    mt = mt.select_rows(*mt.row_key)
    mt = mt.select_entries(n_alt=mt.GT.n_alt_alleles(), adj=mt.adj)

    frequency_expression = []
    for i in range(len(sample_group_filters)):
        subgroup_dict = sample_group_filters[i][0]
        subgroup_dict['group'] = 'adj'

        freq_expression = hl.struct(
            ac=hl.agg.sum(hl.agg.filter(mt.group_membership[i] & mt.adj, mt.n_alt)),
            an=2 * hl.agg.count_where(mt.group_membership[i] & mt.adj & hl.is_defined(mt.n_alt)),
            hom=hl.agg.count_where(mt.group_membership[i] & mt.adj & (mt.n_alt == 2)),
            meta=subgroup_dict
        )
        frequency_expression.append(freq_expression)
    freq_expression = hl.struct(
        ac=hl.agg.sum(mt.n_alt),
        an=2 * hl.agg.count_where(hl.is_defined(mt.n_alt)),
        hom=hl.agg.count_where(mt.n_alt == 2),
        meta={'group': 'raw'}
    )
    frequency_expression.insert(1, freq_expression)

    mt = mt.annotate_rows(freq=frequency_expression)
    mt.rows().write()
```

**Comment by tpoterba** [comment]
OK, Dan fixed this

**Comment by ce-carey** [comment]
Code: 

```
import hail as hl
import time
import argparse
from slack_utils import send_message

def flip_text(base):
    """
    :param StringExpression base: Expression of a single base
    :return: StringExpression of flipped base
    :rtype: StringExpression
    """
    return hl.cond(base == 'A', 'T',
                          hl.cond(base == 'T', 'A',
                                         hl.cond(base == 'C', 'G',
                                                        hl.cond(base == 'G', 'C', base))))

def main(pheno):
    # load ldpred sumstats file
    sumstats = hl.import_table('gs://ukbb_prs/sumstats/UKB_'+pheno+'_LDPred.txt', delimiter='\s+', impute=True, min_partitions=100)

    # create locus and alleles columns and key by locus
    sumstats = (sumstats.annotate(locus=hl.parse_locus(sumstats.chrom[6:] + ":" + hl.str(sumstats.pos)),
                         alleles=[sumstats.nt1,sumstats.nt2])
                .key_by('locus'))

    # write the sumstats table
    sumstats.write('gs://ukbb_prs/sumstats/temp.kt', overwrite=True)

    # read the sumstats table
    sumstats = hl.read_table('gs://ukbb_prs/sumstats/temp.kt')

    # remove leading zeros from contigs
    contigs = {'0{}'.format(x):str(x) for x in range(1, 10)}

    # import bgen(s)
    mt = hl.methods.import_bgen('gs://fc-7d5088b4-7673-45b5-95c2-17ae00a04183/imputed/ukb_imp_chr{22}_v3.bgen',
                               ['dosage'],
                               sample_file='gs://phenotype_31063/ukb31063.imputed_v3.autosomes.sample',
                               contig_recoding=contigs)

    # load scoring sample
    sampleids = hl.import_table('gs://ukb31063-mega-gwas/hail-0.1/qc/ukb31063.gwas_samples.txt', delimiter='\s+').key_by('s')

    # merge sumstats on bgen matrixtable
    mt = mt.annotate_rows(ss=sumstats[mt.locus])

    # handle strand/sign flips -- score in terms of alt allele
    mt = mt.annotate_rows(beta = hl.case()
                  .when(((mt.alleles[0] == mt.ss.nt1) &
                        (mt.alleles[1] == mt.ss.nt2)) |
                        ((flip_text(mt.alleles[0]) == mt.ss.nt1) &
                        (flip_text(mt.alleles[1]) == mt.ss.nt2)),
                       (-1*mt.ss.ldpred_inf_beta))
                  .when(((mt.alleles[0] == mt.ss.nt2) &
                        (mt.alleles[1] == mt.ss.nt1)) |
                        ((flip_text(mt.alleles[0]) == mt.ss.nt2) &
                        (flip_text(mt.alleles[1]) == mt.ss.nt1)),
                       mt.ss.ldpred_inf_beta)
                  .or_missing())

    # filter bgen matrixtable down to only SNPs with betas
    mt = mt.filter_rows(hl.is_defined(mt.beta))

    # filter bgen matrixtable to only include people in scoring sample
    mt = mt.filter_cols(hl.is_defined(sampleids[mt.s]))

    # score sample
    mt = mt.annotate_cols(prs=hl.agg.sum(mt.beta * mt.dosage))

    # write out table with sample IDs and PRS scores
    mt.cols().export('gs://ukbb_prs/prs/UKB_'+pheno+'_PRS_22.txt')

parser = argparse.ArgumentParser()
parser.add_argument("--phenotype", help="name of the sumstat phenotype")
args = parser.parse_args()

try:
    start = time.time()
    main(args.phenotype)
    end = time.time()
    message = "Success! Job was completed in %s" % time.strftime("%H:%M:%S", time.gmtime(end - start))
    send_message(message)
except Exception as e:
    send_message("Fail.")
```

"Failure Reason":
```
Job aborted due to stage failure: Task 98 in stage 13.0 failed 20 times, most recent failure: Lost task 98.19 in stage 13.0 (TID 22699, ccarey-sw-xt4j.c.ukbb-robinson.internal, executor 68): java.lang.NegativeArraySizeException
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at is.hail.annotations.Region.ensure(Region.scala:139)
	at is.hail.annotations.Region.allocate(Region.scala:152)
	at is.hail.annotations.Region.allocate(Region.scala:159)
	at is.hail.expr.types.TContainer.allocate(TContainer.scala:127)
	at is.hail.annotations.RegionValueBuilder.fixupArray(RegionValueBuilder.scala:278)
	at is.hail.annotations.RegionValueBuilder.addRegionValue(RegionValueBuilder.scala:432)
	at is.hail.expr.MatrixMapRows$$anonfun$25$$anonfun$apply$19.apply(Relational.scala:815)
	at is.hail.expr.MatrixMapRows$$anonfun$25$$anonfun$apply$19.apply(Relational.scala:804)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:914)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:914)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
	at is.hail.sparkextras.ContextRDD$$anonfun$6$$anonfun$apply$11.apply(ContextRDD.scala:237)
	at is.hail.sparkextras.ContextRDD$$anonfun$6$$anonfun$apply$11.apply(ContextRDD.scala:235)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.sparkextras.ContextRDD$$anonfun$6.apply(ContextRDD.scala:235)
	at is.hail.sparkextras.ContextRDD$$anonfun$6.apply(ContextRDD.scala:234)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
```

_All_ of my workers had this error:
```
java.lang.NegativeArraySizeException
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at is.hail.annotations.Region.ensure(Region.scala:139)
	at is.hail.annotations.Region.allocate(Region.scala:152)
	at is.hail.annotations.Region.allocate(Region.scala:159)
	at is.hail.expr.types.TContainer.allocate(TContainer.scala:127)
	at is.hail.annotations.RegionValueBuilder.fixupArray(RegionValueBuilder.scala:278)
	at is.hail.annotations.RegionValueBuilder.addRegionValue(RegionValueBuilder.scala:432)
	at is.hail.expr.MatrixMapRows$$anonfun$25$$anonfun$apply$19.apply(Relational.scala:815)
	at is.hail.expr.MatrixMapRows$$anonfun$25$$anonfun$apply$19.apply(Relational.scala:804)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:914)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:914)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:911)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
	at is.hail.sparkextras.ContextRDD$$anonfun$6$$anonfun$apply$11.apply(ContextRDD.scala:237)
	at is.hail.sparkextras.ContextRDD$$anonfun$6$$anonfun$apply$11.apply(ContextRDD.scala:235)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.sparkextras.ContextRDD$$anonfun$6.apply(ContextRDD.scala:235)
	at is.hail.sparkextras.ContextRDD$$anonfun$6.apply(ContextRDD.scala:234)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by danking** [comment]
@ce-carey Do you know which hail version hash you were running?

**Comment by ce-carey** [comment]
@danking Unfortunately I didn't get the hash, but I was running whatever version was the default 6 days ago. Started the cluster using `--version devel --spark 2.2.0`, no specific hash specified.

**Comment by danking** [comment]
My best guess as to what you're running into is fixed by [this PR](https://github.com/hail-is/hail/pull/3572) which should land soon.

**Comment by danking** [comment]
I think this is resolved, re-open if it's still an issue!
