### ISSUE TITLE
AssertionError on key_by

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3516]
Easy to reproduce:
```
x = hl.utils.range_table(10).annotate(x='x', y=hl.rand_bool(0.5))
x.show()
+-------+-----+-------+
|   idx | x   | y     |
+-------+-----+-------+
| int32 | str | bool  |
+-------+-----+-------+
|     0 | x   | true  |
|     1 | x   | false |
|     2 | x   | true  |
|     3 | x   | true  |
|     4 | x   | true  |
|     5 | x   | false |
|     6 | x   | false |
|     7 | x   | true  |
|     8 | x   | false |
|     9 | x   | false |
+-------+-----+-------+
x.key_by('y').show()
2018-05-06 23:22:14 Hail: INFO: Coerced almost-sorted dataset
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-304965820738>", line 1, in <module>
    x.key_by('y').show()
  File "<decorator-gen-598>", line 2, in show
  File "/Users/konradk/Dropbox/src/python/hail/typecheck/check.py", line 486, in _typecheck
    return __orig_func__(*args_, **kwargs_)
  File "/Users/konradk/Dropbox/src/python/hail/table.py", line 1101, in show
    print(self._show(n,width, truncate, types))
  File "/Users/konradk/Dropbox/src/python/hail/table.py", line 1104, in _show
    return self._jt.showString(n, joption(truncate), types, width)
  File "/Users/konradk/programs/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/konradk/Dropbox/src/python/hail/utils/java.py", line 196, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: AssertionError: assertion failed
Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 9.0 failed 1 times, most recent failure: Lost task 0.0 in stage 9.0 (TID 49, localhost, executor driver): java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:926)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.utils.package$.getIteratorSizeWithMaxN(package.scala:349)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at is.hail.sparkextras.ContextRDD.runJob(ContextRDD.scala:456)
	at is.hail.sparkextras.ContextRDD.head(ContextRDD.scala:433)
	at is.hail.rvd.OrderedRVD.head(OrderedRVD.scala:285)
	at is.hail.rvd.OrderedRVD.head(OrderedRVD.scala:21)
	at is.hail.rvd.RVD$class.takeAsBytes(RVD.scala:243)
	at is.hail.rvd.OrderedRVD.takeAsBytes(OrderedRVD.scala:21)
	at is.hail.rvd.RVD$class.take(RVD.scala:247)
	at is.hail.rvd.OrderedRVD.take(OrderedRVD.scala:21)
	at is.hail.table.Table.take(Table.scala:990)
	at is.hail.table.Table.showString(Table.scala:1031)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:926)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:908)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.utils.package$.getIteratorSizeWithMaxN(package.scala:349)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:433)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1$$anonfun$apply$34.apply(ContextRDD.scala:458)
	at is.hail.utils.package$.using(package.scala:577)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:458)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Hail version: devel-9a5678f
Error summary: AssertionError: assertion failed
```

**Comment by tpoterba** [comment]
sneaky.

**Comment by tpoterba** [comment]
this isn't a keyby bug, this is the random nondeterminism bug.

**Comment by konradjk** [comment]
wat

**Comment by konradjk** [comment]
oh, bc of rand_bool? weeeird

**Comment by tpoterba** [comment]
if you cache x before the keyby, I think it would work

**Comment by konradjk** [comment]
oooooo fun. is the key changing along the way?

**Comment by tpoterba** [comment]
yep. The keys scanned and the keys shuffled are totally different.

**Comment by tpoterba** [comment]
we already have issue for this, I think
