### ISSUE TITLE
Table.union assertion fails on mismatched requiredness in globals

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3639]
table1:
```
'Table{global:+Struct{},key:[s],row:Struct{s:String,PC1:Float64,PC2:Float64,PC3:Float64,PC4:Float64,PC5:Float64,PC6:Float64,PC7:Float64,PC8:Float64,PC9:Float64,PC10:Float64,PC11:Float64,PC12:Float64,PC13:Float64,PC14:Float64,PC15:Float64,PC16:Float64,PC17:Float64,PC18:Float64,PC19:Float64,PC20:Float64,source:String}}'
```

table2:
```
'Table{global:Struct{},key:[s],row:Struct{s:String,PC1:Float64,PC2:Float64,PC3:Float64,PC4:Float64,PC5:Float64,PC6:Float64,PC7:Float64,PC8:Float64,PC9:Float64,PC10:Float64,PC11:Float64,PC12:Float64,PC13:Float64,PC14:Float64,PC15:Float64,PC16:Float64,PC17:Float64,PC18:Float64,PC19:Float64,PC20:Float64,source:String}}'
```

`table1.union(table2)` fails with:
```
Java stack trace:
java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:156)
    at is.hail.expr.TableUnion.<init>(Relational.scala:1996)
    at is.hail.table.Table.union(Table.scala:947)
    at is.hail.table.Table.union(Table.scala:945)
```

**Comment by konradjk** [comment]
To be clear `.select_globals()` fixes the problem, but...
