### ISSUE TITLE
OOB on MT.from_rows_table()

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3668]
```
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-2-84a33bbdd0f1> in <module>()
      1 pre_process_data(annotations_ht_path('genomes', 'frequencies'),
----> 2                  split_context_mt_path, processed_genomes_ht_path, True)

/home/konradk/constraint_utils.py in pre_process_data(ht_path, split_context_mt_path, output_ht_path, overwrite)
    126                      output_ht_path: str, overwrite: bool = False) -> None:
    127     ht = hl.read_table(ht_path)
--> 128     mt = hl.MatrixTable.from_rows_table(ht, partition_key='locus')
    129     mt.write(ht_path.replace('.ht', '.mt'))
    130     mt = hl.read_matrix_table(ht_path.replace('.ht', '.mt'))

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

/home/hail/hail.zip/hail/matrixtable.py in from_rows_table(cls, table, partition_key)
   3107             elif list(table.key)[:len(partition_key)] != partition_key:
   3108                 raise ValueError('partition_key must be a prefix of table key')
-> 3109         jmt = scala_object(Env.hail().variant, 'MatrixTable').fromRowsTable(table._jt, partition_key)
   3110         return MatrixTable(jmt)
   3111 

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/home/hail/hail.zip/hail/utils/java.py in deco(*args, **kwargs)
    194             raise FatalError('%s\n\nJava stack trace:\n%s\n'
    195                              'Hail version: %s\n'
--> 196                              'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
    197         except pyspark.sql.utils.CapturedException as e:
    198             raise FatalError('%s\n\nJava stack trace:\n%s\n'

FatalError: ArrayIndexOutOfBoundsException: 0

Java stack trace:
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.catalyst.expressions.GenericRow.get(rows.scala:173)
	at org.apache.spark.sql.Row$class.apply(Row.scala:163)
	at org.apache.spark.sql.catalyst.expressions.GenericRow.apply(rows.scala:165)
	at is.hail.annotations.Annotation$$anonfun$isSafe$1.apply$mcZI$sp(Annotation.scala:70)
	at is.hail.annotations.Annotation$$anonfun$isSafe$1.apply(Annotation.scala:70)
	at is.hail.annotations.Annotation$$anonfun$isSafe$1.apply(Annotation.scala:70)
	at scala.collection.IndexedSeqOptimized$class.prefixLengthImpl(IndexedSeqOptimized.scala:38)
	at scala.collection.IndexedSeqOptimized$class.forall(IndexedSeqOptimized.scala:43)
	at scala.collection.mutable.ArrayOps$ofInt.forall(ArrayOps.scala:234)
	at is.hail.annotations.Annotation$.isSafe(Annotation.scala:70)
	at is.hail.annotations.BroadcastRow.<init>(BroadcastValue.scala:27)
	at is.hail.variant.MatrixTable$.fromRowsTable(MatrixTable.scala:462)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-1ea0ab823b1f
Error summary: ArrayIndexOutOfBoundsException: 0
```

**Comment by konradjk** [comment]
The output of ht.describe():
```

----------------------------------------
Global fields:
    'downsamplings': array<int32> 
----------------------------------------
Row fields:
    'locus': locus<GRCh37> 
    'alleles': array<str> 
    'freq': array<struct {
        AC: array<int32>, 
        AF: array<float64>, 
        AN: int32, 
        homozygote_count: array<int32>, 
        meta: dict<str, str>
    }> 
    'project_max': array<struct {
        AC: array<int32>, 
        AF: array<float64>, 
        AN: int32, 
        homozygote_count: array<int32>, 
        project: str
    }> 
----------------------------------------
Key: ['locus', 'alleles']
----------------------------------------
```

**Comment by konradjk** [comment]
Also this goes at least all the way back to `b76333115`
