### ISSUE TITLE
int typecheck on hl.literal() errors out with None

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3690]
When this was a float, it was fine. But when I try to `hl.literal()` a struct with a `None` in an int field, the typecheck gets it and can't verify it (I passed it the correct `dtype`). This is part of a general series of problems when going from `x = ht.aggregate(hl.agg.counter(ht.row_field))` - that once `row_field` has any missing data, you can't `hl.literal(x)` without some more work.

```
Traceback (most recent call last):
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/hail-devel-72603c5e840e.zip/hail/expr/functions.py", line 98, in literal
    dtype._typecheck(x)
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/hail-devel-72603c5e840e.zip/hail/expr/types.py", line 641, in _typecheck
    self.key_type._typecheck(k)
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/hail-devel-72603c5e840e.zip/hail/expr/types.py", line 730, in _typecheck
    t._typecheck(annotation.get(f))
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/hail-devel-72603c5e840e.zip/hail/expr/types.py", line 231, in _typecheck
    if not self.min_value <= annotation <= self.max_value:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/pyscripts_gYULqI.zip/gnomad_hail/utils/slack.py", line 95, in try_slack
    func(*args)
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/constraint2.py", line 70, in main
    coverage_ht = get_proportion_observed_by_coverage(rare_autosomes_exome_ht, autosomes_context_ht, mutation_ht, False)
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/constraint2.py", line 32, in get_proportion_observed_by_coverage
    ht = ht.annotate(possible_variants=hl.literal(possible_variants.variant_count, dtype=variant_counts_dtype)[ht.key],
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/hail-devel-72603c5e840e.zip/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/tmp/79408a38ad73483d9f4c5afc91adbb19/hail-devel-72603c5e840e.zip/hail/expr/functions.py", line 101, in literal
    .format(dtype)) from e
TypeError: 'literal': object did not match the passed type 'dict<struct{context: str, ref: str, alt: str, methylation_level: int32, exome_coverage: int32}, int64>'
```

**Comment by tpoterba** [comment]
My proposal here is to make the result of aggregate an expression.

**Comment by tpoterba** [comment]
This actually lets us compile / optimize across aggregations!

**Comment by konradjk** [comment]
And then `.collect()` to bring it back into Python? I'm totally fine with that.
