### ISSUE TITLE
A Missing Default Case Should Have An Informative Error Message

### ISSUE THREAD

**Issue by danking** [hail-is/hail#3696]
### Hail version:
`6d4d50458`
### What you did:
```
label_expr = (hl.case(missing_false=True)
                  .when(ht[tp_col] & ~ht[fp_col], "TP")
                  .when(ht[fp_col] & ~ht[tp_col], "FP”))
```

### What went wrong (all error messages here, including the full java stack trace):
```
I’m getting an error that reads,
Traceback (most recent call last):
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/variantqc.py", line 567, in <module>
    try_slack(args.slack_channel, main, args)
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/pyscripts_SuuLaL.zip/gnomad_hail/utils/slack.py", line 112, in try_slack
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/pyscripts_SuuLaL.zip/gnomad_hail/utils/slack.py", line 95, in try_slack
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/variantqc.py", line 508, in main
    run_hash = train_rf(data_type, args) if args.train_rf else args.run_hash
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/variantqc.py", line 422, in train_rf
    fp_to_tp=args.fp_to_tp)
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/variantqc.py", line 240, in sample_rf_training_examples
    train_col: train_expr})
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/hail-6d4d50458.zip/hail/table.py", line 720, in annotate
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/hail-6d4d50458.zip/hail/utils/misc.py", line 336, in get_annotate_exprs
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/hail-6d4d50458.zip/hail/utils/misc.py", line 336, in <dictcomp>
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/hail-6d4d50458.zip/hail/expr/expressions/base_expression.py", line 102, in to_expr
  File "/tmp/99ecf728f92847f2bfddb1e75cbd0a4e/hail-6d4d50458.zip/hail/expr/expressions/base_expression.py", line 93, in impute_type
hail.expr.expressions.base_expression.ExpressionException: Hail cannot automatically impute type of <class 'hail.expr.builders.CaseBuilder'>: <hail.expr.builders.CaseBuilder object at 0x7f2ad03c74e0>
```

**Comment by tpoterba** [comment]
They have to have default or or_missing

**Comment by tpoterba** [comment]
We could throw a nicer error
