### ISSUE TITLE
`hl.eval_expr(ht.globals)` errors when globals is empty

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#3728]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:

```
print(metrics_ht['vqsr'].globals)
hl.eval_expr(metrics_ht['vqsr'].globals)
```

### What went wrong (all error messages here, including the full java stack trace):

```
<StructExpression of type struct{}>
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-51-e812f4924948> in <module>()
      1 print(metrics_ht['vqsr'].globals)
----> 2 hl.eval_expr(metrics_ht['vqsr'].globals)

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

/home/hail/hail.zip/hail/expr/expressions/expression_utils.py in eval_expr(expression)
    135         Result of evaluating `expression`.
    136     """
--> 137     return eval_expr_typed(expression)[0]
    138 
    139 

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

/home/hail/hail.zip/hail/expr/expressions/expression_utils.py in eval_expr_typed(expression)
    169     analyze('eval_expr_typed', expression, Indices(expression._indices.source))
    170 
--> 171     return expression.collect()[0], expression.dtype
    172 
    173 

/home/hail/hail.zip/hail/expr/expressions/base_expression.py in collect(self)
    755         """
    756         uid = Env.get_uid()
--> 757         t = self._to_table(uid)
    758         return [r[uid] for r in t._select("collect", None, hl.struct(**{uid: t[uid]})).collect()]
    759 

/home/hail/hail.zip/hail/expr/expressions/base_expression.py in _to_table(self, name)
    584             source = source.select_globals(**{uid: self})
    585             df = Env.dummy_table()
--> 586             df = df.select(**{name: source.index_globals()[uid]})
    587             return df
    588         elif len(axes) == 1:

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

/home/hail/hail.zip/hail/table.py in select(self, *exprs, **named_exprs)
    864                                exprs, named_exprs, self._row_indices,
    865                                protect_keys=True)
--> 866         return self._select('Table.select', value_struct=hl.struct(**row))
    867 
    868     @typecheck_method(exprs=oneof(str, Expression))

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

/home/hail/hail.zip/hail/table.py in _select(self, caller, key_struct, value_struct)
    410             row = value_struct if value_struct is not None else hl.struct()
    411 
--> 412         base, cleanup = self._process_joins(row)
    413         analyze(caller, row, self._row_indices)
    414 

/home/hail/hail.zip/hail/table.py in _process_joins(self, *exprs)
   1459         def broadcast_f(left, data, jt):
   1460             return Table(left._jt.annotateGlobalJSON(data, jt))
-> 1461         return process_joins(self, exprs, broadcast_f)
   1462 
   1463     def cache(self):

/home/hail/hail.zip/hail/utils/misc.py in process_joins(obj, exprs, broadcast_f)
    354         for j in sorted(joins, key=lambda j: j.idx): # Make sure joins happen in order
    355             if j not in used_joins:
--> 356                 left = j.join_func(left)
    357                 all_uids.extend(j.temp_vars)
    358                 used_joins.add(j)

/home/hail/hail.zip/hail/table.py in joiner(obj)
   1448             else:
   1449                 assert isinstance(obj, Table)
-> 1450                 return Table(Env.jutils().joinGlobals(obj._jt, self._jt, uid))
   1451 
   1452         ast = Join(Select(TopLevelReference('global', Indices()), uid),

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/home/hail/hail.zip/hail/utils/java.py in deco(*args, **kwargs)
    194             raise FatalError('%s\n\nJava stack trace:\n%s\n'
    195                              'Hail version: %s\n'
--> 196                              'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
    197         except pyspark.sql.utils.CapturedException as e:
    198             raise FatalError('%s\n\nJava stack trace:\n%s\n'

FatalError: AssertionError: assertion failed

Java stack trace:
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at is.hail.expr.TableMapGlobals.execute(Relational.scala:2158)
	at is.hail.table.Table.value$lzycompute(Table.scala:243)
	at is.hail.table.Table.value(Table.scala:238)
	at is.hail.table.Table.x$5$lzycompute(Table.scala:246)
	at is.hail.table.Table.x$5(Table.scala:246)
	at is.hail.table.Table.globals$lzycompute(Table.scala:246)
	at is.hail.table.Table.globals(Table.scala:246)
	at is.hail.utils.Py4jUtils$class.joinGlobals(Py4jUtils.scala:137)
	at is.hail.utils.package$.joinGlobals(package.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-5b299ddae758
Error summary: AssertionError: assertion failed
```

**Comment by tpoterba** [comment]
I can't replicate this
