### ISSUE TITLE
Method code too large on uniroot

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3746]
Trying to run a bunch of 201 aggregators + uniroot on a custom branch (https://github.com/konradjk/hail/tree/freq_filter), and getting:
```
Traceback (most recent call last):
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/generate_frequency_data.py", line 141, in <module>
    try_slack(args.slack_channel, main, args)
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/pyscripts_CSD0RS.zip/gnomad_hail/utils/slack.py", line 112, in try_slack
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/pyscripts_CSD0RS.zip/gnomad_hail/utils/slack.py", line 95, in try_slack
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/generate_frequency_data.py", line 121, in main
    mt, sample_table = generate_frequency_data(mt, args.subpop, args.downsampling, args.genomes)
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/generate_frequency_data.py", line 102, in generate_frequency_data
    mt = mt.annotate_rows(freq=frequency_expression)
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/hail-1e2e8c7e8.zip/hail/matrixtable.py", line 905, in annotate_rows
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/hail-1e2e8c7e8.zip/hail/typecheck/check.py", line 547, in wrapper
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/hail-1e2e8c7e8.zip/hail/matrixtable.py", line 2893, in _select_rows
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/tmp/9c7c1cdf3da74749a388ecb2e4365430/hail-1e2e8c7e8.zip/hail/utils/java.py", line 196, in deco
hail.utils.java.FatalError: RuntimeException: Method code too large!

Java stack trace:
java.lang.RuntimeException: Method code too large!
	at is.hail.relocated.org.objectweb.asm.MethodWriter.a(Unknown Source)
	at is.hail.relocated.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at is.hail.asm4s.FunctionBuilder.classAsBytes(FunctionBuilder.scala:306)
	at is.hail.asm4s.FunctionBuilder.result(FunctionBuilder.scala:340)
	at is.hail.expr.CM.runWithDelayedValues(CM.scala:80)
	at is.hail.expr.Parser$.is$hail$expr$Parser$$evalNoTypeCheck(Parser.scala:60)
	at is.hail.expr.Parser$.eval(Parser.scala:73)
	at is.hail.expr.Parser$.parseExpr(Parser.scala:88)
	at is.hail.variant.MatrixTable.selectRows(MatrixTable.scala:1232)
	at is.hail.variant.MatrixTable.selectRows(MatrixTable.scala:1205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-1e2e8c7e86f3
Error summary: RuntimeException: Method code too large!
```

**Comment by konradjk** [comment]
Oh and code is something like:
```
    callstats = hl.agg.call_stats(mt.GT, mt.alleles)
    frequency_expression.insert(1, callstats.annotate(meta={'group': 'raw'},
                                                      faf95=hl.faf(callstats.AC[1], callstats.AN, 0.95),
                                                      faf99=hl.faf(callstats.AC[1], callstats.AN, 0.99)))
    mt = mt.annotate_rows(freq=frequency_expression)
```

**Comment by catoverdrive** [comment]
I'm going to close this since this appears to be an AST problem for now.
