### ISSUE TITLE
_select_entries fails with multiple implicit-entry-join expressions

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#3763]
This impacts all the methods that use _select_entries, e.g. within process_joins, like group_by.aggregate_rows/cols, annotate_rows/cols, transmute_rows/cols, etc.

The error is expression source mismatch, which may be due to `annotate_entries` being done separately from `_annotate_all` in the joiner for `index_entries` AST:
```
        def joiner(left: MatrixTable):
                localized = Table(self._jvds.localizeEntries(row_uid))
                src_cols_indexed = self.cols().add_index(col_uid)
                src_cols_indexed = src_cols_indexed.annotate(**{col_uid: hl.int32(src_cols_indexed[col_uid])})
                left = left._annotate_all(row_exprs = {row_uid: localized.index(*row_exprs)[row_uid]},
                                          col_exprs = {col_uid: src_cols_indexed.index(*col_exprs)[col_uid]})
                return left.annotate_entries(**{uid: left[row_uid][left[col_uid]]})
```

### Hail version:
master
b1ac051d34bcc4c26fe9dea58aeac53038f2963e

### What you did:

```
mt = hl.utils.range_matrix_table(4, 4)
mt2 = hl.utils.range_matrix_table(4, 4)
mt2 = mt2.annotate_entries(x=mt2.row_idx + mt2.col_idx)
mt.select_entries(a=mt2[mt.row_idx, mt.col_idx].x,
                  b=mt2[mt.row_idx, mt.col_idx].x)._force_count_rows()
```

### What went wrong (all error messages here, including the full java stack trace):

```
Error
Traceback (most recent call last):
  File "/Users/jbloom/anaconda/envs/py36/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/jbloom/anaconda/envs/py36/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/jbloom/hail/python/hail/tests/test_api.py", line 1557, in test_force_bug
    b=mt2[mt.row_idx, mt.col_idx].x)._force_count_rows()
  File "/Users/jbloom/hail/python/hail/matrixtable.py", line 1171, in select_entries
    return self._select_entries("MatrixTable.select_entries", hl.struct(**entry))
  File "/Users/jbloom/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/Users/jbloom/hail/python/hail/matrixtable.py", line 2844, in _select_entries
    base, cleanup = self._process_joins(s)
  File "/Users/jbloom/hail/python/hail/matrixtable.py", line 2503, in _process_joins
    return process_joins(self, exprs, broadcast_f)
  File "/Users/jbloom/hail/python/hail/utils/misc.py", line 356, in process_joins
    left = j.join_func(left)
  File "/Users/jbloom/hail/python/hail/matrixtable.py", line 2414, in joiner
    col_exprs = {col_uid: src_cols_indexed.index(*col_exprs)[col_uid]})
  File "/Users/jbloom/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/Users/jbloom/hail/python/hail/matrixtable.py", line 2443, in _annotate_all
    analyze("MatrixTable.annotate_rows", row_struct, self._row_indices)
  File "/Users/jbloom/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/Users/jbloom/hail/python/hail/expr/expressions/expression_utils.py", line 105, in analyze
    raise errors[0]
hail.expr.expressions.base_expression.ExpressionException: MatrixTable.annotate_rows expects an expression from source <hail.matrixtable.MatrixTable object at 0x10889c908>, found expression derived from <hail.matrixtable.MatrixTable object at 0x108acbf60>
```

**Comment by jbloom22** [comment]
Did you add the example above or similar as a regression test?

**Comment by tpoterba** [comment]
ah, no. I'll make a followup.

**Comment by jbloom22** [comment]
thanks, assign it to me
