### ISSUE TITLE
json parsing error on hl.literal([float('nan')]).value

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#3785]
`hl.literal(float('nan')).value` works as expected, the trouble arised when parsing non-numeric values inside an array, e.g. `[float('nan'), float('inf'), float('-inf')]`.

```
Error summary: JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: {"__uid_3": [NaN, Infinity, -Infinity]}; line: 1, column: 17]
```

I'm not sure how to enable this feature:
https://github.com/FasterXML/jackson-core/wiki/JsonParser-Features

### Hail version:
master
c908fd74abd819f4fcfbcdad88c5db6bf77083b2

### What you did:

`hl.literal([float('nan')]).value`

### What went wrong (all error messages here, including the full java stack trace):

hl.literal([float('nan'), float('inf'), float('-inf')]).value
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-3-ea2ec4f5df06> in <module>()
----> 1 hl.literal([float('nan'), float('inf'), float('-inf')]).value

~/hail/python/hail/expr/expressions/base_expression.py in value(self)
    773 
    774         """
--> 775         return hl.eval_expr(self)
    776 
    777 

~/hail/python/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

~/hail/python/hail/expr/expressions/expression_utils.py in eval_expr(expression)
    135         Result of evaluating `expression`.
    136     """
--> 137     return eval_expr_typed(expression)[0]
    138 
    139 

~/hail/python/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

~/hail/python/hail/expr/expressions/expression_utils.py in eval_expr_typed(expression)
    169     analyze('eval_expr_typed', expression, Indices(expression._indices.source))
    170 
--> 171     return expression.collect()[0], expression.dtype
    172 
    173 

~/hail/python/hail/expr/expressions/base_expression.py in collect(self)
    755         """
    756         uid = Env.get_uid()
--> 757         t = self._to_table(uid)
    758         return [r[uid] for r in t._select("collect", None, hl.struct(**{uid: t[uid]})).collect()]
    759 

~/hail/python/hail/expr/expressions/base_expression.py in _to_table(self, name)
    578             # scalar expression
    579             df = Env.dummy_table()
--> 580             df = df.select(**{name: self})
    581             return df
    582         elif len(axes) == 0:

~/hail/python/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

~/hail/python/hail/table.py in select(self, *exprs, **named_exprs)
    890                                exprs, named_exprs, self._row_indices,
    891                                protect_keys=True)
--> 892         return self._select('Table.select', value_struct=hl.struct(**row))
    893 
    894     @typecheck_method(exprs=oneof(str, Expression))

~/hail/python/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

~/hail/python/hail/table.py in _select(self, caller, key_struct, value_struct, do_process_joins)
    433 
    434         if do_process_joins:
--> 435             base, cleanup = self._process_joins(row)
    436             analyze(caller, row, self._row_indices)
    437         else:

~/hail/python/hail/table.py in _process_joins(self, *exprs)
   1484         def broadcast_f(left, data, jt):
   1485             return Table(left._jt.annotateGlobalJSON(data, jt))
-> 1486         return process_joins(self, exprs, broadcast_f)
   1487 
   1488     def cache(self):

~/hail/python/hail/utils/misc.py in process_joins(obj, exprs, broadcast_f)
    364         data = hail.Struct(**{b.uid: b.value for b in broadcasts})
    365         data_json = t._to_json(data)
--> 366         left = broadcast_f(left, data_json, t._jtype)
    367 
    368     def cleanup(table):

~/hail/python/hail/table.py in broadcast_f(left, data, jt)
   1483     def _process_joins(self, *exprs):
   1484         def broadcast_f(left, data, jt):
-> 1485             return Table(left._jt.annotateGlobalJSON(data, jt))
   1486         return process_joins(self, exprs, broadcast_f)
   1487 

~/apache/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

~/hail/python/hail/utils/java.py in deco(*args, **kwargs)
    194             raise FatalError('%s\n\nJava stack trace:\n%s\n'
    195                              'Hail version: %s\n'
--> 196                              'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
    197         except pyspark.sql.utils.CapturedException as e:
    198             raise FatalError('%s\n\nJava stack trace:\n%s\n'

FatalError: JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: {"__uid_3": [NaN, Infinity, -Infinity]}; line: 1, column: 17]

Java stack trace:
com.fasterxml.jackson.core.JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: {"__uid_3": [NaN, Infinity, -Infinity]}; line: 1, column: 17]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1602)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:26)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:42)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:35)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
	at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:20)
	at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:50)
	at is.hail.table.Table.annotateGlobalJSON(Table.scala:476)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

Hail version: devel-2d80e80610df
Error summary: JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: {"__uid_3": [NaN, Infinity, -Infinity]}; line: 1, column: 17]

**Comment by jbloom22** [comment]
Resolving this issue is necessary to fix `_test_hwe` in `test_api.py` after #3825 has gone in.

**Comment by jbloom22** [comment]
Though I may instead modify the test first, will update here.

**Comment by jbloom22** [comment]
I reworked the test so no longer connected to this issue
