### ISSUE TITLE
VEP annotation with CSQ flag enabled raises exception

### ISSUE THREAD

**Issue by mikelynch** [hail-is/hail#3790]
### Hail version:
Latest build of `devel` from https://storage.googleapis.com/hail-common/distributions/devel/Hail-devel-5d0f74cef4f2-Spark-2.2.0.zip

### What you did:
1. Import VCF file into MatrixTable.
2. Annotate VCF file with `output = hl.vep(input, 'vep.properties', csq=True)`.
3. Attempt to view output with `output.rows().show()`.

With `csq=False`, step 3 succeeds.

### What went wrong (all error messages here, including the full java stack trace):
```
2018-06-19 17:15:41 Hail: INFO: vep: annotated 2 variants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/opt/hail/python/hail/table.py", line 1195, in show
    print(self._show(n,width, truncate, types))
  File "/opt/hail/python/hail/table.py", line 1198, in _show
    return self._jt.showString(n, joption(truncate), types, width)
  File "/opt/spark-2.2.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/opt/hail/python/hail/utils/java.py", line 196, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: MatchError: [Ljava.lang.String;@7cd5fe91 (of class [Ljava.lang.String;)

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 11.0 failed 1 times, most recent failure: Lost task 0.0 in stage 11.0 (TID 11, localhost, executor driver): scala.MatchError: [Ljava.lang.String;@7cd5fe91 (of class [Ljava.lang.String;)
	at is.hail.annotations.RegionValueBuilder.addAnnotation(RegionValueBuilder.scala:489)
	at is.hail.methods.VEP$$anonfun$9$$anonfun$apply$4.apply(VEP.scala:350)
	at is.hail.methods.VEP$$anonfun$9$$anonfun$apply$4.apply(VEP.scala:345)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:926)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:920)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.RVD$$anonfun$3$$anon$1.hasNext(RVD.scala:226)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:1004)
	at is.hail.utils.richUtils.RichIterator$$anon$5.isValid(RichIterator.scala:21)
	at is.hail.utils.StagingIterator.isValid(FlipbookIterator.scala:46)
	at is.hail.utils.FlipbookIterator$$anon$1.calculateValidity(FlipbookIterator.scala:178)
	at is.hail.utils.FlipbookIterator$ValidityCachingStateMachine$class.refreshValidity(FlipbookIterator.scala:167)
	at is.hail.utils.FlipbookIterator$$anon$1.refreshValidity(FlipbookIterator.scala:176)
	at is.hail.utils.FlipbookIterator$ValidityCachingStateMachine$class.$init$(FlipbookIterator.scala:171)
	at is.hail.utils.FlipbookIterator$$anon$1.<init>(FlipbookIterator.scala:176)
	at is.hail.utils.FlipbookIterator.staircased(FlipbookIterator.scala:176)
	at is.hail.utils.FlipbookIterator.cogroup(FlipbookIterator.scala:212)
	at is.hail.utils.FlipbookIterator.leftJoinDistinct(FlipbookIterator.scala:281)
	at is.hail.annotations.OrderedRVIterator.leftJoinDistinct(OrderedRVIterator.scala:59)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$6.apply(KeyedOrderedRVD.scala:84)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$6.apply(KeyedOrderedRVD.scala:84)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$orderedJoinDistinct$1.apply(KeyedOrderedRVD.scala:95)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$orderedJoinDistinct$1.apply(KeyedOrderedRVD.scala:92)
	at is.hail.sparkextras.ContextRDD$$anonfun$czipPartitions$1$$anonfun$apply$26.apply(ContextRDD.scala:355)
	at is.hail.sparkextras.ContextRDD$$anonfun$czipPartitions$1$$anonfun$apply$26.apply(ContextRDD.scala:355)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$22$$anonfun$apply$23.apply(ContextRDD.scala:308)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$22$$anonfun$apply$23.apply(ContextRDD.scala:308)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.utils.package$.getIteratorSizeWithMaxN(package.scala:347)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:442)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:442)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:469)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:467)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1504)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1732)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2050)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
	at is.hail.sparkextras.ContextRDD.runJob(ContextRDD.scala:465)
	at is.hail.sparkextras.ContextRDD.head(ContextRDD.scala:442)
	at is.hail.rvd.OrderedRVD.head(OrderedRVD.scala:286)
	at is.hail.rvd.OrderedRVD.head(OrderedRVD.scala:22)
	at is.hail.rvd.RVD$class.takeAsBytes(RVD.scala:247)
	at is.hail.rvd.OrderedRVD.takeAsBytes(OrderedRVD.scala:22)
	at is.hail.rvd.RVD$class.take(RVD.scala:251)
	at is.hail.rvd.OrderedRVD.take(OrderedRVD.scala:22)
	at is.hail.table.Table.take(Table.scala:958)
	at is.hail.table.Table.showString(Table.scala:999)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)scala.MatchError: [Ljava.lang.String;@7cd5fe91 (of class [Ljava.lang.String;)
	at is.hail.annotations.RegionValueBuilder.addAnnotation(RegionValueBuilder.scala:489)
	at is.hail.methods.VEP$$anonfun$9$$anonfun$apply$4.apply(VEP.scala:350)
	at is.hail.methods.VEP$$anonfun$9$$anonfun$apply$4.apply(VEP.scala:345)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:926)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.next(OrderedRVD.scala:920)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.RVD$$anonfun$3$$anon$1.hasNext(RVD.scala:226)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:1004)
	at is.hail.utils.richUtils.RichIterator$$anon$5.isValid(RichIterator.scala:21)
	at is.hail.utils.StagingIterator.isValid(FlipbookIterator.scala:46)
	at is.hail.utils.FlipbookIterator$$anon$1.calculateValidity(FlipbookIterator.scala:178)
	at is.hail.utils.FlipbookIterator$ValidityCachingStateMachine$class.refreshValidity(FlipbookIterator.scala:167)
	at is.hail.utils.FlipbookIterator$$anon$1.refreshValidity(FlipbookIterator.scala:176)
	at is.hail.utils.FlipbookIterator$ValidityCachingStateMachine$class.$init$(FlipbookIterator.scala:171)
	at is.hail.utils.FlipbookIterator$$anon$1.<init>(FlipbookIterator.scala:176)
	at is.hail.utils.FlipbookIterator.staircased(FlipbookIterator.scala:176)
	at is.hail.utils.FlipbookIterator.cogroup(FlipbookIterator.scala:212)
	at is.hail.utils.FlipbookIterator.leftJoinDistinct(FlipbookIterator.scala:281)
	at is.hail.annotations.OrderedRVIterator.leftJoinDistinct(OrderedRVIterator.scala:59)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$6.apply(KeyedOrderedRVD.scala:84)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$6.apply(KeyedOrderedRVD.scala:84)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$orderedJoinDistinct$1.apply(KeyedOrderedRVD.scala:95)
	at is.hail.rvd.KeyedOrderedRVD$$anonfun$orderedJoinDistinct$1.apply(KeyedOrderedRVD.scala:92)
	at is.hail.sparkextras.ContextRDD$$anonfun$czipPartitions$1$$anonfun$apply$26.apply(ContextRDD.scala:355)
	at is.hail.sparkextras.ContextRDD$$anonfun$czipPartitions$1$$anonfun$apply$26.apply(ContextRDD.scala:355)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$22$$anonfun$apply$23.apply(ContextRDD.scala:308)
	at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$22$$anonfun$apply$23.apply(ContextRDD.scala:308)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.rvd.OrderedRVD$$anonfun$apply$16$$anon$3.hasNext(OrderedRVD.scala:923)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at is.hail.utils.package$.getIteratorSizeWithMaxN(package.scala:347)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:442)
	at is.hail.sparkextras.ContextRDD$$anonfun$12.apply(ContextRDD.scala:442)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:469)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:467)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Hail version: devel-5d0f74cef4f2
Error summary: MatchError: [Ljava.lang.String;@7cd5fe91 (of class [Ljava.lang.String;)
```

**Comment by mikelynch** [comment]
I've been looking into why this is happening. The problem is triggered in VEP.scala, line 350 (even though this line succeeds when `csq=False`). The first two calls are successful (i.e. lines 348–349):
```scala
rvb.addAnnotation(vepRowType.types(0), v.asInstanceOf[Row].get(0))
rvb.addAnnotation(vepRowType.types(1), v.asInstanceOf[Row].get(1))
```
but the last one fails:
```scala
rvb.addAnnotation(vepRowType.types(2), vep)
```

In my experiments, `vepRowType` has the value `struct{locus: locus<GRCh37>, alleles: array<str>, vep: array<str>}`. `vep`'s string representation is also `array<str>`, so I'm not sure what's causing the issue.

The exception is actually generated in `RegionValueBuilder.scala`, in the `addAnnotation` method. In the pattern match on type, the `TArray` case is correctly matched on, but neither `UnsafeIndexedSeq` or `IndexedSeq[Annotation]` then match, so we get the `MatchError`. I'm afraid I don't know enough about Hail's type system. Is there a case missing from the `TArray` match, or are the current ones correct and the annotations are being created wrong?

**Comment by tpoterba** [comment]
Hey, I'm sorry to have left this so long! I had just pushed up a branch fixing it when you posted your comment.

**Comment by tpoterba** [comment]
the CSQ mode was totally busted.

**Comment by tpoterba** [comment]
We don't automate VEP tests as part of our deployment, though -- could I ask you to test the fix later today when it goes in?

**Comment by mikelynch** [comment]
Great, thank you! I've just checked out your branch and will do some manual testing this morning and let you know how that goes.

I noticed that the VEP logic didn't have test coverage right now, but had a few ideas for some modest refactoring so unit tests are possible. I'll see if I can get that working!

**Comment by mikelynch** [comment]
Seems to work for me running things manually from the IDE. I can check again with the pre-built distribution when that commits merged into master.
