### ISSUE TITLE
None.get in TableMapRows

### ISSUE THREAD

**Issue by gtiao** [hail-is/hail#3814]
### What you did:

I'm working with a `ht` containing families where one of the fields is an array of strings, e.g.,
```
+----------------+----------------+------------------------------------------+------------+-------------+-------+----------------+
| father_id      | mother_id      | probands                                 | n_probands |      r_prob |   idx | n_cum_probands |
+----------------+----------------+------------------------------------------+------------+-------------+-------+----------------+
| str            | str            | array<str>                               |      int64 |     float64 | int64 |          int64 |
+----------------+----------------+------------------------------------------+------------+-------------+-------+----------------+
| RG1692         | RG1695         | ["RG1655","RG1681","RG1691","RG1706",... |          8 | 1.71331e-01 |     0 |              8 |
| G01-GEA-28-PA  | G01-GEA-28-MA  | ["G01-GEA-28-HI"]                        |          1 | 4.93356e-02 |   867 |            717 |
| DEASD_0210_500 | DEASD_0210_600 | ["DEASD_0210_001"]                       |          1 | 4.93218e-02 |   866 |            716 |

```
Then I do:
```
keep_fams_ht = keep_fams_ht.annotate(relateds=keep_fams_ht.probands.append(keep_fams_ht.mother_id).append(keep_fams_ht.father_id))
relateds = keep_fams_ht.explode(keep_fams_ht.relateds).key_by('relateds').distinct()

```
### What went wrong (all error messages here, including the full java stack trace):
```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-99-84209896ffb7> in <module>()
      1 keep_fams_ht = keep_fams_ht.annotate(relateds=keep_fams_ht.probands.append(keep_fams_ht.mother_id).append(keep_fams_ht.father_id))
----> 2 relateds = keep_fams_ht.explode(keep_fams_ht.relateds).key_by('relateds').distinct()

/home/hail/hail.zip/hail/table.py in distinct(self)
   2607         """
   2608         hail.methods.misc.require_key(self, "distinct")
-> 2609         return Table(self._jt.distinctByKey())
   2610 
   2611 table_type.set(Table)

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/home/hail/hail.zip/hail/utils/java.py in deco(*args, **kwargs)
    182         import pyspark
    183         try:
--> 184             return f(*args, **kwargs)
    185         except py4j.protocol.Py4JJavaError as e:
    186             s = e.java_exception.toString()

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1507.distinctByKey.
: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at is.hail.expr.TableMapRows.execute(Relational.scala:2089)
	at is.hail.expr.TableMapRows.execute(Relational.scala:2064)
	at is.hail.expr.TableExplode.execute(Relational.scala:2166)
	at is.hail.expr.TableUnkey.execute(Relational.scala:1857)
	at is.hail.expr.TableMapRows.execute(Relational.scala:2064)
	at is.hail.expr.TableKeyBy.execute(Relational.scala:1820)
	at is.hail.expr.TableKeyBy.execute(Relational.scala:1820)
	at is.hail.table.Table.value$lzycompute(Table.scala:237)
	at is.hail.table.Table.value(Table.scala:232)
	at is.hail.table.Table.x$5$lzycompute(Table.scala:240)
	at is.hail.table.Table.x$5(Table.scala:240)
	at is.hail.table.Table.rvd$lzycompute(Table.scala:240)
	at is.hail.table.Table.rvd(Table.scala:240)
	at is.hail.table.Table.distinctByKey(Table.scala:593)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tpoterba** [comment]
I don't think this is append, I think this is a problem with distinctByKey.

**Comment by cseed** [comment]
@tpoterba was this resolved by #3828?

**Comment by tpoterba** [comment]
I don't think so. that was just to make it easier to debug when it appeared again.

**Comment by tpoterba** [comment]
Let's close this, my guess is it's been fixed in the 2 months since then.
