### ISSUE TITLE
LD Prune fails on duplicate row keys

### ISSUE THREAD

**Issue by maccum** [hail-is/hail#3835]
### Hail version:

d5007d8878f2dc330dd2f01c1c0251785f259dac

### What you did:

```
ds = hl.import_vcf(resource("sample.vcf"))
ds_duplicate = ds.annotate_rows(duplicate = [1,2])
ds_duplicate = ds_duplicate.explode_rows(ds_duplicate['duplicate'])
result = hl.ld_prune(ds_duplicate.GT)
result.show()
```

### What went wrong (all error messages here, including the full java stack trace):

```
Java stack trace:
java.lang.AssertionError: assertion failed: absoluteUpperIndexBounds length 197 did not match GridPartition nRows 394
	at scala.Predef$.assert(Predef.scala:170)
	at is.hail.methods.UpperIndexBounds$.computeCoverByUpperTriangularBlocks(UpperIndexBounds.scala:69)
	at is.hail.linalg.BlockMatrix.filteredEntriesTable(BlockMatrix.scala:1198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by maccum** [comment]
The quick fix for this is to call `distinct_by_row` inside LD Prune, but I'm not sure if I should throw some kind of warning to the user if there are duplicate row keys? Or should the method fail on a dataset with duplicate row keys?
