### ISSUE TITLE
method readTable does not exist (tutorials)

### ISSUE THREAD

**Issue by jackgoldsmith4** [hail-is/hail#3989]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

Tutorials 05 and 08

### What you did:
(From tutorial 05-tables)

import hail as hl
hl.init()
hl.utils.get_movie_lens('data/')
users = hl.read_table('data/users.ht')

### What went wrong (all error messages here, including the full java stack trace):

Py4JError: An error occurred while calling o1.readTable. Trace:
py4j.Py4JException: Method readTable([class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:272)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tpoterba** [comment]
jar mismatch
