### ISSUE TITLE
Attempting to export NA loci gives bad error message.

### ISSUE THREAD

**Issue by bavila-broad** [hail-is/hail#4011]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
Hail version: devel-eb1e04205793

### What you did:

Attempt to `export_vcf` with a MT where some `locus` values are `NA`.

### What went wrong (all error messages here, including the full java stack trace):

Bad error message. Didn't really tell me anything except Java Assertion Error.

[Stage 2:===========================================>       (1709 + 291) / 2000]Traceback (most recent call last):
  File "/tmp/0eccddcf-0d49-4280-8b79-c43e193b044d/vdstovcf.py", line 12, in <module>
    hail.export_vcf(myvds, 'gs://ibd-exomes/v34meta/exomes.ccdg.vcf.bgz')
  File "/home/hail/hail.zip/hail/typecheck/check.py", line 547, in wrapper
  File "/home/hail/hail.zip/hail/methods/impex.py", line 422, in export_vcf
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/home/hail/hail.zip/hail/utils/java.py", line 196, in deco
hail.utils.java.FatalError: AssertionError: assertion failed

**Comment by bavila-broad** [comment]
https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/Error.20writing.20vcf
