### ISSUE TITLE
Parallel export broken

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#4033]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:

```
ht = hl.import_table('gs://gnomad/annotations/hail-0.2/ht/genomes/score_rankings/gnomad.sites.RF.newStats24.txt.bgz', types={'chrom': hl.tstr}, impute=True, min_partitions=100).cache()
ht.export('gs://gnomad-tmp/genomes_rf.txt.bgz', parallel=True)
```

### What went wrong (all error messages here, including the full java stack trace):
```
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-17-671d2e9c22c8> in <module>()
      1 #ht = hl.import_table('gs://gnomad/annotations/hail-0.2/ht/genomes/score_rankings/gnomad.sites.RF.newStats24.txt.bgz', types={'chrom': hl.tstr}, impute=True, min_partitions=100).cache()
----> 2 ht.export('gs://gnomad-tmp/genomes_rf.txt.bgz', parallel=True)

/home/hail/hail.zip/hail/table.py in export(self, output, types_file, header, parallel)
    994         """
    995 
--> 996         self._jt.export(output, types_file, header, Env.hail().utils.ExportType.getExportType(parallel))
    997 
    998     def group_by(self, *exprs, **named_exprs) -> 'GroupedTable':

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/home/hail/hail.zip/hail/utils/java.py in deco(*args, **kwargs)
    186         import pyspark
    187         try:
--> 188             return f(*args, **kwargs)
    189         except py4j.protocol.Py4JJavaError as e:
    190             s = e.java_exception.toString()

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    321                 raise Py4JError(
    322                     "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
--> 323                     format(target_id, ".", name, value))
    324         else:
    325             raise Py4JError(

Py4JError: An error occurred while calling z:is.hail.utils.ExportType.getExportType. Trace:
py4j.Py4JException: Method getExportType([class java.lang.Boolean]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lfrancioli** [comment]
Works without `parallel=True`

**Comment by jbloom22** [comment]
@lfrancioli see the docs, `parallel` takes a string. The PR adds a typechecker to give a better error message to future you.

**Comment by lfrancioli** [comment]
Thank @jbloom22 ! Hadn't seen that this had change (was `bool` back in the days). And indeed the error message did not put me on the right track :)
