### ISSUE TITLE
export_elasticsearch does not accept config argument

### ISSUE THREAD

**Issue by nawatts** [hail-is/hail#4063]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:

devel-406fc7f6af42

### What you did:

Calling `export_elasticsearch` without a `config` argument works fine.
```python
hl.export_elasticsearch(table, "host", 9200, "someindex", "sometype", 1000, config=None)
```

However, attempting to pass `config`, for example:
```python
es_config = {"es.write.operation": "index"}
hl.export_elasticsearch(table, "host", 9200, "someindex", "sometype", 1000, config=es_config)
```
causes the following error:

### What went wrong (all error messages here, including the full java stack trace):

```
Traceback (most recent call last):
  File "/tmp/0ba8fc2c770d4b2ba96dc23c50fd6eab/load_clinvar_to_es.py", line 105, in <module>
    verbose=True,
  File "/tmp/0ba8fc2c770d4b2ba96dc23c50fd6eab/hail_v02_scripts.zip/hail_v02_scripts/utils/elasticsearch/client.py", line 234, in export_table_to_elasticsearch
  File "/home/hail/hail.zip/hail/typecheck/check.py", line 547, in wrapper
  File "/home/hail/hail.zip/hail/methods/impex.py", line 1885, in export_elasticsearch
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/home/hail/hail.zip/hail/utils/java.py", line 188, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 323, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling z:is.hail.io.ElasticsearchConnector.export. Trace:
py4j.Py4JException: Method export([class is.hail.table.Table, class java.lang.String, class java.lang.Integer, class java.lang.String, class java.lang.String, class java.lang.Integer, class java.util.HashMap, class java.lang.Boolean]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tpoterba** [comment]
Good catch! This is something that's not tested as part of CI, but we should do that (eventually). Will fix this bug, though.
