### ISSUE TITLE
Error when iterating over a set literal

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#4078]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:

```
x = hl.literal(hl.set(['A','B']))
x
Out[5]: <SetExpression of type set<str>>
x.contains('A')
Out[6]: <BooleanExpression of type bool>
x.contains('A').value
```

### What went wrong (all error messages here, including the full java stack trace):

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-21a57f32eefb>", line 1, in <module>
    x.contains('A').value
  File "/Users/laurent/tools/hail/python/hail/expr/expressions/base_expression.py", line 786, in value
    return hl.eval_expr(self)
  File "/Users/laurent/tools/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/Users/laurent/tools/hail/python/hail/expr/expressions/expression_utils.py", line 137, in eval_expr
    return eval_expr_typed(expression)[0]
  File "/Users/laurent/tools/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/Users/laurent/tools/hail/python/hail/expr/expressions/expression_utils.py", line 171, in eval_expr_typed
    return expression.collect()[0], expression.dtype
  File "/Users/laurent/tools/hail/python/hail/expr/expressions/base_expression.py", line 768, in collect
    t = self._to_table(uid)
  File "/Users/laurent/tools/hail/python/hail/expr/expressions/base_expression.py", line 591, in _to_table
    df = df.select(**{name: self})
  File "/Users/laurent/tools/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/Users/laurent/tools/hail/python/hail/table.py", line 893, in select
    return self._select('Table.select', value_struct=hl.struct(**row))
  File "/Users/laurent/tools/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/Users/laurent/tools/hail/python/hail/table.py", line 402, in _select
    base, cleanup = self._process_joins(row)
  File "/Users/laurent/tools/hail/python/hail/table.py", line 1495, in _process_joins
    return process_joins(self, exprs, broadcast_f)
  File "/Users/laurent/tools/hail/python/hail/utils/misc.py", line 365, in process_joins
    data_json = t._to_json(data)
  File "/Users/laurent/tools/hail/python/hail/expr/types.py", line 185, in _to_json
    converted = self._convert_to_json_na(x)
  File "/Users/laurent/tools/hail/python/hail/expr/types.py", line 192, in _convert_to_json_na
    return self._convert_to_json(x)
  File "/Users/laurent/tools/hail/python/hail/expr/types.py", line 802, in _convert_to_json
    return {f: t._convert_to_json_na(x[f]) for f, t in self.items()}
  File "/Users/laurent/tools/hail/python/hail/expr/types.py", line 802, in <dictcomp>
    return {f: t._convert_to_json_na(x[f]) for f, t in self.items()}
  File "/Users/laurent/tools/hail/python/hail/expr/types.py", line 192, in _convert_to_json_na
    return self._convert_to_json(x)
  File "/Users/laurent/tools/hail/python/hail/expr/types.py", line 578, in _convert_to_json
    return [self.element_type._convert_to_json_na(elt) for elt in x]
  File "/Users/laurent/tools/hail/python/hail/expr/expressions/base_expression.py", line 368, in __iter__
    raise TypeError("'Expression' object is not iterable")
TypeError: 'Expression' object is not iterable
```

**Comment by tpoterba** [comment]
Ah, the problem here is using an expression in a literal.

**Comment by lfrancioli** [comment]
of course!!

**Comment by tpoterba** [comment]
still a bad error message. almost done with a fix.

**Comment by tpoterba** [comment]
and really you should be able to do this, and we just evaluate it and stick it in a literal.

**Comment by lfrancioli** [comment]
OK, fair enough :)
