### ISSUE TITLE
Bad error message when using a non-aggregator expr in aggregate 

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#4110]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:

```
ht.group_by('model', 'rank_id', 'bin').aggregate(titv=ht.n_ti/ht.n_tv, 
                                                              min_score=hl.agg.min(ht.min_score),
                                                              max_score=hl.agg.min(ht.max_score)
                                                             ).show()
```
### What went wrong (all error messages here, including the full java stack trace):
```
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-26-65c5654a1482> in <module>()
      1 ht.group_by('model', 'rank_id', 'bin').aggregate(titv=ht.n_ti/ht.n_tv, 
      2                                                               min_score=hl.agg.min(ht.min_score),
----> 3                                                               max_score=hl.agg.min(ht.max_score)
      4                                                              ).show()

/home/hail/gnomad_hail/utils/plotting.py in new_show(t, n, width, truncate, types)
     24 
     25     def new_show(t, n=10, width=170, truncate=40, types=True):
---> 26         old_show(t, n, width, truncate, types)
     27     hl.Table.show = new_show
     28 

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(*args, **kwargs)
    545         def wrapper(*args, **kwargs):
    546             args_, kwargs_ = check_all(f, args, kwargs, checkers, is_method=is_method)
--> 547             return f(*args_, **kwargs_)
    548 
    549         update_wrapper(wrapper, f)

/home/hail/hail.zip/hail/table.py in show(self, n, width, truncate, types)
   1215             Print an extra header line with the type of each field.
   1216         """
-> 1217         print(self._show(n,width, truncate, types))
   1218 
   1219     def _show(self, n=10, width=90, truncate=None, types=True):

/home/hail/hail.zip/hail/table.py in _show(self, n, width, truncate, types)
   1218 
   1219     def _show(self, n=10, width=90, truncate=None, types=True):
-> 1220         return self._jt.showString(n, joption(truncate), types, width)
   1221 
   1222     def index(self, *exprs):

/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/home/hail/hail.zip/hail/utils/java.py in deco(*args, **kwargs)
    198             raise FatalError('%s\n\nJava stack trace:\n%s\n'
    199                              'Hail version: %s\n'
--> 200                              'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
    201         except pyspark.sql.utils.CapturedException as e:
    202             raise FatalError('%s\n\nJava stack trace:\n%s\n'

FatalError: RuntimeException: Cannot find row in Map()

Java stack trace:
is.hail.utils.HailException: Error while typechecking IR:
(MakeStruct
  (titv
    (ApplyBinaryPrimOp FloatingPointDivide
      (GetField n_ti
        (Ref Struct{rank_id:String,snv:Boolean,bi_allelic:Boolean,singleton:Boolean,bin:Int32,min_score:Float64,max_score:Float64,n_ti:Int64,n_tv:Int64,model:String} row))
      (GetField n_tv
        (Ref Struct{rank_id:String,snv:Boolean,bi_allelic:Boolean,singleton:Boolean,bin:Int32,min_score:Float64,max_score:Float64,n_ti:Int64,n_tv:Int64,model:String} row))))
  (min_score
    (GetField `0`
      (In Struct{`0`:Float64,`1`:Float64} 0)))
  (max_score
    (GetField `1`
      (In Struct{`0`:Float64,`1`:Float64} 0))))
	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:11)
	at is.hail.utils.package$.fatal(package.scala:26)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:11)
	at is.hail.expr.ir.Emit$.emit(Emit.scala:42)
	at is.hail.expr.ir.Emit$.apply(Emit.scala:28)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:51)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:31)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:74)
	at is.hail.expr.ir.TableKeyByAndAggregate.execute(TableIR.scala:843)
	at is.hail.table.Table.value$lzycompute(Table.scala:215)
	at is.hail.table.Table.value(Table.scala:213)
	at is.hail.table.Table.x$5$lzycompute(Table.scala:218)
	at is.hail.table.Table.x$5(Table.scala:218)
	at is.hail.table.Table.rvd$lzycompute(Table.scala:218)
	at is.hail.table.Table.rvd(Table.scala:218)
	at is.hail.table.Table.take(Table.scala:649)
	at is.hail.table.Table.showString(Table.scala:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)java.lang.RuntimeException: Cannot find row in Map()
	at is.hail.expr.ir.Env$$anonfun$lookup$1.apply(Env.scala:15)
	at is.hail.expr.ir.Env$$anonfun$lookup$1.apply(Env.scala:15)
	at scala.Option.getOrElse(Option.scala:121)
	at is.hail.expr.ir.Env.lookup(Env.scala:15)
	at is.hail.expr.ir.Env.lookup(Env.scala:22)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:53)
	at is.hail.expr.ir.TypeCheck$.is$hail$expr$ir$TypeCheck$$check$1(TypeCheck.scala:17)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:198)
	at is.hail.expr.ir.TypeCheck$.is$hail$expr$ir$TypeCheck$$check$1(TypeCheck.scala:17)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:56)
	at is.hail.expr.ir.TypeCheck$.is$hail$expr$ir$TypeCheck$$check$1(TypeCheck.scala:17)
	at is.hail.expr.ir.TypeCheck$$anonfun$apply$18.apply(TypeCheck.scala:174)
	at is.hail.expr.ir.TypeCheck$$anonfun$apply$18.apply(TypeCheck.scala:174)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:174)
	at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:9)
	at is.hail.expr.ir.Emit$.emit(Emit.scala:42)
	at is.hail.expr.ir.Emit$.apply(Emit.scala:28)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:51)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:31)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:74)
	at is.hail.expr.ir.TableKeyByAndAggregate.execute(TableIR.scala:843)
	at is.hail.table.Table.value$lzycompute(Table.scala:215)
	at is.hail.table.Table.value(Table.scala:213)
	at is.hail.table.Table.x$5$lzycompute(Table.scala:218)
	at is.hail.table.Table.x$5(Table.scala:218)
	at is.hail.table.Table.rvd$lzycompute(Table.scala:218)
	at is.hail.table.Table.rvd(Table.scala:218)
	at is.hail.table.Table.take(Table.scala:649)
	at is.hail.table.Table.showString(Table.scala:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)


Hail version: devel-f2b0dca9f506
Error summary: RuntimeException: Cannot find row in Map()
```

**Comment by tpoterba** [comment]
this is a python error, with analyze probably

**Comment by tpoterba** [comment]
or we need to call analyze, I mean
