### ISSUE TITLE
Requiredness mismatch throws error

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4127]
Not getting a lot of info on the traceback except that it's on write. A version or two back works fine:
```
Traceback (most recent call last):
  File "/tmp/d30041623ee542dca820faecd29538a9/pyscripts_tyqA4p.zip/gnomad_hail/utils/slack.py", line 95, in try_slack
    func(*args)
  File "/tmp/d30041623ee542dca820faecd29538a9/generate_frequency_data.py", line 155, in main
    write_temp_gcs(ht, annotations_ht_path(data_type, location), args.overwrite)
  File "/tmp/d30041623ee542dca820faecd29538a9/pyscripts_tyqA4p.zip/gnomad_hail/utils/generic.py", line 36, in write_temp_gcs
    t.write(temp_path, overwrite=True)
  File "/tmp/d30041623ee542dca820faecd29538a9/hail-devel-cb98819b64ad.zip/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/tmp/d30041623ee542dca820faecd29538a9/hail-devel-cb98819b64ad.zip/hail/table.py", line 1183, in write
    self._jt.write(output, overwrite, stage_locally, _codec_spec)
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/tmp/d30041623ee542dca820faecd29538a9/hail-devel-cb98819b64ad.zip/hail/utils/java.py", line 200, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: AssertionError: assertion failed: type mismatch:
  name: global
  actual: +Struct{}
  expect: Struct{}

Java stack trace:
java.lang.AssertionError: assertion failed: type mismatch:
  name: global
  actual: +Struct{}
  expect: Struct{}
    at scala.Predef$.assert(Predef.scala:170)
    at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:55)
    at is.hail.expr.ir.TypeCheck$.is$hail$expr$ir$TypeCheck$$check$1(TypeCheck.scala:17)
    at is.hail.expr.ir.TypeCheck$.apply(TypeCheck.scala:186)
    at is.hail.expr.ir.Interpret$.apply(Interpret.scala:39)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1636)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapRows.execute(MatrixIR.scala:1147)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapCols.execute(MatrixIR.scala:1364)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapCols.execute(MatrixIR.scala:1364)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixAggregateColsByKey.execute(MatrixIR.scala:839)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixMapRows.execute(MatrixIR.scala:1147)
    at is.hail.expr.ir.MatrixMapGlobals.execute(MatrixIR.scala:1634)
    at is.hail.expr.ir.MatrixRowsTable.execute(TableIR.scala:763)
    at is.hail.expr.ir.Interpret$.apply(Interpret.scala:603)
    at is.hail.expr.ir.Interpret$.apply(Interpret.scala:48)
    at is.hail.expr.ir.Interpret$.apply(Interpret.scala:23)
    at is.hail.table.Table.write(Table.scala:604)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:280)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:214)
    at java.lang.Thread.run(Thread.java:748)

Hail version: devel-cb98819b64ad
Error summary: AssertionError: assertion failed: type mismatch:
  name: global
  actual: +Struct{}
  expect: Struct{}
```

**Comment by tpoterba** [comment]
need the hail.log

**Comment by tpoterba** [comment]
I won't be able to replicate this on current master, because really it's the result of a bug on the version used to write the file -- top-level structs like `globals` shouldn't be required.

**Comment by konradjk** [comment]
Sounds like there's a minor backwards-incompatible change. `mt = mt.annotate_globals()` seems to be the workaround, and hopefully should not crop up again. Will re-open if I find any other issues.
