### ISSUE TITLE
handle missingness correctly for arrays in user interface

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4134]
Example that currently fails:

```
>>> mt = hl.import_vcf('sample.vcf')
>>> mt.annotate_entries(PL = hl.cond(mt.DP > 20, mt.PL, hl.map(lambda x: x, mt.PL)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cotton/hail/python/hail/matrixtable.py", line 975, in annotate_entries
    return self._select_entries(caller, s=self.entry.annotate(**e))
  File "/home/cotton/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/home/cotton/hail/python/hail/matrixtable.py", line 2887, in _select_entries
    return cleanup(MatrixTable(base._jvds.selectEntries(str(s._ir))))
  File "/home/cotton/opt/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/home/cotton/hail/python/hail/utils/java.py", line 212, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: AssertionError: assertion failed: mismatch:
  array<int32>
  array<int32>
  ApplyComparisonOp(GT(int32,int32),GetField(ArrayRef(GetField(Ref(va,struct{locus: locus<GRCh37>, alleles: array<str>, rsid: str, qual: float64, filters: set<str>, info: struct{NEGATIVE_TRAIN_SITE: bool, HWP: float64, AC: array<int32>, culprit: str, MQ0: int32, ReadPosRankSum: float64, AN: int32, InbreedingCoeff: float64, AF: array<float64>, GQ_STDDEV: float64, FS: float64, DP: int32, GQ_MEAN: float64, POSITIVE_TRAIN_SITE: bool, VQSLOD: float64, ClippingRankSum: float64, BaseQRankSum: float64, MLEAF: array<float64>, MLEAC: array<int32>, MQ: float64, QD: float64, END: int32, DB: bool, HaplotypeScore: float64, MQRankSum: float64, CCC: int32, NCC: int32, DS: bool}, `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`: array<struct{GT: call, AD: array<int32>, DP: int32, GQ: int32, PL: array<int32>}>}),the entries! [877f12a8827e18f61222c6c8c5fb04a8]),Ref(i,int32)),DP),I32(20))

Java stack trace:
java.lang.AssertionError: assertion failed: mismatch:
  array<int32>
  array<int32>
  ApplyComparisonOp(GT(int32,int32),GetField(ArrayRef(GetField(Ref(va,struct{locus: locus<GRCh37>, alleles: array<str>, rsid: str, qual: float64, filters: set<str>, info: struct{NEGATIVE_TRAIN_SITE: bool, HWP: float64, AC: array<int32>, culprit: str, MQ0: int32, ReadPosRankSum: float64, AN: int32, InbreedingCoeff: float64, AF: array<float64>, GQ_STDDEV: float64, FS: float64, DP: int32, GQ_MEAN: float64, POSITIVE_TRAIN_SITE: bool, VQSLOD: float64, ClippingRankSum: float64, BaseQRankSum: float64, MLEAF: array<float64>, MLEAC: array<int32>, MQ: float64, QD: float64, END: int32, DB: bool, HaplotypeScore: float64, MQRankSum: float64, CCC: int32, NCC: int32, DS: bool}, `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`: array<struct{GT: call, AD: array<int32>, DP: int32, GQ: int32, PL: array<int32>}>}),the entries! [877f12a8827e18f61222c6c8c5fb04a8]),Ref(i,int32)),DP),I32(20))
	at scala.Predef$.assert(Predef.scala:170)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:10)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.If.typ(IR.scala:77)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:63)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:59)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:59)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.InsertFields.typ(IR.scala:154)
	at is.hail.expr.ir.InsertFields.typ(IR.scala:153)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:39)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.ArrayMap.typ(IR.scala:101)
	at is.hail.expr.ir.ArrayMap.typ(IR.scala:100)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:63)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:59)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:59)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.InsertFields.typ(IR.scala:154)
	at is.hail.expr.ir.MatrixMapEntries.<init>(MatrixIR.scala:1075)
	at is.hail.variant.MatrixTable.selectEntries(MatrixTable.scala:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-0eb009391fd5
Error summary: AssertionError: assertion failed: mismatch:
  array<int32>
  array<int32>
  ApplyComparisonOp(GT(int32,int32),GetField(ArrayRef(GetField(Ref(va,struct{locus: locus<GRCh37>, alleles: array<str>, rsid: str, qual: float64, filters: set<str>, info: struct{NEGATIVE_TRAIN_SITE: bool, HWP: float64, AC: array<int32>, culprit: str, MQ0: int32, ReadPosRankSum: float64, AN: int32, InbreedingCoeff: float64, AF: array<float64>, GQ_STDDEV: float64, FS: float64, DP: int32, GQ_MEAN: float64, POSITIVE_TRAIN_SITE: bool, VQSLOD: float64, ClippingRankSum: float64, BaseQRankSum: float64, MLEAF: array<float64>, MLEAC: array<int32>, MQ: float64, QD: float64, END: int32, DB: bool, HaplotypeScore: float64, MQRankSum: float64, CCC: int32, NCC: int32, DS: bool}, `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`: array<struct{GT: call, AD: array<int32>, DP: int32, GQ: int32, PL: array<int32>}>}),the entries! [877f12a8827e18f61222c6c8c5fb04a8]),Ref(i,int32)),DP),I32(20))
```

**Comment by tpoterba** [comment]
that needs to have parsableType on it

**Comment by cseed** [comment]
This will be fixed by physical types.

**Comment by cseed** [comment]
Agreed, I will PR.
