### ISSUE TITLE
IllegalArgumentException on outer join

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4216]
`ht = ht.join(possible_ht, 'outer')`
gave:
```
Java stack trace:
java.lang.IllegalArgumentException: requirement failed
    at scala.Predef$.require(Predef.scala:212)
    at is.hail.rvd.OrderedRVD.<init>(OrderedRVD.scala:37)
    at is.hail.rvd.KeyedOrderedRVD.orderedJoin(KeyedOrderedRVD.scala:38)
    at is.hail.rvd.OrderedRVD.orderedJoin(OrderedRVD.scala:283)
    at is.hail.expr.ir.TableJoin.execute(TableIR.scala:436)
    at is.hail.expr.ir.TableMapGlobals.execute(TableIR.scala:652)
    at is.hail.expr.ir.TableMapRows.execute(TableIR.scala:495)
    at is.hail.expr.ir.TableMapGlobals.execute(TableIR.scala:652)
    at is.hail.expr.ir.TableMapGlobals.execute(TableIR.scala:652)
    at is.hail.expr.ir.TableMapRows.execute(TableIR.scala:495)
    at is.hail.expr.ir.TableMapGlobals.execute(TableIR.scala:652)
    at is.hail.expr.ir.Interpret$.apply(Interpret.scala:591)
    at is.hail.expr.ir.Interpret$.apply(Interpret.scala:49)
    at is.hail.expr.ir.Interpret$.apply(Interpret.scala:24)
    at is.hail.table.Table.write(Table.scala:606)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:280)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:214)
    at java.lang.Thread.run(Thread.java:748)

Hail version: devel-02b7ad0299d7
Error summary: IllegalArgumentException: requirement failed
```

**Comment by konradjk** [comment]
Actually looks like just a bad error message. One of the Tables had 0 rows.

**Comment by tpoterba** [comment]
can you explain? An outer join with 0 rows shouldn't fail.

**Comment by tpoterba** [comment]
any join with 0 rows shouldn't fail.

**Comment by konradjk** [comment]
it was failing on an assertion of num_partitions and i think a table with 0 rows has 0 partitions

**Comment by konradjk** [comment]
but i suppose you're right - outer join with 0 rows is odd (warning might be nice) but probably shouldn't fail

**Comment by patrick-schultz** [comment]
@konradjk Any chance you could retry this? Things have changed a lot since this commit. I think I see what the bug was, and it shouldn't be an issue anymore.

**Comment by konradjk** [comment]
Uhh, well it was a bug in my code to begin with, which I've fixed. Not sure I can reproduce the exact environment

**Comment by patrick-schultz** [comment]
Well this works now, so I'm pretty sure the bug is fixed:
```python
t1 = hl.utils.range_table(10, n_partitions=2)
t2 = hl.Table.parallelize(hl.literal([], 'array<struct{idx: int}>'), key='idx', n_partitions=0)
t1.join(t2, 'outer')
```
