### ISSUE TITLE
bad error message on export_vcf

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4283]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
`devel-17d79be1221e`
### What you did:
```
import hail as hl

mt = hl.balding_nichols_model(3, 100, 100)
hl.export_vcf(mt, 'foo.vcf.bgz')
```
### What went wrong (all error messages here, including the full java stack trace):
```
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    hl.export_vcf(mt, 'foo.vcf.bgz')
  File "<decorator-gen-878>", line 2, in export_vcf
  File "/Users/dking/projects/hail/python/hail/typecheck/check.py", line 546, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/dking/projects/hail/python/hail/methods/impex.py", line 424, in export_vcf
    joption(typ._convert_to_j(metadata)))
  File "/Users/dking/borg/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/Users/dking/projects/hail/python/hail/utils/java.py", line 210, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: HailException: in export_vcf: column key must be type 'str', found: [Lis.hail.expr.types.Type;@1e5a1972

Java stack trace:
is.hail.utils.HailException: in export_vcf: column key must be type 'str', found: [Lis.hail.expr.types.Type;@1e5a1972
	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:9)
	at is.hail.utils.package$.fatal(package.scala:26)
	at is.hail.variant.MatrixTable.requireColKeyString(MatrixTable.scala:392)
	at is.hail.io.vcf.ExportVCF$.apply(ExportVCF.scala:202)
	at is.hail.io.vcf.ExportVCF.apply(ExportVCF.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

Hail version: devel-17d79be1221e
Error summary: HailException: in export_vcf: column key must be type 'str', found: [Lis.hail.expr.types.Type;@1e5a1972

``

**Comment by tpoterba** [comment]
fixed, I think
