### ISSUE TITLE
Table.flatten is broken

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4286]
```python
hl.utils.range_table(10).key_by(x = hl.struct(a=1, b=2)).flatten().count()

Java stack trace:
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at is.hail.expr.ir.TableMapRows.<init>(TableIR.scala:546)
	at is.hail.table.Table.select(Table.scala:448)
	at is.hail.table.Table.flatten(Table.scala:565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

Assigned patrick because this might be fixed by things he is working on

**Comment by patrick-schultz** [comment]
... and because it's very likely I broke it.

**Comment by tpoterba** [comment]
I believe this is related to Danfeng's issue as well: https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/subject/to_pandas.20illegal.20argument.20exception/near/133517502

**Comment by tpoterba** [comment]
We should be able to do this with expandTypes as well

**Comment by tpoterba** [comment]
ah okay here's her bug:
```python
hl.utils.range_table(10).key_by(x = hl.locus('1', 1000)).expand_types().count()
```

```
Java stack trace:
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at is.hail.rvd.OrderedRVD.<init>(OrderedRVD.scala:39)
	at is.hail.rvd.OrderedRVD$.apply(OrderedRVD.scala:1093)
	at is.hail.rvd.OrderedRVD.copy(OrderedRVD.scala:361)
	at is.hail.table.Table.expandTypes(Table.scala:537)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
```
