### ISSUE TITLE
NPE on keyby

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4314]
```
hail.utils.java.FatalError: NullPointerException: null

Java stack trace:
java.lang.NullPointerException: null
    at scala.collection.convert.Wrappers$JListWrapper.length(Wrappers.scala:86)
    at scala.collection.SeqLike$class.size(SeqLike.scala:106)
    at scala.collection.AbstractSeq.size(Seq.scala:41)
    at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:285)
    at scala.collection.AbstractTraversable.toArray(Traversable.scala:104)
    at is.hail.utils.richUtils.RichIterable.toFastIndexedSeq(RichIterable.scala:83)
    at is.hail.table.Table.keyBy(Table.scala:419)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:280)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:214)
    at java.lang.Thread.run(Thread.java:748)
```
Pipeline's a lot of steps but fairly simple:
```
    keys = ('transcript', 'gene', 'canonical')
    po_ht = po_ht.repartition(n_partitions).persist()

    # Getting classic LoF annotations (no LOFTEE)
    classic_lof_annotations = hl.literal({'stop_gained', 'splice_donor_variant', 'splice_acceptor_variant'})
    lof_ht_classic = po_ht.filter(classic_lof_annotations.contains(po_ht.annotation) &
                                  ((po_ht.modifier == 'HC') | (po_ht.modifier == 'LC')))
    lof_ht_classic = collapse_lof_ht(lof_ht_classic, keys)
    lof_ht_classic = lof_ht_classic.rename({x: f'{x}_classic' for x in list(lof_ht_classic.row_value)})

    # Getting classic LoF annotations (with LOFTEE)
    lof_ht_classic_hc = po_ht.filter(classic_lof_annotations.contains(po_ht.annotation) & (po_ht.modifier == 'HC'))
    lof_ht_classic_hc = collapse_lof_ht(lof_ht_classic_hc, keys)
    lof_ht_classic_hc = lof_ht_classic_hc.rename({x: f'{x}_classic_hc' for x in list(lof_ht_classic_hc.row_value)})

    # Getting all LoF annotations (LOFTEE HC + new splice variants)
    lof_ht = po_ht.filter(po_ht.modifier == 'HC')
    po_ht = po_ht.drop('possible_variants', 'adjusted_mutation_rate', 'obs_exp')
    lof_ht = collapse_lof_ht(lof_ht, keys)
    lof_ht = lof_ht.annotate(**oe_confidence_interval(lof_ht, lof_ht.obs_lof, lof_ht.exp_lof)[lof_ht.key])

    mis_ht = po_ht.filter(po_ht.annotation == 'missense_variant')
    mis_ht = mis_ht.group_by(*keys).aggregate(obs_mis=hl.agg.sum(mis_ht.variant_count),
                                              exp_mis=hl.agg.sum(mis_ht.expected_variants),
                                              oe_mis=hl.agg.sum(mis_ht.variant_count) / hl.agg.sum(mis_ht.expected_variants)
                                              )

    pphen_mis_ht = po_ht.filter(po_ht.modifier == 'probably_damaging').key_by(*keys).drop('modifier', 'annotation')
    pphen_mis_ht = pphen_mis_ht.transmute(obs_mis_pphen=pphen_mis_ht.variant_count,
                                          exp_mis_pphen=pphen_mis_ht.expected_variants,
                                          oe_mis_pphen=pphen_mis_ht.variant_count / pphen_mis_ht.expected_variants)

    syn_ht = po_ht.filter((po_ht.annotation == 'synonymous_variant') & (po_ht.modifier == 'None')).key_by(*keys).drop('modifier', 'annotation')
    syn_ht = syn_ht.transmute(obs_syn=syn_ht.variant_count, exp_syn=syn_ht.expected_variants,
                              oe_mis_syn=syn_ht.variant_count / syn_ht.expected_variants)

    ht = lof_ht_classic.annotate(**mis_ht[lof_ht_classic.key], **pphen_mis_ht[lof_ht_classic.key],
                                 **syn_ht[lof_ht_classic.key], **lof_ht[lof_ht_classic.key],
                                 **lof_ht_classic_hc[lof_ht_classic.key])
    ht = ht.annotate(**oe_confidence_interval(ht, ht.obs_lof_classic_hc, ht.exp_lof_classic_hc,
                                              prefix='oe_classic_hc')[ht.key])
    return ht.annotate(**oe_confidence_interval(ht, ht.obs_lof, ht.exp_lof)[ht.key])
```

**Comment by konradjk** [comment]
NB: this worked a week or two ago

**Comment by konradjk** [comment]
Just hit it again on another pipeline that has some `.key_by`s - this is now a showstopper ☹️

**Comment by tpoterba** [comment]
looks like a keyBy(None) is getting into Scala somehow

**Comment by patrick-schultz** [comment]
@konradjk do you have the Python stack trace from one of these?

**Comment by konradjk** [comment]
not the same one but:
```
Traceback (most recent call last):
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/constraint.py", line 126, in <module>
    try_slack(args.slack_channel, main, args)
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/pyscripts_Zf07i2.zip/gnomad_hail/utils/slack.py", line 112, in try_slack
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/pyscripts_Zf07i2.zip/gnomad_hail/utils/slack.py", line 95, in try_slack
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/constraint.py", line 36, in main
    recalculate_all_possible_summary=True, remove_common_downsampled=False, remove_common_ordinary=True)
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/pyscripts_Zf07i2.zip/constraint_utils/constraint_basics.py", line 263, in calculate_mu_by_downsampling
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/pyscripts_Zf07i2.zip/constraint_utils/constraint_basics.py", line 41, in get_old_mu_data
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/hail-devel-17a988f2a628.zip/hail/table.py", line 772, in transmute
  File "<decorator-gen-648>", line 2, in _select
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/hail-devel-17a988f2a628.zip/hail/typecheck/check.py", line 546, in wrapper
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/hail-devel-17a988f2a628.zip/hail/table.py", line 438, in _select
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/hail-devel-17a988f2a628.zip/hail/table.py", line 447, in _select_scala
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/tmp/c38a09976d3c40abbc33f88f4fd39639/hail-devel-17a988f2a628.zip/hail/utils/java.py", line 210, in deco
hail.utils.java.FatalError: NullPointerException: null

Java stack trace:
java.lang.NullPointerException: null
	at scala.collection.convert.Wrappers$JListWrapper.length(Wrappers.scala:86)
	at scala.collection.SeqLike$class.size(SeqLike.scala:106)
	at scala.collection.AbstractSeq.size(Seq.scala:41)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:285)
	at scala.collection.AbstractTraversable.toArray(Traversable.scala:104)
	at is.hail.utils.richUtils.RichIterable.toFastIndexedSeq(RichIterable.scala:83)
	at is.hail.table.Table.select(Table.scala:436)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by konradjk** [comment]
oh whoa

**Comment by konradjk** [comment]
that one is simple:
```
def get_old_mu_data() -> hl.Table:
    old_mu_data = hl.import_table('gs://gnomad-resources/constraint/source/fordist_1KG_mutation_rate_table.txt',
                                  delimiter=' ', impute=True)
    return old_mu_data.transmute(context=old_mu_data['from'], ref=old_mu_data['from'][1],
                                 alt=old_mu_data.to[1]).key_by('context', 'ref', 'alt')
```

**Comment by konradjk** [comment]
i import with no key to start

**Comment by patrick-schultz** [comment]
I'd guess this would probably fix it: add
```python
elif new_keys is None:
    new_key = preserved_key = preserved_key_new = []
```
after the `if new_keys == "default":` in `Table._select`
Could you check when you have a chance?

**Comment by patrick-schultz** [comment]
Wait, nevermind

**Comment by patrick-schultz** [comment]
Could you try this on current master? #4285 made a change that might resolve this.

**Comment by konradjk** [comment]
Can confirm fixed in master. Byeeeee
