### ISSUE TITLE
Lots of aggregators breaks down

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4516]
I mean, I didn't really need to do 3751 aggregators, but just seemed like it might be fun. Instead, got:
```
FatalError: RuntimeException: Class file too large!

Java stack trace:
java.lang.RuntimeException: Class file too large!
	at is.hail.relocated.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at is.hail.asm4s.FunctionBuilder.classAsBytes(FunctionBuilder.scala:305)
	at is.hail.expr.ir.EmitFunctionBuilder.resultWithIndex(EmitFunctionBuilder.scala:337)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:53)
	at is.hail.expr.ir.Compile$.apply(Compile.scala:31)
	at is.hail.expr.ir.CompileWithAggregators$$anonfun$3.apply(Compile.scala:194)
	at is.hail.expr.ir.CompileWithAggregators$$anonfun$3.apply(Compile.scala:194)
	at is.hail.expr.ir.CompileWithAggregators$.apply(Compile.scala:219)
	at is.hail.expr.ir.CompileWithAggregators$.apply(Compile.scala:249)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:618)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:50)
	at is.hail.table.Table.aggregate(Table.scala:373)
	at is.hail.table.Table.aggregate(Table.scala:369)
	at is.hail.table.Table.aggregateJSON(Table.scala:364)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-414f3f183bd5
Error summary: RuntimeException: Class file too large!
```
Code was:
```
cutoff = 10

agg_expr = {
    'downsampling': hl.agg.collect(ht.downsamplings)[0]
}
locations = list(zip(('syn', 'mis', 'lof'), ('', '', '_classic_hc')))
agg_expr.update({
    f'median_expected_{var}_{pop}': [hl.median(hl.agg.collect(ht[f'exp_{var}_{pop}{var_loc}'][i])) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
agg_expr.update({
    f'median_observed_{var}_{pop}': [hl.median(hl.agg.collect(ht[f'obs_{var}_{pop}{var_loc}'][i])) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
agg_expr.update({
    f'mean_expected_{var}_{pop}': [hl.agg.mean(ht[f'exp_{var}_{pop}{var_loc}'][i]) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
agg_expr.update({
    f'mean_observed_{var}_{pop}': [hl.agg.mean(ht[f'obs_{var}_{pop}{var_loc}'][i]) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
agg_expr.update({
    f'fraction_expected_{var}_{pop}': [hl.agg.fraction(ht[f'exp_{var}_{pop}{var_loc}'][i] > cutoff) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
agg_expr.update({
    f'fraction_observed_{var}_{pop}': [hl.agg.fraction(ht[f'obs_{var}_{pop}{var_loc}'][i] > cutoff) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
agg_expr.update({
    f'fraction_missing_expected_{var}_{pop}': [1 - hl.agg.fraction(ht[f'exp_{var}_{pop}{var_loc}'][i] > cutoff) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
agg_expr.update({
    f'fraction_missing_observed_{var}_{pop}': [1 - hl.agg.fraction(ht[f'obs_{var}_{pop}{var_loc}'][i] > cutoff) for i in range(length)]
    for length, pop in pop_lengths
    for var, var_loc in locations
})
high = 40
step = 20
for length, pop in pop_lengths:
    for var, var_loc in locations:
        exp_hist = []
        obs_hist = []
        for i in range(length):
            data = hl.agg.hist(ht[f'exp_{var}_{pop}{var_loc}'][i], 0, high, step)
            exp_hist.append(data.bin_freq.append(data.n_larger))
            data = hl.agg.hist(ht[f'obs_{var}_{pop}{var_loc}'][i], 0, high, step)
            obs_hist.append(data.bin_freq.append(data.n_larger))
        agg_expr[f'hist_expected_{var}_{pop}'] = exp_hist
        agg_expr[f'hist_observed_{var}_{pop}'] = obs_hist
ds = ht.aggregate(hl.struct(**agg_expr))
```

**Comment by konradjk** [comment]
Is there a benchmark test for this?
