### ISSUE TITLE
CI cannot test itself if batch is still running

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4531]
404s occur in `hail-ci-build.sh` because batch is already bound to port 5000 when CI tries to start.

https://storage.googleapis.com/hail-ci-0-1/ci/7aa524504b8bafe0a4af859e73bc4f9efdaa052c/39a94649482a2512a7a514e6084c5b84f48b8205/index.html

The error from `ci.py`:
```
Traceback (most recent call last):
  File "ci/ci.py", line 372, in <module>
    app.run(host='0.0.0.0', threaded=False)
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/site-packages/werkzeug/serving.py", line 666, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/site-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/socketserver.py", line 449, in __init__
    self.server_bind()
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/hail/.conda/envs/hail-ci/lib/python3.7/socketserver.py", line 463, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by danking** [comment]
See more details on #4532 where this was co-reported with an unrelated GitHub issue.
