### ISSUE TITLE
batch created ~30 pods for a single job during a k8s state refresh

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4608]
I saw this happen to the job that was supposed to be running the deploy-svc PR.

**Comment by danking** [comment]
[batch.log](https://github.com/hail-is/hail/files/2504453/batch.log)

Here's a snippet:
```
INFO    | 2018-10-23 03:27:48,536       | server.py     | mark_complete:184 | job 151 complete, exit_code 2
INFO    | 2018-10-23 03:27:48,541       | _internal.py  | _log:88 | 127.0.0.1 - - [23/Oct/2018 03:27:48] "POST /pod_changed HTTP/1.1" 204 -
...skipping...
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=120)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/batch/server.py", line 417, in run_forever
    target(*args, **kwargs)
  File "/batch/server.py", line 441, in kube_event_loop
    requests.post('http://127.0.0.1:5000/pod_changed', json={'pod_name': name}, timeout=120)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=120)
INFO    | 2018-10-23 03:58:08,124       | server.py     | run_forever:416 | run_forever: run target kube_event_loop
INFO    | 2018-10-23 03:59:30,729       | server.py     | mark_complete:175 | wrote log for job 153 to logs/job-153.log
INFO    | 2018-10-23 03:59:30,730       | server.py     | set_state:141 | job 153 changed state: Created -> Complete
INFO    | 2018-10-23 03:59:30,730       | server.py     | mark_complete:184 | job 153 complete, exit_code 2
INFO    | 2018-10-23 03:59:30,737       | _internal.py  | _log:88 | 127.0.0.1 - - [23/Oct/2018 03:59:30] "POST /pod_changed HTTP/1.1" 204 -
INFO    | 2018-10-23 03:59:30,806       | _internal.py  | _log:88 | 10.56.142.33 - - [23/Oct/2018 03:59:30] "GET /jobs HTTP/1.1" 200 -
INFO    | 2018-10-23 03:59:30,815       | _internal.py  | _log:88 | 127.0.0.1 - - [23/Oct/2018 03:59:30] "POST /pod_changed HTTP/1.1" 204 -
INFO    | 2018-10-23 03:59:30,816       | _internal.py  | _log:88 | 127.0.0.1 - - [23/Oct/2018 03:59:30] "POST /pod_changed HTTP/1.1" 204 -
INFO    | 2018-10-23 03:59:30,817       | server.py     | refresh_k8s_state:385 | started k8s state refresh
INFO    | 2018-10-23 03:59:31,183       | server.py     | _create_pod:80 | created pod name: job-99-f4gwv for job 99
INFO    | 2018-10-23 03:59:31,191       | server.py     | _create_pod:80 | created pod name: job-150-h6snc for job 150
INFO    | 2018-10-23 03:59:31,202       | server.py     | _create_pod:80 | created pod name: job-99-xbc7z for job 99
INFO    | 2018-10-23 03:59:31,209       | server.py     | _create_pod:80 | created pod name: job-150-fhpqn for job 150
INFO    | 2018-10-23 03:59:31,220       | server.py     | _create_pod:80 | created pod name: job-99-tfb2w for job 99
INFO    | 2018-10-23 03:59:31,231       | server.py     | _create_pod:80 | created pod name: job-150-pntb2 for job 150
INFO    | 2018-10-23 03:59:31,246       | server.py     | _create_pod:80 | created pod name: job-99-5bswd for job 99
INFO    | 2018-10-23 03:59:31,253       | server.py     | _create_pod:80 | created pod name: job-150-jlpnt for job 150
INFO    | 2018-10-23 03:59:31,261       | server.py     | _create_pod:80 | created pod name: job-99-vll64 for job 99
INFO    | 2018-10-23 03:59:31,269       | server.py     | _create_pod:80 | created pod name: job-150-sb5hd for job 150
INFO    | 2018-10-23 03:59:31,276       | server.py     | _create_pod:80 | created pod name: job-99-ncz59 for job 99
INFO    | 2018-10-23 03:59:31,284       | server.py     | _create_pod:80 | created pod name: job-150-m2psg for job 150
INFO    | 2018-10-23 03:59:31,292       | server.py     | _create_pod:80 | created pod name: job-99-v26dg for job 99
INFO    | 2018-10-23 03:59:31,302       | server.py     | _create_pod:80 | created pod name: job-150-fpvj2 for job 150
INFO    | 2018-10-23 03:59:31,310       | server.py     | _create_pod:80 | created pod name: job-99-dk82m for job 99
INFO    | 2018-10-23 03:59:31,318       | server.py     | _create_pod:80 | created pod name: job-150-hz66n for job 150
INFO    | 2018-10-23 03:59:31,325       | server.py     | _create_pod:80 | created pod name: job-99-9gx4s for job 99
INFO    | 2018-10-23 03:59:31,334       | server.py     | _create_pod:80 | created pod name: job-150-7hkcs for job 150
INFO    | 2018-10-23 03:59:31,343       | server.py     | _create_pod:80 | created pod name: job-99-j2pgl for job 99
INFO    | 2018-10-23 03:59:31,353       | server.py     | _create_pod:80 | created pod name: job-150-z89rg for job 150
INFO    | 2018-10-23 03:59:31,360       | server.py     | _create_pod:80 | created pod name: job-99-6zh45 for job 99
INFO    | 2018-10-23 03:59:31,370       | server.py     | _create_pod:80 | created pod name: job-150-tvgbp for job 150
INFO    | 2018-10-23 03:59:31,379       | server.py     | _create_pod:80 | created pod name: job-99-nvqc9 for job 99
INFO    | 2018-10-23 03:59:31,386       | server.py     | _create_pod:80 | created pod name: job-150-g6b99 for job 150
INFO    | 2018-10-23 03:59:31,394       | server.py     | _create_pod:80 | created pod name: job-99-dwrfl for job 99
INFO    | 2018-10-23 03:59:31,401       | server.py     | _create_pod:80 | created pod name: job-150-dmrbb for job 150
INFO    | 2018-10-23 03:59:31,408       | server.py     | _create_pod:80 | created pod name: job-99-tkw49 for job 99
INFO    | 2018-10-23 03:59:31,416       | server.py     | _create_pod:80 | created pod name: job-150-wc8x6 for job 150
INFO    | 2018-10-23 03:59:31,424       | server.py     | _create_pod:80 | created pod name: job-99-btcb2 for job 99
INFO    | 2018-10-23 03:59:31,432       | server.py     | _create_pod:80 | created pod name: job-150-xjsqg for job 150
INFO    | 2018-10-23 03:59:31,445       | server.py     | _create_pod:80 | created pod name: job-99-wzwdh for job 99
INFO    | 2018-10-23 03:59:31,452       | server.py     | _create_pod:80 | created pod name: job-150-7vf4t for job 150
INFO    | 2018-10-23 03:59:31,461       | server.py     | _create_pod:80 | created pod name: job-99-sfs6v for job 99
INFO    | 2018-10-23 03:59:31,472       | server.py     | _create_pod:80 | created pod name: job-150-58qrs for job 150
INFO    | 2018-10-23 03:59:31,479       | server.py     | _create_pod:80 | created pod name: job-99-vtscc for job 99
INFO    | 2018-10-23 03:59:31,489       | server.py     | _create_pod:80 | created pod name: job-150-9xzc4 for job 150
INFO    | 2018-10-23 03:59:31,498       | server.py     | _create_pod:80 | created pod name: job-99-z8rms for job 99
INFO    | 2018-10-23 03:59:31,353       | server.py     | _create_pod:80 | created pod name: job-150-z89rg for job 150
INFO    | 2018-10-23 03:59:31,360       | server.py     | _create_pod:80 | created pod name: job-99-6zh45 for job 99
INFO    | 2018-10-23 03:59:31,370       | server.py     | _create_pod:80 | created pod name: job-150-tvgbp for job 150
INFO    | 2018-10-23 03:59:31,379       | server.py     | _create_pod:80 | created pod name: job-99-nvqc9 for job 99
INFO    | 2018-10-23 03:59:31,386       | server.py     | _create_pod:80 | created pod name: job-150-g6b99 for job 150
INFO    | 2018-10-23 03:59:31,394       | server.py     | _create_pod:80 | created pod name: job-99-dwrfl for job 99
INFO    | 2018-10-23 03:59:31,401       | server.py     | _create_pod:80 | created pod name: job-150-dmrbb for job 150
INFO    | 2018-10-23 03:59:31,408       | server.py     | _create_pod:80 | created pod name: job-99-tkw49 for job 99
INFO    | 2018-10-23 03:59:31,416       | server.py     | _create_pod:80 | created pod name: job-150-wc8x6 for job 150
INFO    | 2018-10-23 03:59:31,424       | server.py     | _create_pod:80 | created pod name: job-99-btcb2 for job 99
INFO    | 2018-10-23 03:59:31,432       | server.py     | _create_pod:80 | created pod name: job-150-xjsqg for job 150
INFO    | 2018-10-23 03:59:31,445       | server.py     | _create_pod:80 | created pod name: job-99-wzwdh for job 99
INFO    | 2018-10-23 03:59:31,452       | server.py     | _create_pod:80 | created pod name: job-150-7vf4t for job 150
INFO    | 2018-10-23 03:59:31,461       | server.py     | _create_pod:80 | created pod name: job-99-sfs6v for job 99
INFO    | 2018-10-23 03:59:31,472       | server.py     | _create_pod:80 | created pod name: job-150-58qrs for job 150
INFO    | 2018-10-23 03:59:31,479       | server.py     | _create_pod:80 | created pod name: job-99-vtscc for job 99
INFO    | 2018-10-23 03:59:31,489       | server.py     | _create_pod:80 | created pod name: job-150-9xzc4 for job 150
INFO    | 2018-10-23 03:59:31,498       | server.py     | _create_pod:80 | created pod name: job-99-z8rms for job 99
INFO    | 2018-10-23 03:59:31,506       | server.py     | _create_pod:80 | created pod name: job-150-g9wxc for job 150
INFO    | 2018-10-23 03:59:31,512       | server.py     | _create_pod:80 | created pod name: job-99-4lmqk for job 99
INFO    | 2018-10-23 03:59:31,521       | server.py     | _create_pod:80 | created pod name: job-150-xdr44 for job 150
INFO    | 2018-10-23 03:59:31,534       | server.py     | _create_pod:80 | created pod name: job-99-b5p7g for job 99
INFO    | 2018-10-23 03:59:31,544       | server.py     | _create_pod:80 | created pod name: job-150-4xp5w for job 150
INFO    | 2018-10-23 03:59:31,553       | server.py     | _create_pod:80 | created pod name: job-99-pprt9 for job 99
INFO    | 2018-10-23 03:59:31,561       | server.py     | _create_pod:80 | created pod name: job-150-hr877 for job 150
INFO    | 2018-10-23 03:59:31,569       | server.py     | _create_pod:80 | created pod name: job-99-wx6j4 for job 99
INFO    | 2018-10-23 03:59:31,581       | server.py     | _create_pod:80 | created pod name: job-150-ckkqc for job 150
INFO    | 2018-10-23 03:59:31,590       | server.py     | _create_pod:80 | created pod name: job-99-9sdnt for job 99
INFO    | 2018-10-23 03:59:31,599       | server.py     | _create_pod:80 | created pod name: job-150-d2jww for job 150
INFO    | 2018-10-23 03:59:31,599       | server.py     | refresh_k8s_state:404 | k8s state refresh complete
INFO    | 2018-10-23 03:59:31,601       | _internal.py  | _log:88 | 127.0.0.1 - - [23/Oct/2018 03:59:31] "POST /refresh_k8s_state HTTP/1.1" 204 -
```

**Comment by danking** [comment]
I restarted batch at 0405 UTC and then CI shortly thereafter and deleted all batch-job pods.

**Comment by danking** [comment]
Happened again
[batch.log](https://github.com/hail-is/hail/files/2635158/batch.log)

**Comment by danking** [comment]
I'll reopen if this issue recurs.

**Comment by johnc1231** [comment]
Out of date
