### ISSUE TITLE
Implement java version checker in hail.init() and fail if wrong version of java installed

### ISSUE THREAD

**Issue by dekinsitro** [hail-is/hail#4896]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

Running on Ubuntu 18.04.  I had installed openjdk-11-jre-headless instead of openjdk-8-jre-headless.

### Hail version:
0.2 
### What went wrong (all error messages here, including the full java stack trace):
2018-12-04 22:13:57 root: ERROR: IllegalArgumentException: null
From java.lang.IllegalArgumentException: null
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:443)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:426)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:426)
        at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:257)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:256)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:256)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:156)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2294)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:794)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:793)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
        at org.apache.spark.rdd.RDD.mapPartitions(RDD.scala:793)
        at is.hail.sparkextras.ContextRDD.cmapPartitions(ContextRDD.scala:351)
        at is.hail.HailContext.readRows(HailContext.scala:629)
        at is.hail.rvd.AbstractRVDSpec.read(AbstractRVDSpec.scala:151)
        at is.hail.variant.RVDComponentSpec.read(MatrixTable.scala:98)
        at is.hail.expr.ir.TableRead.execute(TableIR.scala:78)
        at is.hail.expr.ir.TableHead.execute(TableIR.scala:325)
        at is.hail.expr.ir.Interpret$.apply(Interpret.scala:56)
        at is.hail.table.Table.x$3$lzycompute(Table.scala:216)
        at is.hail.table.Table.x$3(Table.scala:216)
        at is.hail.table.Table.value$lzycompute(Table.scala:216)
        at is.hail.table.Table.value(Table.scala:216)
        at is.hail.table.Table.rdd$lzycompute(Table.scala:220)
        at is.hail.table.Table.rdd(Table.scala:220)
        at is.hail.table.Table.collect(Table.scala:538)
        at is.hail.table.Table.showString(Table.scala:582)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:844)

The problem here is that the message gives zero information on why the python hail code failed.

Please implement a version checker; run the java binary and query its version, and if it's not compatible, raise a python exception with a clear message about which java version is installed and needs to be installed.

**Comment by tpoterba** [comment]
@cseed @danking do we work with java 9 or just java 8?

We have a check, just may need to make it stricter:
https://github.com/hail-is/hail/blob/master/hail/src/main/scala/is/hail/HailContext.scala#L216

**Comment by dekinsitro** [comment]
This failed with OpenJDK 11 installed.  I don't know Scala, but my read of your checker is that it's looking for older versions, not newer ones.  The docs explicitly say java 8 is required.

**Comment by danking** [comment]
@tpoterba We're stuck with 8 [due to spark](https://issues.igniterealtime.org/browse/SPARK-2017). I'll update the check. Thanks for the report @dekinsitro

**Comment by tpoterba** [comment]
I vaguely remember things working on Java 9 when someone joined the group and installed that. Am I imagining that?

**Comment by dekinsitro** [comment]
Sure, I don't mind the version (well, I do, but I understand the constraint),

**Comment by danking** [comment]
I hodgepodge of things that don't invoke the closure cleaner will work. Any serious use of Hail will not work.
