### ISSUE TITLE
issue with select_all usage in regression methods

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4941]
```python
mt = hl.utils.range_matrix_table(1, 1).annotate_cols(y=0, cov1=1).annotate_entries(x=1)

# x_expr uses a col field
x_expr = hl.case().when(mt.cov1 == 1, 2).default(mt.x)

hl.logistic_regression_rows(y=mt.y, x=x_expr, test='wald', covariates=[1])
```

```
Java stack trace:
java.lang.AssertionError: assertion failed: cov1 not in struct{__y: float64, __cov0: float64}
	at scala.Predef$.assert(Predef.scala:170)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:74)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:62)
	at is.hail.expr.ir.GetField.typ(IR.scala:215)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:561)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:511)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:536)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:511)
	at is.hail.expr.ir.IRParser$$anonfun$ir_value_children$1.apply(Parser.scala:507)
	at is.hail.expr.ir.IRParser$$anonfun$ir_value_children$1.apply(Parser.scala:507)
	at is.hail.expr.ir.IRParser$.repUntil(Parser.scala:281)
	at is.hail.expr.ir.IRParser$.ir_value_children(Parser.scala:507)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:714)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:511)
	at is.hail.expr.ir.IRParser$.named_value_ir(Parser.scala:494)
	at is.hail.expr.ir.IRParser$$anonfun$named_value_irs$1.apply(Parser.scala:489)
	at is.hail.expr.ir.IRParser$$anonfun$named_value_irs$1.apply(Parser.scala:489)
	at is.hail.expr.ir.IRParser$.repUntil(Parser.scala:281)
	at is.hail.expr.ir.IRParser$.named_value_irs(Parser.scala:489)
	at is.hail.expr.ir.IRParser$.ir_value_expr_1(Parser.scala:670)
	at is.hail.expr.ir.IRParser$.ir_value_expr(Parser.scala:511)
	at is.hail.expr.ir.IRParser$.matrix_ir_1(Parser.scala:920)
	at is.hail.expr.ir.IRParser$.matrix_ir(Parser.scala:885)
	at is.hail.expr.ir.IRParser$.matrix_ir_1(Parser.scala:923)
	at is.hail.expr.ir.IRParser$.matrix_ir(Parser.scala:885)
	at is.hail.expr.ir.IRParser$$anonfun$parse_matrix_ir$2.apply(Parser.scala:1023)
	at is.hail.expr.ir.IRParser$$anonfun$parse_matrix_ir$2.apply(Parser.scala:1023)
	at is.hail.expr.ir.IRParser$.parse(Parser.scala:1007)
	at is.hail.expr.ir.IRParser$.parse_matrix_ir(Parser.scala:1023)
	at is.hail.expr.ir.IRParser$.parse_matrix_ir(Parser.scala:1022)
	at is.hail.expr.ir.IRParser.parse_matrix_ir(Parser.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)



Hail version: 0.2.5-e017bef1c26c
Error summary: AssertionError: assertion failed: cov1 not in struct{__y: float64, __cov0: float64}
```

**Comment by tpoterba** [comment]
This is an issue with `MT._select_all`. The operation needs to modify all schemas atomically, which is not an easy fix.

**Comment by tpoterba** [comment]
I can see a fix using _annotate_all and then a select directly before entering the logreg, though.

**Comment by tpoterba** [comment]
I'll claim this
