### ISSUE TITLE
liftover error

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#5174]
FatalError: IllegalArgumentException: Zero-length interval cannot be lifted over.  Interval: null

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 20 times, most recent failure: Lost task 0.19 in stage 2.0 (TID 21, ap01-sw-wdp1.c.topmed-kathiresan-lipids-wgs.internal, executor 7): java.lang.IllegalArgumentException: Zero-length interval cannot be lifted over.  Interval: null
    at htsjdk.samtools.liftover.LiftOver.liftOver(LiftOver.java:137)
    at is.hail.io.reference.LiftOver.queryInterval(LiftOver.scala:61)
    at is.hail.variant.ReferenceGenome.liftoverLocusInterval(ReferenceGenome.scala:435)
    at is.hail.codegen.generated.C11.method1(Unknown Source)
    at is.hail.codegen.generated.C11.apply(Unknown Source)
    at is.hail.codegen.generated.C11.apply(Unknown Source)
    at is.hail.expr.ir.TableMapRows$$anonfun$21$$anonfun$apply$11.apply(TableIR.scala:627)
    at is.hail.expr.ir.TableMapRows$$anonfun$21$$anonfun$apply$11.apply(TableIR.scala:626)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.next(RVD.scala:1264)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.next(RVD.scala:1258)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at scala.collection.Iterator$JoinIterator.next(Iterator.scala:232)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1138)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
    at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1371)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1145)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1125)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:108)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by jigold** [comment]
I replicated the issue with this:
```
In [1]: grch37 = hl.get_reference('GRCh37')

In [2]: grch37.add_liftover('src/test/resources/grch37_to_grch38_chr20.over.chain.gz', 'GRCh38')

In [3]: i = hl.parse_locus_interval('1:10000-10000')

In [4]: hl.eval(hl.liftover(i))
```

The issue is this interval is `Interval(10000, 10000, includesStart=True, includesEnd=False)` which has a length of zero.

@patrick-schultz Should this be a valid interval? i.e. start==end and includesStart = True and includesEnd = False. Otherwise, if it is a valid Hail interval, then I'll throw a nicer error message.

**Comment by patrick-schultz** [comment]
No, that should not be a valid interval.
