### ISSUE TITLE
Hail throws MalformedInputException: Input length = 1 on a weird CSV

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5221]
This CSV file is lacking any commas, it uses semicolons instead. https://github.com/jvns/pandas-cookbook/blob/master/data/bikes.csv I don't think hail should generate this error message:

```
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-5-2e52d209a59b> in <module>
----> 1 broken_ht = hl.import_table('../data/bikes.csv')
      2 # Look at the first 3 rows
      3 broken_ht[:3]

</Users/dking/anaconda2/envs/foofoo/lib/python3.7/site-packages/decorator.py:decorator-gen-1110> in import_table(paths, key, min_partitions, impute, no_header, comment, delimiter, missing, types, quote, skip_blank_lines, force_bgz)

~/anaconda2/envs/foofoo/lib/python3.7/site-packages/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    558     def wrapper(__original_func, *args, **kwargs):
    559         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 560         return __original_func(*args_, **kwargs_)
    561 
    562     return wrapper

~/anaconda2/envs/foofoo/lib/python3.7/site-packages/hail/methods/impex.py in import_table(paths, key, min_partitions, impute, no_header, comment, delimiter, missing, types, quote, skip_blank_lines, force_bgz)
   1326     jt = Env.hc()._jhc.importTable(paths, key, min_partitions, jtypes, comment,
   1327                                    delimiter, missing, no_header, impute, quote,
-> 1328                                    skip_blank_lines, force_bgz)
   1329     return Table._from_java(jt)
   1330 

~/anaconda2/envs/foofoo/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~/anaconda2/envs/foofoo/lib/python3.7/site-packages/hail/utils/java.py in deco(*args, **kwargs)
    225             raise FatalError('%s\n\nJava stack trace:\n%s\n'
    226                              'Hail version: %s\n'
--> 227                              'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
    228         except pyspark.sql.utils.CapturedException as e:
    229             raise FatalError('%s\n\nJava stack trace:\n%s\n'

FatalError: MalformedInputException: Input length = 1

Java stack trace:
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
	at scala.collection.Iterator$$anon$21.hasNext(Iterator.scala:836)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:330)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1336)
	at is.hail.utils.TextTableReader$$anonfun$14.apply(TextTableReader.scala:218)
	at is.hail.utils.TextTableReader$$anonfun$14.apply(TextTableReader.scala:215)
	at is.hail.utils.richUtils.RichHadoopConfiguration$$anonfun$readLines$extension$1.apply(RichHadoopConfiguration.scala:301)
	at is.hail.utils.richUtils.RichHadoopConfiguration$$anonfun$readLines$extension$1.apply(RichHadoopConfiguration.scala:292)
	at is.hail.utils.package$.using(package.scala:587)
	at is.hail.utils.richUtils.RichHadoopConfiguration$.readFile$extension(RichHadoopConfiguration.scala:285)
	at is.hail.utils.richUtils.RichHadoopConfiguration$.readLines$extension(RichHadoopConfiguration.scala:292)
	at is.hail.utils.TextTableReader$.read(TextTableReader.scala:215)
	at is.hail.HailContext$$anonfun$importTables$3.apply(HailContext.scala:516)
	at is.hail.HailContext$$anonfun$importTables$3.apply(HailContext.scala:518)
	at is.hail.HailContext.maybeGZipAsBGZip(HailContext.scala:586)
	at is.hail.HailContext.importTables(HailContext.scala:515)
	at is.hail.HailContext.importTable(HailContext.scala:477)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)



Hail version: 0.2.8-70304a52d33d
Error summary: MalformedInputException: Input length = 1
```

**Comment by danking** [comment]
randomly assigned.

**Comment by tpoterba** [comment]
looks like this is a weird character message maybe? There are some non-ascii chars in there

**Comment by danking** [comment]
Yeah, I think I'm saying `import_table` should take an encoding parameter.

**Comment by danking** [comment]
Not a problem in 0.2.95
