### ISSUE TITLE
Error when using `agg.group_by` with `agg.filter` 

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#5296]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:
```
pops_for_subpop = pops_ht.aggregate(
                hl.agg.filter(
                    hl.is_defined(pops_ht.pop) & (pops_ht.pop != "oth"),
                    hl.agg.group_by(pops_ht.pop, hl.agg.count())
                )
            )
```

### What went wrong (all error messages here, including the full java stack trace):
```
Traceback (most recent call last):
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/sample_qc.py", line 530, in <module>
    main(args)
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/sample_qc.py", line 458, in main
    hl.agg.group_by(pops_ht.pop, hl.agg.count())
  File "</opt/conda/lib/python3.6/site-packages/decorator.py:decorator-gen-764>", line 2, in aggregate
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/hail-0.2-c3b1183e4246.zip/hail/typecheck/check.py", line 560, in wrapper
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/hail-0.2-c3b1183e4246.zip/hail/table.py", line 1133, in aggregate
  File "</opt/conda/lib/python3.6/site-packages/decorator.py:decorator-gen-436>", line 2, in analyze
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/hail-0.2-c3b1183e4246.zip/hail/typecheck/check.py", line 560, in wrapper
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/hail-0.2-c3b1183e4246.zip/hail/expr/expressions/expression_utils.py", line 94, in analyze
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/hail-0.2-c3b1183e4246.zip/hail/expr/expressions/expression_utils.py", line 237, in get_refs
  File "/tmp/251cbf7beb5f4503ba74e4d69bd09ec3/hail-0.2-c3b1183e4246.zip/hail/expr/expressions/expression_utils.py", line 212, in _get_refs
AttributeError: 'NoneType' object has no attribute '_indices_from_ref'
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [251cbf7beb5f4503ba74e4d69bd09ec3] entered state [ERROR] while waiting for [DONE].
Traceback (most recent call last):
  File "/Users/laurent/tools/gnomad_hail/pyhail.py", line 132, in <module>
    main(args, pass_through_args)
  File "/Users/laurent/tools/gnomad_hail/pyhail.py", line 113, in main
    subprocess.check_output(job)
  File "/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
```

Note that first filtering the table, then running  agg.group_by it works, if I just run agg_filter without agg.group_by (just agg.count()), it also works.

For ref, this is `pops_ht` schema:
```
----------------------------------------
Global fields:
    None
----------------------------------------
Row fields:
    's': str 
    'known_pop': str 
    'known_subpop': str 
    '_kgp': bool 
    'pop': str 
    'prob_afr': float64 
    'prob_amr': float64 
    'prob_eas': float64 
    'prob_eur': float64 
    'prob_sas': float64 
----------------------------------------
Key: ['s', '_kgp']
----------------------------------------
```

And this is the result when first filtering:
```
pops_ht = pops_ht.filter(hl.is_defined(pops_ht.pop) & (pops_ht.pop != "oth"))
pops_ht.aggregate(hl.agg.group_by(pops_ht.pop, hl.agg.count()) )
```
=>
```
{'afr': 858, 'eas': 537, 'sas': 588, 'amr': 436, 'eur': 657}
```

**Comment by catoverdrive** [comment]
I think this was fixed by #6740. (Didn't notice that there was an issue open for it when I made the PR)
