### ISSUE TITLE
hl.locus_windows should have an option that doesn't serialize to Python

### ISSUE THREAD

**Issue by catoverdrive** [hail-is/hail#5407]
It's primary use is packaged in `ld_matrix`, and the serialization is expensive and can't be parallelized.

**Comment by konradjk** [comment]
to correspond to aggregate, probably `_localize=False`?

**Comment by catoverdrive** [comment]
(This definitely feels like a problem. Took three minutes to serialize an array with 10 million ints and with 40 million ints, this happens:)

```
>>> def serialize_test(n):
...     t = [i for i in range(n)]
...     t1 = datetime.now()
...     print(len(t))
...     print(hl.eval(hl.len(hl.array(t))))
...     t2 = datetime.now()
...     print(t2 - t1)
... 
>>> serialize_test(40000000)
40000000
Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at py4j.StringUtil.unescape(StringUtil.java:57)
	at py4j.Protocol.getString(Protocol.java:475)
	at py4j.Protocol.getObject(Protocol.java:302)
	at py4j.commands.AbstractCommand.getArguments(AbstractCommand.java:82)
	at py4j.commands.CallCommand.execute(CallCommand.java:77)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/Users/wang/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1035, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wang/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 883, in send_command
    response = connection.send_command(command)
  File "/Users/wang/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1040, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in serialize_test
  File "<decorator-gen-466>", line 2, in eval
  File "/Users/wang/code/hail/hail/python/hail/typecheck/check.py", line 561, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/wang/code/hail/hail/python/hail/expr/expressions/expression_utils.py", line 158, in eval
    return eval_typed(expression)[0]
  File "<decorator-gen-468>", line 2, in eval_typed
  File "/Users/wang/code/hail/hail/python/hail/typecheck/check.py", line 561, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/wang/code/hail/hail/python/hail/expr/expressions/expression_utils.py", line 199, in eval_typed
    return (Env.backend().execute(expression._ir), expression.dtype)
  File "/Users/wang/code/hail/hail/python/hail/backend/backend.py", line 94, in execute
    self._to_java_ir(ir)))
  File "/Users/wang/code/hail/hail/python/hail/backend/backend.py", line 86, in _to_java_ir
    code = r(ir)
  File "/Users/wang/code/hail/hail/python/hail/ir/renderer.py", line 29, in __call__
    return x.render(self)
  File "/Users/wang/code/hail/hail/python/hail/ir/ir.py", line 511, in render
    return '(ArrayLen {})'.format(r(self.a))
  File "/Users/wang/code/hail/hail/python/hail/ir/renderer.py", line 29, in __call__
    return x.render(self)
  File "/Users/wang/code/hail/hail/python/hail/ir/ir.py", line 2003, in render
    return f'(Literal {self._typ._parsable_string()} ' \
  File "/Users/wang/code/hail/hail/python/hail/utils/java.py", line 159, in escape_str
    return Env.jutils().escapePyString(s)
  File "/Users/wang/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/Users/wang/code/hail/hail/python/hail/utils/java.py", line 215, in deco
    return f(*args, **kwargs)
  File "/Users/wang/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 327, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling o33.escapePyString
```
