### ISSUE TITLE
Linear Regression in Hail on Broad Cluster Errors

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5559]
I think we need to figure out how to get cblas on the broad cluster.

```
# use UGER
# ish -l os=RedHat7
# use Anaconda3
# use Java-1.8
# use OpenBLAS
# source activate hail
# ipython
In [1]: import hail as hl                                                                                                                                                            

In [2]: mt = hl.balding_nichols_model(3, 100, 100)                                                                                                                                   
Initializing Spark and Hail with default parameters...
using hail jar at /home/unix/dking/.conda/envs/hail/lib/python3.7/site-packages/hail/hail-all-spark.jar
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Running on Apache Spark version 2.2.3
SparkUI available at http://10.200.100.39:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.11-cf54f08305d1
LOGGING: writing to /home/unix/dking/hail-20190307-1908-0.2.11-cf54f08305d1.log
2019-03-07 19:08:30 Hail: INFO: balding_nichols_model: generating genotypes for 3 populations, 100 samples, and 100 variants...
^[[A
In [3]: t = hl.linear_regression_rows(x=mt.GT.n_alt_alleles(), y=mt.pop, covariates=[1])                                                                                             
[Stage 0:============================================>              (6 + 1) / 8]2019-03-07 19:08:39 Hail: INFO: Coerced sorted dataset
2019-03-07 19:08:40 Hail: INFO: linear_regression_rows: running on 100 samples for 1 response variable y,
    with input variable x, and 1 additional covariate...
/broad/software/free/Linux/redhat_7_x86_64/pkgs/jdk1.8.0_181/bin/java: symbol lookup error: /tmp/jniloader1327638724610654731netlib-native_system-linux-x86_64.so: undefined symbol: cblas_dgemm
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/home/unix/dking/.conda/envs/hail/lib/python3.7/site-packages/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/unix/dking/.conda/envs/hail/lib/python3.7/site-packages/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/home/unix/dking/.conda/envs/hail/lib/python3.7/site-packages/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-3-9b1033d0ac55> in <module>
----> 1 t = hl.linear_regression_rows(x=mt.GT.n_alt_alleles(), y=mt.pop, covariates=[1])

<decorator-gen-1332> in linear_regression_rows(y, x, covariates, block_size, pass_through)

~/.conda/envs/hail/lib/python3.7/site-packages/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    559     def wrapper(__original_func, *args, **kwargs):
    560         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 561         return __original_func(*args_, **kwargs_)
    562 
    563     return wrapper

~/.conda/envs/hail/lib/python3.7/site-packages/hail/methods/statgen.py in linear_regression_rows(y, x, covariates, block_size, pass_through)
    434         ht_result = ht_result.annotate(**{f: ht_result[f][0] for f in fields})
    435 
--> 436     return ht_result.persist()
    437 
    438 

<decorator-gen-918> in persist(self, storage_level)

~/.conda/envs/hail/lib/python3.7/site-packages/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    559     def wrapper(__original_func, *args, **kwargs):
    560         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 561         return __original_func(*args_, **kwargs_)
    562 
    563     return wrapper

~/.conda/envs/hail/lib/python3.7/site-packages/hail/table.py in persist(self, storage_level)
   1677             Persisted table.
   1678         """
-> 1679         return Env.backend().persist_table(self, storage_level)
   1680 
   1681     def unpersist(self) -> 'Table':

~/.conda/envs/hail/lib/python3.7/site-packages/hail/backend/backend.py in persist_table(self, t, storage_level)
    107 
    108     def persist_table(self, t, storage_level):
--> 109         return Table._from_java(self._to_java_ir(t._tir).pyPersist(storage_level))
    110 
    111     def unpersist_table(self, t):

~/.conda/envs/hail/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~/.conda/envs/hail/lib/python3.7/site-packages/hail/utils/java.py in deco(*args, **kwargs)
    213         import pyspark
    214         try:
--> 215             return f(*args, **kwargs)
    216         except py4j.protocol.Py4JJavaError as e:
    217             s = e.java_exception.toString()

~/.conda/envs/hail/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    334             raise Py4JError(
    335                 "An error occurred while calling {0}{1}{2}".
--> 336                 format(target_id, ".", name))
    337     else:
    338         type = answer[1]

Py4JError: An error occurred while calling o51.pyPersist
```

```
(hail) -bash:uger-r7-c001:~ 1037 $ find /lib /lib64/ -regex '.*blas.*' -exec ls -al \{\} \;
lrwxrwxrwx. 1 root root 16 Dec 13  2017 /lib64/libblas.so.3.4 -> libblas.so.3.4.2
lrwxrwxrwx. 1 root root 16 Dec 13  2017 /lib64/libblas.so.3 -> libblas.so.3.4.2
lrwxrwxrwx. 1 root root 16 Dec 13  2017 /lib64/libblas.so -> libblas.so.3.4.2
-rwxr-xr-x. 1 root root 364808 Mar  2  2017 /lib64/libblas.so.3.4.2
```

```
(hail) -bash:uger-r7-c001:~ 1034 $ objdump -T /lib64/liblapack.so.3 | grep dgemm
0000000000000000      DF *UND*	0000000000000000              dgemm_
(hail) -bash:uger-r7-c001:~ 1035 $ objdump -T /lib64/libblas.so.3 | grep dgemm
0000000000018850 g    DF .text	0000000000000935  Base        dgemm_
```

**Comment by danking** [comment]
I sent an email to BITS about how to get a shared object with `cblas_dgemm` via dotkit.

**Comment by danking** [comment]
Heard from BITS yesterday, responded today with more detail. I think the issue is that there is no dotkit for LAPACK, Intel's MKL, or ATLAS, all of which, I believe, supply `cblas_dgemm`.

**Comment by danking** [comment]
The issue is that `use OpenBLAS` puts `libopenblas.so` on `LD_LIBRARY_PATH`. `netlib-java` links against `libblas.so` which is expected to contain the CBLAS symbols. It appears that Debian-style distributions use `update-alternatives` to symlink `libblas.so` to a library of the user's choice.

Broad's UGER cluster does not provide such `update-alternatives` functionality. There exists two fixes:
- create a symlink to `libopenblas.so` named `libblas.so` and put it on the LD_LIBRARY_PATH
- use `LD_PRELOAD` to forcibly load `libopenblas.so`

The two solutions look like:

1.
```
mkdir ~/lib
ln -s /broad/software/free/Linux/redhat_7_x86_64/pkgs/openblas_0.2.20/lib/libopenblas.so ~/lib/libblas.so.3
export LD_LIBARRY_PATH=~/lib:$LD_LIBRARY_PATH
```

2.
```
export LD_PRELOAD=/broad/software/free/Linux/redhat_7_x86_64/pkgs/openblas_0.2.20/lib/libopenblas.so
```

Clearly neither of these are ideal. I recommend users place the lines from option 1 in an rc file.

**Comment by danking** [comment]
To be clear, a broad user can execute this command on the cluster to fix their environment:

```
cat >>~/.my.bash.rc <<EOF
mkdir ~/lib
ln -s /broad/software/free/Linux/redhat_7_x86_64/pkgs/openblas_0.2.20/lib/libopenblas.so ~/lib/libblas.so.3
export LD_LIBARRY_PATH=~/lib:$LD_LIBRARY_PATH
EOF
```

**Comment by danking** [comment]
Broad IT graciously provided a hidden dotkit that enables Hail to use openblas without manually creating symlinks:

```
use .openblas_for_hail-0.2.20
```
