### ISSUE TITLE
Error of using Nirvana in the HAIL

### ISSUE THREAD

**Issue by houhsein** [hail-is/hail#5657]
We have some problem with running nirvana in hail and we use the sample file of GWAS Tutorial

Code: 
hl.utils.get_1kg('data/')
vcfVds = hl.import_vcf('data/1kg.vcf.bgz', min_partitions=8)
vds = hl.nirvana(vcfVds,'data/nirvana.properties')

Version:
Running on Apache Spark version 2.2.1
Hail version: 0.2.10-ceb85fc87544

We got this error massage:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-1226>", line 2, in nirvana
  File "/seqslab/hail/hail/build/distributions/hail-python.zip/hail/typecheck/check.py", line 561, in wrapper
  File "/seqslab/hail/hail/build/distributions/hail-python.zip/hail/methods/qc.py", line 860, in nirvana
  File "/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/seqslab/hail/hail/build/distributions/hail-python.zip/hail/utils/java.py", line 227, in deco
hail.utils.java.FatalError: AssertionError: assertion failed

Java stack trace:
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:156)
        at is.hail.methods.Nirvana$.annotate(Nirvana.scala:361)
        at is.hail.methods.Nirvana$.apply(Nirvana.scala:487)
        at is.hail.methods.Nirvana.apply(Nirvana.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)

Hail version: 0.2.10-ceb85fc87544
Error summary: AssertionError: assertion failed

We also check the key of input file:
 
>>> vcfVds.describe()
----------------------------------------
Global fields:
    None
----------------------------------------
Column fields:
    's': str
----------------------------------------
Row fields:
    'locus': locus<GRCh37>
    'alleles': array<str>
    'rsid': str
    'qual': float64
    'filters': set<str>
    'info': struct {
        AC: array<int32>,
        AF: array<float64>,
        AN: int32,
        BaseQRankSum: float64,
        ClippingRankSum: float64,
        DP: int32,
        DS: bool,
        FS: float64,
        HaplotypeScore: float64,
        InbreedingCoeff: float64,
        MLEAC: array<int32>,
        MLEAF: array<float64>,
        MQ: float64,
        MQ0: int32,
        MQRankSum: float64,
        QD: float64,
        ReadPosRankSum: float64,
        set: str
    }
----------------------------------------
Entry fields:
    'GT': call
    'AD': array<int32>
    'DP': int32
    'GQ': int32
    'PL': array<int32>
----------------------------------------
Column key: ['s']
Row key: ['locus', 'alleles']
----------------------------------------

**Comment by tpoterba** [comment]
can you try running with the latest version? I fixed this specific issue recently, but it's possible you'll get another error (it's not tested as part of our CI)

**Comment by tpoterba** [comment]
If this is still an issue, please make a post on the forum, OK? We're more responsive there.
