### ISSUE TITLE
Hail should support quote-escaped quotes.

### ISSUE THREAD

**Issue by nawatts** [hail-is/hail#5796]
Some delimited text processors use quotes to escape quotes so that the string `a"b` is rendered as `a""b`. Moreover an individual entry of the delimited text is itself wrapped in double quotes, so, for example, a delimited text file representing one row containing the strings: `hello`, `a"b`, `goodbye` would contain the following bytes:
```
"hello","a""b","goodbye"
```

---

Attempting to import and show the attached TSV file with `hl.import_table("test.txt", quote='"').show()` throws an exception:
```
is.hail.utils.HailException: terminating quote character '"' not at end of field
	at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:9)
	at is.hail.utils.package$.fatal(package.scala:28)
	at is.hail.expr.ir.TextTableReader$.splitLine(TextTableReader.scala:107)
	at is.hail.expr.ir.TextTableReader$$anonfun$28$$anonfun$apply$7$$anonfun$apply$8.apply(TextTableReader.scala:379)
	at is.hail.expr.ir.TextTableReader$$anonfun$28$$anonfun$apply$7$$anonfun$apply$8.apply(TextTableReader.scala:378)
	at is.hail.utils.WithContext.map(Context.scala:33)
	at is.hail.expr.ir.TextTableReader$$anonfun$28$$anonfun$apply$7.apply(TextTableReader.scala:378)
	at is.hail.expr.ir.TextTableReader$$anonfun$28$$anonfun$apply$7.apply(TextTableReader.scala:408)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at is.hail.utils.package$.getIteratorSizeWithMaxN(package.scala:385)
	at is.hail.sparkextras.ContextRDD$$anonfun$14.apply(ContextRDD.scala:559)
	at is.hail.sparkextras.ContextRDD$$anonfun$14.apply(ContextRDD.scala:559)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:589)
	at is.hail.sparkextras.ContextRDD$$anonfun$runJob$1.apply(ContextRDD.scala:587)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Expected output:
```
+-----+-----------+
| idx | value     |
+-----+-----------+
| str | str       |
+-----+-----------+
| "1" | "\"foo\"" |
| "2" | "\"bar\"" |
| "3" | "\"baz\"" |
+-----+-----------+
```

Hail version: 0.2.12-9409c0635781

[test.txt](https://github.com/hail-is/hail/files/3049195/test.txt)

**Comment by tpoterba** [comment]
Isn't this invalid? Shouldn't it be `"\"\"foo\"\""`

**Comment by tpoterba** [comment]
ah, this suggests that double quotes are the escaping motif?
https://en.wikipedia.org/wiki/Delimiter-separated_values

**Comment by nawatts** [comment]
> ah, this suggests that double quotes are the escaping motif?

Yes. Python and Excel both import this CSV with one double quote character around the value fields.

https://tools.ietf.org/html/rfc4180#section-2 is another source for escaping double quotes with double quotes.

**Comment by tpoterba** [comment]
randomly assigned @jigold

**Comment by tpoterba** [comment]
randomly reassigned to @johnc1231

**Comment by johnc1231** [comment]
Confirmed still a problem in 0.2.38.

**Comment by danking** [comment]
Still a problem in 0.2.95.

**Comment by danking** [comment]
We're replacing this issue with [#13563](https://github.com/hail-is/hail/issues/13563) which contains a little less discussion but has some directions forward.
