### ISSUE TITLE
import_vcf and import_table fail on tutorial

### ISSUE THREAD

**Issue by JT17** [hail-is/hail#6299]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

I'm working through the GWAS tutorial and getting some strange errors with two different functions. On the 4th line calling hl.import_vcf('data/1kg.vcf.bgz').write('data/1kg.mt', overwrite=True) I'm getting the following error:

```
File "gwas_tutorial.py", line 12, in <module>
    hl.import_vcf('data/1kg.vcf.bgz').write('data/1kg.mt',overwrite=True)
  File "</Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/decorator.py:decorator-gen-946>", line 2, in write
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/typecheck/check.py", line 561, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/matrixtable.py", line 2494, in write
    Env.backend().execute(MatrixWrite(self._mir, writer))
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/backend/backend.py", line 106, in execute
    result = json.loads(Env.hail().backend.spark.SparkBackend.executeJSON(self._to_java_ir(ir)))
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/utils/java.py", line 240, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: ScalaSigParserError: Unexpected failure

Java stack trace:
org.json4s.scalap.ScalaSigParserError: Unexpected failure
	at org.json4s.scalap.Rules$$anonfun$expect$1.apply(Rules.scala:73)
	at org.json4s.scalap.scalasig.ClassFileParser$.parse(ClassFileParser.scala:95)
	at org.json4s.reflect.ScalaSigReader$.parseClassFileFromByteCode(ScalaSigReader.scala:178)
	at org.json4s.reflect.ScalaSigReader$.findScalaSig(ScalaSigReader.scala:172)
	at org.json4s.reflect.ScalaSigReader$.findClass(ScalaSigReader.scala:53)
	at org.json4s.reflect.ScalaSigReader$.org$json4s$reflect$ScalaSigReader$$findField(ScalaSigReader.scala:100)
	at org.json4s.reflect.ScalaSigReader$.org$json4s$reflect$ScalaSigReader$$read$1(ScalaSigReader.scala:45)
	at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:49)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:69)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:68)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:68)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:85)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:184)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:48)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:48)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:118)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:164)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:64)
	at org.json4s.Extraction$.decompose(Extraction.scala:242)
	at org.json4s.jackson.Serialization$.write(Serialization.scala:27)
	at is.hail.variant.RelationalSpec$$anonfun$write$1.apply(MatrixTable.scala:85)
	at is.hail.variant.RelationalSpec$$anonfun$write$1.apply(MatrixTable.scala:84)
	at is.hail.utils.package$.using(package.scala:594)
	at is.hail.utils.richUtils.RichHadoopConfiguration$.writeTextFile$extension(RichHadoopConfiguration.scala:281)
	at is.hail.variant.RelationalSpec.write(MatrixTable.scala:84)
	at is.hail.expr.ir.MatrixValue.writeGlobals(MatrixValue.scala:91)
	at is.hail.expr.ir.MatrixValue.is$hail$expr$ir$MatrixValue$$finalizeWrite(MatrixValue.scala:104)
	at is.hail.expr.ir.MatrixValue.write(MatrixValue.scala:184)
	at is.hail.expr.ir.MatrixNativeWriter.apply(MatrixWriter.scala:36)
	at is.hail.expr.ir.WrappedMatrixWriter.apply(MatrixWriter.scala:23)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:754)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:87)
	at is.hail.expr.ir.CompileAndEvaluate$$anonfun$1.apply(CompileAndEvaluate.scala:31)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:20)
	at is.hail.expr.ir.CompileAndEvaluate$.apply(CompileAndEvaluate.scala:31)
	at is.hail.backend.spark.SparkBackend$.execute(SparkBackend.scala:75)
	at is.hail.backend.spark.SparkBackend$.executeJSON(SparkBackend.scala:18)
	at is.hail.backend.spark.SparkBackend.executeJSON(SparkBackend.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)



Hail version: 0.2.14-8dcb6722c72a
Error summary: ScalaSigParserError: Unexpected failure
```
If that does execute, which it does sometimes (unclear why, I don't make any code changes), I get an error from mt = hl.read_matrix_table('data/1kg.mt'):

```
[Stage 1:>                                                          (0 + 2) / 2]2019-06-10 14:40:22 Hail: INFO: Coerced sorted dataset
[Stage 2:>                                                          (0 + 2) / 2]2019-06-10 14:40:25 Hail: INFO: wrote matrix table with 10961 rows and 284 columns in 2 partitions to data/1kg.mt
Traceback (most recent call last):
  File "gwas_tutorial.py", line 13, in <module>
    mt = hl.read_matrix_table('data/1kg.mt')
  File "</Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/decorator.py:decorator-gen-1136>", line 2, in read_matrix_table
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/typecheck/check.py", line 561, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/methods/impex.py", line 1708, in read_matrix_table
    return MatrixTable(MatrixRead(MatrixNativeReader(path), _drop_cols, _drop_rows))
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/matrixtable.py", line 558, in __init__
    self._type = self._mir.typ
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/ir/base_ir.py", line 158, in typ
    self._compute_type()
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/ir/matrix_ir.py", line 40, in _compute_type
    self._type = Env.backend().matrix_type(self)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/backend/backend.py", line 121, in matrix_type
    jir = self._to_java_ir(mir)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/backend/backend.py", line 102, in _to_java_ir
    ir._jir = ir.parse(r(ir), ir_map=r.jirs)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/ir/base_ir.py", line 163, in parse
    return Env.hail().expr.ir.IRParser.parse_matrix_ir(code, ref_map, ir_map)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/username/miniconda3/envs/hail1/lib/python3.7/site-packages/hail/utils/java.py", line 240, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: MatchError: 17 (of class java.lang.Integer)

Java stack trace:
scala.MatchError: 17 (of class java.lang.Integer)
	at org.json4s.scalap.scalasig.ClassFileParser$$anonfun$37.apply(ClassFileParser.scala:119)
	at org.json4s.scalap.scalasig.ClassFileParser$$anonfun$37.apply(ClassFileParser.scala:119)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:33)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:32)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.StateRules$class.rep$2(Rules.scala:137)
	at org.json4s.scalap.StateRules$$anonfun$repeatUntil$1.apply(Rules.scala:143)
	at org.json4s.scalap.StateRules$$anonfun$repeatUntil$1.apply(Rules.scala:143)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:33)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:32)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:33)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:32)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:33)
	at org.json4s.scalap.Rule$$anonfun$flatMap$1.apply(Rule.scala:32)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rule$$anonfun$mapResult$1.apply(Rule.scala:43)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:67)
	at org.json4s.scalap.Rules$DefaultRule.apply(Rules.scala:65)
	at org.json4s.scalap.Rules$$anonfun$expect$1.apply(Rules.scala:71)
	at org.json4s.scalap.scalasig.ClassFileParser$.parse(ClassFileParser.scala:95)
	at org.json4s.reflect.ScalaSigReader$.parseClassFileFromByteCode(ScalaSigReader.scala:178)
	at org.json4s.reflect.ScalaSigReader$.findScalaSig(ScalaSigReader.scala:172)
	at org.json4s.reflect.ScalaSigReader$.findClass(ScalaSigReader.scala:53)
	at org.json4s.reflect.ScalaSigReader$.org$json4s$reflect$ScalaSigReader$$findField(ScalaSigReader.scala:100)
	at org.json4s.reflect.ScalaSigReader$.org$json4s$reflect$ScalaSigReader$$read$1(ScalaSigReader.scala:45)
	at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:49)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:69)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:68)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:68)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:85)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:184)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:48)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:48)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
	at org.json4s.Extraction$$anonfun$extract$6.apply(Extraction.scala:393)
	at org.json4s.Extraction$$anonfun$extract$6.apply(Extraction.scala:392)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
	at org.json4s.Extraction$.extract(Extraction.scala:392)
	at org.json4s.Extraction$ClassInstanceBuilder.mkWithTypeHint(Extraction.scala:587)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:596)
	at org.json4s.Extraction$$anonfun$extract$6.apply(Extraction.scala:400)
	at org.json4s.Extraction$$anonfun$extract$6.apply(Extraction.scala:392)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
	at org.json4s.Extraction$.extract(Extraction.scala:392)
	at org.json4s.Extraction$.extract(Extraction.scala:39)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at org.json4s.jackson.Serialization$.read(Serialization.scala:50)
	at org.json4s.Serialization$class.read(Serialization.scala:30)
	at org.json4s.jackson.Serialization$.read(Serialization.scala:17)
	at is.hail.expr.ir.IRParser$.matrix_ir_1(Parser.scala:1117)
	at is.hail.expr.ir.IRParser$.matrix_ir(Parser.scala:1053)
	at is.hail.expr.ir.IRParser$$anonfun$parse_matrix_ir$2.apply(Parser.scala:1269)
	at is.hail.expr.ir.IRParser$$anonfun$parse_matrix_ir$2.apply(Parser.scala:1269)
	at is.hail.expr.ir.IRParser$.parse(Parser.scala:1253)
	at is.hail.expr.ir.IRParser$.parse_matrix_ir(Parser.scala:1269)
	at is.hail.expr.ir.IRParser$.parse_matrix_ir(Parser.scala:1268)
	at is.hail.expr.ir.IRParser.parse_matrix_ir(Parser.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)



Hail version: 0.2.14-8dcb6722c72a
Error summary: MatchError: 17 (of class java.lang.Integer)
```

Any ideas on what is causing this? It seems like something in Spark itself, but I can't trace it down. I'm running Apache Spark version 2.4.1

**Comment by tpoterba** [comment]
You installed Hail using pip, right? You're running locally?

**Comment by JT17** [comment]
Yeah, it turns out that I had to reinstall Java, which seems to have fixed the issue.

**Comment by tpoterba** [comment]
oh ok, cool.

**Comment by zillurbmb51** [comment]
Hello, I am having similar problems. I installed using conda according to https://hail.is/docs/0.2/getting_started.html#requirements 
I created the environment, activated it and installed with pip. When I try to load a vcf file, I am getting:
` hl.import_vcf('/Volumes/Macintosh HD2/data/thousands_genome/hector.Q15d5.vcf.gz')`
`py4j.protocol.Py4JJavaError: An error occurred while calling z:is.hail.HailContext.apply.
: is.hail.utils.HailException: Hail requires Java 8, found 12.0.1`
Any help? Best, Zillur

**Comment by danking** [comment]
@zillurbmb51 You need to install Java 8, you have Java 12.

**Comment by zillurbmb51** [comment]
Thank you. I have java 8 in my system. 
(base) rcmi-29:snpcall mzillur$ ls /Library/Java/JavaVirtualMachines/
jdk-12.0.1.jdk		jdk1.8.0_202.jdk	jdk1.8.0_221.jdk	openjdk-11.0.2.jdk
How can I speicfy it? Best, Zillur

**Comment by danking** [comment]
https://discuss.hail.is/t/on-mac-os-x-how-do-i-install-and-use-java-8-if-i-already-have-a-different-version-of-java-installed/831/2
