### ISSUE TITLE
[hail][hailctl] hailctl fails with cryptic error messages

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6565]
Christina reports https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/initialization.20action.20failed.20in.20starting.20cluster:
```
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [d0a8142009bf49a1a51f5276576aeddb] failed with error:
Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found in 'gs://dataproc-c3e3c3c1-4a54-41e4-aa06-83d5d2ce80ec-us/google-cloud-dataproc-metainfo/c174dc73-2817-4ec1-8c2d-ae4e0c4f91ae/jobs/d0a8142009bf49a1a51f5276576aeddb/driveroutput'.
Traceback (most recent call last):
  File "/Users/cchen/anaconda/envs/hail-env/bin/hailctl", line 10, in <module>
    sys.exit(main())
  File "/Users/cchen/anaconda/envs/hail-env/lib/python3.7/site-packages/hailctl/__main__.py", line 90, in main
    module(args)
  File "/Users/cchen/anaconda/envs/hail-env/lib/python3.7/site-packages/hailctl/dataproc/cli.py", line 99, in main
    jmp[args.module].main(args, pass_through_args)
  File "/Users/cchen/anaconda/envs/hail-env/lib/python3.7/site-packages/hailctl/dataproc/submit.py", line 72, in main
    check_call(cmd)
  File "/Users/cchen/anaconda/envs/hail-env/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcloud', 'dataproc', 'jobs', 'submit', 'pyspark', 'ukbb_hdpca.py', '--cluster=chen', '--files=', '--py-files=/var/folders/6h/ll2dv8t15zs9pzf4g6kjb2rrt2fc9q/T/pyscripts_2740r0cj.zip', '--properties=']' returned non-zero exit status 1.
```
The file does not exist but there are files with the same prefix but a `.000000001` suffix or similar.

Grace reports (a possibly unrelated issue) https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/Cryptic.20array.20concordance.20error:
```
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [873db5659acd43f7b539dcb17182959d] entered state [ERROR] while waiting for [DONE].
Traceback (most recent call last):
  File "/miniconda3/bin/hailctl", line 10, in <module>
    sys.exit(main())
  File "/miniconda3/lib/python3.7/site-packages/hailctl/__main__.py", line 90, in main
    module(args)
  File "/miniconda3/lib/python3.7/site-packages/hailctl/dataproc/cli.py", line 99, in main
    jmp[args.module].main(args, pass_through_args)
  File "/miniconda3/lib/python3.7/site-packages/hailctl/dataproc/submit.py", line 72, in main
    check_call(cmd)
  File "/miniconda3/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcloud', 'dataproc', 'jobs', 'submit', 'pyspark', '/Users/gtiao/ukbb_qc/scratch.py', '--cluster=gt1', '--files=', '--py-files=/var/folders/rn/t2xcx1ps4h96txll46qkkfsj2q8bnl/T/pyscripts_lh2k36v4.zip', '--properties=', '--', '--slack_channel', '@grace']' returned non-zero exit status 1.
```

**Comment by danking** [comment]
Finally got a lead on Christina's bug:
```
# hailctl dataproc submit dk foo.py
Submitting to cluster 'dk'...
gcloud command:
gcloud dataproc jobs submit pyspark foo.py \
    --cluster=dk \
    --files= \
    --py-files=/var/folders/cq/p_l4jm3x72j7wkxqxswccs180000gq/T/pyscripts_yg_wzlu0.zip \
    --properties=
Job [66c1d088108948b2b76bb607f61d7b3f] submitted.
Waiting for job output...
Initializing Spark and Hail with default parameters...
using hail jar at /opt/conda/default/lib/python3.6/site-packages/hail/hail-all-spark.jar
Running on Apache Spark version 2.4.3
SparkUI available at http://dk-m.c.broad-ctsa.internal:4041
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.16-277ccc7aec45
LOGGING: writing to /tmp/66c1d088108948b2b76bb607f61d7b3f/hail-20190703-2330-0.2.16-277ccc7aec45.log
yo dawg

[Stage 0:>                                                          (0 + 1) / 1]OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f2e73b00000, 1035468800, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1035468800 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/66c1d088108948b2b76bb607f61d7b3f/hs_err_pid10896.log
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [66c1d088108948b2b76bb607f61d7b3f] failed with error:
Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found in 'gs://dataproc-7f9e9d5e-03bd-4e95-bea1-fe0321239b35-us/google-cloud-dataproc-metainfo/f03fbc39-c07f-4e3e-8f21-47ffa986058e/jobs/66c1d088108948b2b76bb607f61d7b3f/driveroutput'.
Traceback (most recent call last):
  File "/usr/local/bin/hailctl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/hailtop/hailctl/__main__.py", line 91, in main
    cli.main(args)
  File "/usr/local/lib/python3.7/site-packages/hailtop/hailctl/dataproc/cli.py", line 99, in main
    jmp[args.module].main(args, pass_through_args)
  File "/usr/local/lib/python3.7/site-packages/hailtop/hailctl/dataproc/submit.py", line 72, in main
    check_call(cmd)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcloud', 'dataproc', 'jobs', 'submit', 'pyspark', 'foo.py', '--cluster=dk', '--files=', '--py-files=/var/folders/cq/p_l4jm3x72j7wkxqxswccs180000gq/T/pyscripts_yg_wzlu0.zip', '--properties=']' returned non-zero exit status 1.
```

trying to get the core dump now. This was what finally got it to fail:
```
mt = hl.read_matrix_table( ... )
n_samples = mt.count_cols()
mt = mt.add_col_index()
mt = mt.add_row_index()
mt = mt._filter_partitions([1])

perm = np.random.permutation(n_samples)

n_indvs = int(0.5 * n_samples)

mt1 = mt.filter_cols(hl.literal(set([int(i) for i in perm[:n_indvs]]), dtype='set<int64>').contains(mt.col_idx))

mt1 = mt1.annotate_rows(GT_stats = hl.agg.stats(mt1.GT.n_alt_alleles()))
mt1 = mt1.annotate_rows(hwe_sd = (mt1.GT_stats.mean * (1 - mt1.GT_stats.mean / 2))**0.5)
mt1 = mt1.annotate_entries(normed_GT = hl.or_else((mt1.GT.n_alt_alleles() - mt1.GT_stats.mean) / mt1.hwe_sd, 0.0))
mt1 = mt1.filter_rows(hl.rand_bool(0.99))

print('yo dawg')
mt1.count_rows()
```

**Comment by tpoterba** [comment]
what's the file that causes a fail? This works on small data.

It may be worth trying before/after the spilling collect aggregator change -- this contains a scan and the rest of it seems quite straightforward

**Comment by danking** [comment]
stale, likely related to aggregator changes that have seen many improvements since then
