### ISSUE TITLE
[ci] do not 500 if a batch has been deleted

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6587]
```
ERROR	| 2019-07-09 09:52:15,823 	| web_protocol.py 	| log_exception:355 | Error handling request
Jul 9, 2019 @ 05:52:15.824
Traceback (most recent call last):
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 418, in start
Jul 9, 2019 @ 05:52:15.824
    resp = await task
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 458, in _handle
Jul 9, 2019 @ 05:52:15.824
    resp = await handler(request)
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 157, in handler_wrapper
Jul 9, 2019 @ 05:52:15.824
    result = await result
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/aiohttp_jinja2/__init__.py", line 91, in wrapped
Jul 9, 2019 @ 05:52:15.824
    context = await coro(*args)
Jul 9, 2019 @ 05:52:15.824
  File "/ci/ci.py", line 118, in get_pr
Jul 9, 2019 @ 05:52:15.824
    status = await pr.batch.status()
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/hailtop/batch_client/aioclient.py", line 209, in status
Jul 9, 2019 @ 05:52:15.824
    return await self._client._get(f'/api/v1alpha/batches/{self.id}')
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/hailtop/batch_client/aioclient.py", line 412, in _get
Jul 9, 2019 @ 05:52:15.824
    self.url + path, params=params, cookies=self._cookies, headers=self._headers)
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 581, in _request
Jul 9, 2019 @ 05:52:15.824
    resp.raise_for_status()
Jul 9, 2019 @ 05:52:15.824
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 942, in raise_for_status
Jul 9, 2019 @ 05:52:15.824
    headers=self.headers)
Jul 9, 2019 @ 05:52:15.824
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'
Jul 9, 2019 @ 05:52:15.824
INFO	| 2019-07-09 09:52:15,824 	| web_log.py 	| log:233 | 10.32.17.240 [09/Jul/2019:09:52:15 +0000] "GET /watched_branches/0/pr/6561 HTTP/1.0" 500 315 "https://ci.hail.is/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
```

**Comment by danking** [comment]
https://internal.hail.is/monitoring/kibana/app/infra#/logs?_g=()&flyoutOptions=(flyoutId:Cs8K1GsBylIYXqvkSfbm,flyoutVisibility:hidden,surroundingLogsId:!n)&logFilter=(expression:'kubernetes.labels.app%20:ci',kind:kuery)&logPosition=(position:(tiebreaker:23440993,time:1562665935824),streamLive:!f)
