### ISSUE TITLE
can't read table with lots of fields

### ISSUE THREAD

**Issue by catoverdrive** [hail-is/hail#7396]
to reproduce:

```
import hail as hl
t = hl.utils.range_table(10)
t = t.annotate(**{f'f{i}': 0 for i in range(1300)})
t.write('foo.ht')
hl.read_table('foo.ht')._force_count()
```

MethodCodeTooLarge error is thrown inside the decoder.

**Comment by tpoterba** [comment]
aha!

**Comment by tpoterba** [comment]
yeah, encoders/decoders don't wrap within structs. That's not hard to fix.

**Comment by catoverdrive** [comment]
https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/Method.20code.20too.20large

I believe this issue is what's encountered in this case, although more indirectly; the table import doesn't hit it, but when we annotate_cols to join in the wide table, the literal encoding/decoding we use to serialize the table does.

**Comment by catoverdrive** [comment]
to elaborate, I'm seeing this test case hit the same error:
```
t = hl.utils.range_table(10).annotate(**{f'f{i}': 0 for i in range(1300)})
mt = hl.utils.range_matrix_table(10, 10)

mt.annotate_cols(foo=t[mt.col_idx])._force_count_rows()
```

with the following stack trace: 
```
2019-10-28 17:15:08 root: ERROR: Verify Output 1 for is/hail/codegen/generated/C_etypeDecode_9:
2019-10-28 17:15:08 root: ERROR: RuntimeException: Method code too large!
From java.lang.RuntimeException: Method code too large!
	at is.hail.relocated.org.objectweb.asm.MethodWriter.a(Unknown Source)
	at is.hail.relocated.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at is.hail.asm4s.FunctionBuilder.classAsBytes(FunctionBuilder.scala:333)
	at is.hail.asm4s.FunctionBuilder.result(FunctionBuilder.scala:372)
	at is.hail.expr.types.encoded.EType$.buildDecoder(EType.scala:199)
	at is.hail.io.TypedCodecSpec.buildDecoder(RowStore.scala:36)
	at is.hail.rvd.RVD.collect(RVD.scala:694)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:750)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:90)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:59)
	at is.hail.expr.ir.InterpretNonCompilable$$anonfun$5.apply(InterpretNonCompilable.scala:16)
	at is.hail.expr.ir.InterpretNonCompilable$$anonfun$5.apply(InterpretNonCompilable.scala:16)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at is.hail.expr.ir.InterpretNonCompilable$.apply(InterpretNonCompilable.scala:16)
	at is.hail.expr.ir.TableMapGlobals.execute(TableIR.scala:1125)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:762)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:90)
	at is.hail.expr.ir.Interpret$.apply(Interpret.scala:59)
	at is.hail.expr.ir.InterpretNonCompilable$$anonfun$7.apply(InterpretNonCompilable.scala:19)
	at is.hail.expr.ir.InterpretNonCompilable$$anonfun$7.apply(InterpretNonCompilable.scala:19)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at is.hail.expr.ir.InterpretNonCompilable$.apply(InterpretNonCompilable.scala:19)
	at is.hail.expr.ir.CompileAndEvaluate$$anonfun$2.apply(CompileAndEvaluate.scala:37)
	at is.hail.expr.ir.CompileAndEvaluate$$anonfun$2.apply(CompileAndEvaluate.scala:37)
	at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:24)
	at is.hail.expr.ir.CompileAndEvaluate$.apply(CompileAndEvaluate.scala:37)
	at is.hail.backend.Backend$$anonfun$execute$1.apply(Backend.scala:57)
	at is.hail.backend.Backend$$anonfun$execute$1.apply(Backend.scala:57)
	at is.hail.utils.package$.using(package.scala:596)
	at is.hail.expr.ir.ExecuteContext$$anonfun$scoped$1.apply(ExecuteContext.scala:10)
	at is.hail.expr.ir.ExecuteContext$$anonfun$scoped$1.apply(ExecuteContext.scala:9)
	at is.hail.utils.package$.using(package.scala:596)
	at is.hail.annotations.Region$.scoped(Region.scala:18)
	at is.hail.expr.ir.ExecuteContext$.scoped(ExecuteContext.scala:9)
	at is.hail.backend.Backend.execute(Backend.scala:57)
	at is.hail.backend.Backend.executeJSON(Backend.scala:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
