### ISSUE TITLE
GroupedMatrixTable.describe is broken

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7410]
From Akhil:

```
Traceback (most recent call last):
  File "/tmp/e9b3538af9b14d6ba440edbdf89e1ef1/phewas_rvas_jhs_unrel.py", line 55, in <module>
    print(mt.describe())
  File "/opt/conda/default/lib/python3.6/site-packages/hail/matrixtable.py", line 85, in describe
    rowstr = "\nRows: \n" + "\n    ".join(["{}: {}".format(k, v._type) for k, v in self._row_keys.items()])
AttributeError: 'list' object has no attribute 'items'
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [e9b3538af9b14d6ba440edbdf89e1ef1] failed with error:
Job failed with message [AttributeError: 'list' object has no attribute 'items']. Additional details can be found in 'gs://dataproc-37b10a9c-3ebd-47a4-9228-bf38bdfba439-us/google-cloud-dataproc-metainfo/e432509c-1bea-4839-9cb8-4d404d195a35/jobs/e9b3538af9b14d6ba440edbdf89e1ef1/driveroutput'.
```
```
mt = hl.read_matrix_table('gs://jhs_data_topmed/HCLOF_JHS_AF_01_unrel.mt')
mt.describe()
print(mt.count())
mt = mt.annotate_rows(genes = mt.vep.transcript_consequences.gene_symbol)
mt = mt.group_rows_by(mt.genes)
print(mt.describe())
```

**Comment by tpoterba** [comment]
I dunno. Probably need to look at the row key exprs of the same index

**Comment by eric-czech** [comment]
I imagine this is a low priority issue, but is there a workaround for learning what the structure of a grouped MT is in the meantime?  Or has there been any progress on this?

**Comment by tpoterba** [comment]
It's somewhat low-prio because we imagine that GroupedMatrixTable as pretty much just an intermediate between `group_{rows, cols}_by` and `aggregate` that probably shouldn't be bound to a variable and inspected. Its structure is the same as the parent MT, but just records group expressions.
