### ISSUE TITLE
error with textTableReader --impute with one-line file

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#750]
```
hail: importannotations table: caught exception: java.lang.IllegalArgumentException: requirement failed
       	at scala.Predef$.require(Predef.scala:221)
       	at org.broadinstitute.hail.utils.TextTableReader$.guessType(TextTableReader.scala:64)
       	at org.broadinstitute.hail.utils.TextTableReader$$anonfun$20.apply(TextTableReader.scala:159)
       	at org.broadinstitute.hail.utils.TextTableReader$$anonfun$20.apply(TextTableReader.scala:153)
       	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
       	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
       	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
       	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
       	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
       	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
       	at org.broadinstitute.hail.utils.TextTableReader$.read(TextTableReader.scala:153)
       	at org.broadinstitute.hail.driver.ImportAnnotationsTable$.run(ImportAnnotations.scala:53)
       	at org.broadinstitute.hail.driver.ImportAnnotationsTable$.run(ImportAnnotations.scala:22)
       	at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:239)
       	at org.broadinstitute.hail.driver.Main$.runCommand(Main.scala:121)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:145)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:145)
       	at org.broadinstitute.hail.Utils$.time(Utils.scala:1260)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:144)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:138)
       	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
       	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
       	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:108)
       	at org.broadinstitute.hail.driver.Main$.runCommands(Main.scala:138)
       	at org.broadinstitute.hail.driver.Main$.main(Main.scala:305)
       	at org.broadinstitute.hail.driver.Main.main(Main.scala)
```

**Comment by tpoterba** [comment]
This is not an issue, I was doing silly things with bash temp files:
```
<(printf "...")
```
