### ISSUE TITLE
Incompatible file format ,supported version: 1.1.0, found 1.2.0

### ISSUE THREAD

**Issue by Ainyana** [hail-is/hail#7647]
I created the cluster using hailctl as hailctl dataproc --beta start hailjupy --vep GRCh37 --optional-components=ANACONDA,JUPYTER --enable-component-gateway --bucket bucketname --project projectname --region us-central1

The following error occurs when trying to read table from bucket,
table1 = hl.read_table(‘gs://…ht’), 

FatalError: HailException: incompatible file format when reading: gs://gnomad-public/release/3.0/ht/genomes/gnomad.genomes.r3.0.sites.ht
supported version: 1.1.0, found 1.2.0

Java stack trace:
is.hail.utils.HailException: incompatible file format when reading: gs://…ht
supported version: 1.1.0, found 1.2.0
at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:9)
at is.hail.utils.package$.fatal(package.scala:74)
at is.hail.variant.RelationalSpec$.readMetadata(MatrixTable.scala:54)
at is.hail.variant.RelationalSpec$.readReferences(MatrixTable.scala:71)
at is.hail.variant.ReferenceGenome$.fromHailDataset(ReferenceGenome.scala:586)
at is.hail.variant.ReferenceGenome.fromHailDataset(ReferenceGenome.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.lang.Thread.run(Thread.java:748)

Hail version: 0.2.23-aaf52cafe5ef
Error summary: HailException: incompatible file format when reading: gs://…ht
supported version: 1.1.0, found 1.2.0

Kindly tell me how can i resolve it?

**Comment by tpoterba** [comment]
answered here: https://discuss.hail.is/t/incompatible-file-format-supported-version-1-1-0-found-1-2-0/1196
