### ISSUE TITLE
[batch] hailctl batch list broken

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7756]
I can't use `hailctl batch list`
```
Last login: Wed Dec 18 15:05:20 on ttys001
# hailctl batch list
Traceback (most recent call last):
  File "/usr/local/bin/hailctl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/hailtop/hailctl/__main__.py", line 103, in main
    cli.main(args)
  File "/usr/local/lib/python3.7/site-packages/hailtop/hailctl/batch/cli.py", line 97, in main
    jmp[args.module].main(args, pass_through_args, client)
  File "/usr/local/lib/python3.7/site-packages/hailtop/hailctl/batch/list_batches.py", line 39, in main
    batch_list = client.list_batches(success=success, complete=complete, attributes=attributes)
TypeError: list_batches() got an unexpected keyword argument 'success'
# 
```

**Comment by johnc1231** [comment]
Fix included in #7783
