### ISSUE TITLE
Fix multi_way_zip_join key issue

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#8027]
This pipeline:
```python3
# cwd = repo_root/hail
vcf2 = hl.import_vcf('src/test/resources/gvcfs/HG00268.g.vcf.gz', force_bgz=True, reference_genome='GRCh38')
vcf1 = hl.import_vcf('src/test/resources/gvcfs/HG00096.g.vcf.gz', force_bgz=True, reference_genome='GRCh38')
vcfs = [vcf1.rows().key_by('locus'), vcf2.rows().key_by('locus')]
ht = hl.Table.multi_way_zip_join(vcfs, 'data', 'new_globals')
ht._force_count()
```
Fails with:
```
java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:224)
        at is.hail.rvd.RVD.<init>(RVD.scala:46)
        at is.hail.rvd.RVD$.apply(RVD.scala:1411)
        at is.hail.expr.ir.TableMultiWayZipJoin.execute(TableIR.scala:925)
```

**Comment by chrisvittal** [comment]
Adding a printout to the requirement, shows that the partitioner's key is not getting trimmed.
```
java.lang.IllegalArgumentException: requirement failed: struct{locus: locus<GRCh38>} struct{locus: locus<GRCh38>, alleles: array<str>}
```
