### ISSUE TITLE
[batch] new docker error

### ISSUE THREAD

**Issue by danking** [hail-is/hail#8029]
I found this while on a PR based on:

```
* 8e61ad87c - (3 days ago) [batch] fix scheduler -- schedule job timeout 1sec (#8022) - jigold (hi/master, master)
```

The error was:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/batch/worker.py", line 281, in run
    await docker_call_retry(self.container.start)
  File "/usr/local/lib/python3.6/site-packages/batch/worker.py", line 87, in docker_call_retry
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/aiodocker/containers.py", line 188, in start
    data=kwargs
  File "/usr/local/lib/python3.6/site-packages/aiodocker/docker.py", line 166, in _query
    json.loads(what.decode('utf8')))
aiodocker.exceptions.DockerError: DockerError(500, 'OCI runtime start failed: container process is already dead: unknown')
```

Unfortunately the batch worker had already died by this point.

```
{
  "batch_id": 1,
  "job_id": 19,
  "name": "18",
  "state": "Error",
  "exit_code": null,
  "duration": 10408,
  "msec_mcpu": 1040800,
  "cost": "$0.0000",
  "status": {
    "worker": "batch-worker-dking-16py5",
    "batch_id": 1,
    "job_id": 19,
    "attempt_id": "5cs0mg",
    "user": "dking",
    "state": "error",
    "format_version": 2,
    "container_statuses": {
      "main": {
        "name": "main",
        "state": "error",
        "timing": {
          "pulling": {
            "start_time": 1580760856472,
            "finish_time": 1580760856486,
            "duration": 14
          },
          "creating": {
            "start_time": 1580760856486,
            "finish_time": 1580760856629,
            "duration": 143
          },
          "runtime": {
            "start_time": 1580760856630,
            "finish_time": 1580760867038,
            "duration": 10408
          },
          "starting": {
            "start_time": 1580760856630,
            "finish_time": 1580760867038,
            "duration": 10408
          }
        },
        "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/batch/worker.py\", line 281, in run\n    await docker_call_retry(self.container.start)\n  File \"/usr/local/lib/python3.6/site-packages/batch/worker.py\", line 87, in docker_call_retry\n    return await f(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/aiodocker/containers.py\", line 188, in start\n    data=kwargs\n  File \"/usr/local/lib/python3.6/site-packages/aiodocker/docker.py\", line 166, in _query\n    json.loads(what.decode('utf8')))\naiodocker.exceptions.DockerError: DockerError(500, 'OCI runtime start failed: container process is already dead: unknown')\n"
      }
    },
    "start_time": 1580760856630,
    "end_time": 1580760867038
  },
  "spec": {
    "command": [
      "/bin/bash",
      "-c",
      "set -e; mkdir -p /io/pipeline/pipeline-3dea50d54013/__TASK__18/; /bin/true"
    ],
    "image": "ubuntu:18.04",
    "job_id": 19,
    "mount_docker_socket": false,
    "resources": {
      "cpu": "0.001",
      "memory": "375M"
    },
    "secrets": [
      {
        "namespace": "dking",
        "name": "dking-gsa-key",
        "mount_path": "/gsa-key",
        "mount_in_copy": true
      }
    ],
    "env": []
  },
  "attributes": {
    "name": "18"
  }
}
```

**Comment by danking** [comment]
relevant? https://github.com/docker/for-linux/issues/647

**Comment by danking** [comment]
Seems very likely this is docker/for-linux#647. It occurs about 1% of the time for me when running `/bin/true` jobs on n1-standard-1 workers with no cpu requirements (not sure how much parallelism that results in).
