### ISSUE TITLE
UnsupportedClassVersionError: org/apache/solr/client/solrj/SolrClient : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by BioDCH** [hail-is/hail#825]
Hello, when I test hail in the spark cluster, there is  an error:

bash-4.2$ spark-submit --executor-memory 16g --executor-cores 4 --class org.broadinstitute.hail.driver.Main ***/hail-all-spark.jar --master yarn-client importvcf /user/hail/sample.vcf  splitmulti write -o /user/hail/sample_1.vds exportvcf -o /user/hail/sample_1.vcf

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/solr/client/solrj/SolrClient : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.broadinstitute.hail.driver.ToplevelCommands$.<init>(Command.scala:62)
	at org.broadinstitute.hail.driver.ToplevelCommands$.<clinit>(Command.scala)
	at org.broadinstitute.hail.driver.Main$.main(Main.scala:205)
	at org.broadinstitute.hail.driver.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

I think this may relate to java  version, so I  re-configured java,but  the error still appear, How can I solve it ?

--------------------My java version and path
[root@***-3 opt]# java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

[root@***-3 opt]# echo $JAVA_HOME
/opt/BioDir/jdk/jdk1.8.0_91

[root@bio-x-3 opt]# echo $PATH
/opt/BioDir/plink_1.9:/opt/BioDir/jdk/jdk1.8.0_91/bin:/opt/BioDir/gradle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

My OS is CentOS7
[root@***-3 opt]# uname -a
Linux bio-x-3 3.10.0-229.14.1.el7.x86_64

**Comment by cseed** [comment]
What version/distribution of Spark are you running?

**Comment by cseed** [comment]
I would have thought this was because you were running Java 7 but the Solr jar is compiled with Java 8.  Can you check which version of Java Spark is running against on the cluster?  For example:

```
$ spark-shell
scala> System.getProperty("java.version")
res0: String = 1.8.0_45

val rdd = sc.parallelize(0 to 1000, 4)
scala> rdd.mapPartitions { it => Iterator(System.getProperty("java.version")) }.collect()
res2: Array[String] = Array(1.8.0_45, 1.8.0_45, 1.8.0_45, 1.8.0_45)
```

**Comment by BioDCH** [comment]
When I check my spark configuration, it appears that:
My spark version is version 1.6.0
Using Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_67)

scala> System.getProperty("java.version")
res0: String = 1.7.0_67

scala> val rdd = sc.parallelize(0 to 1000, 4)
scala> rdd.mapPartitions { it => Iterator(System.getProperty("java.version")) }.collect()
res1: Array[String] = Array(1.7.0_67, 1.7.0_67, 1.7.0_67, 1.7.0_67)

It seems I should also update the java relate to the Spark cluster, Thank you !

**Comment by cseed** [comment]
Great!  Let us know if you run into any other problems.

**Comment by BioDCH** [comment]
Hi，cseed @cseed , I configured the java related to the Spark cluster, as follows：

scala> System.getProperty("java.version")
res0: String = 1.8.0_91

scala> val rdd = sc.parallelize(0 to 1000, 4)
rdd: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[0] at parallelize at <console>:27

scala> rdd.mapPartitions { it => Iterator(System.getProperty("java.version")) }.collect()
res1: Array[String] = Array(1.8.0_91, 1.8.0_91, 1.8.0_91, 1.8.0_91) 
------------------
but when testing the “splitmulti ” command， use the “split_test.vcf ” in the test file hail offered:

spark-submit --executor-memory 16g --executor-cores 4 --class org.broadinstitute.hail.driver.Main ******/hail-all-spark.jar 
--master yarn-client importvcf /user/hail/split_test.vcf splitmulti write -o /user/hail/split_test_1_1.vds exportvcf -o /user/hail/split_test_1_1.vcf

there appeared some errors：
 
1.  java.io.FileNotFoundException: hail.log (Permission denied)

2. Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 5, bio-x-3): 
java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN

3. The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN

I tested several  different vcf files, the errors always existed.
The whole error message was attached as follows 
[splitmulti.txt](https://github.com/hail-is/hail/files/502516/splitmulti.txt)    

How can I solve it ?

**Comment by danking** [comment]
Hi there @BioDCH, I reformatted your comment using [markdown code blocks](https://guides.github.com/features/mastering-markdown/#syntax).

It looks like the unix user running `hail` does not have permission to edit `hail.log` file, this likely caused the other two errors. Please add `--log-file PATH` where `PATH` is a file path to which you have write access.

For example:

```
spark-submit --executor-memory 16g --executor-cores 4 --class org.broadinstitute.hail.driver.Main ******/hail-all-spark.jar 
--master yarn-client importvcf --log-file /user/hail/hail.log /user/hail/split_test.vcf splitmulti write -o /user/hail/split_test_1_1.vds exportvcf -o /user/hail/split_test_1_1.vcf
```

Assuming you have write access to `/user/hail/hail.log`.

**Comment by BioDCH** [comment]
Hi,  danking,  I tried two log file pathes ,all had access permission, but the error still appeared

（1）HDFS file path ：/user/hail/hail.log， have access permission
     -rwxrwxrwx   3 hdfs supergroup           0 2016-10-08 10:54 /user/hail/hail.log
（2）log file：local PATH， hava access permission
     -rwxrwxrwx  1 root root 48523 Oct  8 11:42 hail.log

The error message was attached as follows 
[splitmulti_1_1.txt](https://github.com/hail-is/hail/files/517467/splitmulti_1_1.txt)

**Comment by BioDCH** [comment]
@cseed @danking 

Hi, I tried the following command , and configured the log path , but it still not worked,  are there any suggestions?

spark-submit --executor-memory 16g --executor-cores 4 --class org.broadinstitute.hail.driver.Main ******/hail-all-spark.jar  --master yarn-client importvcf --log-file /user/hail/hail.log /user/hail/split_test.vcf splitmulti write -o /user/hail/split_test_1_1.vds exportvcf -o /user/hail/split_test_1_1.vcf

**ERROR:**
WARNING: Running spark-class from user-defined location.
hail: info: running: importvcf /user/hail/sample.vcf
hail: info: Coerced sorted dataset
hail: info: running: splitmulti
hail: info: running: write -o /user/hail/sample_1008.vds
hail: write: caught exception: org.apache.spark.SparkException: Job aborted.
.........
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 5, bio-x-3): java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
...........
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN

[splitmulti_1_1.txt](https://github.com/hail-is/hail/files/521087/splitmulti_1_1.txt)
