### ISSUE TITLE
Assertion error related to ndarray/extract

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#8325]
to replicate:

```python
phenotypes_BP = ['is_BP1', 'is_BP2', 'is_BP', 'is_BP_including_BPSCZ', 'is_BPNOS', 'is_BPSCZ', 'is_BPPSY', 'is_BP_no_PSY']
def make_fake_data():
    mt = hl.utils.range_matrix_table(1000, 100)
    mt = mt.annotate_rows(gene_set = "my_gene", consequence_category = "cnsq")
    mt = mt.annotate_cols(phenotype_boolean = hl.struct(**{pheno : hl.rand_bool(.5) for pheno in phenotypes_BP}))
    mt = mt.annotate_cols(is_female = hl.rand_bool(.5))
    mt = mt.annotate_cols(col_id = hl.str(mt.col_idx))
    mt = mt.annotate_cols(**{f"PC{i + 1}":hl.rand_unif(0, 10) for i in range(10)})
    mt = mt.annotate_entries(x = hl.rand_unif(0, 3))
    mt = mt.key_rows_by(mt.gene_set, mt.consequence_category)
    mt = mt.key_cols_by(mt.col_id)
    return mt

def permute_phenotypes(np_pheno, n_perms):

    np_pheno[np_pheno == None] = 2
    np_pheno = np_pheno.astype(int)
    np_pheno_mat = np.repeat(np_pheno, n_perms).reshape(np_pheno.size, n_perms)
    for i in range(np_pheno_mat.shape[1]):
        np.random.shuffle(np_pheno_mat[:,i])

    return(np_pheno_mat)

def run_regressions_perm(mt, phenotypes, n_perms):

    mt = mt.add_col_index()

    init = True
    for phenotype in phenotypes:

        mt = mt.annotate_globals(
            pheno_perm = permute_phenotypes(np.array(mt.phenotype_boolean[phenotype].collect()), n_perms))
        mt = mt.annotate_globals(
            pheno_perm = mt.pheno_perm.map(
                lambda x: { hl.array([False, True, hl.null(hl.tbool)])[hl.int(x)] }
            ))
        return mt

mt = make_fake_data()
res = run_regressions_perm(mt, phenotypes_BP, 100)
res.show()
```

error:

```
java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:156)
    at is.hail.expr.ir.agg.Extract$.extract(Extract.scala:331)
    at is.hail.expr.ir.agg.Extract$.is$hail$expr$ir$agg$Extract$$extract$1(Extract.scala:215)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:8)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:7)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at is.hail.expr.ir.MapIR$.apply(MapIR.scala:7)
    at is.hail.expr.ir.agg.Extract$.extract(Extract.scala:333)
    at is.hail.expr.ir.agg.Extract$.is$hail$expr$ir$agg$Extract$$extract$1(Extract.scala:215)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:8)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:7)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at is.hail.expr.ir.MapIR$.apply(MapIR.scala:7)
    at is.hail.expr.ir.agg.Extract$.extract(Extract.scala:333)
    at is.hail.expr.ir.agg.Extract$.is$hail$expr$ir$agg$Extract$$extract$1(Extract.scala:215)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:8)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:7)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at is.hail.expr.ir.MapIR$.apply(MapIR.scala:7)
    at is.hail.expr.ir.agg.Extract$.extract(Extract.scala:333)
    at is.hail.expr.ir.agg.Extract$.is$hail$expr$ir$agg$Extract$$extract$1(Extract.scala:215)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.agg.Extract$$anonfun$extract$3.apply(Extract.scala:333)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:8)
    at is.hail.expr.ir.MapIR$$anonfun$apply$1.apply(MapIR.scala:7)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
```

**Comment by johnc1231** [comment]
Just to be clear, this pipeline was what I wrote when trying to replicate the bug Duncan was seeing, but it hit a different assertion error than the one he was hitting. He was hitting "local in the wrong method builder" problems.

**Comment by tpoterba** [comment]
I'm fixing that one next :)

**Comment by tpoterba** [comment]
I saw different errors if a `show()` vs `_force_count_rows()` was the last line.
