### ISSUE TITLE
[query] inconsistent agg or scan environments

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#8338]
in the last step of:
```
def pull_out_col_keys(all_hts, row_keys, col_keys):
    rekeyed_hts = []
    for ht in all_hts:
        glob = ht.aggregate(hl.agg.take(hl.struct(**{x: ht[x] for x in col_keys}), 1)[0], _localize=False)
        rekeyed_hts.append(ht.key_by(*row_keys).drop(*col_keys).annotate_globals(**glob))
    return rekeyed_hts


def join_pheno_hts_to_mt(all_hts, row_keys, col_keys, pheno_dict, temp_dir, inner_mode: str = 'overwrite',
                         repartition_final: int = None):
    rekeyed_hts = pull_out_col_keys(all_hts, row_keys, col_keys)
    mt = mwzj_hts_by_tree(rekeyed_hts, temp_dir, col_keys, debug=True,
                          inner_mode=inner_mode, repartition_final=repartition_final)
    print(f'Unioned MTs...')
    mt = mt.annotate_cols(**pheno_dict[mt.col_key])  # .key_rows_by('locus', 'alleles')
    return mt

def mwzj_hts_by_tree(all_hts, temp_dir, globals_for_col_key, debug=False, inner_mode = 'overwrite',
                     repartition_final: int = None):
    chunk_size = int(len(all_hts) ** 0.5) + 1
    outer_hts = []

    checkpoint_kwargs = {inner_mode: True}
    if repartition_final is not None:
        intervals = get_n_even_intervals(repartition_final)
        checkpoint_kwargs['_intervals'] = intervals

    if debug: print(f'Running chunk size {chunk_size}...')
    for i in range(chunk_size):
        if i * chunk_size >= len(all_hts): break
        hts = all_hts[i * chunk_size:(i + 1) * chunk_size]
        if debug: print(f'Going from {i * chunk_size} to {(i + 1) * chunk_size} ({len(hts)} HTs)...')
        try:
            if isinstance(hts[0], str):
                hts = list(map(lambda x: hl.read_table(x), hts))
            ht = hl.Table.multi_way_zip_join(hts, 'row_field_name', 'global_field_name')
        except:
            if debug:
                print(f'problem in range {i * chunk_size}-{i * chunk_size + chunk_size}')
                _ = [ht.describe() for ht in hts]
            raise
        outer_hts.append(ht.checkpoint(f'{temp_dir}/temp_output_{i}.ht', **checkpoint_kwargs))
    ht = hl.Table.multi_way_zip_join(outer_hts, 'row_field_name_outer', 'global_field_name_outer')
    ht = ht.transmute(inner_row=hl.flatmap(lambda i:
                                           hl.cond(hl.is_missing(ht.row_field_name_outer[i].row_field_name),
                                                   hl.range(0, hl.len(ht.global_field_name_outer[i].global_field_name))
                                                   .map(lambda _: hl.null(ht.row_field_name_outer[i].row_field_name.dtype.element_type)),
                                                   ht.row_field_name_outer[i].row_field_name),
                                           hl.range(hl.len(ht.global_field_name_outer))))
    ht = ht.transmute_globals(inner_global=hl.flatmap(lambda x: x.global_field_name, ht.global_field_name_outer))
    mt = ht._unlocalize_entries('inner_row', 'inner_global', globals_for_col_key)
    return mt

        all_hts = list(map(lambda x: unify_saige_ht_schema(hl.read_table(x)), all_variant_outputs))
        mt = join_pheno_hts_to_mt(all_hts, row_keys, col_keys, pheno_dict, f'{temp_bucket}/{pop}/variant',
                                  inner_mode=inner_mode, repartition_final=20000)
        mt = mt.annotate_cols(saige_heritability=heritability_dict[mt.col_key])
        mt = mt.filter_cols(mt.pheno != "").drop('varT', 'varTstar', 'Is.SPA.converge')
        mt.key_rows_by('locus', 'alleles').write(get_variant_results_path(pop, 'mt'), overwrite=args.overwrite)
```
I'm getting the following error:
```
hail.utils.java.FatalError: RuntimeException: found inconsistent agg or scan environments:
  left: true, true
  right: false, false

Java stack trace:
java.lang.RuntimeException: found inconsistent agg or scan environments:
  left: true, true
  right: false, false
    at is.hail.expr.ir.BindingEnv.merge(Env.scala:68)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$2.apply(FreeVariables.scala:38)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$2.apply(FreeVariables.scala:38)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.fold(TraversableOnce.scala:212)
    at scala.collection.AbstractIterator.fold(Iterator.scala:1334)
    at is.hail.expr.ir.FreeVariables$.is$hail$expr$ir$FreeVariables$$compute$1(FreeVariables.scala:38)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$1.apply(FreeVariables.scala:27)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$1.apply(FreeVariables.scala:24)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.fold(TraversableOnce.scala:212)
    at scala.collection.AbstractIterator.fold(Iterator.scala:1334)
    at is.hail.expr.ir.FreeVariables$.is$hail$expr$ir$FreeVariables$$compute$1(FreeVariables.scala:38)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$1.apply(FreeVariables.scala:27)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$1.apply(FreeVariables.scala:24)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.fold(TraversableOnce.scala:212)
    at scala.collection.AbstractIterator.fold(Iterator.scala:1334)
    at is.hail.expr.ir.FreeVariables$.is$hail$expr$ir$FreeVariables$$compute$1(FreeVariables.scala:38)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$1.apply(FreeVariables.scala:27)
    at is.hail.expr.ir.FreeVariables$$anonfun$is$hail$expr$ir$FreeVariables$$compute$1$1.apply(FreeVariables.scala:24)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
    at scala.collection.TraversableOnce$class.fold(TraversableOnce.scala:212)
    at scala.collection.AbstractIterator.fold(Iterator.scala:1334)
    at is.hail.expr.ir.FreeVariables$.is$hail$expr$ir$FreeVariables$$compute$1(FreeVariables.scala:38)
    at is.hail.expr.ir.FreeVariables$.apply(FreeVariables.scala:42)
    at is.hail.expr.ir.Mentions$.inAggOrScan(Mentions.scala:10)
    at is.hail.expr.ir.Simplify$$anonfun$matrixRules$1.applyOrElse(Simplify.scala:893)
    at is.hail.expr.ir.Simplify$$anonfun$matrixRules$1.applyOrElse(Simplify.scala:828)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$rewriteMatrixNode(Simplify.scala:68)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$3.apply(Simplify.scala:50)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$3.apply(Simplify.scala:50)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$visitNode(Simplify.scala:31)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$simplifyMatrix(Simplify.scala:52)
    at is.hail.expr.ir.Simplify$.apply(Simplify.scala:21)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$2.apply(Simplify.scala:49)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$2.apply(Simplify.scala:49)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at is.hail.expr.ir.BaseIR.mapChildren(BaseIR.scala:17)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$visitNode(Simplify.scala:30)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$simplifyMatrix(Simplify.scala:52)
    at is.hail.expr.ir.Simplify$.apply(Simplify.scala:21)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$2.apply(Simplify.scala:49)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$2.apply(Simplify.scala:49)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at is.hail.expr.ir.BaseIR.mapChildren(BaseIR.scala:17)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$visitNode(Simplify.scala:30)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$simplifyMatrix(Simplify.scala:52)
    at is.hail.expr.ir.Simplify$.apply(Simplify.scala:21)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$2.apply(Simplify.scala:49)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyMatrix$2.apply(Simplify.scala:49)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at is.hail.expr.ir.BaseIR.mapChildren(BaseIR.scala:17)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$visitNode(Simplify.scala:30)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$simplifyMatrix(Simplify.scala:52)
    at is.hail.expr.ir.Simplify$.apply(Simplify.scala:21)
    at is.hail.expr.ir.Simplify$.apply(Simplify.scala:11)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyValue$1.apply(Simplify.scala:36)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyValue$1.apply(Simplify.scala:36)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at is.hail.expr.ir.BaseIR.mapChildren(BaseIR.scala:17)
    at is.hail.expr.ir.Simplify$.is$hail$expr$ir$Simplify$$visitNode(Simplify.scala:30)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyValue$3.apply(Simplify.scala:35)
    at is.hail.expr.ir.Simplify$$anonfun$is$hail$expr$ir$Simplify$$simplifyValue$3.apply(Simplify.scala:35)
    at is.hail.expr.ir.Simplify$.apply(Simplify.scala:19)
    at is.hail.expr.ir.Simplify$.apply(Simplify.scala:11)
    at is.hail.expr.ir.Optimize$$anonfun$apply$1$$anonfun$apply$mcV$sp$3.apply(Optimize.scala:25)
    at is.hail.expr.ir.Optimize$$anonfun$apply$1$$anonfun$apply$mcV$sp$3.apply(Optimize.scala:25)
    at is.hail.expr.ir.Optimize$$anonfun$is$hail$expr$ir$Optimize$$runOpt$1$1.apply(Optimize.scala:17)
    at is.hail.expr.ir.Optimize$$anonfun$is$hail$expr$ir$Optimize$$runOpt$1$1.apply(Optimize.scala:17)
    at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:69)
    at is.hail.expr.ir.Optimize$.is$hail$expr$ir$Optimize$$runOpt$1(Optimize.scala:17)
    at is.hail.expr.ir.Optimize$$anonfun$apply$1.apply$mcV$sp(Optimize.scala:25)
    at is.hail.expr.ir.Optimize$$anonfun$apply$1.apply(Optimize.scala:21)
    at is.hail.expr.ir.Optimize$$anonfun$apply$1.apply(Optimize.scala:21)
    at is.hail.utils.ExecutionTimer.time(ExecutionTimer.scala:69)
    at is.hail.expr.ir.Optimize$.apply(Optimize.scala:20)
    at is.hail.expr.ir.lowering.LoweringPipeline.apply(LoweringPipeline.scala:16)
    at is.hail.expr.ir.CompileAndEvaluate$._apply(CompileAndEvaluate.scala:27)
    at is.hail.backend.Backend.is$hail$backend$Backend$$_execute(Backend.scala:90)
    at is.hail.backend.Backend$$anonfun$execute$1.apply(Backend.scala:78)
...
```

**Comment by johnc1231** [comment]
We can replicate this without external data by running the following:

```
def make_outer_hts_data(n_tables):
    tables = []
    for i in range(n_tables):
        t = hl.utils.range_table(20)
        t.key_by()
        
        field_array_length = 3

        # Globals
        global_struct_array = [ 
            hl.struct(n_cases=5, n_controls=10, pheno=f"pheno_{i}", coding="code", trait_type="trait")
            for i in range(field_array_length)]
        t = t.annotate_globals(global_field_name=global_struct_array)
        
        # Rows
        t = t.annotate(locus=hl.locus("1", 10000 + t.idx, reference_genome='GRCh37'), alleles = ['A', 'T'])
        t = t.annotate(gene="myGene", annotation="myAnnotation")
        row_struct_array = [
            hl.struct(
                AC_Allele2=2.0,
                AF_Allele2=.6,
                imputationInfo=1.0,
                N=15,
                BETA=4.5,
                SE=2.6
            )
            for i in range(field_array_length)]
        t = t.annotate(row_field_name=row_struct_array)
        
        t = t.key_by(t.locus, t.alleles, t.gene, t.annotation)
        tables.append(t)
    return tables

def create_broadcast_dict(key, value):
    """
    Create broadcast join (local dictionary from key -> value)
    from a Hail Table.

    :param Expression key: Key Expression
    :param Expression value: Value Expression
    :return: Hail DictExpression (without an index)
    :rtype: DictExpression
    """
    ht = key._indices.source
    return hl.dict(ht.aggregate(hl.agg.collect((key, value)), _localize=False))

def interesting_bit(outer_hts, globals_for_col_key):
    ht = hl.Table.multi_way_zip_join(outer_hts, 'row_field_name_outer', 'global_field_name_outer')
    ht = ht.transmute(inner_row=hl.flatmap(lambda i:
                                           hl.cond(hl.is_missing(ht.row_field_name_outer[i].row_field_name),
                                                   hl.range(0, hl.len(ht.global_field_name_outer[i].global_field_name))
                                                   .map(lambda _: hl.null(ht.row_field_name_outer[i].row_field_name.dtype.element_type)),
                                                   ht.row_field_name_outer[i].row_field_name),
                                           hl.range(hl.len(ht.global_field_name_outer))))
    ht = ht.transmute_globals(inner_global=hl.flatmap(lambda x: x.global_field_name, ht.global_field_name_outer))
    mt = ht._unlocalize_entries('inner_row', 'inner_global', globals_for_col_key)
    return mt

outer_hts = make_outer_hts_data(3)
mt = interesting_bit(outer_hts, ['pheno', 'coding', 'trait_type'])
    pop = "AFR"    
    heritability_ht = hl.utils.range_table(100).annotate(pop = "AFR", coding = "code", trait="myTrait", heritability="yes", pheno="sick")
    heritability_ht = heritability_ht.filter(heritability_ht.pop == pop)
    heritability_dict = create_broadcast_dict(hl.struct(pheno=heritability_ht.pheno, coding=heritability_ht.coding, trait_type=heritability_ht.trait),
                                                  heritability_ht.heritability)
mt = mt.annotate_cols(saige_heritability=heritability_dict[mt.col_key])
mt.show()
```

The bug doesn't occur without that final `annotate_cols`
