### ISSUE TITLE
Issue with hail.init()

### ISSUE THREAD

**Issue by sealedaway** [hail-is/hail#8423]
After I set-up my spark context on my spark cluster, I ran hail.init() and ran into the following: 
`py4j.protocol.Py4JError: An error occurred while calling z:is.hail.HailContext.apply. Trace:
py4j.Py4JException: Method apply([null, class java.lang.String, class scala.None$, class java.lang.String, class java.lang.String, class java.lang.Boolean, class java.lang.Boolean, class java.lang.Integer, class java.lang.Integer, class java.lang.String, class java.lang.Integer]) does not exist`

**Comment by tpoterba** [comment]
what version, and what's the full stack trace?

**Comment by sealedaway** [comment]
hail 0.2.33, python 3.7.3

`hl.init(sc)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<decorator-gen-1214>", line 2, in init
  File "/tmp/conda-9cc77aa7-66f1-4cac-870e-53c3df210a16/real/envs/conda-env/lib/python3.7/site-packages/hail/typecheck/check.py", line 585, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/tmp/conda-9cc77aa7-66f1-4cac-870e-53c3df210a16/real/envs/conda-env/lib/python3.7/site-packages/hail/context.py", line 290, in init
    _optimizer_iterations,_backend)
  File "<decorator-gen-1212>", line 2, in __init__
  File "/tmp/conda-9cc77aa7-66f1-4cac-870e-53c3df210a16/real/envs/conda-env/lib/python3.7/site-packages/hail/typecheck/check.py", line 585, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/tmp/conda-9cc77aa7-66f1-4cac-870e-53c3df210a16/real/envs/conda-env/lib/python3.7/site-packages/hail/context.py", line 121, in __init__
    min_block_size, branching_factor, tmp_dir, optimizer_iterations)
  File "/tmp/conda-9cc77aa7-66f1-4cac-870e-53c3df210a16/real/envs/conda-env/lib/python3.7/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/tmp/conda-9cc77aa7-66f1-4cac-870e-53c3df210a16/real/envs/conda-env/lib/python3.7/site-packages/transforms/_java_utils.py", line 237, in wrapper
    return func(*args, **kwargs)
  File "/tmp/conda-9cc77aa7-66f1-4cac-870e-53c3df210a16/real/envs/conda-env/lib/python3.7/site-packages/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling z:is.hail.HailContext.apply. Trace:
py4j.Py4JException: Method apply([class org.apache.spark.SparkContext, class java.lang.String, class scala.None$, class java.lang.String, class java.lang.String, class java.lang.Boolean, class java.lang.Boolean, class java.lang.Integer, class java.lang.Integer, class java.lang.String, class java.lang.Integer]) does not exist`

**Comment by tpoterba** [comment]
how did you install Hail? `pip install hail` or from source?

**Comment by sealedaway** [comment]
https://anaconda.org/bioconda/hail

Through bioconda^

**Comment by tpoterba** [comment]
that's not a distribution maintained by the Hail team. There's definitely no guarantee it works; for all we know, it could be malware.

**Comment by tpoterba** [comment]
Here's the PR that added this recipe:
https://github.com/bioconda/bioconda-recipes/pull/20739/files

**Comment by tpoterba** [comment]
please refer to this page for up-to-date installation instructions: https://hail.is/docs/0.2/getting_started.html
