### ISSUE TITLE
TableAggregateByKey AssertionError

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#8694]
```
Hail version: 0.2.38-16624ac88829
Error summary: AssertionError: assertion failed: +PCStruct{locus:PCLocus(GRCh37),alleles:PCArray[PCString],gene:+PCString,annotation:+PCString,__iruid_97596:+PCArray[+PCStruct{gene:+PCString,annotation:+PCString,`the entries! [877f12a8827e18f61222c6c8c5fb04a8]`:+PCArray[PCStruct{AF_Allele2:PFloat64,imputationInfo:PFloat64,BETA:PFloat64,SE:PFloat64,`p.value.NA`:PFloat64,`AF.Cases`:PFloat64,`AF.Controls`:PFloat64,Pvalue:PFloat64}]}]}, struct{locus: locus<GRCh37>, alleles: array<str>, __iruid_97596: array<struct{gene: str, annotation: str, `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`: array<struct{AF_Allele2: float64, imputationInfo: float64, BETA: float64, SE: float64, `p.value.NA`: float64, `AF.Cases`: float64, `AF.Controls`: float64, Pvalue: float64}>}>}
...
    at scala.Predef$.assert(Predef.scala:170)
    at is.hail.expr.ir.TableAggregateByKey.execute(TableIR.scala:1879)
    at is.hail.expr.ir.TableFilter.execute(TableIR.scala:581)
    at is.hail.expr.ir.TableOrderBy.execute(TableIR.scala:1971)
    at is.hail.expr.ir.TableSubset$class.execute(TableIR.scala:626)
    at is.hail.expr.ir.TableHead.execute(TableIR.scala:634)
    at is.hail.expr.ir.TableMapRows.execute(TableIR.scala:1176)
```
pipeline:
```
mt = hl.read_matrix_table(...)
x = mt._filter_partitions(range(1))
x.entries().show()
```
version is some minor commits off of f836e49cb179117837aaae7614b6bdd28febe857

**Comment by tpoterba** [comment]
found this one

**Comment by konradjk** [comment]
Oh I presumed this was related to #8708 but I guess not?

**Comment by tpoterba** [comment]
nope, isolated agg by key bug
