### ISSUE TITLE
AssertionError on dropping field that was a key

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#8751]
`0.2.39-d38fca12930d`

```
ht_out = ht.group_by(_x=True).aggregate(
   ...:     data=hl.agg.downsample(
   ...:         hl.log10(eur_freq.gnomad_genomes_af), hl.log10(eur_freq.af / 2),
   ...:         [ht.pass_status, hl.str(hl.abs(hl.log(eur_freq.gnomad_genomes_af / eur_freq.gnomad_exomes_af, 2)) > 2)])
   ...: ).explode('data').key_by().drop('_x')
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-59-3a16f061373b>", line 5, in <module>
    ).explode('data').key_by().drop('_x')
  File "<decorator-gen-1731>", line 2, in drop
  File "/Users/konradk/hail/hail/python/hail/typecheck/check.py", line 585, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/Users/konradk/hail/hail/python/hail/table.py", line 965, in drop
    protected_key = set(self._row_indices.protected_key)
  File "/Users/konradk/hail/hail/python/hail/expr/expressions/indices.py", line 42, in protected_key
    self._cached_key = self._get_key()
  File "/Users/konradk/hail/hail/python/hail/expr/expressions/indices.py", line 56, in _get_key
    assert isinstance(self.source, hl.MatrixTable)
AssertionError
```

**Comment by danking** [comment]
Closing as stale. Please open new issue if this occurs in recent versions of Hail.
