### ISSUE TITLE
hb.Batch(backend=backend, name=batch_name) error when batch_name is not a string

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#9050]
I accidentally passed a list instead of a string as the hb.Batch name and got this error
```
Traceback (most recent call last):
  File "outrider_batch_pipeline.py", line 216, in <module>
    main()
  File "outrider_batch_pipeline.py", line 212, in main
    logger.info(f"Output: {output_file}")
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/weisburd/code/methods/batch/batch_utils.py", line 66, in run_batch
    batch.run(dry_run=args.dry_run, verbose=args.verbose)
  File "/usr/local/lib/python3.7/site-packages/hailtop/batch/batch.py", line 423, in run
    return self._backend._run(self, dry_run, verbose, delete_scratch_on_exit, **backend_kwargs)
  File "/usr/local/lib/python3.7/site-packages/hailtop/batch/backend.py", line 435, in _run
    bc_batch = bc_batch.submit(disable_progress_bar=disable_progress_bar)
  File "/usr/local/lib/python3.7/site-packages/hailtop/batch_client/client.py", line 167, in submit
    async_batch = async_to_blocking(self._async_builder.submit(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/hailtop/batch_client/client.py", line 7, in async_to_blocking
    return asyncio.get_event_loop().run_until_complete(coro)
  File "/usr/local/lib/python3.7/site-packages/nest_asyncio.py", line 63, in run_until_complete
    return self._run_until_complete_orig(future)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.7/site-packages/hailtop/batch_client/aioclient.py", line 492, in submit
    batch = await self._create()
  File "/usr/local/lib/python3.7/site-packages/hailtop/batch_client/aioclient.py", line 478, in _create
    json=batch_spec)).json()
  File "/usr/local/lib/python3.7/site-packages/hailtop/batch_client/aioclient.py", line 576, in _post
    self.url + path, data=data, json=json, headers=self._headers)
  File "/usr/local/lib/python3.7/site-packages/hailtop/utils/utils.py", line 349, in request_retry_transient_errors
    return await retry_transient_errors(session.request, method, url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hailtop/utils/utils.py", line 321, in retry_transient_errors
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 588, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='batch.attributes has non-str value', url='https://batch.hail.is/api/v1alpha/batches/create

```

**Comment by johnc1231** [comment]
@jigold
