### ISSUE TITLE
hl.hadoop_ls error when filename contains "::" (eg. "CCDG::133.tsv.bgz") 

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#9607]
Error summary: URISyntaxException: Relative path in absolute URI: CCDG::133.tsv.bgz

```
In [4]: tsvs = hl.hadoop_ls("gs://my-bucket/*.tsv*")
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
<ipython-input-4-3a6cee08b392> in <module>
----> 1 tsvs = hl.hadoop_ls("gs://my-bucket/*.tsv*")

/Library/Python/3.7/site-packages/hail/utils/hadoop_utils.py in hadoop_ls(path)
    212     :obj:`list` [:obj:`dict`]
    213     """
--> 214     return Env.fs().ls(path)
    215
    216

/Library/Python/3.7/site-packages/hail/fs/hadoop_fs.py in ls(self, path)
     40
     41     def ls(self, path: str) -> List[Dict]:
---> 42         return json.loads(self._utils_package_object.ls(self._jfs, path))
     43
     44     def mkdir(self, path: str) -> None:

/Library/Python/3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258
   1259         for temp_arg in temp_args:

/Library/Python/3.7/site-packages/hail/backend/spark_backend.py in deco(*args, **kwargs)
     49                 raise FatalError('%s\n\nJava stack trace:\n%s\n'
     50                                  'Hail version: %s\n'
---> 51                                  'Error summary: %s' % (deepest, full, hail.__version__, deepest), error_id) from None
     52         except pyspark.sql.utils.CapturedException as e:
     53             raise FatalError('%s\n\nJava stack trace:\n%s\n'

FatalError: URISyntaxException: Relative path in absolute URI: CCDG::133.tsv.bgz

Java stack trace:
java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: CCDG::133.tsv.bgz
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.concurrentGlobInternal(GoogleHadoopFileSystemBase.java:1284)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1261)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1229)
	at is.hail.io.fs.HadoopFS.listStatus(HadoopFS.scala:104)
	at is.hail.utils.Py4jUtils$class.ls(Py4jUtils.scala:55)
	at is.hail.utils.package$.ls(package.scala:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: CCDG::133.tsv.bgz
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at java.util.concurrent.AbstractExecutorService.doInvokeAny(AbstractExecutorService.java:193)
	at java.util.concurrent.AbstractExecutorService.invokeAny(AbstractExecutorService.java:215)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.concurrentGlobInternal(GoogleHadoopFileSystemBase.java:1282)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1261)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1229)
	at is.hail.io.fs.HadoopFS.listStatus(HadoopFS.scala:104)
	at is.hail.utils.Py4jUtils$class.ls(Py4jUtils.scala:55)
	at is.hail.utils.package$.ls(package.scala:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: CCDG::133.tsv.bgz
	at org.apache.hadoop.fs.Path.initialize(Path.java:205)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at org.apache.hadoop.fs.Path.<init>(Path.java:93)
	at org.apache.hadoop.fs.Globber.glob(Globber.java:241)
	at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1676)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globInternal(GoogleHadoopFileSystemBase.java:1370)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.lambda$concurrentGlobInternal$4(GoogleHadoopFileSystemBase.java:1279)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

java.net.URISyntaxException: Relative path in absolute URI: CCDG::133.tsv.bgz
	at java.net.URI.checkPath(URI.java:1823)
	at java.net.URI.<init>(URI.java:745)
	at org.apache.hadoop.fs.Path.initialize(Path.java:202)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at org.apache.hadoop.fs.Path.<init>(Path.java:93)
	at org.apache.hadoop.fs.Globber.glob(Globber.java:241)
	at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1676)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globInternal(GoogleHadoopFileSystemBase.java:1370)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.lambda$concurrentGlobInternal$4(GoogleHadoopFileSystemBase.java:1279)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)






Hail version: 0.2.58-3f304aae6ce2
Error summary: URISyntaxException: Relative path in absolute URI: CCDG::133.tsv.bgz
```

**Comment by danking** [comment]
This is a limitation of the Hadoop library that we cannot avoid.
